export const MEMBER_KEY="study-tracker-family-member-v1",TOKEN_KEY="study-tracker-family-token-v1",REALTIME_TOKEN_KEY="study-tracker-family-realtime-token-v1",AUTH_KEY="study-tracker-family-auth-v1";

function tokenClaims(token){try{const parts=String(token||"").split("."),part=parts.length===3?parts[1]:parts[0],value=part.replace(/-/g,"+").replace(/_/g,"/");return JSON.parse(atob(value+"=".repeat((4-value.length%4)%4)))}catch{return null}}
function notify(authenticated){window.dispatchEvent(new CustomEvent("family-auth-changed",{detail:{authenticated}}))}

export function restoreFamilyAuth(){try{localStorage.removeItem(AUTH_KEY);const auth=JSON.parse(sessionStorage.getItem(AUTH_KEY)||"null"),claims=tokenClaims(auth?.token),realtimeClaims=tokenClaims(auth?.realtimeToken),member=auth?.member||{id:claims?.sub,family_id:claims?.family,member_key:auth?.memberKey||claims?.key,display_name:"",role:claims?.role};if(!claims||!realtimeClaims||claims.exp<=Date.now()/1000||realtimeClaims.exp<=Date.now()/1000||claims.sub!==realtimeClaims.sub||claims.sub!==member.id||claims.family!==member.family_id||claims.key!==member.member_key){clearFamilyAuth(false);return null}return{token:auth.token,realtimeToken:auth.realtimeToken,member}}catch{clearFamilyAuth(false);return null}}
export function familyAuthExpiresAt(token,realtimeToken){const claims=tokenClaims(token),realtimeClaims=tokenClaims(realtimeToken);return Math.min(claims?.exp||0,realtimeClaims?.exp||0)*1000}
export function saveFamilyAuth({token,realtimeToken,member}){const auth={savedAt:new Date().toISOString(),token,realtimeToken,member:{id:member.id,family_id:member.family_id,member_key:member.member_key,display_name:member.display_name,role:member.role,avatar_emoji:member.avatar_emoji||"👤"}};sessionStorage.setItem(TOKEN_KEY,token);sessionStorage.setItem(REALTIME_TOKEN_KEY,realtimeToken);sessionStorage.setItem(AUTH_KEY,JSON.stringify(auth));localStorage.setItem(MEMBER_KEY,member.member_key);localStorage.removeItem(AUTH_KEY);notify(true);return auth}
export function clearFamilyAuth(shouldNotify=true){try{sessionStorage.removeItem(TOKEN_KEY);sessionStorage.removeItem(REALTIME_TOKEN_KEY);sessionStorage.removeItem(AUTH_KEY);localStorage.removeItem(AUTH_KEY)}catch{}if(shouldNotify)notify(false)}
