import { createClient } from "./vendor/supabase-js.js";
import { SUPABASE_CONFIG } from "./config.js";
import { MEMBER_KEY, REALTIME_TOKEN_KEY, TOKEN_KEY, clearFamilyAuth, familyAuthExpiresAt, restoreFamilyAuth, saveFamilyAuth } from "./family-auth.js";

const $=selector=>document.querySelector(selector);
const storedAuth=restoreFamilyAuth();
const state={members:[],member:storedAuth?.member||null,token:storedAuth?.token||sessionStorage.getItem(TOKEN_KEY)||"",realtimeToken:storedAuth?.realtimeToken||sessionStorage.getItem(REALTIME_TOKEN_KEY)||"",deviceSessionExpires:null,messages:[],active:false,channel:null,sending:false,selectedId:"",selectedKey:storedAuth?.member?.member_key||localStorage.getItem(MEMBER_KEY)||"",membersLoading:false,membersError:"",oldest:null,settings:null,pushStatus:"idle",authExpiryTimer:null,initialScrollDone:false,realtimeNoticeTimer:null,realtimeNoticeHideTimer:null,reconnectTimer:null,realtimeNoticeVisible:false};
let authenticationRequired=false;
let authenticationWaiters=[];
let eventsBound=false;
const supabase=SUPABASE_CONFIG.url&&SUPABASE_CONFIG.publishableKey?createClient(SUPABASE_CONFIG.url,SUPABASE_CONFIG.publishableKey):null;

function scheduleAuthExpiry(){clearTimeout(state.authExpiryTimer);const expiresAt=familyAuthExpiresAt(state.token,state.realtimeToken);if(!expiresAt)return;state.authExpiryTimer=setTimeout(async()=>{logout(false);if(!await restoreDeviceSession()&&state.active)openLogin()},Math.max(0,expiresAt-Date.now()))}
function saveAuth(){saveFamilyAuth({token:state.token,realtimeToken:state.realtimeToken,member:state.member});scheduleAuthExpiry()}

async function request(url,options={}){
 const startedAt=performance.now();
 const {auth=true,...fetchOptions}=options,headers={"Content-Type":"application/json",...(fetchOptions.headers||{})};if(auth&&state.token)headers.Authorization=`Bearer ${state.token}`;
 const response=await fetch(url,{credentials:"same-origin",...fetchOptions,headers,cache:"no-store"});let data={};try{data=await response.json()}catch{};window.__studyTrackerStartupRequests?.push({label:url,ms:Math.round(performance.now()-startedAt),ok:response.ok});
 if(!response.ok){const error=new Error(data.error||"요청을 처리하지 못했어요.");error.status=response.status;error.code=data.code;error.apiMessage=data.message||null;error.details=data.details||null;error.lockedUntil=data.lockedUntil;throw error}return data;
}
function showToast(message){const el=$("#toast");if(!el)return;el.textContent=message;el.classList.add("show");window.clearTimeout(showToast.timer);showToast.timer=window.setTimeout(()=>el.classList.remove("show"),3200)}
function showNotice(message,error=false){const el=$("#familyChatNotice");el.classList.remove("fade-out");el.hidden=!message;el.textContent=message||"";el.classList.toggle("error",error)}
function clearRealtimeNoticeTimers(){clearTimeout(state.realtimeNoticeTimer);clearTimeout(state.realtimeNoticeHideTimer);state.realtimeNoticeTimer=null;state.realtimeNoticeHideTimer=null}
function hideRealtimeNotice(){clearRealtimeNoticeTimers();if(!state.realtimeNoticeVisible)return;state.realtimeNoticeHideTimer=setTimeout(()=>{const el=$("#familyChatNotice");if(el.hidden)return;el.classList.add("fade-out");state.realtimeNoticeHideTimer=setTimeout(()=>{state.realtimeNoticeVisible=false;showNotice("")},250)},750)}
function deferRealtimeNotice(){if(state.realtimeNoticeTimer||state.realtimeNoticeVisible||!navigator.onLine)return;state.realtimeNoticeTimer=setTimeout(()=>{state.realtimeNoticeTimer=null;if(state.active&&navigator.onLine){state.realtimeNoticeVisible=true;showNotice("실시간 연결을 다시 확인하고 있습니다...",true)}},2500)}
function setBadge(count){const el=$("#familyUnreadBadge");const value=Math.max(0,Number(count)||0);el.textContent=value>99?"99+":String(value);el.hidden=value===0}
function dateLabel(value){return new Intl.DateTimeFormat("ko-KR",{year:"numeric",month:"long",day:"numeric",weekday:"long"}).format(new Date(value))}
function timeLabel(value){return new Intl.DateTimeFormat("ko-KR",{hour:"2-digit",minute:"2-digit"}).format(new Date(value))}
function appendLinkedText(root,text){const re=/(https?:\/\/[^\s]+)/g;let last=0;for(const match of String(text).matchAll(re)){root.append(document.createTextNode(text.slice(last,match.index)));try{const url=new URL(match[0]);const a=document.createElement("a");a.href=url.href;a.target="_blank";a.rel="noopener noreferrer";a.textContent=match[0];root.append(a)}catch{root.append(document.createTextNode(match[0]))}last=match.index+match[0].length}root.append(document.createTextNode(text.slice(last)))}
function isNearBottom(list){return list.scrollHeight-list.scrollTop-list.clientHeight<96}
function appendMessageNodes(list,messages,day=""){
 let previousSenderId=list.querySelector(".family-message-row:last-of-type")?.dataset.senderId||"";
 for(const message of messages){
  const current=new Date(message.created_at).toDateString();
  if(current!==day){day=current;previousSenderId="";const divider=document.createElement("div");divider.className="family-date-divider";divider.textContent=dateLabel(message.created_at);list.append(divider)}
  if(message.message_type==="system"){const system=document.createElement("div");system.className="family-system-message";system.textContent=`🤖 ${message.content}`;list.append(system);previousSenderId="";continue}
  const mine=message.sender_id===state.member?.id,grouped=previousSenderId===message.sender_id,row=document.createElement("article");
  row.className=`family-message-row${mine?" mine":""}${grouped?" grouped":""}`;row.dataset.messageId=message.id;row.dataset.senderId=message.sender_id||"";
  const stack=document.createElement("div");stack.className="family-message-stack";
  if(!mine&&!grouped){const sender=document.createElement("div"),avatar=document.createElement("span"),name=document.createElement("p");sender.className="family-message-sender";avatar.className="family-message-avatar";avatar.textContent=message.sender?.avatar_emoji||"👤";name.className="family-message-name";name.textContent=message.sender?.display_name||"가족";sender.append(avatar,name);stack.append(sender)}
  const bubble=document.createElement("div");bubble.className="family-message-bubble";appendLinkedText(bubble,message.content);stack.append(bubble);const time=document.createElement("time");time.className="family-message-time";time.dateTime=message.created_at;time.textContent=timeLabel(message.created_at);stack.append(time);row.append(stack);list.append(row);previousSenderId=message.sender_id||"";
 }
 return day
}
function renderMessages({preserveTop=false,forceBottom=false}={}){
 const list=$("#familyMessageList"),oldTop=list.scrollTop,oldHeight=list.scrollHeight;list.replaceChildren();if(!state.messages.length){const empty=document.createElement("div");empty.className="empty";empty.textContent="아직 메시지가 없어요. 첫 인사를 남겨보세요!";list.append(empty);return}
 appendMessageNodes(list,state.messages);
 if(preserveTop)list.scrollTop=oldTop+list.scrollHeight-oldHeight;else if(forceBottom||!state.initialScrollDone)list.scrollTop=list.scrollHeight;else list.scrollTop=oldTop;
 state.initialScrollDone=true;
}
function appendMessages(messages,previousDay="",stickToBottom=false){if(!messages.length)return;const list=$("#familyMessageList"),oldTop=list.scrollTop;list.querySelector(".empty")?.remove();appendMessageNodes(list,messages,previousDay);list.scrollTop=stickToBottom?list.scrollHeight:oldTop;state.initialScrollDone=true;
}
function mergeMessages(messages){const map=new Map(state.messages.map(m=>[m.id,m]));for(const m of messages||[])map.set(m.id,m);state.messages=[...map.values()].sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));state.oldest=state.messages[0]?.created_at||null}
async function markRead(){if(!state.active||!state.token)return;const ids=state.messages.filter(m=>m.sender_id!==state.member?.id).map(m=>m.id);if(!ids.length){setBadge(0);return}try{await request("/api/family/read",{method:"POST",body:JSON.stringify({messageIds:ids.slice(-100)})});setBadge(0)}catch(e){console.warn("[family chat] read failed",e.message)}}
async function loadMessages({older=false,silent=false,appendOnly=false}={}){if(!state.token)return;try{const list=$("#familyMessageList"),oldTop=list.scrollTop,stickToBottom=isNearBottom(list),knownIds=new Set(state.messages.map(message=>message.id)),previousDay=new Date(state.messages.at(-1)?.created_at||0).toDateString(),suffix=older&&state.oldest?`?before=${encodeURIComponent(state.oldest)}&limit=50`:"?limit=50";const data=await request(`/api/family/messages${suffix}`),added=(data.messages||[]).filter(message=>!knownIds.has(message.id));mergeMessages(data.messages);if(appendOnly)appendMessages(added,previousDay,stickToBottom);else renderMessages({preserveTop:older,forceBottom:!older&&added.length>0&&stickToBottom});if(appendOnly&&!stickToBottom)list.scrollTop=oldTop;if(state.active)await markRead();else setBadge(data.unread);showNotice("")}catch(e){if(e.status===401){logout(false);if(state.active)openLogin()}else if(!silent)showNotice(navigator.onLine?"메시지를 불러오지 못했어요.":"인터넷 연결을 확인해 주세요.",true)}}
function stopRealtime(preserveNotice=false){clearTimeout(state.reconnectTimer);state.reconnectTimer=null;clearRealtimeNoticeTimers();if(!preserveNotice&&state.realtimeNoticeVisible){state.realtimeNoticeVisible=false;showNotice("")}const channel=state.channel;state.channel=null;if(channel&&supabase)supabase.removeChannel(channel)}
async function startRealtime(){stopRealtime(true);if(!supabase||!state.member||!state.realtimeToken)return;await supabase.realtime.setAuth(state.realtimeToken);const channel=supabase.channel(`family-chat-${state.member.id}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"family_messages",filter:`family_id=eq.${state.member.family_id}`},async()=>{await loadMessages({silent:true,appendOnly:true});if(state.active)await markRead()}).subscribe(status=>{if(state.channel!==channel)return;if(status==="SUBSCRIBED"){console.info("[family realtime] connected");hideRealtimeNotice()}if(["CHANNEL_ERROR","TIMED_OUT","CLOSED"].includes(status)&&state.active){console.info("[family realtime] reconnect pending",{status});if(!navigator.onLine){clearRealtimeNoticeTimers();state.realtimeNoticeVisible=true;showNotice("인터넷 연결이 없습니다.",true)}else deferRealtimeNotice();clearTimeout(state.reconnectTimer);state.reconnectTimer=setTimeout(()=>{if(state.active){startRealtime();loadMessages({silent:true})}},2500)}});state.channel=channel}
function renderMemberHeader(){const el=$("#familyCurrentMember");el.textContent=state.member?`${state.member.avatar_emoji||"👤"} ${state.member.display_name}님으로 접속 중`:`${state.selectedKey?"PIN을 입력해 다시 인증해 주세요.":"가족 사용자를 선택해 주세요."}`;$("#familyMessageInput").disabled=!state.token;$("#familySendButton").disabled=!state.token||state.sending;const allowed=Boolean(state.token&&state.member?.role==="parent");const pinButton=$("#familySelfPinButton"),parentPinButton=$("#parentChangePinButton");if(pinButton)pinButton.disabled=!allowed;if(parentPinButton)parentPinButton.disabled=!allowed;renderPushButton()}
function renderPushButton(){const button=$("#familyPushButton");if(!button)return;const supported="Notification" in window&&"serviceWorker" in navigator&&"PushManager" in window;if(!supported){button.textContent="알림 미지원";button.disabled=true;return}if(!state.token){button.textContent="🔔 알림 받기";button.disabled=true;return}if(Notification.permission==="denied"){button.textContent="🔕 알림이 차단됨";button.disabled=true;return}button.disabled=state.pushStatus==="working";button.textContent=state.pushStatus==="ready"?"🔔 알림 사용 중":state.pushStatus==="working"?"알림 설정 중...":"🔔 알림 받기"}
async function refreshPushStatus(){try{if(!state.token||!("Notification" in window)||!("serviceWorker" in navigator)||!("PushManager" in window))return;if(Notification.permission==="denied"){state.pushStatus="denied";renderPushButton();return}if(Notification.permission!=="granted")return;const registration=await navigator.serviceWorker.ready,sub=await registration.pushManager.getSubscription();state.pushStatus=sub?"ready":"idle";renderPushButton()}catch{}}
function resizeMessageInput(){const input=$("#familyMessageInput");if(!input)return;input.style.height="auto";input.style.height=`${Math.min(input.scrollHeight,116)}px`;}
function focusMessageInput(){const input=$("#familyMessageInput");if(!input||input.disabled)return;const focus=()=>{try{input.focus({preventScroll:true})}catch{input.focus()}};requestAnimationFrame(focus);setTimeout(focus,40)}
function updateFamilyViewport(){const height=window.visualViewport?.height||window.innerHeight;document.documentElement.style.setProperty("--family-viewport-height",`${Math.round(height)}px`)}
function renderChoices(){
 const root=$("#familyMemberChoices"),status=$("#familyMemberSelectionStatus");if(!root||!status)return;root.replaceChildren();
 if(state.membersLoading){status.textContent="가족 구성원을 불러오고 있어요.";return}
 if(state.membersError){status.textContent="가족 구성원을 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.";const retry=document.createElement("button");retry.type="button";retry.className="family-member-retry";retry.textContent="다시 시도";retry.addEventListener("click",()=>loadMembers());root.append(retry);return}
 if(!state.members.length){status.textContent="등록된 가족 구성원이 없습니다.";return}
 const selected=state.members.find(member=>member.id===state.selectedId||member.member_key===state.selectedKey),childSelected=selected?.role==="child",pinField=$("#familyPinField"),loginButton=$("#familyLoginButton"),rememberField=$("#rememberDeviceField");status.textContent=selected?childSelected?`${selected.avatar_emoji||"👤"} ${selected.display_name} 카드를 누르면 바로 시작해요.`:`${selected.avatar_emoji||"👤"} ${selected.display_name} 선택됨`:"가족 구성원을 선택해 주세요.";if(pinField)pinField.hidden=childSelected;if(loginButton)loginButton.hidden=childSelected;if(rememberField)rememberField.hidden=childSelected;
 for(const member of state.members){const isSelected=member.id===state.selectedId||member.member_key===state.selectedKey,button=document.createElement("button"),avatar=document.createElement("span"),name=document.createElement("strong"),check=document.createElement("span");button.type="button";button.className=`family-member-choice${isSelected?" selected":""}`;button.dataset.memberId=member.id;button.dataset.memberKey=member.member_key;button.setAttribute("aria-pressed",String(isSelected));avatar.className="family-member-choice-avatar";avatar.textContent=member.avatar_emoji||"👤";name.textContent=member.display_name;check.className="family-member-check";check.textContent=isSelected?"✓":"";button.append(avatar,name,check);button.addEventListener("click",async()=>{state.selectedId=member.id;state.selectedKey=member.member_key;$("#familyLoginError").textContent="";renderChoices();if(member.role==="child")await loginChild(member);else $("#familyPinInput").focus()});root.append(button)}
}
async function loadMembers(){state.membersLoading=true;state.membersError="";renderChoices();try{const data=await request("/api/family/members",{auth:Boolean(state.token)});console.info("[family members] response",{count:Array.isArray(data?.members)?data.members.length:0,members:data?.members});if(!Array.isArray(data?.members))throw new Error("Invalid members response.");state.members=data.members.filter(member=>member&&member.is_active!==false&&member.id&&member.member_key&&member.display_name).map(member=>({id:member.id,family_id:member.family_id||null,member_key:String(member.member_key),display_name:String(member.display_name),avatar_emoji:String(member.avatar_emoji||"👤"),role:member.role,is_active:member.is_active!==false,notifications_enabled:member.notifications_enabled!==false,device_count:Number(member.device_count||0)}));state.settings=data.settings||null;const selected=state.members.find(member=>member.member_key===state.selectedKey);state.selectedId=selected?.id||"";if(!selected&&state.selectedKey)state.selectedKey=""}catch(error){state.members=[];state.selectedId="";state.membersError="load-failed";console.error("[family members] request failed",{status:error.status||0,message:error.message})}finally{state.membersLoading=false;renderChoices();renderAdmin()}return state.members}
async function openLogin(){$("#familyLoginError").textContent="";const dialog=$("#familyLoginDialog"),wasOpen=dialog.open||dialog.hasAttribute("open");if(!wasOpen)$("#familyPinInput").value="";if(dialog.showModal&&!dialog.open)dialog.showModal();else dialog.setAttribute("open","");if(!wasOpen)await loadMembers()}
function closeDialog(dialog){dialog.close?.()||dialog.removeAttribute("open")}
function updateLoginGate(){const close=$("#closeFamilyLoginButton"),dialog=$("#familyLoginDialog");if(close)close.hidden=authenticationRequired;if(dialog)dialog.addEventListener("cancel",preventRequiredLoginClose)}
function preventRequiredLoginClose(event){if(authenticationRequired)event.preventDefault()}
function resolveAuthentication(){authenticationRequired=false;updateLoginGate();const waiters=authenticationWaiters;authenticationWaiters=[];for(const resolve of waiters)resolve(state.member)}
async function requireAuthentication(){if(state.token&&state.realtimeToken&&state.member)return state.member;authenticationRequired=true;updateLoginGate();const pending=new Promise(resolve=>authenticationWaiters.push(resolve));await openLogin();return pending}
function renderDeviceSession(){const parent=state.member?.role==="parent";if($("#deviceSessionMember"))$("#deviceSessionMember").textContent=parent?state.member.display_name:"-";if($("#deviceSessionState"))$("#deviceSessionState").textContent=state.deviceSessionExpires?"사용 중":"사용 안 함";if($("#deviceSessionExpires"))$("#deviceSessionExpires").textContent=state.deviceSessionExpires?new Date(state.deviceSessionExpires).toLocaleString("ko-KR"):"-";if($("#logoutCurrentDeviceButton"))$("#logoutCurrentDeviceButton").disabled=!state.deviceSessionExpires;if($("#logoutAllDevicesButton"))$("#logoutAllDevicesButton").disabled=!parent}
function applyLogin(data){state.token=data.token;state.realtimeToken=data.realtimeToken;state.member=data.member;state.deviceSessionExpires=data.expires_at||null;state.selectedId=data.member.id;state.selectedKey=data.member.member_key;sessionStorage.setItem(TOKEN_KEY,state.token);sessionStorage.setItem(REALTIME_TOKEN_KEY,state.realtimeToken);localStorage.setItem(MEMBER_KEY,state.member.member_key);saveAuth();closeDialog($("#familyLoginDialog"));resolveAuthentication();renderMemberHeader();renderDeviceSession();refreshPushStatus();void syncExistingPushSubscription()}
async function loginChild(member){const buttons=[...document.querySelectorAll(".family-member-choice")];try{buttons.forEach(button=>button.disabled=true);$("#familyMemberSelectionStatus").textContent=`${member.avatar_emoji||"👤"} ${member.display_name}(으)로 들어가는 중...`;const data=await request("/api/family/child-login",{method:"POST",auth:false,body:JSON.stringify({memberId:member.id})});applyLogin(data);await loadMembers();await loadMessages();if(state.active)startRealtime()}catch(error){$("#familyLoginError").textContent=error.status===404?"사용할 수 없는 자녀 계정이에요.":"로그인에 실패했습니다. 잠시 후 다시 시도해 주세요.";console.error("[family child login] failed",{status:error.status||0,message:error.message});buttons.forEach(button=>button.disabled=false);renderChoices()}}
async function login(event){event.preventDefault();const pin=$("#familyPinInput").value,selected=state.members.find(member=>member.id===state.selectedId&&member.member_key===state.selectedKey);if(!selected){$("#familyLoginError").textContent="가족 사용자를 선택해 주세요.";return}if(selected.role==="child"){await loginChild(selected);return}try{$("#familyLoginButton").disabled=true;const data=await request("/api/family/verify-pin",{method:"POST",auth:false,headers:{"X-Device-Name":navigator.platform||"browser"},body:JSON.stringify({memberKey:selected.member_key,pin,rememberDevice:$("#rememberDeviceInput")?.checked===true})});applyLogin(data);if(data.warningCode==="DEVICE_SESSION_SAVE_FAILED")console.warn("[family login] automatic login session was not saved",{code:data.warningCode});await loadMembers();await loadMessages();if(state.active)startRealtime()}catch(e){$("#familyLoginError").textContent=e.status===423?"5회 실패하여 30초 동안 잠겼어요.":e.status===401?"PIN이 맞지 않아요.":"로그인에 실패했습니다. 잠시 후 다시 시도해 주세요.";console.error("[family login] failed",{status:e.status||0,message:e.message,code:e.code||null,details:e.details||null})}finally{$("#familyLoginButton").disabled=false}}
function logout(show=true){stopRealtime();clearTimeout(state.authExpiryTimer);state.authExpiryTimer=null;state.initialScrollDone=false;state.token="";state.realtimeToken="";state.member=null;state.deviceSessionExpires=null;state.messages=[];clearFamilyAuth();renderMemberHeader();renderDeviceSession();renderMessages();if(show)openLogin()}
async function restoreDeviceSession(){if(state.token&&state.realtimeToken&&state.member)return true;try{const data=await request("/api/family/session",{auth:false});applyLogin(data);return true}catch(error){if(error.status!==401)console.warn("[device session] restore failed",{status:error.status||0,code:error.code||null});return false}}
async function logoutCurrentDevice(showLogin=true){try{await request("/api/family/logout",{method:"POST",auth:false})}catch{}if(showLogin)logout(true);else{state.deviceSessionExpires=null;renderDeviceSession();showToast("이 기기의 자동 로그인을 해제했습니다.")}}
async function logoutAllDevices(){if(!state.token||!confirm("모든 기기에서 로그아웃할까요?"))return;try{await request("/api/family/logout-all",{method:"POST"});showToast("모든 기기에서 로그아웃했습니다.");logout(true)}catch(e){showToast(e.message||"모든 기기 로그아웃에 실패했습니다.")}}
async function send(event){event.preventDefault();const input=$("#familyMessageInput"),content=input.value.trim();if(!content){focusMessageInput();return}if(state.sending)return;state.sending=true;renderMemberHeader();const clientMessageId=`web_${crypto.randomUUID?.()||`${Date.now()}_${Math.random().toString(36).slice(2)}`}`;try{const data=await request("/api/family/messages",{method:"POST",body:JSON.stringify({content,clientMessageId})}),exists=state.messages.some(message=>message.id===data.message.id),previousDay=new Date(state.messages.at(-1)?.created_at||0).toDateString();mergeMessages([data.message]);if(!exists)appendMessages([data.message],previousDay,true);else $("#familyMessageList").scrollTop=$("#familyMessageList").scrollHeight;input.value="";resizeMessageInput();await markRead();showNotice("")}catch(e){input.value=content;resizeMessageInput();showNotice("메시지 전송에 실패했어요. 내용은 남겨두었으니 다시 전송해 주세요.",true)}finally{state.sending=false;renderMemberHeader();focusMessageInput()}}
async function savePushSubscription(subscription){return request("/api/notifications/subscribe",{method:"POST",body:JSON.stringify({subscription:subscription.toJSON(),deviceName:navigator.platform||"브라우저"})})}
async function syncExistingPushSubscription(){if(!state.token||!("Notification" in window)||Notification.permission!=="granted"||!("serviceWorker" in navigator)||!("PushManager" in window))return;try{const registration=await navigator.serviceWorker.ready,subscription=await registration.pushManager.getSubscription();if(subscription)await savePushSubscription(subscription)}catch(error){console.error("[push subscription account sync failed]",{status:error.status||0,code:error.code||null,message:error.apiMessage||error.message,details:error.details||null,memberKey:state.member?.member_key||null,role:state.member?.role||null})}}
async function enablePush(){let stage="preflight";try{state.pushStatus="working";renderPushButton();if(!window.isSecureContext&&!["localhost","127.0.0.1"].includes(location.hostname))throw new Error("HTTPS에서만 알림을 켤 수 있어요.");if(!("Notification" in window)||!("serviceWorker" in navigator)||!("PushManager" in window))throw new Error("현재 브라우저는 Push 알림을 지원하지 않아요.");if(/iphone|ipad|ipod/i.test(navigator.userAgent)&&!matchMedia("(display-mode: standalone)").matches&&!navigator.standalone)throw new Error("iPhone에서는 홈 화면에 앱을 설치한 후 알림을 켜 주세요.");stage="notification-permission";const permission=Notification.permission==="default"?await Notification.requestPermission():Notification.permission;if(permission!=="granted")throw new Error("알림 권한이 허용되지 않았어요.");stage="service-worker";const registration=await navigator.serviceWorker.ready;let sub=await registration.pushManager.getSubscription();if(!sub){stage="public-key";const key=await request("/api/notifications/public-key");if(!key.configured||!key.publicKey)throw new Error("알림 서버 설정이 아직 완료되지 않았어요.");const value=key.publicKey,padding="=".repeat((4-value.length%4)%4),raw=atob((value+padding).replace(/-/g,"+").replace(/_/g,"/"));stage="push-manager-subscribe";sub=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:Uint8Array.from(raw,c=>c.charCodeAt(0))})}stage="api-subscribe";await savePushSubscription(sub);state.pushStatus="ready";showNotice("이 기기에서 가족방 알림을 받습니다.");await loadMembers()}catch(e){state.pushStatus=("Notification" in window&&Notification.permission==="denied")?"denied":"idle";console.error("[push subscribe failed]",{stage,status:e.status||0,code:e.code||e.name||null,message:e.apiMessage||e.message,details:e.details||null,memberKey:state.member?.member_key||null,role:state.member?.role||null});showNotice("알림 등록에 실패했습니다. 로그인 권한 또는 기기 알림 설정을 확인해 주세요.",true)}finally{renderPushButton()}}
function renderAdmin(){const root=$("#familyAdminList");if(!root)return;root.replaceChildren();const global=$("#familyChatNotificationsEnabled"),system=$("#familySystemNotificationsEnabled"),parent=state.member?.role==="parent";global.disabled=system.disabled=!parent;global.checked=state.settings?.chat_notifications_enabled!==false;system.checked=state.settings?.system_notifications_enabled!==false;if(!parent){const guide=document.createElement("p");guide.textContent="PIN을 변경하려면 아빠 또는 엄마로 인증해 주세요.";const authenticate=document.createElement("button");authenticate.type="button";authenticate.className="primary";authenticate.textContent="부모 사용자 인증하기";authenticate.addEventListener("click",()=>document.querySelector('[data-view="family-chat"]')?.click());root.append(guide,authenticate);return}for(const m of state.members){const row=document.createElement("div");row.className="family-admin-item";const label=document.createElement("strong");label.textContent=`${m.avatar_emoji||"👤"} ${m.display_name} · ${m.role==="parent"?"부모":"자녀"} · 기기 ${m.device_count||0}대`;const toggle=document.createElement("button");toggle.type="button";toggle.textContent=m.is_active?"활성":"비활성";toggle.addEventListener("click",async()=>{await request("/api/family/members",{method:"PATCH",body:JSON.stringify({memberId:m.id,isActive:!m.is_active})});await loadMembers()});const notification=document.createElement("button");notification.type="button";notification.textContent=m.notifications_enabled?"알림 켜짐":"알림 꺼짐";notification.addEventListener("click",async()=>{await request("/api/family/members",{method:"PATCH",body:JSON.stringify({memberId:m.id,notificationsEnabled:!m.notifications_enabled})});await loadMembers()});const pin=document.createElement("button");pin.type="button";pin.textContent="PIN 변경";pin.addEventListener("click",()=>{$("#familyPinMemberId").value=m.id;$("#familyPinTitle").textContent=`${m.display_name} PIN 변경`;$("#familyPinDialog").showModal()});row.append(label,toggle,notification,pin);root.append(row)}}
async function changePin(event){event.preventDefault();const pin=$("#familyNewPin").value,confirm=$("#familyConfirmPin").value;if(!/^\d{4}$/.test(pin)||pin!==confirm){$("#familyPinError").textContent="같은 4자리 PIN을 두 번 입력해 주세요.";return}try{await request("/api/family/pin",{method:"POST",body:JSON.stringify({memberId:$("#familyPinMemberId").value,pin})});closeDialog($("#familyPinDialog"));showNotice("PIN을 변경했어요.")}catch(e){$("#familyPinError").textContent=e.message}}
async function updateFamilySettings(){try{await request("/api/family/members",{method:"PATCH",body:JSON.stringify({familySettings:{chatNotificationsEnabled:$("#familyChatNotificationsEnabled").checked,systemNotificationsEnabled:$("#familySystemNotificationsEnabled").checked}})});await loadMembers()}catch(e){showNotice(e.message,true)}}
function pinValue(selector){return ($(selector)?.value||"").replace(/\D/g,"").slice(0,4)}
function cleanPinInput(event){event.currentTarget.value=event.currentTarget.value.replace(/\D/g,"").slice(0,4)}
function simplePin(pin){return new Set(["0000","1111","1234","4321"]).has(pin)||/^(\d)\1{3}$/.test(pin)}
function resetSelfPinForm(){for(const id of ["#familyCurrentPin","#familySelfNewPin","#familySelfConfirmPin"]){const input=$(id);input.value="";input.type="password"}document.querySelectorAll("[data-pin-visibility]").forEach(button=>{button.setAttribute("aria-pressed","false");button.setAttribute("aria-label",button.getAttribute("aria-label").replace("숨기기","표시"))})}
function openSelfPinDialog(){if(state.member?.role!=="parent")return;$("#familySelfPinError").textContent="";$("#familySelfPinMember").textContent=`${state.member.avatar_emoji||"👤"} ${state.member.display_name}`;resetSelfPinForm();const dialog=$("#familySelfPinDialog");if(dialog.showModal&&!dialog.open)dialog.showModal();else dialog.setAttribute("open","");$("#familyCurrentPin").focus()}
function togglePinVisibility(event){const button=event.currentTarget,input=document.getElementById(button.dataset.pinVisibility);if(!input)return;const visible=input.type==="text";input.type=visible?"password":"text";button.setAttribute("aria-pressed",String(!visible));button.setAttribute("aria-label",button.getAttribute("aria-label").replace(visible?"숨기기":"표시",visible?"표시":"숨기기"))}
async function changeSelfPin(event){event.preventDefault();if(state.member?.role!=="parent")return;const current=pinValue("#familyCurrentPin"),next=pinValue("#familySelfNewPin"),confirm=pinValue("#familySelfConfirmPin"),error=$("#familySelfPinError"),button=$("#familySelfPinSubmitButton");error.textContent="";if(!current||!next||!confirm){error.textContent="현재 PIN, 새 PIN, 새 PIN 확인을 모두 입력해 주세요.";return}if(!/^\d{4}$/.test(current)||!/^\d{4}$/.test(next)||!/^\d{4}$/.test(confirm)){error.textContent="PIN은 숫자 4자리로 입력해 주세요.";return}if(next!==confirm){error.textContent="새 PIN과 새 PIN 확인이 일치하지 않습니다.";return}if(current===next){error.textContent="새 PIN은 현재 PIN과 다르게 입력해 주세요.";return}if(simplePin(next)){error.textContent="0000, 1111, 1234처럼 너무 단순한 PIN은 사용할 수 없습니다.";return}button.disabled=true;const original=button.textContent;button.textContent="변경 중…";try{await request("/api/family/change-pin",{method:"POST",body:JSON.stringify({member_key:state.member.member_key,current_pin:current,new_pin:next})});resetSelfPinForm();closeDialog($("#familySelfPinDialog"));showToast("부모 PIN 번호가 변경되었습니다. 다음 로그인부터 새 PIN을 사용해주세요.")}catch(e){error.textContent=e.status?e.message:"PIN 번호를 변경하지 못했습니다. 잠시 후 다시 시도해주세요."}finally{button.disabled=false;button.textContent=original}}
function bind(){
 if(eventsBound)return;eventsBound=true;updateFamilyViewport();window.visualViewport?.addEventListener("resize",updateFamilyViewport);window.addEventListener("resize",updateFamilyViewport);$("#familySendButton")?.addEventListener("pointerdown",event=>{if(document.activeElement===$("#familyMessageInput"))event.preventDefault()});$("#familyMessageInput")?.addEventListener("keydown",event=>{if(event.isComposing||event.keyCode===229)event.stopImmediatePropagation()},{capture:true});
 $("#logoutCurrentDeviceButton")?.addEventListener("click",()=>logoutCurrentDevice(false));$("#logoutAllDevicesButton")?.addEventListener("click",logoutAllDevices);$("#familyChangeMemberButton")?.addEventListener("click",()=>request("/api/family/logout",{method:"POST",auth:false}).catch(()=>{}),{capture:true});
 $("#parentChangePinButton")?.addEventListener("click",openSelfPinDialog);document.querySelectorAll("[data-pin-visibility]").forEach(button=>button.addEventListener("click",togglePinVisibility));$("#closeFamilySelfPinButton")?.addEventListener("click",resetSelfPinForm);$("#cancelFamilySelfPinButton")?.addEventListener("click",resetSelfPinForm);
 const view=$("#family-chat"),messageInput=$("#familyMessageInput"),messageForm=$("#familyMessageForm");const updateFamilyMode=()=>document.body.classList.toggle("family-chat-mode",view?.classList.contains("active"));if(view){new MutationObserver(updateFamilyMode).observe(view,{attributes:true,attributeFilter:["class"]});updateFamilyMode()}messageInput?.addEventListener("input",resizeMessageInput);messageForm?.addEventListener("submit",()=>[0,250,750,1500,3000].forEach(delay=>window.setTimeout(resizeMessageInput,delay)));
 $("#familyLoginForm").addEventListener("submit",login);$("#closeFamilyLoginButton").addEventListener("click",()=>closeDialog($("#familyLoginDialog")));$("#familyChangeMemberButton").addEventListener("click",()=>logout(true));$("#familySelfPinButton")?.addEventListener("click",openSelfPinDialog);$("#familySelfPinForm")?.addEventListener("submit",changeSelfPin);$("#closeFamilySelfPinButton")?.addEventListener("click",()=>closeDialog($("#familySelfPinDialog")));$("#cancelFamilySelfPinButton")?.addEventListener("click",()=>closeDialog($("#familySelfPinDialog")));["#familyCurrentPin","#familySelfNewPin","#familySelfConfirmPin"].forEach(selector=>$(selector)?.addEventListener("input",cleanPinInput));$("#familyMessageForm").addEventListener("submit",send);$("#familyMessageInput").addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();$("#familyMessageForm").requestSubmit()}});$("#familyPushButton").addEventListener("click",enablePush);$("#familyPinForm").addEventListener("submit",changePin);$("#closeFamilyPinButton").addEventListener("click",()=>closeDialog($("#familyPinDialog")));$("#familyChatNotificationsEnabled").addEventListener("change",updateFamilySettings);$("#familySystemNotificationsEnabled").addEventListener("change",updateFamilySettings);$("#familyMessageList").addEventListener("scroll",async e=>{if(e.currentTarget.scrollTop<50&&state.oldest)await loadMessages({older:true})});window.addEventListener("online",()=>{if(state.active){startRealtime();loadMessages({silent:true})}});window.addEventListener("offline",()=>{clearRealtimeNoticeTimers();state.realtimeNoticeVisible=true;showNotice("인터넷 연결이 없습니다.",true)});
}
export async function initFamilyChat(){bind();renderMemberHeader();renderDeviceSession();refreshPushStatus();await restoreDeviceSession();await loadMembers();if(state.token&&state.realtimeToken){try{const chosen=state.members.find(m=>m.member_key===state.selectedKey);if(chosen)state.member=chosen;else throw new Error();saveAuth();renderMemberHeader();renderDeviceSession();refreshPushStatus()}catch{logout(false)}}else if(state.token)logout(false);return{isAuthenticated(){return Boolean(state.token&&state.realtimeToken&&state.member)},currentMember(){return state.member},changeUser(){logoutCurrentDevice(true)},requireAuthentication,setActive(active){state.active=active;if(active){if(!state.token)openLogin();else{startRealtime();loadMessages({silent:true})}}else stopRealtime()},refreshAdmin:renderAdmin}}

