import { TOKEN_KEY, clearFamilyAuth, restoreFamilyAuth } from "./family-auth.js";

const RETURN_KEY="study-tracker-family-return-to-v1";
const WALLET_MEMBER_KEY="study-tracker-reward-wallet-member-v1";
const $=selector=>document.querySelector(selector);
const state={data:null,dataUrl:"",loading:false,timer:null,active:false,editing:null,authChecking:true,authenticated:false,loadError:"",traceMemberKey:"",traceStarted:false,traceHistory:false,traceRendered:false};
let openFamily=()=>{},returnToRewards=()=>{},onStickerData=()=>{};

function token(){return restoreFamilyAuth()?.token||sessionStorage.getItem(TOKEN_KEY)||""}
function selectedWalletMember(){try{return localStorage.getItem(WALLET_MEMBER_KEY)||""}catch{return""}}
function saveSelectedWalletMember(memberId){try{if(memberId)localStorage.setItem(WALLET_MEMBER_KEY,memberId);else localStorage.removeItem(WALLET_MEMBER_KEY)}catch{}}
function rewardsUrl(){const auth=restoreFamilyAuth(),memberId=auth?.member?.role==="parent"?selectedWalletMember():"";return memberId?`/api/rewards?memberId=${encodeURIComponent(memberId)}`:"/api/rewards"}
async function request(url,options={}){const startedAt=performance.now(),auth=token();if(!auth){const e=new Error("가족 사용자 인증이 필요해요.");e.status=401;throw e}const response=await fetch(url,{...options,cache:"no-store",headers:{"Content-Type":"application/json",Authorization:`Bearer ${auth}`,...(options.headers||{})}});let data={};try{data=await response.json()}catch{}window.__studyTrackerStartupRequests?.push({label:url,ms:Math.round(performance.now()-startedAt),ok:response.ok});if(!response.ok){const e=new Error(data.error||"요청을 처리하지 못했어요.");e.status=response.status;e.code=data.code||null;e.details=data.details||null;e.hint=data.hint||null;throw e}return data}
function esc(value){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function validImage(value){try{const url=new URL(value);return ["http:","https:"].includes(url.protocol)?url.href:""}catch{return""}}
function formatDate(value,withTime=false){if(!value)return"-";return new Intl.DateTimeFormat("ko-KR",withTime?{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}:{year:"numeric",month:"numeric",day:"numeric"}).format(new Date(value))}
function stars(count){const n=Math.max(0,Math.min(Number(count)||0,30));return `${"⭐".repeat(n)}${Number(count)>30?` +${Number(count)-30}`:""}`||"아직 비어 있어요"}
function currentProduct(product){return product.is_active}
function close(dialog){dialog.close?.()||dialog.removeAttribute("open")}
function showToast(message){const el=$("#toast");if(!el)return;el.textContent=message;el.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>el.classList.remove("show"),2400)}

function resetStickerTrace(memberKey=""){state.traceMemberKey=memberKey;state.traceStarted=false;state.traceHistory=false;state.traceRendered=false}
function renderStickerSummary(status,balance){const summary=$("#stickerSummary"),count=$("#stickerCount");if(!summary||!count)return;if(status==="ready"){const value=Number(balance||0);count.textContent=String(value);summary.classList.remove("startup-skeleton");summary.dataset.state="ready";summary.setAttribute("aria-label",`현재 스티커 ${value}개`);if(!state.traceRendered){console.info("[sticker startup] final rendered sticker count:",value);state.traceRendered=true}return}count.textContent="-";summary.dataset.state=status;summary.setAttribute("aria-label",status==="error"?"스티커 조회 실패, 재시도 필요":"스티커 조회 중");summary.classList.toggle("startup-skeleton",status==="loading")}

function authNotice(){return `<div class="empty reward-auth"><h3>가족 사용자 인증이 필요해요</h3><p>가족방에서 하겸이로 인증하면 지갑과 보상상점을 이용할 수 있어요.</p><button type="button" class="primary" data-reward-open-family>가족 사용자 인증</button></div>`}
function renderWallet(){const data=state.data,balance=Number(data.balance||0),available=data.availableBalance??balance,field=$("#rewardWalletMemberField"),select=$("#rewardWalletMemberSelect"),children=(data.members||[]).filter(member=>member.role==="child"&&member.is_active);field.hidden=data.viewer?.role!=="parent"||!children.length;if(!field.hidden){select.innerHTML=children.map(member=>`<option value="${esc(member.id)}">${esc(member.display_name)}</option>`).join("");select.value=data.viewer.walletMemberId}$("#walletBalance").textContent=balance;$("#walletStars").textContent=stars(balance);$("#walletAvailable").textContent=`${data.viewer?.walletMemberName?`${data.viewer.walletMemberName} 지갑 · `:""}${available<balance?`교환 신청 예약분 제외 ${available}개`:"스티커는 원하는 보상으로 교환할 수 있어요."}`;renderStickerSummary("ready",balance);const list=$("#stickerTransactionList");list.innerHTML=data.transactions.length?data.transactions.map(row=>`<div class="sticker-transaction ${row.amount>0?"earn":"spend"}"><strong>${row.amount>0?"+":""}${row.amount}</strong><span>${esc(row.description)}</span><time>${formatDate(row.created_at,true)}</time></div>`).join(""):`<div class="empty">아직 적립·사용 내역이 없어요.</div>`}
function renderGoal(){const root=$("#rewardGoalWidget");if(!state.data){root.hidden=true;return}const product=state.data.products.filter(currentProduct).find(p=>state.data.wishlist.includes(p.id));if(!product){root.hidden=true;return}const balance=state.data.balance,percent=Math.min(100,Math.round(balance/product.sticker_cost*100));root.hidden=false;root.innerHTML=`<span>현재 목표</span><strong>${esc(product.emoji)} ${esc(product.name)}</strong><div class="goal-progress"><i style="width:${percent}%"></i></div><small>${balance} / ${product.sticker_cost}</small>`}
function productCard(product){const balance=state.data.availableBalance,wished=state.data.wishlist.includes(product.id),soldOut=product.stock===0,canBuy=balance>=product.sticker_cost&&!soldOut,img=validImage(product.image_url);return `<article class="store-product-card${soldOut?" sold-out":""}"><button type="button" class="wishlist-button${wished?" wished":""}" data-wishlist="${product.id}" aria-label="위시리스트">${wished?"♥":"♡"}</button><div class="product-visual">${img?`<img src="${esc(img)}" alt="" />`:`<span>${esc(product.emoji)}</span>`}</div><p class="product-category">${esc(product.category)}</p><h3>${esc(product.name)}</h3><p>${esc(product.description)}</p><strong class="product-cost">⭐ ${product.sticker_cost}</strong><small>${product.stock===null?"재고 무제한":soldOut?"품절":`재고 ${product.stock}개`}</small><button type="button" class="primary" data-exchange="${product.id}" ${canBuy?"":"disabled"}>${soldOut?"품절":balance<product.sticker_cost?"스티커 부족":"교환하기"}</button></article>`}
function renderStore(){const root=$("#rewardPanel");if(!state.data){root.innerHTML=authNotice();return}const products=state.data.products.filter(currentProduct),walletMemberId=state.data.viewer.walletMemberId;const pending=state.data.requests.filter(r=>r.status==="pending"&&r.member_id===walletMemberId);root.innerHTML=`<section class="store-balance"><span>${esc(state.data.viewer.walletMemberName||"현재")} 보유</span><strong>${stars(state.data.balance)}</strong><b>${state.data.balance}개</b>${state.data.availableBalance<state.data.balance?`<small>신청 예약 제외 사용 가능 ${state.data.availableBalance}개</small>`:""}</section>${pending.length?`<section class="pending-exchanges"><h3>교환 신청중</h3>${pending.map(r=>`<p>${esc(r.product_emoji)} ${esc(r.product_name)} · ⭐${r.sticker_cost} · ${formatDate(r.requested_at,true)}</p>`).join("")}</section>`:""}<div class="reward-store-grid">${products.length?products.map(productCard).join(""):`<div class="empty">현재 판매 중인 상품이 없어요.</div>`}</div><section class="exchange-history"><h3>교환 이력</h3>${state.data.requests.filter(r=>r.status!=="pending").length?state.data.requests.filter(r=>r.status!=="pending").map(r=>`<div><time>${formatDate(r.decided_at||r.requested_at)}</time><span>${esc(r.product_emoji)} ${esc(r.product_name)}</span><strong>${r.status==="approved"?`-${r.sticker_cost}`:"차감 없음"}</strong><em>${r.status==="approved"?"교환완료":"신청취소"}</em></div>`).join(""):`<p>아직 교환 이력이 없어요.</p>`}</section>`}
function renderAdmin(){const productRoot=$("#rewardProductAdminList"),requestRoot=$("#rewardRequestAdminList");if(!state.data||state.data.viewer.role!=="parent"){productRoot.innerHTML='<p class="reward-product-guide"><span aria-hidden="true">ℹ️</span><span>가족방에서 아빠 또는 엄마로 인증하면 관리할 수 있어요.</span></p>';requestRoot.innerHTML="<p>가족방에서 아빠 또는 엄마로 인증하면 관리할 수 있어요.</p>";return}productRoot.innerHTML=state.data.products.map(p=>`<div class="reward-admin-row"><span>${esc(p.emoji)} ${esc(p.name)} · ⭐${p.sticker_cost} · ${p.stock===null?"무제한":`재고 ${p.stock}`} · ${p.is_active?"활성":"비활성"}</span><div><button type="button" data-edit-product="${p.id}">수정</button><button type="button" class="delete-btn" data-delete-product="${p.id}">비활성화</button></div></div>`).join("")||"<p>등록된 상품이 없어요.</p>";const pending=state.data.requests.filter(r=>r.status==="pending");requestRoot.innerHTML=pending.length?pending.map(r=>`<article class="exchange-request-card"><strong>${esc(r.member?.avatar_emoji)} ${esc(r.member?.display_name||"가족")}</strong><span>${esc(r.product_emoji)} ${esc(r.product_name)}</span><small>⭐${r.sticker_cost} · ${formatDate(r.requested_at,true)}</small><div><button type="button" class="primary" data-decide="approve" data-request-id="${r.id}">승인</button><button type="button" data-decide="reject" data-request-id="${r.id}">거절</button></div></article>`).join(""):`<p>대기 중인 교환 신청이 없어요.</p>`}
function render(){if(state.authChecking||state.authenticated&&!state.data){const title=state.authChecking?"가족 인증 확인 중":"보상상점을 불러오지 못했어요",message=state.authChecking?"보상상점을 불러오고 있어요.":state.loadError||"잠시 후 다시 시도해 주세요.";renderStickerSummary(state.authChecking?"loading":"error");$("#rewardGoalWidget").hidden=true;$("#rewardPanel").innerHTML=`<div class="empty"><h3>${title}</h3><p>${esc(message)}</p></div>`;$("#rewardProductAdminList").innerHTML=$("#rewardRequestAdminList").innerHTML=`<p class="empty-note">${esc(message)}</p>`;return}if(!state.data){renderStickerSummary("loading");return}renderWallet();renderGoal();renderStore();renderAdmin()}

async function refresh({silent=false}={}){if(state.loading)return;const auth=restoreFamilyAuth();const memberKey=auth?.member?.member_key||"";if(!memberKey){state.authenticated=false;state.data=null;state.authChecking=false;render();return}const url=rewardsUrl();if(state.traceMemberKey!==memberKey)resetStickerTrace(memberKey);if(state.dataUrl!==url){state.data=null;state.authChecking=true}if(!state.traceStarted){console.info("[sticker startup] lookup started:",{member_key:memberKey,at:new Date().toISOString()});state.traceStarted=true}state.loading=true;state.authenticated=true;render();try{let data;let resolvedUrl=url;try{data=await request(url)}catch(error){if(error.status===404&&url.includes("memberId=")){saveSelectedWalletMember("");resolvedUrl="/api/rewards";data=await request(resolvedUrl)}else throw error}const currentMemberKey=restoreFamilyAuth()?.member?.member_key||"";if(currentMemberKey!==memberKey){const staleError=new Error("로그인 사용자가 변경되어 스티커 조회 결과를 취소했습니다.");staleError.code="STALE_STICKER_REQUEST";throw staleError}state.data=data;state.dataUrl=resolvedUrl;if(data.viewer.role==="parent")saveSelectedWalletMember(data.viewer.walletMemberId);if(!state.traceHistory){console.info("[sticker startup] actual sticker history count:",Number(data.stickerHistoryCount||0));state.traceHistory=true}onStickerData(data);state.loadError=""}catch(error){state.data=null;state.dataUrl="";if(error.code==="STALE_STICKER_REQUEST"){window.setTimeout(()=>refresh({silent:true}),0)}else if(error.status===401){clearFamilyAuth();state.authenticated=false}else{state.loadError=error.message;if(!silent)showToast(error.message)}}finally{state.loading=false;state.authChecking=false;render()}}
function scheduleRefresh(){clearTimeout(state.timer);state.timer=setTimeout(()=>refresh({silent:true}),250)}
function openExchange(id){const product=state.data?.products.find(p=>p.id===id);if(!product)return;$("#rewardExchangeProductId").value=id;$("#rewardExchangeTitle").textContent=`${product.name} 교환 신청`;$("#rewardExchangeSummary").innerHTML=`<p><span>보유</span><strong>${state.data.balance}개</strong></p><p><span>사용</span><strong>${product.sticker_cost}개</strong></p><p><span>승인 후 남은 스티커</span><strong>${state.data.balance-product.sticker_cost}개</strong></p><small>부모가 승인할 때 스티커가 차감됩니다.</small>`;$("#rewardExchangeError").textContent="";$("#rewardExchangeDialog").showModal()}
async function submitExchange(event){event.preventDefault();const button=$("#confirmRewardExchangeButton");button.disabled=true;try{await request("/api/rewards/exchange",{method:"POST",body:JSON.stringify({productId:$("#rewardExchangeProductId").value,memberId:state.data?.viewer?.walletMemberId,clientRequestId:`reward_${crypto.randomUUID?.()||`${Date.now()}_${Math.random().toString(36).slice(2)}`}`})});close($("#rewardExchangeDialog"));showToast("부모님께 교환을 신청했어요.");await refresh()}catch(error){$("#rewardExchangeError").textContent=error.message}finally{button.disabled=false}}
function resetProductForm(){state.editing=null;$("#rewardProductForm").reset();$("#rewardProductId").value="";$("#rewardProductActive").checked=true;$("#rewardProductSort").value="0";$("#rewardProductSubmit").textContent="상품 추가"}
function editProduct(id){const p=state.data?.products.find(item=>item.id===id);if(!p)return;state.editing=p;$("#rewardProductId").value=p.id;$("#rewardProductName").value=p.name;$("#rewardProductEmoji").value=p.emoji;$("#rewardProductCost").value=p.sticker_cost;$("#rewardProductStock").value=p.stock??"";$("#rewardProductCategory").value=p.category;$("#rewardProductSort").value=p.sort_order;$("#rewardProductDescription").value=p.description;$("#rewardProductImage").value=p.image_url;$("#rewardProductActive").checked=p.is_active;$("#rewardProductSubmit").textContent="상품 수정";$("#rewardProductForm").scrollIntoView({behavior:"smooth"})}
async function saveProduct(event){event.preventDefault();const id=$("#rewardProductId").value,payload={id,name:$("#rewardProductName").value,emoji:$("#rewardProductEmoji").value,stickerCost:$("#rewardProductCost").value,stock:$("#rewardProductStock").value,category:$("#rewardProductCategory").value,sortOrder:$("#rewardProductSort").value,description:$("#rewardProductDescription").value,imageUrl:$("#rewardProductImage").value,isActive:$("#rewardProductActive").checked};try{await request("/api/rewards/products",{method:id?"PATCH":"POST",body:JSON.stringify(payload)});resetProductForm();showToast("보상 상품을 저장했어요.");await refresh()}catch(error){console.error("[reward product] save failed",{message:error.message,code:error.code,details:error.details,hint:error.hint,payload});showToast(error.message)}}
async function decide(id,action){if(!confirm(action==="approve"?"교환을 승인하고 스티커를 차감할까요?":"교환 신청을 거절할까요?"))return;try{await request("/api/rewards/exchange",{method:"PATCH",body:JSON.stringify({requestId:id,action})});showToast(action==="approve"?"교환을 승인했어요.":"교환 신청을 거절했어요.");await refresh()}catch(error){showToast(error.message)}}
async function toggleWishlist(id){try{await request("/api/rewards/wishlist",{method:"POST",body:JSON.stringify({productId:id})});await refresh()}catch(error){showToast(error.message)}}
function bind(){document.addEventListener("click",async event=>{const family=event.target.closest("[data-reward-open-family]");if(family){if(token()){await refresh();return}sessionStorage.setItem(RETURN_KEY,"rewards");openFamily();return}const exchange=event.target.closest("[data-exchange]");if(exchange){openExchange(exchange.dataset.exchange);return}const wish=event.target.closest("[data-wishlist]");if(wish){await toggleWishlist(wish.dataset.wishlist);return}const edit=event.target.closest("[data-edit-product]");if(edit){editProduct(edit.dataset.editProduct);return}const remove=event.target.closest("[data-delete-product]");if(remove&&confirm("상품을 비활성화할까요?")){await request("/api/rewards/products",{method:"DELETE",body:JSON.stringify({id:remove.dataset.deleteProduct})});await refresh();return}const decision=event.target.closest("[data-decide]");if(decision)await decide(decision.dataset.requestId,decision.dataset.decide)});$("#rewardWalletMemberSelect").addEventListener("change",async event=>{saveSelectedWalletMember(event.currentTarget.value);await refresh()});window.addEventListener("family-auth-changed",async event=>{if(!event.detail?.authenticated){state.authenticated=false;state.data=null;state.authChecking=false;render();return}state.authenticated=true;state.authChecking=true;render();await refresh({silent:true});if(sessionStorage.getItem(RETURN_KEY)==="rewards"){sessionStorage.removeItem(RETURN_KEY);returnToRewards()}});$("#rewardExchangeForm").addEventListener("submit",submitExchange);$("#closeRewardExchangeButton").addEventListener("click",()=>close($("#rewardExchangeDialog")));$("#cancelRewardExchangeButton").addEventListener("click",()=>close($("#rewardExchangeDialog")));$("#rewardProductForm").addEventListener("submit",saveProduct);$("#rewardProductReset").addEventListener("click",resetProductForm)}

export async function initRewardStore(options={}){openFamily=options.openFamily||openFamily;returnToRewards=options.returnToRewards||returnToRewards;onStickerData=options.onStickerData||onStickerData;const auth=restoreFamilyAuth();resetStickerTrace(auth?.member?.member_key||"");if(auth?.member?.member_key)console.info("[sticker startup] restored member_key:",auth.member.member_key);bind();render();await refresh({silent:true});return{render,scheduleRefresh,refresh,setActive(active){state.active=active;if(active)refresh({silent:true})}}}
