const TOKEN_KEY="study-tracker-family-token-v1";
const $=selector=>document.querySelector(selector);
const state={data:null,loading:false,timer:null,active:false,editing:null};
let openFamily=()=>{};

function token(){return sessionStorage.getItem(TOKEN_KEY)||""}
async function request(url,options={}){const auth=token();if(!auth){const e=new Error("가족 사용자 인증이 필요해요.");e.status=401;throw e}const response=await fetch(url,{...options,cache:"no-store",headers:{"Content-Type":"application/json",Authorization:`Bearer ${auth}`,...(options.headers||{})}});let data={};try{data=await response.json()}catch{}if(!response.ok){const e=new Error(data.error||"요청을 처리하지 못했어요.");e.status=response.status;throw e}return data}
function esc(value){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function validImage(value){try{const url=new URL(value);return ["http:","https:"].includes(url.protocol)?url.href:""}catch{return""}}
function formatDate(value,withTime=false){if(!value)return"-";return new Intl.DateTimeFormat("ko-KR",withTime?{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}:{year:"numeric",month:"numeric",day:"numeric"}).format(new Date(value))}
function stars(count){const n=Math.max(0,Math.min(Number(count)||0,30));return `${"⭐".repeat(n)}${Number(count)>30?` +${Number(count)-30}`:""}`||"아직 비어 있어요"}
function currentProduct(product){return product.is_active}
function close(dialog){dialog.close?.()||dialog.removeAttribute("open")}
function showToast(message){const el=$("#toast");if(!el)return;el.textContent=message;el.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>el.classList.remove("show"),2400)}

function authNotice(){return `<div class="empty reward-auth"><h3>가족 사용자 인증이 필요해요</h3><p>가족방에서 하겸이로 인증하면 지갑과 보상상점을 이용할 수 있어요.</p><button type="button" class="primary" data-reward-open-family>가족 사용자 인증</button></div>`}
function renderWallet(){const data=state.data,balance=data?.balance||0,available=data?.availableBalance??balance;$("#walletBalance").textContent=balance;$("#walletStars").textContent=stars(balance);$("#walletAvailable").textContent=available<balance?`교환 신청 예약분을 제외한 사용 가능: ${available}개`:"스티커는 원하는 보상으로 교환할 수 있어요.";$("#stickerCount").textContent=balance;const list=$("#stickerTransactionList");if(!data){list.innerHTML=authNotice();return}list.innerHTML=data.transactions.length?data.transactions.map(row=>`<div class="sticker-transaction ${row.amount>0?"earn":"spend"}"><strong>${row.amount>0?"+":""}${row.amount}</strong><span>${esc(row.description)}</span><time>${formatDate(row.created_at,true)}</time></div>`).join(""):`<div class="empty">아직 적립·사용 내역이 없어요.</div>`}
function renderGoal(){const root=$("#rewardGoalWidget");if(!state.data){root.hidden=true;return}const product=state.data.products.filter(currentProduct).find(p=>state.data.wishlist.includes(p.id));if(!product){root.hidden=true;return}const balance=state.data.balance,percent=Math.min(100,Math.round(balance/product.sticker_cost*100));root.hidden=false;root.innerHTML=`<span>현재 목표</span><strong>${esc(product.emoji)} ${esc(product.name)}</strong><div class="goal-progress"><i style="width:${percent}%"></i></div><small>${balance} / ${product.sticker_cost}</small>`}
function productCard(product){const balance=state.data.availableBalance,wished=state.data.wishlist.includes(product.id),soldOut=product.stock===0,canBuy=balance>=product.sticker_cost&&!soldOut,img=validImage(product.image_url);return `<article class="store-product-card${soldOut?" sold-out":""}"><button type="button" class="wishlist-button${wished?" wished":""}" data-wishlist="${product.id}" aria-label="위시리스트">${wished?"♥":"♡"}</button><div class="product-visual">${img?`<img src="${esc(img)}" alt="" />`:`<span>${esc(product.emoji)}</span>`}</div><p class="product-category">${esc(product.category)}</p><h3>${esc(product.name)}</h3><p>${esc(product.description)}</p><strong class="product-cost">⭐ ${product.sticker_cost}</strong><small>${product.stock===null?"재고 무제한":soldOut?"품절":`재고 ${product.stock}개`}</small><button type="button" class="primary" data-exchange="${product.id}" ${canBuy?"":"disabled"}>${soldOut?"품절":balance<product.sticker_cost?"스티커 부족":"교환하기"}</button></article>`}
function renderStore(){const root=$("#rewardPanel");if(!state.data){root.innerHTML=authNotice();return}const products=state.data.products.filter(currentProduct);const pending=state.data.requests.filter(r=>r.status==="pending"&&r.member_id===state.data.viewer.id);root.innerHTML=`<section class="store-balance"><span>현재 보유</span><strong>${stars(state.data.balance)}</strong><b>${state.data.balance}개</b>${state.data.availableBalance<state.data.balance?`<small>신청 예약 제외 사용 가능 ${state.data.availableBalance}개</small>`:""}</section>${pending.length?`<section class="pending-exchanges"><h3>교환 신청중</h3>${pending.map(r=>`<p>${esc(r.product_emoji)} ${esc(r.product_name)} · ⭐${r.sticker_cost} · ${formatDate(r.requested_at,true)}</p>`).join("")}</section>`:""}<div class="reward-store-grid">${products.length?products.map(productCard).join(""):`<div class="empty">현재 판매 중인 상품이 없어요.</div>`}</div><section class="exchange-history"><h3>교환 이력</h3>${state.data.requests.filter(r=>r.status!=="pending").length?state.data.requests.filter(r=>r.status!=="pending").map(r=>`<div><time>${formatDate(r.decided_at||r.requested_at)}</time><span>${esc(r.product_emoji)} ${esc(r.product_name)}</span><strong>${r.status==="approved"?`-${r.sticker_cost}`:"차감 없음"}</strong><em>${r.status==="approved"?"교환완료":"신청취소"}</em></div>`).join(""):`<p>아직 교환 이력이 없어요.</p>`}</section>`}
function renderAdmin(){const productRoot=$("#rewardProductAdminList"),requestRoot=$("#rewardRequestAdminList");if(!state.data||state.data.viewer.role!=="parent"){productRoot.innerHTML='<p class="reward-product-guide"><span aria-hidden="true">ℹ️</span><span>가족방에서 아빠 또는 엄마로 인증하면 관리할 수 있어요.</span></p>';requestRoot.innerHTML="<p>가족방에서 아빠 또는 엄마로 인증하면 관리할 수 있어요.</p>";return}productRoot.innerHTML=state.data.products.map(p=>`<div class="reward-admin-row"><span>${esc(p.emoji)} ${esc(p.name)} · ⭐${p.sticker_cost} · ${p.stock===null?"무제한":`재고 ${p.stock}`} · ${p.is_active?"활성":"비활성"}</span><div><button type="button" data-edit-product="${p.id}">수정</button><button type="button" class="delete-btn" data-delete-product="${p.id}">비활성화</button></div></div>`).join("")||"<p>등록된 상품이 없어요.</p>";const pending=state.data.requests.filter(r=>r.status==="pending");requestRoot.innerHTML=pending.length?pending.map(r=>`<article class="exchange-request-card"><strong>${esc(r.member?.avatar_emoji)} ${esc(r.member?.display_name||"가족")}</strong><span>${esc(r.product_emoji)} ${esc(r.product_name)}</span><small>⭐${r.sticker_cost} · ${formatDate(r.requested_at,true)}</small><div><button type="button" class="primary" data-decide="approve" data-request-id="${r.id}">승인</button><button type="button" data-decide="reject" data-request-id="${r.id}">거절</button></div></article>`).join(""):`<p>대기 중인 교환 신청이 없어요.</p>`}
function render(){renderWallet();renderGoal();renderStore();renderAdmin()}

async function refresh({silent=false}={}){if(state.loading)return;state.loading=true;try{state.data=await request("/api/rewards");render()}catch(error){if(error.status===401){state.data=null;render()}else if(!silent)showToast(error.message)}finally{state.loading=false}}
function scheduleRefresh(){clearTimeout(state.timer);state.timer=setTimeout(()=>refresh({silent:true}),250)}
function openExchange(id){const product=state.data?.products.find(p=>p.id===id);if(!product)return;$("#rewardExchangeProductId").value=id;$("#rewardExchangeTitle").textContent=`${product.name} 교환 신청`;$("#rewardExchangeSummary").innerHTML=`<p><span>보유</span><strong>${state.data.balance}개</strong></p><p><span>사용</span><strong>${product.sticker_cost}개</strong></p><p><span>승인 후 남은 스티커</span><strong>${state.data.balance-product.sticker_cost}개</strong></p><small>부모가 승인할 때 스티커가 차감됩니다.</small>`;$("#rewardExchangeError").textContent="";$("#rewardExchangeDialog").showModal()}
async function submitExchange(event){event.preventDefault();const button=$("#confirmRewardExchangeButton");button.disabled=true;try{await request("/api/rewards/exchange",{method:"POST",body:JSON.stringify({productId:$("#rewardExchangeProductId").value,clientRequestId:`reward_${crypto.randomUUID?.()||`${Date.now()}_${Math.random().toString(36).slice(2)}`}`})});close($("#rewardExchangeDialog"));showToast("부모님께 교환을 신청했어요.");await refresh()}catch(error){$("#rewardExchangeError").textContent=error.message}finally{button.disabled=false}}
function resetProductForm(){state.editing=null;$("#rewardProductForm").reset();$("#rewardProductId").value="";$("#rewardProductActive").checked=true;$("#rewardProductSort").value="0";$("#rewardProductSubmit").textContent="상품 추가"}
function editProduct(id){const p=state.data?.products.find(item=>item.id===id);if(!p)return;state.editing=p;$("#rewardProductId").value=p.id;$("#rewardProductName").value=p.name;$("#rewardProductEmoji").value=p.emoji;$("#rewardProductCost").value=p.sticker_cost;$("#rewardProductStock").value=p.stock??"";$("#rewardProductCategory").value=p.category;$("#rewardProductSort").value=p.sort_order;$("#rewardProductDescription").value=p.description;$("#rewardProductImage").value=p.image_url;$("#rewardProductActive").checked=p.is_active;$("#rewardProductSubmit").textContent="상품 수정";$("#rewardProductForm").scrollIntoView({behavior:"smooth"})}
async function saveProduct(event){event.preventDefault();const id=$("#rewardProductId").value,payload={id,name:$("#rewardProductName").value,emoji:$("#rewardProductEmoji").value,stickerCost:$("#rewardProductCost").value,stock:$("#rewardProductStock").value,category:$("#rewardProductCategory").value,sortOrder:$("#rewardProductSort").value,description:$("#rewardProductDescription").value,imageUrl:$("#rewardProductImage").value,isActive:$("#rewardProductActive").checked};try{await request("/api/rewards/products",{method:id?"PATCH":"POST",body:JSON.stringify(payload)});resetProductForm();showToast("보상 상품을 저장했어요.");await refresh()}catch(error){showToast(error.message)}}
async function decide(id,action){if(!confirm(action==="approve"?"교환을 승인하고 스티커를 차감할까요?":"교환 신청을 거절할까요?"))return;try{await request("/api/rewards/exchange",{method:"PATCH",body:JSON.stringify({requestId:id,action})});showToast(action==="approve"?"교환을 승인했어요.":"교환 신청을 거절했어요.");await refresh()}catch(error){showToast(error.message)}}
async function toggleWishlist(id){try{await request("/api/rewards/wishlist",{method:"POST",body:JSON.stringify({productId:id})});await refresh()}catch(error){showToast(error.message)}}
function bind(){document.addEventListener("click",async event=>{const family=event.target.closest("[data-reward-open-family]");if(family){openFamily();return}const exchange=event.target.closest("[data-exchange]");if(exchange){openExchange(exchange.dataset.exchange);return}const wish=event.target.closest("[data-wishlist]");if(wish){await toggleWishlist(wish.dataset.wishlist);return}const edit=event.target.closest("[data-edit-product]");if(edit){editProduct(edit.dataset.editProduct);return}const remove=event.target.closest("[data-delete-product]");if(remove&&confirm("상품을 비활성화할까요?")){await request("/api/rewards/products",{method:"DELETE",body:JSON.stringify({id:remove.dataset.deleteProduct})});await refresh();return}const decision=event.target.closest("[data-decide]");if(decision)await decide(decision.dataset.requestId,decision.dataset.decide)});$("#rewardExchangeForm").addEventListener("submit",submitExchange);$("#closeRewardExchangeButton").addEventListener("click",()=>close($("#rewardExchangeDialog")));$("#cancelRewardExchangeButton").addEventListener("click",()=>close($("#rewardExchangeDialog")));$("#rewardProductForm").addEventListener("submit",saveProduct);$("#rewardProductReset").addEventListener("click",resetProductForm)}

export async function initRewardStore(options={}){openFamily=options.openFamily||openFamily;bind();render();await refresh({silent:true});return{render,scheduleRefresh,refresh,setActive(active){state.active=active;if(active)refresh({silent:true})}}}
