const assert=require("node:assert/strict");
const crypto=require("node:crypto");
const fs=require("node:fs");
const path=require("node:path");
const test=require("node:test");
const {parseCsv}=require("../scripts/learning-content-csv");
const {QUESTION_HEADERS,UNIT_HEADERS}=require("../scripts/generate-learning-content-csv-template");
const {importUnit}=require("../scripts/import-learning-content-csv");
const {generateMigration,generateRollback,generateVerification}=require("../scripts/generate-learning-content-migration");
const {validateLearningContent}=require("../scripts/validate-learning-content");
const root=path.join(__dirname,".."); const read=f=>fs.readFileSync(path.join(root,f),"utf8"); const sha=f=>crypto.createHash("sha256").update(fs.readFileSync(path.join(root,f))).digest("hex");
const curriculum=JSON.parse(read("content/learning/curriculum/math/grade-2-2022.json"));
const unitsPath=path.join(root,"content/learning/templates/grade2-math-units.csv"),questionsPath=path.join(root,"content/learning/authored/grade2-four-digit-numbers-v1.csv"),definitionsPath=path.join(root,"content/learning/authored/grade2-four-digit-numbers-skill-definitions-v1.csv");
const unitsRows=parseCsv(fs.readFileSync(unitsPath,"utf8"),UNIT_HEADERS,unitsPath),questionRows=parseCsv(fs.readFileSync(questionsPath,"utf8"),QUESTION_HEADERS,questionsPath),definitions=parseCsv(fs.readFileSync(definitionsPath,"utf8"),["skill_code","subject_code","display_name","description"],definitionsPath);
const content=JSON.parse(read("content/learning/math/grade2-four-digit-numbers-v1.json")); const questions=content.stages.flatMap(s=>s.questions); const at=(stage,order)=>content.stages.find(s=>s.difficulty===stage).questions[order-1]; const answer=q=>q.options.find(o=>o.isCorrect).text;
const migration=read("supabase/migrations/202608090012_seed_grade2_four_digit_numbers_learning_content.sql"),verification=read("supabase/verification/202608090012_seed_grade2_four_digit_numbers_learning_content_verify.sql"),rollback=read("supabase/rollbacks/202608090012_rollback_grade2_four_digit_numbers_learning_content.sql"),skillMigration=read("supabase/migrations/202608090011_add_grade2_four_digit_numbers_skill_definitions.sql"),skillVerification=read("supabase/verification/202608090011_add_grade2_four_digit_numbers_skill_definitions_verify.sql"),skillRollback=read("supabase/rollbacks/202608090011_rollback_grade2_four_digit_numbers_skill_definitions.sql");

test("four digit authored CSV deterministically produces canonical 4/40/160 content",()=>{const imported=importUnit({curriculum,unitsRows,questionRows,unitSlug:"grade2-four-digit-numbers"});assert.deepEqual(imported,content);assert.deepEqual(validateLearningContent(content),{valid:true,errors:[]});assert.equal(content.unit.displayOrder,7);assert.deepEqual(content.stages.map(s=>s.questions.length),[10,10,10,10]);assert.equal(questions.length,40);assert.equal(questions.flatMap(q=>q.options).length,160);});

test("nine new skills and seven general prior skills cover each question without redefining prior taxonomy",()=>{const newCodes=new Set(definitions.map(d=>d.skill_code));const reused=new Set(["identify-place-value","value-of-digit","understand-zero-placeholder","complete-number-sequence","infer-number-from-place-conditions","correct-comparison-order-error","correct-zero-place-value-error"]);assert.equal(newCodes.size,9);assert.ok(definitions.every(d=>d.subject_code==="math"&&d.display_name&&d.description));assert.deepEqual(new Set(questions.map(q=>q.skillCode).filter(code=>!newCodes.has(code))),reused);for(const code of reused)assert.doesNotMatch(skillMigration,new RegExp(`'${code}'`));});

test("answers are unique single and balanced by stage",()=>{const dist=qs=>[1,2,3,4].map(n=>qs.filter(q=>q.options.find(o=>o.isCorrect).displayOrder===n).length);assert.deepEqual(content.stages.map(s=>dist(s.questions)),[[3,3,2,2],[2,2,3,3],[3,3,2,2],[2,2,3,3]]);assert.deepEqual(dist(questions),[10,10,10,10]);assert.ok(questions.every(q=>q.options.filter(o=>o.isCorrect).length===1&&new Set(q.options.map(o=>o.text)).size===4));});

test("place values composition and zero placeholders remain exact",()=>{assert.equal(answer(at("seed",1)),"1000");assert.equal(answer(at("seed",6)),"700");assert.equal(answer(at("seed",7)),"6325");assert.equal(answer(at("seed",8)),"칠천십");assert.equal(answer(at("seed",10)),"5006");assert.equal(answer(at("leaf",1)),"천 4개, 백 0개, 십 2개, 일 0개");assert.equal(answer(at("leaf",4)),"5000+6");assert.equal(answer(at("tree",7)),"4039");assert.equal(answer(at("crown",8)),"700");});

test("compare order missing digit and card constraints are deterministic",()=>{assert.equal(answer(at("leaf",5)),"4321");assert.equal(answer(at("leaf",6)),"5608<5630");assert.equal(answer(at("tree",1)),"3025, 3205, 3250");assert.equal(answer(at("tree",3)),"5");assert.equal(answer(at("tree",4)),"8530");assert.equal(answer(at("tree",5)),"2047");assert.equal(answer(at("tree",6)),"6");assert.equal(answer(at("crown",1)),"5205");assert.equal(answer(at("crown",2)),"3019");assert.equal(answer(at("crown",5)),"4862");assert.equal(answer(at("crown",6)),"1");assert.equal(answer(at("crown",9)),"7506");assert.equal(answer(at("crown",10)),"2075");});

test("content differs from three digit work and explanations provide child-level reasoning",()=>{const text=JSON.stringify(content);assert.ok(questions.every(q=>q.explanation.trim().length>=15&&!/^정답입니다[.!]?$/.test(q.explanation.trim())));assert.ok(questions.filter(q=>/0/.test(q.prompt+q.explanation)).length>=15);assert.ok(questions.some(q=>/1000|천의 자리/.test(q.prompt)));assert.ok(questions.some(q=>/가장 큰|가장 작은|두 번째/.test(q.prompt)));assert.ok(questions.some(q=>/잘못/.test(q.prompt)));assert.doesNotMatch(text,/runtime AI|인공지능/);});

test("generated SQL and rollback preserve additive official and review boundaries",()=>{assert.equal(generateMigration(content),migration);assert.equal(generateVerification(content),verification);assert.equal(generateRollback(content),rollback);assert.match(migration,/Content-only and additive/);assert.match(verification,/grade2_four_digit_numbers_v1_question_skills_exact/);assert.match(rollback,/rollback blocked: grade2_four_digit_numbers_v1 content has assignment or learning history/);assert.match(skillRollback,/skill_codes_snapshot && target_skill_codes/);assert.equal((skillVerification.match(/from checks/g)||[]).length,2);for(const sql of [skillMigration,migration])assert.doesNotMatch(sql,/(?:insert into|update|delete from) public\.(?:learning_attempts|learning_attempt_answers|learning_stage_progress|learning_stage_first_passes|sticker_transactions|learning_mistake_review_answers)/i);});

test("all existing published content stays byte-identical",()=>{const expected={"content/learning/math/make-ten-v1.json":"3d2342b963ec5f26fc159c766b866858f7d230cb90bc60c9b577bb47aa1ccbc3","content/learning/math/make-ten-v2.json":"d640d6246a137cf08f43e29cb0b3d0e2ef3b27fb7ce917c356e7ea7959f4b91a","content/learning/math/grade2-three-digit-numbers-v1.json":"b527cbe047b4716691c3e08be1414bd956793394c74995cca7b4c1ebe0b17fbb","content/learning/math/grade2-shapes-v1.json":"4c8027ad3dd180b28f70260317eb4f8ef59cfb789524289733749e419462aae1","content/learning/math/grade2-addition-subtraction-v1.json":"70af1685be703597c121e223ec67ae05b46b9a205b96efe046cb25b4ce720d10","content/learning/math/grade2-measuring-length-v1.json":"de5a5522ecdf2d0425f18cb05f5ee52a2b921cb96c78cffd33b22c8e82a651c9","content/learning/math/grade2-classification-v1.json":"d8ad82389f3003fdf572b47eb7a857db0a1fb339b7437af80034ff0ef6961b4b","content/learning/math/grade2-multiplication-meaning-v1.json":"63eb5d1aa17e90c9bdbbc6ad2e02bca3c08a5e4945c6b70cc09a3151de4c7ef4","supabase/migrations/202608090009_add_grade2_multiplication_meaning_skill_definitions.sql":"2d01ba75368936f6d9d83f9744fcfc336b317f960ba3c86a07a26330eadf0d88","supabase/migrations/202608090010_seed_grade2_multiplication_meaning_learning_content.sql":"115203fdb99162298209e301d937982f0cab936530401061574d8eacc45a52ab"};assert.deepEqual(Object.fromEntries(Object.keys(expected).map(f=>[f,sha(f)])),expected);});
