const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const root=path.resolve(__dirname,".."),read=file=>fs.readFileSync(path.join(root,file),"utf8");

test("canonical onboarding projection is selected-Child scoped",async()=>{const m=await import(`../js/onboarding-learning.js?${Date.now()}`);const children=[{id:"a",is_active:true},{id:"b",is_active:true}];assert.equal(m.projectOnboardingState({role:"parent",children:[],selectedChildId:""}),"CHILD_REQUIRED");assert.equal(m.projectOnboardingState({role:"parent",children,selectedChildId:"b",planning:[]}),"LEARNING_SETUP_OPTIONAL");assert.equal(m.projectOnboardingState({role:"parent",children,selectedChildId:"b",planning:[{assignmentId:"x",plan:{id:"p"}}]}),"LEARNING_READY");assert.equal(m.projectOnboardingState({role:"parent",children,selectedChildId:"b",planning:[{assignmentId:"x",plan:null}]}),"LEARNING_SETUP_OPTIONAL");assert.equal(m.projectOnboardingState({role:"child",children,selectedChildId:"a",planning:[]}),"CHILD_APP")});

test("First Learning UX offers existing Learning reuse, safe skip and Child handoff",()=>{const html=read("index.html"),source=read("js/onboarding.js");for(const id of["onboardingLearningSetup","onboardingLearningChild","onboardingCreateLearningPlan","onboardingSkipLearning","onboardingStartChild"])assert.match(html,new RegExp(`id=["']${id}["']`));assert.match(source,/onOpenLearning/);assert.match(source,/onSkipLearning/);assert.match(source,/onHandoffChild/);assert.doesNotMatch(html.match(/id="onboardingLearningSetup"[\s\S]*?<\/section>/)?.[0]||"",/PIN|familyId|memberId/)});

test("App derives readiness from existing learning plans and opens the existing Parent Learning tab",()=>{const app=read("js/app.js");assert.match(app,/\/api\/learning\/plans\?assignedMemberId=/);assert.match(app,/projectOnboardingState/);assert.match(app,/setPlanAssignee/);assert.match(app,/parentTabLearning/);assert.match(app,/learningController\?\.refresh/);assert.doesNotMatch(app,/\/study\/plans[\s\S]{0,300}onboarding/i)});

test("Skip is a non-canonical session preference and reload projection remains server based",()=>{const app=read("js/app.js"),module=read("js/onboarding-learning.js");assert.match(module,/sessionStorage/);assert.match(module,/LEARNING_SETUP_OPTIONAL/);assert.match(app,/evaluateLearningOnboarding/);assert.doesNotMatch(module,/localStorage|stepNumber|onboardingComplete/)});

test("Handoff accepts only a canonical active Child while reusing PIN-less child-login",()=>{const family=read("js/family-chat.js");assert.match(family,/handoffToChild/);assert.match(family,/state\.member\?\.role!==["']parent["']/);assert.match(family,/state\.members\.find/);assert.match(family,/role===["']child["']/);assert.match(family,/loginChild\(child\)/);const login=family.match(/async function loginChild[\s\S]*?\nasync function login/)?.[0]||"";assert.match(login,/\/api\/family\/child-login/);assert.doesNotMatch(login,/pin|verify-pin/i)});

test("Child Today and attempt remain the existing Phase 2 implementation",()=>{const learning=read("js/learning.js");assert.match(learning,/오늘 해야 할 학습이 없어요/);assert.match(learning,/start-attempt/);assert.match(learning,/resume-attempt/);assert.match(learning,/deriveLearningToday/);assert.doesNotMatch(read("js/onboarding.js"),/start_or_resume_learning_attempt|learningAttemptFullscreenPanel/)});

test("Batch 4 adds no API route or migration and retains mobile accessibility",()=>{const router=read("api/[...path].js"),html=read("index.html"),css=read("css/styles.css");assert.doesNotMatch(router,/onboarding\/learning|learning\/setup/);assert.match(html,/onboardingLearningStatus[\s\S]*role="alert"/);assert.match(css,/onboarding-learning-actions/);assert.match(css,/min-height:\s*44px/);assert.equal(fs.readdirSync(path.join(root,"supabase/migrations")).filter(name=>name.includes("learning_setup")||name.includes("child_handoff")).length,0)});
