const crypto=require("crypto");
const push=require("../push/_utils");
function err(message,statusCode=400,code){const e=new Error(message);e.statusCode=statusCode;if(code)e.code=code;return e;}
function secret(){const value=push.env("FAMILY_AUTH_SECRET");if(!value||value.length<32){const error=err("Family authentication is not configured.",500,"FAMILY_AUTH_NOT_CONFIGURED");error.missingEnvironmentVariables=["FAMILY_AUTH_SECRET"];throw error}return value;}
function signToken(member){const payload=Buffer.from(JSON.stringify({sub:member.member_id||member.id,family:member.family_id,key:member.member_key,role:member.role,exp:Math.floor(Date.now()/1000)+28800})).toString("base64url");return `${payload}.${crypto.createHmac("sha256",secret()).update(payload).digest("base64url")}`;}
function signRealtimeToken(member){const jwtSecret=push.env("SUPABASE_JWT_SECRET");if(!jwtSecret){const error=err("Realtime authentication is not configured.",500,"REALTIME_AUTH_NOT_CONFIGURED");error.missingEnvironmentVariables=["SUPABASE_JWT_SECRET"];throw error}const header=Buffer.from(JSON.stringify({alg:"HS256",typ:"JWT"})).toString("base64url"),payload=Buffer.from(JSON.stringify({sub:member.member_id||member.id,aud:"authenticated",role:"authenticated",family_id:member.family_id,exp:Math.floor(Date.now()/1000)+28800})).toString("base64url"),input=`${header}.${payload}`;return `${input}.${crypto.createHmac("sha256",jwtSecret).update(input).digest("base64url")}`;}
function verify(raw){const [payload,sig]=String(raw||"").split(".");if(!payload||!sig)throw err("Authentication is required.",401);const expected=crypto.createHmac("sha256",secret()).update(payload).digest();const actual=Buffer.from(sig,"base64url");if(actual.length!==expected.length||!crypto.timingSafeEqual(actual,expected))throw err("Invalid authentication.",401);let c;try{c=JSON.parse(Buffer.from(payload,"base64url").toString())}catch{throw err("Invalid authentication.",401)}if(!c.sub||!c.family||c.exp<=Date.now()/1000)throw err("Authentication expired.",401);return c;}
function authenticate(req,role){const h=req.headers.authorization||"";const c=verify(h.startsWith("Bearer ")?h.slice(7):"");if(role&&c.role!==role)throw err("Parent permission is required.",403);return c;}
function allow(res,methods){res.setHeader("Allow",methods.join(", "));return push.json(res,405,{error:"Method not allowed."});}
function safe(row){return{id:row.id,family_id:row.family_id,sender_id:row.sender_id,message_type:row.message_type,content:row.content,related_type:row.related_type,related_id:row.related_id,client_message_id:row.client_message_id,created_at:row.created_at,sender:row.sender_id?{id:row.sender_id,display_name:row.sender_name,avatar_emoji:row.sender_avatar}:null};}
async function fetchMessages(family,before,limit){let q=`family_messages?select=id,family_id,sender_id,message_type,content,related_type,related_id,client_message_id,created_at,family_members!family_messages_sender_id_fkey(display_name,avatar_emoji)&family_id=eq.${encodeURIComponent(family)}&deleted_at=is.null&order=created_at.desc&limit=${Math.min(Math.max(Number(limit)||50,1),50)}`;if(before)q+=`&created_at=lt.${encodeURIComponent(before)}`;const rows=await push.supabaseFetch(q);return(rows||[]).map(r=>safe({...r,sender_name:r.family_members?.display_name,sender_avatar:r.family_members?.avatar_emoji})).reverse();}
async function sendPush(message,sender){try{const notifications=require("../notifications/_utils");const family=(await push.supabaseFetch(`families?select=chat_notifications_enabled,system_notifications_enabled&id=eq.${message.family_id}&limit=1`))?.[0];if(!family?.chat_notifications_enabled||(message.message_type==="system"&&!family.system_notifications_enabled))return;const isSystem=message.message_type==="system";let memberKeys;if(!isSystem){const members=await push.supabaseFetch(`family_members?select=member_key&family_id=eq.${message.family_id}&is_active=eq.true&member_key=neq.${encodeURIComponent(sender.member_key)}`);memberKeys=(members||[]).map(member=>member.member_key);if(!memberKeys.length)return}const body=isSystem?notifications.truncate(message.content,50):notifications.truncate(`${sender.display_name}: ${message.content}`,80),title=isSystem?"📚 학습 알림":"가족방 새 메시지";const result=await notifications.sendToFamily({familyId:message.family_id,memberKeys,excludeMemberKey:sender?.member_key,event:isSystem?"study_complete":"family_chat",payload:{title,body,icon:"/icons/icon-192.png",badge:"/icons/icon-192.png",url:"/?tab=family-chat",tag:`family-message-${message.id}`}});console.log("[family push]",{messageId:message.id,ok:result.success,failed:result.failure});await push.supabaseFetch(`family_messages?id=eq.${message.id}`,{method:"PATCH",body:JSON.stringify({push_sent_at:new Date().toISOString()})});}catch(e){console.warn("[family push] delivery failed",{messageId:message.id,statusCode:e.statusCode||500})}}
module.exports={allow,authenticate,env:push.env,err,fetchMessages,json:push.json,readJson:push.readJson,requireEnv:push.requireEnv,safe,sendPush,signRealtimeToken,signToken,supabaseFetch:push.supabaseFetch};
