\set ON_ERROR_STOP on

do $roles$
begin
  if not exists(select 1 from pg_roles where rolname='anon') then create role anon nologin; end if;
  if not exists(select 1 from pg_roles where rolname='authenticated') then create role authenticated nologin; end if;
  if not exists(select 1 from pg_roles where rolname='service_role') then create role service_role nologin bypassrls; end if;
end
$roles$;
create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

create table public.families(id uuid primary key, family_key text not null unique);
create table public.family_members(
  id uuid primary key,family_id uuid not null references public.families(id),member_key text not null,
  display_name text not null,role text not null,is_active boolean not null default true,
  pin_hash text,failed_attempts integer not null default 0,locked_until timestamptz,updated_at timestamptz not null default now(),
  unique(family_id,member_key),unique(family_id,id)
);
create table public.reward_settings(
  id bigint primary key generated by default as identity,
  target_stickers integer default 10,
  reward_name text,
  created_at timestamptz default now()
);
create table public.family_reward_settings(
  family_id uuid primary key references public.families(id),target_stickers integer not null,
  reward_name text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.reward_products(
  id uuid primary key,family_id uuid not null references public.families(id),name text not null,
  category text not null default '기타',sticker_cost integer not null,stock integer,
  sort_order integer not null default 0,emoji text not null default '🎁',description text,image_url text,
  is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
  unique(family_id,id),
  constraint reward_products_name_check check(char_length(btrim(name)) between 1 and 80),
  constraint reward_products_sticker_cost_check check(sticker_cost>0),
  constraint reward_products_stock_check check(stock is null or stock>=0),
  constraint reward_products_sort_order_check check(sort_order>=0)
);
create index reward_products_family_active_order_idx on public.reward_products(family_id,is_active,sort_order,created_at);
create table public.reward_exchange_requests(
  id uuid primary key default extensions.gen_random_uuid(),family_id uuid not null,member_id uuid not null,
  product_id uuid,product_name text not null,product_emoji text,sticker_cost integer not null,
  status text not null default 'pending',requested_at timestamptz not null default now(),decided_at timestamptz,
  decided_by uuid,rejection_reason text,client_request_id text not null unique,
  created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
  unique(family_id,id,member_id),
  foreign key(family_id,member_id) references public.family_members(family_id,id),
  foreign key(family_id,product_id) references public.reward_products(family_id,id)
);
create table public.sticker_transactions(
  id uuid primary key,family_id uuid not null,member_id uuid not null,amount integer not null
);

create function public.create_reward_exchange_request(uuid,uuid,uuid,text)
returns public.reward_exchange_requests language plpgsql as $function$
begin raise exception 'legacy fixture function must not execute'; end
$function$;
create function public.set_family_member_pin(uuid,uuid,text)
returns void language plpgsql as $function$
begin raise exception 'legacy fixture function must not execute'; end
$function$;

insert into public.families values
 ('10000000-0000-4000-8000-000000000001','default'),
 ('10000000-0000-4000-8000-000000000002','family-b');
insert into public.family_members(id,family_id,member_key,display_name,role,is_active,pin_hash) values
 ('20000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000001','parent-a','Parent A','parent',true,extensions.crypt('2468',extensions.gen_salt('bf',4))),
 ('20000000-0000-4000-8000-000000000002','10000000-0000-4000-8000-000000000001','child-a','Child A','child',true,extensions.crypt('1357',extensions.gen_salt('bf',4))),
 ('20000000-0000-4000-8000-000000000003','10000000-0000-4000-8000-000000000001','child-a2','Child A2','child',true,extensions.crypt('3579',extensions.gen_salt('bf',4))),
 ('20000000-0000-4000-8000-000000000004','10000000-0000-4000-8000-000000000002','parent-b','Parent B','parent',true,extensions.crypt('8642',extensions.gen_salt('bf',4))),
 ('20000000-0000-4000-8000-000000000005','10000000-0000-4000-8000-000000000002','child-b','Child B','child',true,extensions.crypt('7531',extensions.gen_salt('bf',4)));
insert into public.reward_settings(target_stickers,reward_name) values(17,'Legacy reward');
insert into public.reward_products(id,family_id,name,emoji,sticker_cost,stock,is_active) values
 ('40000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000001','Product A','A',5,10,true),
 ('40000000-0000-4000-8000-000000000002','10000000-0000-4000-8000-000000000002','Product B','B',5,10,true);
insert into public.sticker_transactions values
 ('50000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000002',30),
 ('50000000-0000-4000-8000-000000000002','10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000003',30);

create function public.fixture_expect_error(label text,statement text,expected text[])
returns void language plpgsql as $function$
begin
  begin execute statement;
  exception when others then
    if sqlstate=any(expected) then return; end if;
    raise exception '% raised %, expected %',label,sqlstate,expected;
  end;
  raise exception '% unexpectedly succeeded',label;
end
$function$;
