\set ON_ERROR_STOP on

do $roles$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then
    create role service_role nologin bypassrls;
  end if;
end
$roles$;

create table public.family_members (
  id uuid primary key,
  family_id uuid not null,
  role text not null,
  is_active boolean not null
);

create table public.book_plans (
  id uuid primary key,
  subject text,
  workbook text,
  chapter text,
  lesson text,
  content text,
  start_date date,
  study_weekdays smallint[],
  start_page integer,
  end_page integer,
  pages_per_day integer,
  goal text,
  memo text,
  expected_end_date date,
  updated_at timestamptz default statement_timestamp(),
  family_id uuid,
  assigned_member_id uuid,
  created_by_member_id uuid
);

create table public.study_plans (
  id bigint generated by default as identity primary key,
  subject text,
  workbook text,
  chapter text,
  lesson text,
  study_date date,
  day_label text,
  content text,
  goal text,
  status text,
  book_plan_id uuid,
  sequence_no integer,
  start_page integer,
  end_page integer,
  task_type text,
  note text,
  family_id uuid,
  assigned_member_id uuid,
  created_by_member_id uuid
);

create table public.academy_schedules (
  id uuid primary key default gen_random_uuid(),
  academy_name text not null,
  day_of_week integer not null check (day_of_week between 0 and 6),
  start_time time not null,
  memo text,
  star_count integer not null default 1 check (star_count > 0),
  created_at timestamptz not null default statement_timestamp(),
  family_id uuid,
  assigned_member_id uuid,
  created_by_member_id uuid
);

create table public.academy_completion_history (
  id uuid primary key,
  family_id uuid not null,
  member_id uuid not null,
  academy_schedule_id uuid not null
    references public.academy_schedules(id) on delete cascade,
  completed_date date not null,
  star_count integer not null default 1 check (star_count > 0),
  created_at timestamptz not null default statement_timestamp(),
  unique (member_id, academy_schedule_id, completed_date)
);

create table public.sticker_transactions (
  id bigint generated by default as identity primary key,
  family_id uuid not null,
  member_id uuid not null,
  amount integer not null check (amount <> 0),
  transaction_type text not null,
  source_type text not null,
  source_id text not null,
  description text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default statement_timestamp(),
  unique (member_id, source_type, source_id)
);

alter table public.book_plans enable row level security;
create policy "book_plans_existing_app_access"
  on public.book_plans
  for all
  to anon, authenticated
  using (true)
  with check (true);
grant select, insert, update, delete on public.book_plans to anon, authenticated, service_role;
grant select, insert, update, delete on public.study_plans to anon, authenticated, service_role;
alter table public.academy_schedules enable row level security;
create policy academy_schedules_existing_app_access
  on public.academy_schedules
  for all
  to anon, authenticated
  using (true)
  with check (true);
grant select, insert, update, delete
  on public.academy_schedules
  to anon, authenticated, service_role;
alter table public.academy_completion_history enable row level security;
create policy academy_completion_family_select
  on public.academy_completion_history
  for select
  to authenticated
  using (true);
grant select on public.academy_completion_history to authenticated, service_role;
grant select, insert, update, delete on public.academy_completion_history to service_role;
grant select, insert, update, delete on public.sticker_transactions to service_role;

create function public.reflow_book_plan_for_family(
  p_family_id uuid,
  p_actor_member_id uuid,
  p_book_plan_id uuid,
  p_from_date date
)
returns integer
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  perform 1 from public.book_plans
  where id = p_book_plan_id and family_id = p_family_id
  for update;
  if not found then raise exception using errcode = 'P0002', message = 'not found'; end if;
  update public.book_plans
  set updated_at = statement_timestamp()
  where id = p_book_plan_id and family_id = p_family_id;
  return 1;
end
$$;

create function public.add_book_plan_review_for_family(
  p_family_id uuid,
  p_actor_member_id uuid,
  p_book_plan_id uuid,
  p_after_sequence integer,
  p_content text
)
returns text
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare result_id bigint;
begin
  insert into public.study_plans (
    content, status, book_plan_id, sequence_no, task_type,
    family_id, assigned_member_id, created_by_member_id
  )
  select
    p_content, 'planned', plan.id, p_after_sequence + 1, 'review',
    plan.family_id, plan.assigned_member_id, plan.created_by_member_id
  from public.book_plans plan
  where plan.id = p_book_plan_id and plan.family_id = p_family_id
  returning id into result_id;
  if result_id is null then raise exception using errcode = 'P0002', message = 'not found'; end if;
  return result_id::text;
end
$$;

create function public.update_book_plan_pages_for_family(
  p_family_id uuid,
  p_actor_member_id uuid,
  p_book_plan_id uuid,
  p_pages_per_day integer
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  update public.book_plans
  set pages_per_day = p_pages_per_day, updated_at = statement_timestamp()
  where id = p_book_plan_id and family_id = p_family_id;
  if not found then raise exception using errcode = 'P0002', message = 'not found'; end if;
end
$$;

create function public.delete_book_plan_task_for_family(
  p_family_id uuid,
  p_actor_member_id uuid,
  p_study_plan_id text
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  delete from public.study_plans
  where id = p_study_plan_id::bigint
    and family_id = p_family_id
    and status <> 'done';
  if not found then raise exception using errcode = 'P0002', message = 'not found'; end if;
end
$$;

create function public.create_book_plan_for_member(
  uuid, uuid, uuid, text, text, text, text, text, date,
  integer, integer, integer, integer[], text, text
)
returns table(generated_count integer, first_study_date date, last_study_date date, generated_rows jsonb)
language sql security definer set search_path = pg_catalog, public
as $$ select 0, null::date, null::date, '[]'::jsonb $$;

create function public.create_reading_plan_for_member(
  uuid, uuid, uuid, text, text, integer, integer, integer[], date
)
returns table(reading_plan_id uuid, generated_count integer, first_study_date date, last_study_date date)
language sql security definer set search_path = pg_catalog, public
as $$ select null::uuid, 0, null::date, null::date $$;

create function public.complete_study_plan_with_reward_for_member(uuid, uuid, bigint, date)
returns table(completed_plan jsonb)
language sql security definer set search_path = pg_catalog, public
as $$ select '{}'::jsonb $$;

create function public.create_book_plan(
  text, text, text, text, text, date, integer, integer, integer, integer[], text, text
)
returns void language plpgsql security definer set search_path = public as $$ begin end $$;

create function public.complete_study_plan_and_reschedule(bigint, date)
returns void language plpgsql security definer set search_path = public as $$ begin end $$;

create function public.complete_academy_schedule(
  p_family_id uuid,
  p_member_id uuid,
  p_schedule_id uuid,
  p_completed_date date
)
returns public.academy_completion_history
language plpgsql
security definer
set search_path = public
as $$
declare
  schedule public.academy_schedules%rowtype;
  completion public.academy_completion_history%rowtype;
begin
  select *
  into schedule
  from public.academy_schedules
  where id = p_schedule_id
  for update;
  if not found then
    raise exception using errcode = 'P0002', message = 'not found';
  end if;

  insert into public.academy_completion_history (
    id,
    family_id,
    member_id,
    academy_schedule_id,
    completed_date,
    star_count
  )
  values (
    gen_random_uuid(),
    p_family_id,
    p_member_id,
    p_schedule_id,
    p_completed_date,
    schedule.star_count
  )
  on conflict (member_id, academy_schedule_id, completed_date)
  do update set star_count = excluded.star_count
  returning * into completion;

  insert into public.sticker_transactions (
    family_id,
    member_id,
    amount,
    transaction_type,
    source_type,
    source_id,
    description,
    metadata
  )
  values (
    p_family_id,
    p_member_id,
    completion.star_count,
    'earn',
    'academy_complete',
    completion.id::text,
    'academy completion',
    jsonb_build_object('academy_schedule_id', p_schedule_id)
  )
  on conflict (member_id, source_type, source_id)
  do update set amount = excluded.amount;

  return completion;
end
$$;

alter function public.reflow_book_plan_for_family(uuid, uuid, uuid, date) owner to postgres;
alter function public.add_book_plan_review_for_family(uuid, uuid, uuid, integer, text) owner to postgres;
alter function public.update_book_plan_pages_for_family(uuid, uuid, uuid, integer) owner to postgres;
alter function public.delete_book_plan_task_for_family(uuid, uuid, text) owner to postgres;
alter function public.create_book_plan_for_member(
  uuid, uuid, uuid, text, text, text, text, text, date,
  integer, integer, integer, integer[], text, text
) owner to postgres;
alter function public.create_reading_plan_for_member(
  uuid, uuid, uuid, text, text, integer, integer, integer[], date
) owner to postgres;
alter function public.complete_study_plan_with_reward_for_member(uuid, uuid, bigint, date) owner to postgres;
alter function public.create_book_plan(
  text, text, text, text, text, date, integer, integer, integer, integer[], text, text
) owner to postgres;
alter function public.complete_study_plan_and_reschedule(bigint, date) owner to postgres;
alter function public.complete_academy_schedule(uuid, uuid, uuid, date)
  owner to postgres;

revoke all on function public.reflow_book_plan_for_family(uuid, uuid, uuid, date) from public, anon, authenticated;
revoke all on function public.add_book_plan_review_for_family(uuid, uuid, uuid, integer, text) from public, anon, authenticated;
revoke all on function public.update_book_plan_pages_for_family(uuid, uuid, uuid, integer) from public, anon, authenticated;
revoke all on function public.delete_book_plan_task_for_family(uuid, uuid, text) from public, anon, authenticated;
revoke all on function public.create_book_plan_for_member(
  uuid, uuid, uuid, text, text, text, text, text, date,
  integer, integer, integer, integer[], text, text
) from public, anon, authenticated;
revoke all on function public.create_reading_plan_for_member(
  uuid, uuid, uuid, text, text, integer, integer, integer[], date
) from public, anon, authenticated;
revoke all on function public.complete_study_plan_with_reward_for_member(uuid, uuid, bigint, date)
  from public, anon, authenticated;
revoke all on function public.complete_academy_schedule(uuid, uuid, uuid, date)
  from public, anon, authenticated;

grant execute on function public.reflow_book_plan_for_family(uuid, uuid, uuid, date) to service_role;
grant execute on function public.add_book_plan_review_for_family(uuid, uuid, uuid, integer, text) to service_role;
grant execute on function public.update_book_plan_pages_for_family(uuid, uuid, uuid, integer) to service_role;
grant execute on function public.delete_book_plan_task_for_family(uuid, uuid, text) to service_role;
grant execute on function public.create_book_plan_for_member(
  uuid, uuid, uuid, text, text, text, text, text, date,
  integer, integer, integer, integer[], text, text
) to service_role;
grant execute on function public.create_reading_plan_for_member(
  uuid, uuid, uuid, text, text, integer, integer, integer[], date
) to service_role;
grant execute on function public.complete_study_plan_with_reward_for_member(uuid, uuid, bigint, date)
  to service_role;
grant execute on function public.complete_academy_schedule(uuid, uuid, uuid, date)
  to service_role;

grant execute on function public.create_book_plan(
  text, text, text, text, text, date, integer, integer, integer, integer[], text, text
) to anon, authenticated, service_role;
grant execute on function public.complete_study_plan_and_reschedule(bigint, date)
  to anon, authenticated, service_role;
