\set ON_ERROR_STOP on

do $roles$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then
    create role service_role nologin bypassrls;
  end if;
end
$roles$;

create table public.family_members (
  id uuid primary key,
  family_id uuid not null,
  role text not null,
  is_active boolean not null
);

create table public.book_plans (
  id uuid primary key,
  subject text,
  workbook text,
  chapter text,
  lesson text,
  content text,
  start_date date,
  study_weekdays smallint[],
  start_page integer,
  end_page integer,
  pages_per_day integer,
  goal text,
  memo text,
  expected_end_date date,
  updated_at timestamptz default statement_timestamp(),
  family_id uuid,
  assigned_member_id uuid,
  created_by_member_id uuid
);

create table public.study_plans (
  id bigint generated by default as identity primary key,
  subject text,
  workbook text,
  chapter text,
  lesson text,
  study_date date,
  day_label text,
  content text,
  goal text,
  status text,
  book_plan_id uuid,
  sequence_no integer,
  start_page integer,
  end_page integer,
  task_type text,
  note text,
  family_id uuid,
  assigned_member_id uuid,
  created_by_member_id uuid
);

alter table public.book_plans enable row level security;
create policy "book_plans_existing_app_access"
  on public.book_plans
  for all
  to anon, authenticated
  using (true)
  with check (true);
grant select, insert, update, delete on public.book_plans to anon, authenticated, service_role;
grant select, insert, update, delete on public.study_plans to anon, authenticated, service_role;

create function public.reflow_book_plan_for_family(
  p_family_id uuid,
  p_actor_member_id uuid,
  p_book_plan_id uuid,
  p_from_date date
)
returns integer
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  perform 1 from public.book_plans
  where id = p_book_plan_id and family_id = p_family_id
  for update;
  if not found then raise exception using errcode = 'P0002', message = 'not found'; end if;
  update public.book_plans
  set updated_at = statement_timestamp()
  where id = p_book_plan_id and family_id = p_family_id;
  return 1;
end
$$;

create function public.add_book_plan_review_for_family(
  p_family_id uuid,
  p_actor_member_id uuid,
  p_book_plan_id uuid,
  p_after_sequence integer,
  p_content text
)
returns text
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare result_id bigint;
begin
  insert into public.study_plans (
    content, status, book_plan_id, sequence_no, task_type,
    family_id, assigned_member_id, created_by_member_id
  )
  select
    p_content, 'planned', plan.id, p_after_sequence + 1, 'review',
    plan.family_id, plan.assigned_member_id, plan.created_by_member_id
  from public.book_plans plan
  where plan.id = p_book_plan_id and plan.family_id = p_family_id
  returning id into result_id;
  if result_id is null then raise exception using errcode = 'P0002', message = 'not found'; end if;
  return result_id::text;
end
$$;

create function public.update_book_plan_pages_for_family(
  p_family_id uuid,
  p_actor_member_id uuid,
  p_book_plan_id uuid,
  p_pages_per_day integer
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  update public.book_plans
  set pages_per_day = p_pages_per_day, updated_at = statement_timestamp()
  where id = p_book_plan_id and family_id = p_family_id;
  if not found then raise exception using errcode = 'P0002', message = 'not found'; end if;
end
$$;

create function public.delete_book_plan_task_for_family(
  p_family_id uuid,
  p_actor_member_id uuid,
  p_study_plan_id text
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  delete from public.study_plans
  where id = p_study_plan_id::bigint
    and family_id = p_family_id
    and status <> 'done';
  if not found then raise exception using errcode = 'P0002', message = 'not found'; end if;
end
$$;

create function public.create_book_plan_for_member(
  uuid, uuid, uuid, text, text, text, text, text, date,
  integer, integer, integer, integer[], text, text
)
returns table(generated_count integer, first_study_date date, last_study_date date, generated_rows jsonb)
language sql security definer set search_path = pg_catalog, public
as $$ select 0, null::date, null::date, '[]'::jsonb $$;

create function public.create_reading_plan_for_member(
  uuid, uuid, uuid, text, text, integer, integer, integer[], date
)
returns table(reading_plan_id uuid, generated_count integer, first_study_date date, last_study_date date)
language sql security definer set search_path = pg_catalog, public
as $$ select null::uuid, 0, null::date, null::date $$;

create function public.complete_study_plan_with_reward_for_member(uuid, uuid, bigint, date)
returns table(completed_plan jsonb)
language sql security definer set search_path = pg_catalog, public
as $$ select '{}'::jsonb $$;

create function public.create_book_plan(
  text, text, text, text, text, date, integer, integer, integer, integer[], text, text
)
returns void language plpgsql security definer set search_path = public as $$ begin end $$;

create function public.complete_study_plan_and_reschedule(bigint, date)
returns void language plpgsql security definer set search_path = public as $$ begin end $$;

alter function public.reflow_book_plan_for_family(uuid, uuid, uuid, date) owner to postgres;
alter function public.add_book_plan_review_for_family(uuid, uuid, uuid, integer, text) owner to postgres;
alter function public.update_book_plan_pages_for_family(uuid, uuid, uuid, integer) owner to postgres;
alter function public.delete_book_plan_task_for_family(uuid, uuid, text) owner to postgres;
alter function public.create_book_plan_for_member(
  uuid, uuid, uuid, text, text, text, text, text, date,
  integer, integer, integer, integer[], text, text
) owner to postgres;
alter function public.create_reading_plan_for_member(
  uuid, uuid, uuid, text, text, integer, integer, integer[], date
) owner to postgres;
alter function public.complete_study_plan_with_reward_for_member(uuid, uuid, bigint, date) owner to postgres;
alter function public.create_book_plan(
  text, text, text, text, text, date, integer, integer, integer, integer[], text, text
) owner to postgres;
alter function public.complete_study_plan_and_reschedule(bigint, date) owner to postgres;

revoke all on function public.reflow_book_plan_for_family(uuid, uuid, uuid, date) from public, anon, authenticated;
revoke all on function public.add_book_plan_review_for_family(uuid, uuid, uuid, integer, text) from public, anon, authenticated;
revoke all on function public.update_book_plan_pages_for_family(uuid, uuid, uuid, integer) from public, anon, authenticated;
revoke all on function public.delete_book_plan_task_for_family(uuid, uuid, text) from public, anon, authenticated;
revoke all on function public.create_book_plan_for_member(
  uuid, uuid, uuid, text, text, text, text, text, date,
  integer, integer, integer, integer[], text, text
) from public, anon, authenticated;
revoke all on function public.create_reading_plan_for_member(
  uuid, uuid, uuid, text, text, integer, integer, integer[], date
) from public, anon, authenticated;
revoke all on function public.complete_study_plan_with_reward_for_member(uuid, uuid, bigint, date)
  from public, anon, authenticated;

grant execute on function public.reflow_book_plan_for_family(uuid, uuid, uuid, date) to service_role;
grant execute on function public.add_book_plan_review_for_family(uuid, uuid, uuid, integer, text) to service_role;
grant execute on function public.update_book_plan_pages_for_family(uuid, uuid, uuid, integer) to service_role;
grant execute on function public.delete_book_plan_task_for_family(uuid, uuid, text) to service_role;
grant execute on function public.create_book_plan_for_member(
  uuid, uuid, uuid, text, text, text, text, text, date,
  integer, integer, integer, integer[], text, text
) to service_role;
grant execute on function public.create_reading_plan_for_member(
  uuid, uuid, uuid, text, text, integer, integer, integer[], date
) to service_role;
grant execute on function public.complete_study_plan_with_reward_for_member(uuid, uuid, bigint, date)
  to service_role;

grant execute on function public.create_book_plan(
  text, text, text, text, text, date, integer, integer, integer, integer[], text, text
) to anon, authenticated, service_role;
grant execute on function public.complete_study_plan_and_reschedule(bigint, date)
  to anon, authenticated, service_role;
