-- Generated by scripts/generate-learning-content-migration.js.
-- Source: content/learning/math/grade2-time-v1.json
-- Canonical content SHA-256: 4dd42cc233dec6339c6882bcdd7f75aa0a37e6d868461f4752fbdc26500aaac0
-- Content-only and additive: no assignment, attempt, progress, first-pass, ledger, ACL, or Realtime changes.

begin;

do $preflight$
begin
  if exists (
    select 1 from public.learning_courses
    where (id = '51000000-0000-4000-8000-000000000001'::uuid or course_code = 'math-core')
      and not (
        id = '51000000-0000-4000-8000-000000000001'::uuid
        and course_code = 'math-core'
        and internal_name = '수학 기초 과정'
        and subject_name = '수학'
      )
  ) then
    raise exception using errcode = '23505', message = 'grade2_time_v1 course identifier conflicts with different content';
  end if;

  if not exists (
    select 1 from public.learning_courses
    where id = '51000000-0000-4000-8000-000000000001'::uuid
      and course_code = 'math-core'
      and internal_name = '수학 기초 과정'
      and subject_name = '수학'
      and status = 'published'
  ) then
    raise exception using errcode = 'P0002', message = 'grade2_time_v1 existing course is missing or changed';
  end if;

  if exists (
    select 1 from public.learning_units
    where id = 'bb6cc6d7-e1e6-46e9-9d56-3bcb4b42550d'::uuid
       or unit_code = 'grade2-time'
  ) then
    raise exception using errcode = '23505', message = 'grade2_time_v1 unit identifier already exists';
  end if;

  if exists (
    select 1 from public.learning_units
    where course_id = '51000000-0000-4000-8000-000000000001'::uuid
      and sort_order = 11
  ) then
    raise exception using errcode = '23505', message = 'grade2_time_v1 unit sort order already exists';
  end if;

  if to_regclass('public.learning_unit_recommendation_metadata') is null then
    raise exception using errcode = 'P0002', message = 'learning recommendation metadata table is missing';
  end if;

  if exists (
    select 1
    from public.learning_unit_recommendation_metadata metadata
    where metadata.unit_id = 'bb6cc6d7-e1e6-46e9-9d56-3bcb4b42550d'::uuid
      and (
        metadata.subject is distinct from 'math'
        or metadata.recommended_start_level_code is distinct from 'elementary_2'
        or metadata.recommended_end_level_code is distinct from 'elementary_2'
        or metadata.parent_sort_order is distinct from 10
      )
  ) then
    raise exception using errcode = '23505', message = 'learning unit recommendation metadata conflicts with different content';
  end if;

  if to_regclass('public.learning_skill_definitions') is null
     or to_regclass('public.learning_question_skills') is null then
    raise exception using errcode = 'P0002', message = 'learning skill metadata foundation is missing';
  end if;

  if exists (
    select 1
    from (values
  ('read-clock-time'),
  ('use-five-minute-intervals'),
  ('calculate-time-after'),
  ('calculate-time-before'),
  ('distinguish-am-pm'),
  ('calculate-elapsed-time'),
  ('interpret-clock-hands'),
  ('correct-time-reasoning')
    ) expected_skill(skill_code)
    where not exists (
      select 1 from public.learning_skill_definitions definition
      where definition.skill_code = expected_skill.skill_code
    )
  ) then
    raise exception using errcode = 'P0002', message = 'learning skill definition is missing';
  end if;

  if exists (
    select 1 from public.learning_content_versions
    where id = '81f5083b-44b5-4344-8457-9522dbe74c97'::uuid
       or content_hash = '4dd42cc233dec6339c6882bcdd7f75aa0a37e6d868461f4752fbdc26500aaac0'
  ) then
    raise exception using errcode = '23505', message = 'grade2_time_v1 content version already exists';
  end if;

  if exists (
    select 1 from (
      values
  ('81a4c29f-f274-4e60-8608-cc42fcb6c541'::uuid),
  ('415a7931-2908-41d7-ad5e-7365e74d8876'::uuid),
  ('0bade680-571a-459e-aa2f-f824a43137a9'::uuid),
  ('a822b9e2-d1e4-4119-99f5-84972ffa4bbd'::uuid),
  ('3818994e-1446-49d0-b6e0-547dbb06c144'::uuid),
  ('ebd9cd93-a2a7-44c5-9077-964730c9db26'::uuid),
  ('bd84f1dd-305a-49f6-9739-52c652eae77d'::uuid),
  ('e9538d6e-6ad0-4fa8-a057-edf938634b37'::uuid),
  ('20cc2f45-4118-44dc-ada0-bd55b00d29cf'::uuid),
  ('bed0d5ec-67ac-4092-b623-122e293cc6fb'::uuid),
  ('23510083-f811-403d-a323-5d21c58aa36a'::uuid),
  ('cc24da79-915c-4d18-8e48-6d5729a6e4b0'::uuid),
  ('d274099a-7687-4ae2-87d3-6291e13aac94'::uuid),
  ('54aa7f11-bd83-4f1f-98b9-c7845191117a'::uuid),
  ('9a6d16d2-103b-453b-acba-ee89cb3ed4bf'::uuid),
  ('8720201d-5792-4f2b-9884-a97d49df3dc0'::uuid),
  ('7410ae05-c083-4b13-8a1d-43bde4d55efe'::uuid),
  ('f84676e1-41cf-4da4-bfe0-f63948d84f4f'::uuid),
  ('48ad17a3-5661-4dc8-95b6-dce8035c0569'::uuid),
  ('f7d0f319-c128-462c-ab09-2ef9c0a011d2'::uuid),
  ('da1b07db-bea3-49ba-9a50-411136956fe1'::uuid),
  ('e6898529-1d6a-4396-8364-ac09909692fe'::uuid),
  ('ac794063-753e-4ef8-bc4a-3cb81bd9f42f'::uuid),
  ('c0ce045b-ef91-4816-ac4f-30fb13e4963b'::uuid),
  ('8334c12b-4df9-4ef5-a9c9-c9076d72e787'::uuid),
  ('73ce8652-8548-40ff-99e4-2e03cdf2321c'::uuid),
  ('e20a5ee0-16c2-4355-84ce-f2095316b2d1'::uuid),
  ('5b1c8408-682f-431f-bd5b-974dae027ac3'::uuid),
  ('38951de1-c85a-4416-a02b-486d8f3b49d1'::uuid),
  ('16777806-f79b-49e1-b482-5a50a1d8aea0'::uuid),
  ('26ce412e-310e-4d37-8738-5090ddbbfcdd'::uuid),
  ('64f4d13b-3699-45af-8470-69525400d82d'::uuid),
  ('933c5d1f-f232-4abd-be14-29d42a34038a'::uuid),
  ('d1c96f31-9826-4d94-a0f1-58305dc12542'::uuid),
  ('3abd9f5b-0495-416e-99fd-6aa98d479d2e'::uuid),
  ('f6f49f34-4c96-498f-9cf9-8541983ecf22'::uuid),
  ('67622ef9-7597-4c48-9d0e-ce6976689907'::uuid),
  ('1e9c8732-9b47-4ae2-ae52-929c217c27d6'::uuid),
  ('bb9d6456-8264-47a1-91e0-628563614abd'::uuid),
  ('bacb84f3-afe5-4a08-a5cc-551b6b928db1'::uuid),
  ('3a7184e8-e2d5-4327-85ec-40055b8d0836'::uuid),
  ('14f42b5c-af11-49c7-9f64-46d40a7f9f04'::uuid),
  ('63cad63d-789c-481d-ac3f-0fe348ab9f29'::uuid),
  ('81dd26c7-17f4-49dd-a852-a74cc47c0399'::uuid),
  ('3e5ce115-44e7-40eb-8fb5-6efd5465b297'::uuid),
  ('87772183-3106-4690-ae5e-baf0bd02e91c'::uuid),
  ('7d1245d8-443f-4535-a3a7-5013d766e452'::uuid),
  ('651c4a4c-d2dc-45f9-9af1-bf3afe61740e'::uuid),
  ('14c3b689-a863-4f9d-bd13-43511e9c8e93'::uuid),
  ('8c7075d5-4e93-481c-b7cc-464dcb4a77f0'::uuid),
  ('d79b7ad9-4afa-4085-b27c-f260ee5d90dc'::uuid),
  ('f83ffafd-520c-4800-8f19-32ba9e801496'::uuid),
  ('fb0ab948-73d4-4127-a1ce-2d484cbba057'::uuid),
  ('96a79ec6-7d5f-48b9-902d-13fd48bce01b'::uuid),
  ('cf64662c-6e2d-4add-b40a-109135a8cc59'::uuid),
  ('aa0b9c64-4834-4602-af8d-67341e8b3d09'::uuid),
  ('10f7cc9c-82cb-41de-bfd6-926d5334e8e0'::uuid),
  ('30cdb1d9-eb4d-4717-ae94-1ce696513316'::uuid),
  ('de3042e4-d229-4d2f-8eb5-36a4940c0259'::uuid),
  ('d2684447-9837-4a38-b381-f8930b02d770'::uuid),
  ('41f0b0fd-4c2d-461b-8fe6-5975db996c20'::uuid),
  ('7cde75a2-33f9-4f1c-9544-3f2926f0250c'::uuid),
  ('09464608-aaf2-4aea-ac00-20d63ebd51b7'::uuid),
  ('868f3a8f-2182-4368-a2e7-849f1b143374'::uuid),
  ('2063ab16-b477-4bc2-ac6b-a3fb82b5c089'::uuid),
  ('a1ede1e6-8892-4d34-acb4-306acd93659e'::uuid),
  ('41c0a05d-d141-475f-b599-2f0fd6e240c3'::uuid),
  ('28208715-76f1-4d27-9214-e892ad51dc7d'::uuid),
  ('03fd7819-1db4-4ca6-aa1b-cd59f7ba2fbd'::uuid),
  ('fd26077b-1ee2-41a6-b36f-61f018a715d3'::uuid),
  ('4408cfbb-ecc3-45ef-a02f-b0964a551ecd'::uuid),
  ('aaee4ccc-9b82-4551-aef7-df7d0d5efd3d'::uuid),
  ('9dc24878-aa1d-44c9-99a0-f828bcd246b5'::uuid),
  ('f5518741-870b-4d76-b892-d84f8c3a4517'::uuid),
  ('fcbba247-906d-46ff-969a-52358ac0c17b'::uuid),
  ('efbc7335-622a-428f-ba29-b3faddbe87a7'::uuid),
  ('f744d5e1-b663-408c-a0c9-52a4e2bb515a'::uuid),
  ('6ba4979f-ac3e-48a7-9b74-30674c13c58a'::uuid),
  ('586ec7e3-b6eb-430a-b0f8-cd1cbc0f34b9'::uuid),
  ('9b6394c0-9f34-4c7c-a68e-b02987c749d7'::uuid),
  ('69e2953a-1540-4d3a-9f76-3c878d979c16'::uuid),
  ('b6d7feac-5111-4380-9fba-b2704c09de26'::uuid),
  ('8ad9a53a-a814-45db-a88b-d930b9194efa'::uuid),
  ('496d9ac7-c5f9-4338-82b1-aafca779c993'::uuid),
  ('c97b3827-a342-4661-91fb-9aca7cbb967e'::uuid),
  ('052a20ee-16f7-45a2-83ba-6f79db4f75e3'::uuid),
  ('76586d39-3805-42d2-933d-55ac325cda95'::uuid),
  ('eca9fc8a-f766-4f13-9db7-650527d440cc'::uuid),
  ('b81dfd4c-0d05-4db2-b142-1fff1d743c3c'::uuid),
  ('7b70a193-7d78-432f-b678-4e4f4d768e08'::uuid),
  ('b39120de-3dce-40f0-b868-a26f46735d8b'::uuid),
  ('889acc32-34ca-4a3a-b9c7-668209648b3e'::uuid),
  ('2250b9db-7cd0-4e4f-b062-66042009d96c'::uuid),
  ('21ce1f16-0d9b-4a83-b32a-e174cc05965b'::uuid),
  ('46e2de5d-df13-49a7-a27f-d37a95edd2e9'::uuid),
  ('249fd4c6-2f58-4bd9-8224-5ecb129a2528'::uuid),
  ('ad03dbcd-0562-4bf0-a925-d3e1d744d0da'::uuid),
  ('1b31e4ea-01d2-4d96-bca1-84bf1d31304c'::uuid),
  ('48a6f8ea-b46b-48f4-964f-a58e6fbcff72'::uuid),
  ('bdbc4a22-85fd-42c6-86d6-cd12a1bb36f9'::uuid),
  ('c2892225-36b2-4bea-a7e3-58dbc3a30c15'::uuid),
  ('50a33ae9-e7b5-4fb0-9fa9-b438afe5b034'::uuid),
  ('2fd2a08c-d952-4059-8f3d-1b1b09d43e21'::uuid),
  ('7d480400-7252-486d-9e0b-70eb1442f691'::uuid),
  ('b83e568f-807c-4538-95e5-7c924e0f66a6'::uuid),
  ('3be96bb5-0e82-4fad-93a8-9cb2a25ee7df'::uuid),
  ('3945a00f-3f12-4c98-aaf3-221eebfc8f9b'::uuid),
  ('9c8ac369-31d3-4016-aadc-cbe8d330fad2'::uuid),
  ('c03908d5-faf9-407c-a303-731f58148b42'::uuid),
  ('272710a6-91c3-4403-b1b1-33b177f59e8b'::uuid),
  ('5c390f35-a575-4596-8e82-31174e527aa1'::uuid),
  ('4db9bea6-d499-4ae8-bc0f-9a3fb4a10261'::uuid),
  ('40250631-c215-4995-aa06-48c495c9df68'::uuid),
  ('7448c6a9-4b15-4bd2-8619-0958976f6a6f'::uuid),
  ('7d60e0fc-6bff-44f7-a6d9-efc554e476f0'::uuid),
  ('a1478628-f0b4-494d-8fe4-936ef6975afe'::uuid),
  ('d634c73b-fb90-4550-a050-4ce36fa2f8e9'::uuid),
  ('eb09ccac-73ca-4c33-8746-c47a08a37e30'::uuid),
  ('9fd41ca5-9696-444f-8a83-c4376014306d'::uuid),
  ('8a08864a-8ef2-47ca-b08b-419421ffe75e'::uuid),
  ('dabe654d-31f2-4ef2-b441-f85dbf7bb6a6'::uuid),
  ('4147bd31-b03a-4532-886f-92beaee9fe76'::uuid),
  ('5653b83e-b2d1-47f5-8361-c0bf1d7edbc7'::uuid),
  ('2c3faef7-955e-49fd-909d-bbefaed18480'::uuid),
  ('50c7146c-a77a-4d43-b7f1-84a306830aaa'::uuid),
  ('23234a69-532e-4153-9010-d9e98fbb601e'::uuid),
  ('a62ef26e-83b6-458c-adee-5d797fbf7f77'::uuid),
  ('e6b6979e-f391-4525-8d9a-82262f6d893b'::uuid),
  ('7bab11f1-aa2b-4ca9-83b6-ddf629afcc69'::uuid),
  ('f10196f1-ee5a-41e9-b78e-6dcd9e544486'::uuid),
  ('16aa7261-b851-40b0-87cf-9f10ab8d940b'::uuid),
  ('ec7846a5-5971-4043-9e43-f514f3a1f20d'::uuid),
  ('589f22ba-b00a-4757-adf3-e982fb64ce2f'::uuid),
  ('bac07fb8-be23-4509-adc2-164d9399aa05'::uuid),
  ('139a71f2-84fb-41c0-9883-51ca1c11f8f3'::uuid),
  ('30c2cbeb-c959-42da-93cc-82c55b2653de'::uuid),
  ('8c5c5b33-f31f-4725-b165-a67f7a2b3a2d'::uuid),
  ('09d73fe1-c451-4be0-bfbc-49242978f9b1'::uuid),
  ('f686cdcf-7f47-4a63-896b-5fe274fa67fe'::uuid),
  ('3dfcb048-459f-4cb0-97dd-c76ef1faefdc'::uuid),
  ('9a7b8441-fa67-465c-a586-a0c88c1291a2'::uuid),
  ('9abf62bb-b33c-4e3b-b738-6a3b81b62263'::uuid),
  ('677f773b-fd88-4c66-b10c-9c866cc16326'::uuid),
  ('3b481696-b5a0-478e-b563-56672f9217f1'::uuid),
  ('b9dce2d6-1bfe-49d6-9dbb-8ac3fb30181a'::uuid),
  ('30db0655-cb88-4175-b893-646585eec226'::uuid),
  ('8fe997fc-d630-490f-83b8-0a0ca188f5e9'::uuid),
  ('199f03c4-5ce0-4b20-bd66-a476dc61e0ff'::uuid),
  ('75d46cda-f79b-4c31-af23-d5d40742c474'::uuid),
  ('56f15e49-354e-4453-9c67-7d56b82c9430'::uuid),
  ('363139ed-9f4a-4826-a0f2-41045ac9ee0f'::uuid),
  ('f9098620-e0ba-4004-aad1-7c1fe52ef8cd'::uuid),
  ('7329d0f6-e995-4044-a9e3-b596c54a9266'::uuid),
  ('162ba18a-cd90-4bf2-bc02-6234194bd907'::uuid),
  ('8b744d42-f6cf-48fc-8903-b5eeb61d11bd'::uuid),
  ('ee071734-eb6f-45de-9dee-b7a64284ce3c'::uuid),
  ('aa96f19f-d788-4a34-bfde-24ddeefa0c73'::uuid),
  ('c5b16cfe-a548-4ec3-b8e3-a43a161c1e12'::uuid),
  ('24e80355-1655-43e0-add0-9a3a7170c55a'::uuid),
  ('03363e62-e62c-40e1-8d1c-0c3ce4391c5e'::uuid),
  ('443807b2-613a-44d7-b9fc-2dc35704cd64'::uuid),
  ('ea53af1e-c5f0-4ff0-92ab-5997045b87c4'::uuid),
  ('ea800493-08df-4e5a-a209-34bdf62e28d0'::uuid),
  ('a23baa4b-afae-43bc-9ed5-c3b812936d30'::uuid),
  ('98b8581e-81b6-47f2-897f-56c099929ad0'::uuid),
  ('7f13be7a-d428-44c8-9e0d-28978681be25'::uuid),
  ('098f8062-4000-4c79-8d1c-72c4a654404a'::uuid),
  ('2795d988-b2b4-4160-8b5c-04edf51cef76'::uuid),
  ('b56080b7-d1cd-4ad9-9f6f-2a6349cb9b3d'::uuid),
  ('a46c33a2-71ac-4261-af6f-0ed0b99e9a6d'::uuid),
  ('1652a899-c48f-4968-8643-13171df2637a'::uuid),
  ('9fdacfc0-8121-46f9-a9c6-7b6e2141d7d4'::uuid),
  ('b1c15edd-072c-427a-9d4c-281d1d566ab5'::uuid),
  ('d004a648-b0b6-4a49-a4ca-546248da0d77'::uuid),
  ('0e76dcdc-2ac4-4fc5-8fa8-3135c01db8a9'::uuid),
  ('1be15a33-3070-49db-a1bd-d1a36676d222'::uuid),
  ('ddff6326-1183-4f24-83db-f9cd1cd000a2'::uuid),
  ('ca7f7da2-b71a-4046-9774-a9653a0f6769'::uuid),
  ('d89706c5-356a-408d-b59b-93b195e8a582'::uuid),
  ('a18da500-834e-4ca9-b921-1b979a3664d2'::uuid),
  ('2f0923e5-71b7-48f4-8149-8b2dbfa1358b'::uuid),
  ('1308a42c-be75-4510-875b-66ebb12423b2'::uuid),
  ('7a2024d3-f67f-45dd-a261-6cc35b608398'::uuid),
  ('a756bc20-4f47-49a5-b6db-5c9ee5ab61af'::uuid),
  ('1c7ba565-2fbd-4332-847a-69539ac9dc6f'::uuid),
  ('26e13003-7a7d-4083-b7e1-d659521e679a'::uuid),
  ('2ecb56d8-3b75-4521-99bd-5309d7fdb2c3'::uuid),
  ('6220fa0c-907b-4a4b-90f4-8e9eaa4baa55'::uuid),
  ('8ad518e8-4ee3-4d1c-aa31-f687867d000f'::uuid),
  ('74883261-125d-4451-a167-aad136c4936c'::uuid),
  ('4215e911-7362-48e2-a871-7f522cff6ce6'::uuid),
  ('bb59e7f3-0293-4e8f-89a0-3cb5b9aa1d3e'::uuid),
  ('c9c63247-1c3e-477c-9ee1-5dd356e89e01'::uuid),
  ('341dfe49-efb2-413e-b49a-0c98bd624463'::uuid),
  ('7ddc711c-5868-425d-a05f-848bc30008be'::uuid),
  ('e3f55ddd-c093-42e4-903a-06972b748718'::uuid),
  ('ccd3417f-6c8b-495c-a669-f1b04b6090cf'::uuid),
  ('b8fb8579-832b-42e6-8b08-6ea419d2fcee'::uuid),
  ('2244ff09-8ef5-4b1b-b15f-60ebd8630166'::uuid),
  ('9c708d11-fb4e-4f78-9f51-3ed8cd2ba830'::uuid),
  ('fff43af4-90a5-4d7c-a2a3-194313a29d3c'::uuid),
  ('d66f7326-5211-41fb-baff-256f7b3e1e44'::uuid),
  ('c5f61002-07ab-4b55-8d7b-20acaea45e6e'::uuid),
  ('20051a26-4356-4550-8190-910ca545b9d3'::uuid)
    ) as expected_id(id)
    where exists (
      select 1 from public.learning_stages where id = expected_id.id
      union all
      select 1 from public.learning_questions where id = expected_id.id
      union all
      select 1 from public.learning_question_options where id = expected_id.id
    )
  ) then
    raise exception using errcode = '23505', message = 'grade2_time_v1 child content identifier already exists';
  end if;
end
$preflight$;

insert into public.learning_units (id, course_id, unit_code, display_title, sort_order)
values ('bb6cc6d7-e1e6-46e9-9d56-3bcb4b42550d', '51000000-0000-4000-8000-000000000001', 'grade2-time', '시각과 시간을 알아봐요', 11);

insert into public.learning_unit_recommendation_metadata (
  unit_id, subject, recommended_start_level_code, recommended_end_level_code, parent_sort_order
)
select 'bb6cc6d7-e1e6-46e9-9d56-3bcb4b42550d'::uuid, 'math', 'elementary_2', 'elementary_2', 10
where not exists (
  select 1
  from public.learning_unit_recommendation_metadata metadata
  where metadata.unit_id = 'bb6cc6d7-e1e6-46e9-9d56-3bcb4b42550d'::uuid
);

insert into public.learning_content_versions (id, unit_id, version_no, content_hash)
values ('81f5083b-44b5-4344-8457-9522dbe74c97', 'bb6cc6d7-e1e6-46e9-9d56-3bcb4b42550d', 1, '4dd42cc233dec6339c6882bcdd7f75aa0a37e6d868461f4752fbdc26500aaac0');

insert into public.learning_stages (id, content_version_id, display_order, display_title, difficulty)
values
  ('81a4c29f-f274-4e60-8608-cc42fcb6c541', '81f5083b-44b5-4344-8457-9522dbe74c97', 1, '입문', 'seed'),
  ('415a7931-2908-41d7-ad5e-7365e74d8876', '81f5083b-44b5-4344-8457-9522dbe74c97', 2, '기초', 'leaf'),
  ('0bade680-571a-459e-aa2f-f824a43137a9', '81f5083b-44b5-4344-8457-9522dbe74c97', 3, '심화', 'tree'),
  ('a822b9e2-d1e4-4119-99f5-84972ffa4bbd', '81f5083b-44b5-4344-8457-9522dbe74c97', 4, '최상위 도전!', 'crown');

insert into public.learning_questions (id, stage_id, display_order, prompt, explanation)
values
  ('3818994e-1446-49d0-b6e0-547dbb06c144', '81a4c29f-f274-4e60-8608-cc42fcb6c541', 1, '분침이 12을 가리키고 시침을 읽으면 2시입니다. 이 시각은?', '분침은 0분을, 시침은 2시를 나타내므로 2시 정각입니다.'),
  ('ebd9cd93-a2a7-44c5-9077-964730c9db26', '81a4c29f-f274-4e60-8608-cc42fcb6c541', 2, '분침이 6을 가리키고 시침을 읽으면 5시입니다. 이 시각은?', '분침은 30분을, 시침은 5시를 나타내므로 5시 30분입니다.'),
  ('bd84f1dd-305a-49f6-9739-52c652eae77d', '81a4c29f-f274-4e60-8608-cc42fcb6c541', 3, '분침이 3을 가리키고 시침을 읽으면 7시입니다. 이 시각은?', '분침은 15분을, 시침은 7시를 나타내므로 7시 15분입니다.'),
  ('e9538d6e-6ad0-4fa8-a057-edf938634b37', '81a4c29f-f274-4e60-8608-cc42fcb6c541', 4, '분침이 9을 가리키고 시침을 읽으면 9시입니다. 이 시각은?', '분침은 45분을, 시침은 9시를 나타내므로 9시 45분입니다.'),
  ('20cc2f45-4118-44dc-ada0-bd55b00d29cf', '81a4c29f-f274-4e60-8608-cc42fcb6c541', 5, '분침이 5을 가리키고 시침을 읽으면 11시입니다. 이 시각은?', '분침은 25분을, 시침은 11시를 나타내므로 11시 25분입니다.'),
  ('bed0d5ec-67ac-4092-b623-122e293cc6fb', '81a4c29f-f274-4e60-8608-cc42fcb6c541', 6, '분침이 숫자 1을 가리킬 때 지난 분은?', '시계의 숫자 한 칸은 5분이므로 1×5=5분입니다.'),
  ('23510083-f811-403d-a323-5d21c58aa36a', '81a4c29f-f274-4e60-8608-cc42fcb6c541', 7, '분침이 숫자 3을 가리킬 때 지난 분은?', '시계의 숫자 한 칸은 5분이므로 3×5=15분입니다.'),
  ('cc24da79-915c-4d18-8e48-6d5729a6e4b0', '81a4c29f-f274-4e60-8608-cc42fcb6c541', 8, '분침이 숫자 6을 가리킬 때 지난 분은?', '시계의 숫자 한 칸은 5분이므로 6×5=30분입니다.'),
  ('d274099a-7687-4ae2-87d3-6291e13aac94', '81a4c29f-f274-4e60-8608-cc42fcb6c541', 9, '분침이 숫자 8을 가리킬 때 지난 분은?', '시계의 숫자 한 칸은 5분이므로 8×5=40분입니다.'),
  ('54aa7f11-bd83-4f1f-98b9-c7845191117a', '81a4c29f-f274-4e60-8608-cc42fcb6c541', 10, '분침이 숫자 10을 가리킬 때 지난 분은?', '시계의 숫자 한 칸은 5분이므로 10×5=50분입니다.'),
  ('9a6d16d2-103b-453b-acba-ee89cb3ed4bf', '415a7931-2908-41d7-ad5e-7365e74d8876', 1, '8시 10분에서 20분 후는 언제입니까?', '8시 10분에 20분을 더하면 8시 30분입니다.'),
  ('8720201d-5792-4f2b-9884-a97d49df3dc0', '415a7931-2908-41d7-ad5e-7365e74d8876', 2, '9시 25분에서 30분 후는 언제입니까?', '9시 25분에 30분을 더하면 9시 55분입니다.'),
  ('7410ae05-c083-4b13-8a1d-43bde4d55efe', '415a7931-2908-41d7-ad5e-7365e74d8876', 3, '1시 40분에서 15분 후는 언제입니까?', '1시 40분에 15분을 더하면 1시 55분입니다.'),
  ('f84676e1-41cf-4da4-bfe0-f63948d84f4f', '415a7931-2908-41d7-ad5e-7365e74d8876', 4, '3시 5분에서 40분 후는 언제입니까?', '3시 5분에 40분을 더하면 3시 45분입니다.'),
  ('48ad17a3-5661-4dc8-95b6-dce8035c0569', '415a7931-2908-41d7-ad5e-7365e74d8876', 5, '10시 30분에서 20분 전은 언제입니까?', '10시 30분에서 20분을 빼면 10시 10분입니다.'),
  ('f7d0f319-c128-462c-ab09-2ef9c0a011d2', '415a7931-2908-41d7-ad5e-7365e74d8876', 6, '4시 15분에서 10분 전은 언제입니까?', '4시 15분에서 10분을 빼면 4시 5분입니다.'),
  ('da1b07db-bea3-49ba-9a50-411136956fe1', '415a7931-2908-41d7-ad5e-7365e74d8876', 7, '7시 50분에서 25분 전은 언제입니까?', '7시 50분에서 25분을 빼면 7시 25분입니다.'),
  ('e6898529-1d6a-4396-8364-ac09909692fe', '415a7931-2908-41d7-ad5e-7365e74d8876', 8, '12시 20분에서 15분 전은 언제입니까?', '12시 20분에서 15분을 빼면 12시 5분입니다.'),
  ('ac794063-753e-4ef8-bc4a-3cb81bd9f42f', '415a7931-2908-41d7-ad5e-7365e74d8876', 9, '아침 식사를 하는 시각으로 알맞은 것은?', '아침은 낮 12시 전이므로 오전 8시가 알맞습니다.'),
  ('c0ce045b-ef91-4816-ac4f-30fb13e4963b', '415a7931-2908-41d7-ad5e-7365e74d8876', 10, '저녁 운동을 하는 시각으로 알맞은 것은?', '저녁은 낮 12시 뒤이므로 오후 7시가 알맞습니다.'),
  ('8334c12b-4df9-4ef5-a9c9-c9076d72e787', '0bade680-571a-459e-aa2f-f824a43137a9', 1, '8시 정각에 시작해 8시 35분에 끝났습니다. 지난 시간은?', '끝 시각에서 시작 시각을 빼면 515-480=35분입니다.'),
  ('73ce8652-8548-40ff-99e4-2e03cdf2321c', '0bade680-571a-459e-aa2f-f824a43137a9', 2, '9시 20분에 시작해 10시 5분에 끝났습니다. 지난 시간은?', '끝 시각에서 시작 시각을 빼면 605-560=45분입니다.'),
  ('e20a5ee0-16c2-4355-84ce-f2095316b2d1', '0bade680-571a-459e-aa2f-f824a43137a9', 3, '1시 15분에 시작해 2시 정각에 끝났습니다. 지난 시간은?', '끝 시각에서 시작 시각을 빼면 120-75=45분입니다.'),
  ('5b1c8408-682f-431f-bd5b-974dae027ac3', '0bade680-571a-459e-aa2f-f824a43137a9', 4, '3시 40분에 시작해 4시 10분에 끝났습니다. 지난 시간은?', '끝 시각에서 시작 시각을 빼면 250-220=30분입니다.'),
  ('38951de1-c85a-4416-a02b-486d8f3b49d1', '0bade680-571a-459e-aa2f-f824a43137a9', 5, '7시 30분에 시작해 45분 동안 했습니다. 끝난 시각은?', '시작 시각 7시 30분에 45분을 더하면 8시 15분입니다.'),
  ('16777806-f79b-49e1-b482-5a50a1d8aea0', '0bade680-571a-459e-aa2f-f824a43137a9', 6, '10시 10분에 시작해 35분 동안 했습니다. 끝난 시각은?', '시작 시각 10시 10분에 35분을 더하면 10시 45분입니다.'),
  ('26ce412e-310e-4d37-8738-5090ddbbfcdd', '0bade680-571a-459e-aa2f-f824a43137a9', 7, '2시 25분에 시작해 50분 동안 했습니다. 끝난 시각은?', '시작 시각 2시 25분에 50분을 더하면 3시 15분입니다.'),
  ('64f4d13b-3699-45af-8470-69525400d82d', '0bade680-571a-459e-aa2f-f824a43137a9', 8, '9시 50분에 끝났고 30분 동안 했습니다. 시작 시각은?', '끝 시각 9시 50분에서 30분을 빼면 9시 20분입니다.'),
  ('933c5d1f-f232-4abd-be14-29d42a34038a', '0bade680-571a-459e-aa2f-f824a43137a9', 9, '4시 20분에 끝났고 25분 동안 했습니다. 시작 시각은?', '끝 시각 4시 20분에서 25분을 빼면 3시 55분입니다.'),
  ('d1c96f31-9826-4d94-a0f1-58305dc12542', '0bade680-571a-459e-aa2f-f824a43137a9', 10, '11시 15분에 끝났고 40분 동안 했습니다. 시작 시각은?', '끝 시각 11시 15분에서 40분을 빼면 10시 35분입니다.'),
  ('3abd9f5b-0495-416e-99fd-6aa98d479d2e', 'a822b9e2-d1e4-4119-99f5-84972ffa4bbd', 1, '분침이 6을 가리키고 시침이 3과 4 사이에 있습니다. 알맞은 시각은?', '분침 6은 30분이고 시침은 아직 4에 이르지 않았으므로 3시 30분입니다.'),
  ('f6f49f34-4c96-498f-9cf9-8541983ecf22', 'a822b9e2-d1e4-4119-99f5-84972ffa4bbd', 2, '8시 20분에서 30분 후를 8시 40분이라고 했습니다. 바르게 고친 것은?', '20분에 30분을 더하면 50분이므로 8시 50분입니다.'),
  ('67622ef9-7597-4c48-9d0e-ce6976689907', 'a822b9e2-d1e4-4119-99f5-84972ffa4bbd', 3, '10시 5분에서 20분 전을 바르게 구한 것은?', '10시 5분에서 5분 전은 10시이고 15분 더 거슬러 9시 45분입니다.'),
  ('1e9c8732-9b47-4ae2-ae52-929c217c27d6', 'a822b9e2-d1e4-4119-99f5-84972ffa4bbd', 4, '오전 11시와 오후 11시를 바르게 설명한 것은?', '오전 11시는 낮 12시 전이고 오후 11시는 밤이므로 서로 다른 시각입니다.'),
  ('bb9d6456-8264-47a1-91e0-628563614abd', 'a822b9e2-d1e4-4119-99f5-84972ffa4bbd', 5, '2시 35분부터 3시 20분까지 지난 시간은?', '2시 35분부터 3시까지 25분, 다시 20분이므로 모두 45분입니다.'),
  ('bacb84f3-afe5-4a08-a5cc-551b6b928db1', 'a822b9e2-d1e4-4119-99f5-84972ffa4bbd', 6, '분침이 9를 가리키면 9분이라고 한 설명의 오류는?', '분침의 숫자 한 칸은 5분이므로 9는 9×5=45분입니다.'),
  ('3a7184e8-e2d5-4327-85ec-40055b8d0836', 'a822b9e2-d1e4-4119-99f5-84972ffa4bbd', 7, '오후 3시 10분에 시작해 40분 뒤 끝나는 일정은?', '오후 3시 10분에 40분을 더하면 오후 3시 50분이며 오전·오후는 바뀌지 않습니다.'),
  ('14f42b5c-af11-49c7-9f64-46d40a7f9f04', 'a822b9e2-d1e4-4119-99f5-84972ffa4bbd', 8, '9시 40분에 끝난 25분 활동의 시작 시각과 설명이 맞는 것은?', '끝 시각에서 지난 25분을 빼면 9시 15분입니다.'),
  ('63cad63d-789c-481d-ac3f-0fe348ab9f29', 'a822b9e2-d1e4-4119-99f5-84972ffa4bbd', 9, '시침과 분침의 역할을 바르게 설명한 것은?', '시침은 몇 시인지, 분침은 몇 분인지 읽는 데 사용합니다.'),
  ('81dd26c7-17f4-49dd-a852-a74cc47c0399', 'a822b9e2-d1e4-4119-99f5-84972ffa4bbd', 10, '오전 11시 50분에서 20분 후의 시각은?', '11시 50분에서 10분 후가 낮 12시이고 10분 더 지나 오후 12시 10분입니다.');

insert into public.learning_question_options (id, question_id, display_order, option_text, is_correct)
values
  ('3e5ce115-44e7-40eb-8fb5-6efd5465b297', '3818994e-1446-49d0-b6e0-547dbb06c144', 1, '2시 정각', true),
  ('87772183-3106-4690-ae5e-baf0bd02e91c', '3818994e-1446-49d0-b6e0-547dbb06c144', 2, '2시 5분', false),
  ('7d1245d8-443f-4535-a3a7-5013d766e452', '3818994e-1446-49d0-b6e0-547dbb06c144', 3, '3시 정각', false),
  ('651c4a4c-d2dc-45f9-9af1-bf3afe61740e', '3818994e-1446-49d0-b6e0-547dbb06c144', 4, '2시 2분', false),
  ('14c3b689-a863-4f9d-bd13-43511e9c8e93', 'ebd9cd93-a2a7-44c5-9077-964730c9db26', 1, '5시 35분', false),
  ('8c7075d5-4e93-481c-b7cc-464dcb4a77f0', 'ebd9cd93-a2a7-44c5-9077-964730c9db26', 2, '5시 30분', true),
  ('d79b7ad9-4afa-4085-b27c-f260ee5d90dc', 'ebd9cd93-a2a7-44c5-9077-964730c9db26', 3, '6시 30분', false),
  ('f83ffafd-520c-4800-8f19-32ba9e801496', 'ebd9cd93-a2a7-44c5-9077-964730c9db26', 4, '30시 5분', false),
  ('fb0ab948-73d4-4127-a1ce-2d484cbba057', 'bd84f1dd-305a-49f6-9739-52c652eae77d', 1, '7시 20분', false),
  ('96a79ec6-7d5f-48b9-902d-13fd48bce01b', 'bd84f1dd-305a-49f6-9739-52c652eae77d', 2, '8시 15분', false),
  ('cf64662c-6e2d-4add-b40a-109135a8cc59', 'bd84f1dd-305a-49f6-9739-52c652eae77d', 3, '7시 15분', true),
  ('aa0b9c64-4834-4602-af8d-67341e8b3d09', 'bd84f1dd-305a-49f6-9739-52c652eae77d', 4, '15시 7분', false),
  ('10f7cc9c-82cb-41de-bfd6-926d5334e8e0', 'e9538d6e-6ad0-4fa8-a057-edf938634b37', 1, '9시 50분', false),
  ('30cdb1d9-eb4d-4717-ae94-1ce696513316', 'e9538d6e-6ad0-4fa8-a057-edf938634b37', 2, '10시 45분', false),
  ('de3042e4-d229-4d2f-8eb5-36a4940c0259', 'e9538d6e-6ad0-4fa8-a057-edf938634b37', 3, '45시 9분', false),
  ('d2684447-9837-4a38-b381-f8930b02d770', 'e9538d6e-6ad0-4fa8-a057-edf938634b37', 4, '9시 45분', true),
  ('41f0b0fd-4c2d-461b-8fe6-5975db996c20', '20cc2f45-4118-44dc-ada0-bd55b00d29cf', 1, '11시 25분', true),
  ('7cde75a2-33f9-4f1c-9544-3f2926f0250c', '20cc2f45-4118-44dc-ada0-bd55b00d29cf', 2, '11시 30분', false),
  ('09464608-aaf2-4aea-ac00-20d63ebd51b7', '20cc2f45-4118-44dc-ada0-bd55b00d29cf', 3, '12시 25분', false),
  ('868f3a8f-2182-4368-a2e7-849f1b143374', '20cc2f45-4118-44dc-ada0-bd55b00d29cf', 4, '25시 11분', false),
  ('2063ab16-b477-4bc2-ac6b-a3fb82b5c089', 'bed0d5ec-67ac-4092-b623-122e293cc6fb', 1, '1분', false),
  ('a1ede1e6-8892-4d34-acb4-306acd93659e', 'bed0d5ec-67ac-4092-b623-122e293cc6fb', 2, '5분', true),
  ('41c0a05d-d141-475f-b599-2f0fd6e240c3', 'bed0d5ec-67ac-4092-b623-122e293cc6fb', 3, '10분', false),
  ('28208715-76f1-4d27-9214-e892ad51dc7d', 'bed0d5ec-67ac-4092-b623-122e293cc6fb', 4, '0분', false),
  ('03fd7819-1db4-4ca6-aa1b-cd59f7ba2fbd', '23510083-f811-403d-a323-5d21c58aa36a', 1, '15분', true),
  ('fd26077b-1ee2-41a6-b36f-61f018a715d3', '23510083-f811-403d-a323-5d21c58aa36a', 2, '3분', false),
  ('4408cfbb-ecc3-45ef-a02f-b0964a551ecd', '23510083-f811-403d-a323-5d21c58aa36a', 3, '30분', false),
  ('aaee4ccc-9b82-4551-aef7-df7d0d5efd3d', '23510083-f811-403d-a323-5d21c58aa36a', 4, '10분', false),
  ('9dc24878-aa1d-44c9-99a0-f828bcd246b5', 'cc24da79-915c-4d18-8e48-6d5729a6e4b0', 1, '6분', false),
  ('f5518741-870b-4d76-b892-d84f8c3a4517', 'cc24da79-915c-4d18-8e48-6d5729a6e4b0', 2, '30분', true),
  ('fcbba247-906d-46ff-969a-52358ac0c17b', 'cc24da79-915c-4d18-8e48-6d5729a6e4b0', 3, '60분', false),
  ('efbc7335-622a-428f-ba29-b3faddbe87a7', 'cc24da79-915c-4d18-8e48-6d5729a6e4b0', 4, '25분', false),
  ('f744d5e1-b663-408c-a0c9-52a4e2bb515a', 'd274099a-7687-4ae2-87d3-6291e13aac94', 1, '8분', false),
  ('6ba4979f-ac3e-48a7-9b74-30674c13c58a', 'd274099a-7687-4ae2-87d3-6291e13aac94', 2, '80분', false),
  ('586ec7e3-b6eb-430a-b0f8-cd1cbc0f34b9', 'd274099a-7687-4ae2-87d3-6291e13aac94', 3, '40분', true),
  ('9b6394c0-9f34-4c7c-a68e-b02987c749d7', 'd274099a-7687-4ae2-87d3-6291e13aac94', 4, '35분', false),
  ('69e2953a-1540-4d3a-9f76-3c878d979c16', '54aa7f11-bd83-4f1f-98b9-c7845191117a', 1, '10분', false),
  ('b6d7feac-5111-4380-9fba-b2704c09de26', '54aa7f11-bd83-4f1f-98b9-c7845191117a', 2, '100분', false),
  ('8ad9a53a-a814-45db-a88b-d930b9194efa', '54aa7f11-bd83-4f1f-98b9-c7845191117a', 3, '45분', false),
  ('496d9ac7-c5f9-4338-82b1-aafca779c993', '54aa7f11-bd83-4f1f-98b9-c7845191117a', 4, '50분', true),
  ('c97b3827-a342-4661-91fb-9aca7cbb967e', '9a6d16d2-103b-453b-acba-ee89cb3ed4bf', 1, '8시 30분', true),
  ('052a20ee-16f7-45a2-83ba-6f79db4f75e3', '9a6d16d2-103b-453b-acba-ee89cb3ed4bf', 2, '8시 25분', false),
  ('76586d39-3805-42d2-933d-55ac325cda95', '9a6d16d2-103b-453b-acba-ee89cb3ed4bf', 3, '8시 35분', false),
  ('eca9fc8a-f766-4f13-9db7-650527d440cc', '9a6d16d2-103b-453b-acba-ee89cb3ed4bf', 4, '7시 50분', false),
  ('b81dfd4c-0d05-4db2-b142-1fff1d743c3c', '8720201d-5792-4f2b-9884-a97d49df3dc0', 1, '9시 50분', false),
  ('7b70a193-7d78-432f-b678-4e4f4d768e08', '8720201d-5792-4f2b-9884-a97d49df3dc0', 2, '9시 55분', true),
  ('b39120de-3dce-40f0-b868-a26f46735d8b', '8720201d-5792-4f2b-9884-a97d49df3dc0', 3, '10시 정각', false),
  ('889acc32-34ca-4a3a-b9c7-668209648b3e', '8720201d-5792-4f2b-9884-a97d49df3dc0', 4, '8시 55분', false),
  ('2250b9db-7cd0-4e4f-b062-66042009d96c', '7410ae05-c083-4b13-8a1d-43bde4d55efe', 1, '1시 50분', false),
  ('21ce1f16-0d9b-4a83-b32a-e174cc05965b', '7410ae05-c083-4b13-8a1d-43bde4d55efe', 2, '2시 정각', false),
  ('46e2de5d-df13-49a7-a27f-d37a95edd2e9', '7410ae05-c083-4b13-8a1d-43bde4d55efe', 3, '1시 55분', true),
  ('249fd4c6-2f58-4bd9-8224-5ecb129a2528', '7410ae05-c083-4b13-8a1d-43bde4d55efe', 4, '1시 25분', false),
  ('ad03dbcd-0562-4bf0-a925-d3e1d744d0da', 'f84676e1-41cf-4da4-bfe0-f63948d84f4f', 1, '3시 40분', false),
  ('1b31e4ea-01d2-4d96-bca1-84bf1d31304c', 'f84676e1-41cf-4da4-bfe0-f63948d84f4f', 2, '3시 50분', false),
  ('48a6f8ea-b46b-48f4-964f-a58e6fbcff72', 'f84676e1-41cf-4da4-bfe0-f63948d84f4f', 3, '2시 25분', false),
  ('bdbc4a22-85fd-42c6-86d6-cd12a1bb36f9', 'f84676e1-41cf-4da4-bfe0-f63948d84f4f', 4, '3시 45분', true),
  ('c2892225-36b2-4bea-a7e3-58dbc3a30c15', '48ad17a3-5661-4dc8-95b6-dce8035c0569', 1, '10시 5분', false),
  ('50a33ae9-e7b5-4fb0-9fa9-b438afe5b034', '48ad17a3-5661-4dc8-95b6-dce8035c0569', 2, '10시 15분', false),
  ('2fd2a08c-d952-4059-8f3d-1b1b09d43e21', '48ad17a3-5661-4dc8-95b6-dce8035c0569', 3, '10시 10분', true),
  ('7d480400-7252-486d-9e0b-70eb1442f691', '48ad17a3-5661-4dc8-95b6-dce8035c0569', 4, '10시 50분', false),
  ('b83e568f-807c-4538-95e5-7c924e0f66a6', 'f7d0f319-c128-462c-ab09-2ef9c0a011d2', 1, '4시 정각', false),
  ('3be96bb5-0e82-4fad-93a8-9cb2a25ee7df', 'f7d0f319-c128-462c-ab09-2ef9c0a011d2', 2, '4시 10분', false),
  ('3945a00f-3f12-4c98-aaf3-221eebfc8f9b', 'f7d0f319-c128-462c-ab09-2ef9c0a011d2', 3, '4시 25분', false),
  ('9c8ac369-31d3-4016-aadc-cbe8d330fad2', 'f7d0f319-c128-462c-ab09-2ef9c0a011d2', 4, '4시 5분', true),
  ('c03908d5-faf9-407c-a303-731f58148b42', 'da1b07db-bea3-49ba-9a50-411136956fe1', 1, '7시 25분', true),
  ('272710a6-91c3-4403-b1b1-33b177f59e8b', 'da1b07db-bea3-49ba-9a50-411136956fe1', 2, '7시 20분', false),
  ('5c390f35-a575-4596-8e82-31174e527aa1', 'da1b07db-bea3-49ba-9a50-411136956fe1', 3, '7시 30분', false),
  ('4db9bea6-d499-4ae8-bc0f-9a3fb4a10261', 'da1b07db-bea3-49ba-9a50-411136956fe1', 4, '8시 15분', false),
  ('40250631-c215-4995-aa06-48c495c9df68', 'e6898529-1d6a-4396-8364-ac09909692fe', 1, '12시 정각', false),
  ('7448c6a9-4b15-4bd2-8619-0958976f6a6f', 'e6898529-1d6a-4396-8364-ac09909692fe', 2, '12시 5분', true),
  ('7d60e0fc-6bff-44f7-a6d9-efc554e476f0', 'e6898529-1d6a-4396-8364-ac09909692fe', 3, '12시 10분', false),
  ('a1478628-f0b4-494d-8fe4-936ef6975afe', 'e6898529-1d6a-4396-8364-ac09909692fe', 4, '12시 35분', false),
  ('d634c73b-fb90-4550-a050-4ce36fa2f8e9', 'ac794063-753e-4ef8-bc4a-3cb81bd9f42f', 1, '오후 8시', false),
  ('eb09ccac-73ca-4c33-8746-c47a08a37e30', 'ac794063-753e-4ef8-bc4a-3cb81bd9f42f', 2, '오전 12시', false),
  ('9fd41ca5-9696-444f-8a83-c4376014306d', 'ac794063-753e-4ef8-bc4a-3cb81bd9f42f', 3, '오전 8시', true),
  ('8a08864a-8ef2-47ca-b08b-419421ffe75e', 'ac794063-753e-4ef8-bc4a-3cb81bd9f42f', 4, '오후 2시', false),
  ('dabe654d-31f2-4ef2-b441-f85dbf7bb6a6', 'c0ce045b-ef91-4816-ac4f-30fb13e4963b', 1, '오전 7시', false),
  ('4147bd31-b03a-4532-886f-92beaee9fe76', 'c0ce045b-ef91-4816-ac4f-30fb13e4963b', 2, '오전 1시', false),
  ('5653b83e-b2d1-47f5-8361-c0bf1d7edbc7', 'c0ce045b-ef91-4816-ac4f-30fb13e4963b', 3, '오후 7분', false),
  ('2c3faef7-955e-49fd-909d-bbefaed18480', 'c0ce045b-ef91-4816-ac4f-30fb13e4963b', 4, '오후 7시', true),
  ('50c7146c-a77a-4d43-b7f1-84a306830aaa', '8334c12b-4df9-4ef5-a9c9-c9076d72e787', 1, '35분', true),
  ('23234a69-532e-4153-9010-d9e98fbb601e', '8334c12b-4df9-4ef5-a9c9-c9076d72e787', 2, '30분', false),
  ('a62ef26e-83b6-458c-adee-5d797fbf7f77', '8334c12b-4df9-4ef5-a9c9-c9076d72e787', 3, '40분', false),
  ('e6b6979e-f391-4525-8d9a-82262f6d893b', '8334c12b-4df9-4ef5-a9c9-c9076d72e787', 4, '0분', false),
  ('7bab11f1-aa2b-4ca9-83b6-ddf629afcc69', '73ce8652-8548-40ff-99e4-2e03cdf2321c', 1, '40분', false),
  ('f10196f1-ee5a-41e9-b78e-6dcd9e544486', '73ce8652-8548-40ff-99e4-2e03cdf2321c', 2, '45분', true),
  ('16aa7261-b851-40b0-87cf-9f10ab8d940b', '73ce8652-8548-40ff-99e4-2e03cdf2321c', 3, '50분', false),
  ('ec7846a5-5971-4043-9e43-f514f3a1f20d', '73ce8652-8548-40ff-99e4-2e03cdf2321c', 4, '1분', false),
  ('589f22ba-b00a-4757-adf3-e982fb64ce2f', 'e20a5ee0-16c2-4355-84ce-f2095316b2d1', 1, '40분', false),
  ('bac07fb8-be23-4509-adc2-164d9399aa05', 'e20a5ee0-16c2-4355-84ce-f2095316b2d1', 2, '50분', false),
  ('139a71f2-84fb-41c0-9883-51ca1c11f8f3', 'e20a5ee0-16c2-4355-84ce-f2095316b2d1', 3, '45분', true),
  ('30c2cbeb-c959-42da-93cc-82c55b2653de', 'e20a5ee0-16c2-4355-84ce-f2095316b2d1', 4, '1분', false),
  ('8c5c5b33-f31f-4725-b165-a67f7a2b3a2d', '5b1c8408-682f-431f-bd5b-974dae027ac3', 1, '25분', false),
  ('09d73fe1-c451-4be0-bfbc-49242978f9b1', '5b1c8408-682f-431f-bd5b-974dae027ac3', 2, '35분', false),
  ('f686cdcf-7f47-4a63-896b-5fe274fa67fe', '5b1c8408-682f-431f-bd5b-974dae027ac3', 3, '1분', false),
  ('3dfcb048-459f-4cb0-97dd-c76ef1faefdc', '5b1c8408-682f-431f-bd5b-974dae027ac3', 4, '30분', true),
  ('9a7b8441-fa67-465c-a586-a0c88c1291a2', '38951de1-c85a-4416-a02b-486d8f3b49d1', 1, '8시 15분', true),
  ('9abf62bb-b33c-4e3b-b738-6a3b81b62263', '38951de1-c85a-4416-a02b-486d8f3b49d1', 2, '8시 10분', false),
  ('677f773b-fd88-4c66-b10c-9c866cc16326', '38951de1-c85a-4416-a02b-486d8f3b49d1', 3, '8시 20분', false),
  ('3b481696-b5a0-478e-b563-56672f9217f1', '38951de1-c85a-4416-a02b-486d8f3b49d1', 4, '6시 45분', false),
  ('b9dce2d6-1bfe-49d6-9dbb-8ac3fb30181a', '16777806-f79b-49e1-b482-5a50a1d8aea0', 1, '10시 40분', false),
  ('30db0655-cb88-4175-b893-646585eec226', '16777806-f79b-49e1-b482-5a50a1d8aea0', 2, '10시 45분', true),
  ('8fe997fc-d630-490f-83b8-0a0ca188f5e9', '16777806-f79b-49e1-b482-5a50a1d8aea0', 3, '10시 50분', false),
  ('199f03c4-5ce0-4b20-bd66-a476dc61e0ff', '16777806-f79b-49e1-b482-5a50a1d8aea0', 4, '9시 35분', false),
  ('75d46cda-f79b-4c31-af23-d5d40742c474', '26ce412e-310e-4d37-8738-5090ddbbfcdd', 1, '3시 15분', true),
  ('56f15e49-354e-4453-9c67-7d56b82c9430', '26ce412e-310e-4d37-8738-5090ddbbfcdd', 2, '3시 10분', false),
  ('363139ed-9f4a-4826-a0f2-41045ac9ee0f', '26ce412e-310e-4d37-8738-5090ddbbfcdd', 3, '3시 20분', false),
  ('f9098620-e0ba-4004-aad1-7c1fe52ef8cd', '26ce412e-310e-4d37-8738-5090ddbbfcdd', 4, '1시 35분', false),
  ('7329d0f6-e995-4044-a9e3-b596c54a9266', '64f4d13b-3699-45af-8470-69525400d82d', 1, '9시 15분', false),
  ('162ba18a-cd90-4bf2-bc02-6234194bd907', '64f4d13b-3699-45af-8470-69525400d82d', 2, '9시 20분', true),
  ('8b744d42-f6cf-48fc-8903-b5eeb61d11bd', '64f4d13b-3699-45af-8470-69525400d82d', 3, '9시 25분', false),
  ('ee071734-eb6f-45de-9dee-b7a64284ce3c', '64f4d13b-3699-45af-8470-69525400d82d', 4, '10시 20분', false),
  ('aa96f19f-d788-4a34-bfde-24ddeefa0c73', '933c5d1f-f232-4abd-be14-29d42a34038a', 1, '3시 50분', false),
  ('c5b16cfe-a548-4ec3-b8e3-a43a161c1e12', '933c5d1f-f232-4abd-be14-29d42a34038a', 2, '4시 정각', false),
  ('24e80355-1655-43e0-add0-9a3a7170c55a', '933c5d1f-f232-4abd-be14-29d42a34038a', 3, '3시 55분', true),
  ('03363e62-e62c-40e1-8d1c-0c3ce4391c5e', '933c5d1f-f232-4abd-be14-29d42a34038a', 4, '4시 45분', false),
  ('443807b2-613a-44d7-b9fc-2dc35704cd64', 'd1c96f31-9826-4d94-a0f1-58305dc12542', 1, '10시 30분', false),
  ('ea53af1e-c5f0-4ff0-92ab-5997045b87c4', 'd1c96f31-9826-4d94-a0f1-58305dc12542', 2, '10시 40분', false),
  ('ea800493-08df-4e5a-a209-34bdf62e28d0', 'd1c96f31-9826-4d94-a0f1-58305dc12542', 3, '11시 55분', false),
  ('a23baa4b-afae-43bc-9ed5-c3b812936d30', 'd1c96f31-9826-4d94-a0f1-58305dc12542', 4, '10시 35분', true),
  ('98b8581e-81b6-47f2-897f-56c099929ad0', '3abd9f5b-0495-416e-99fd-6aa98d479d2e', 1, '3시 30분', true),
  ('7f13be7a-d428-44c8-9e0d-28978681be25', '3abd9f5b-0495-416e-99fd-6aa98d479d2e', 2, '6시 15분', false),
  ('098f8062-4000-4c79-8d1c-72c4a654404a', '3abd9f5b-0495-416e-99fd-6aa98d479d2e', 3, '4시 30분', false),
  ('2795d988-b2b4-4160-8b5c-04edf51cef76', '3abd9f5b-0495-416e-99fd-6aa98d479d2e', 4, '3시 6분', false),
  ('b56080b7-d1cd-4ad9-9f6f-2a6349cb9b3d', 'f6f49f34-4c96-498f-9cf9-8541983ecf22', 1, '8시 40분', false),
  ('a46c33a2-71ac-4261-af6f-0ed0b99e9a6d', 'f6f49f34-4c96-498f-9cf9-8541983ecf22', 2, '8시 50분', true),
  ('1652a899-c48f-4968-8643-13171df2637a', 'f6f49f34-4c96-498f-9cf9-8541983ecf22', 3, '9시 10분', false),
  ('9fdacfc0-8121-46f9-a9c6-7b6e2141d7d4', 'f6f49f34-4c96-498f-9cf9-8541983ecf22', 4, '7시 50분', false),
  ('b1c15edd-072c-427a-9d4c-281d1d566ab5', '67622ef9-7597-4c48-9d0e-ce6976689907', 1, '10시 25분', false),
  ('d004a648-b0b6-4a49-a4ca-546248da0d77', '67622ef9-7597-4c48-9d0e-ce6976689907', 2, '9시 55분', false),
  ('0e76dcdc-2ac4-4fc5-8fa8-3135c01db8a9', '67622ef9-7597-4c48-9d0e-ce6976689907', 3, '9시 45분', true),
  ('1be15a33-3070-49db-a1bd-d1a36676d222', '67622ef9-7597-4c48-9d0e-ce6976689907', 4, '10시 45분', false),
  ('ddff6326-1183-4f24-83db-f9cd1cd000a2', '1e9c8732-9b47-4ae2-ae52-929c217c27d6', 1, '둘 다 아침입니다.', false),
  ('ca7f7da2-b71a-4046-9774-a9653a0f6769', '1e9c8732-9b47-4ae2-ae52-929c217c27d6', 2, '완전히 같은 시각입니다.', false),
  ('d89706c5-356a-408d-b59b-93b195e8a582', '1e9c8732-9b47-4ae2-ae52-929c217c27d6', 3, '오전 11시는 저녁입니다.', false),
  ('a18da500-834e-4ca9-b921-1b979a3664d2', '1e9c8732-9b47-4ae2-ae52-929c217c27d6', 4, '서로 12시간 떨어진 다른 시각입니다.', true),
  ('2f0923e5-71b7-48f4-8149-8b2dbfa1358b', 'bb9d6456-8264-47a1-91e0-628563614abd', 1, '35분', false),
  ('1308a42c-be75-4510-875b-66ebb12423b2', 'bb9d6456-8264-47a1-91e0-628563614abd', 2, '55분', false),
  ('7a2024d3-f67f-45dd-a261-6cc35b608398', 'bb9d6456-8264-47a1-91e0-628563614abd', 3, '45분', true),
  ('a756bc20-4f47-49a5-b6db-5c9ee5ab61af', 'bb9d6456-8264-47a1-91e0-628563614abd', 4, '85분', false),
  ('1c7ba565-2fbd-4332-847a-69539ac9dc6f', 'bacb84f3-afe5-4a08-a5cc-551b6b928db1', 1, '숫자 9는 90분을 뜻합니다.', false),
  ('26e13003-7a7d-4083-b7e1-d659521e679a', 'bacb84f3-afe5-4a08-a5cc-551b6b928db1', 2, '분침은 시를 나타냅니다.', false),
  ('2ecb56d8-3b75-4521-99bd-5309d7fdb2c3', 'bacb84f3-afe5-4a08-a5cc-551b6b928db1', 3, '숫자 9는 항상 9시입니다.', false),
  ('6220fa0c-907b-4a4b-90f4-8e9eaa4baa55', 'bacb84f3-afe5-4a08-a5cc-551b6b928db1', 4, '숫자 9는 45분을 뜻합니다.', true),
  ('8ad518e8-4ee3-4d1c-aa31-f687867d000f', '3a7184e8-e2d5-4327-85ec-40055b8d0836', 1, '오후 3시 50분', true),
  ('74883261-125d-4451-a167-aad136c4936c', '3a7184e8-e2d5-4327-85ec-40055b8d0836', 2, '오전 3시 50분', false),
  ('4215e911-7362-48e2-a871-7f522cff6ce6', '3a7184e8-e2d5-4327-85ec-40055b8d0836', 3, '오후 4시 10분', false),
  ('bb59e7f3-0293-4e8f-89a0-3cb5b9aa1d3e', '3a7184e8-e2d5-4327-85ec-40055b8d0836', 4, '오후 2시 30분', false),
  ('c9c63247-1c3e-477c-9ee1-5dd356e89e01', '14f42b5c-af11-49c7-9f64-46d40a7f9f04', 1, '9시 65분이며 40+25입니다.', false),
  ('341dfe49-efb2-413e-b49a-0c98bd624463', '14f42b5c-af11-49c7-9f64-46d40a7f9f04', 2, '9시 15분이며 40-25=15분입니다.', true),
  ('7ddc711c-5868-425d-a05f-848bc30008be', '14f42b5c-af11-49c7-9f64-46d40a7f9f04', 3, '10시 5분이며 25분을 더합니다.', false),
  ('e3f55ddd-c093-42e4-903a-06972b748718', '14f42b5c-af11-49c7-9f64-46d40a7f9f04', 4, '9시 25분이며 40-25=25입니다.', false),
  ('ccd3417f-6c8b-495c-a669-f1b04b6090cf', '63cad63d-789c-481d-ac3f-0fe348ab9f29', 1, '짧은 시침은 분만 나타냅니다.', false),
  ('b8fb8579-832b-42e6-8b08-6ea419d2fcee', '63cad63d-789c-481d-ac3f-0fe348ab9f29', 2, '긴 분침은 오전과 오후만 나타냅니다.', false),
  ('2244ff09-8ef5-4b1b-b15f-60ebd8630166', '63cad63d-789c-481d-ac3f-0fe348ab9f29', 3, '짧은 시침은 시를, 긴 분침은 분을 나타냅니다.', true),
  ('9c708d11-fb4e-4f78-9f51-3ed8cd2ba830', '63cad63d-789c-481d-ac3f-0fe348ab9f29', 4, '두 바늘은 언제나 같은 숫자를 가리킵니다.', false),
  ('fff43af4-90a5-4d7c-a2a3-194313a29d3c', '81dd26c7-17f4-49dd-a852-a74cc47c0399', 1, '오전 12시 10분', false),
  ('d66f7326-5211-41fb-baff-256f7b3e1e44', '81dd26c7-17f4-49dd-a852-a74cc47c0399', 2, '오후 11시 70분', false),
  ('c5f61002-07ab-4b55-8d7b-20acaea45e6e', '81dd26c7-17f4-49dd-a852-a74cc47c0399', 3, '오전 11시 30분', false),
  ('20051a26-4356-4550-8190-910ca545b9d3', '81dd26c7-17f4-49dd-a852-a74cc47c0399', 4, '오후 12시 10분', true);

insert into public.learning_question_skills (
  question_id, skill_code, is_primary
)
values
  ('3818994e-1446-49d0-b6e0-547dbb06c144', 'read-clock-time', true),
  ('ebd9cd93-a2a7-44c5-9077-964730c9db26', 'read-clock-time', true),
  ('bd84f1dd-305a-49f6-9739-52c652eae77d', 'read-clock-time', true),
  ('e9538d6e-6ad0-4fa8-a057-edf938634b37', 'read-clock-time', true),
  ('20cc2f45-4118-44dc-ada0-bd55b00d29cf', 'read-clock-time', true),
  ('bed0d5ec-67ac-4092-b623-122e293cc6fb', 'use-five-minute-intervals', true),
  ('23510083-f811-403d-a323-5d21c58aa36a', 'use-five-minute-intervals', true),
  ('cc24da79-915c-4d18-8e48-6d5729a6e4b0', 'use-five-minute-intervals', true),
  ('d274099a-7687-4ae2-87d3-6291e13aac94', 'use-five-minute-intervals', true),
  ('54aa7f11-bd83-4f1f-98b9-c7845191117a', 'use-five-minute-intervals', true),
  ('9a6d16d2-103b-453b-acba-ee89cb3ed4bf', 'calculate-time-after', true),
  ('8720201d-5792-4f2b-9884-a97d49df3dc0', 'calculate-time-after', true),
  ('7410ae05-c083-4b13-8a1d-43bde4d55efe', 'calculate-time-after', true),
  ('f84676e1-41cf-4da4-bfe0-f63948d84f4f', 'calculate-time-after', true),
  ('48ad17a3-5661-4dc8-95b6-dce8035c0569', 'calculate-time-before', true),
  ('f7d0f319-c128-462c-ab09-2ef9c0a011d2', 'calculate-time-before', true),
  ('da1b07db-bea3-49ba-9a50-411136956fe1', 'calculate-time-before', true),
  ('e6898529-1d6a-4396-8364-ac09909692fe', 'calculate-time-before', true),
  ('ac794063-753e-4ef8-bc4a-3cb81bd9f42f', 'distinguish-am-pm', true),
  ('c0ce045b-ef91-4816-ac4f-30fb13e4963b', 'distinguish-am-pm', true),
  ('8334c12b-4df9-4ef5-a9c9-c9076d72e787', 'calculate-elapsed-time', true),
  ('73ce8652-8548-40ff-99e4-2e03cdf2321c', 'calculate-elapsed-time', true),
  ('e20a5ee0-16c2-4355-84ce-f2095316b2d1', 'calculate-elapsed-time', true),
  ('5b1c8408-682f-431f-bd5b-974dae027ac3', 'calculate-elapsed-time', true),
  ('38951de1-c85a-4416-a02b-486d8f3b49d1', 'calculate-time-after', true),
  ('16777806-f79b-49e1-b482-5a50a1d8aea0', 'calculate-time-after', true),
  ('26ce412e-310e-4d37-8738-5090ddbbfcdd', 'calculate-time-after', true),
  ('64f4d13b-3699-45af-8470-69525400d82d', 'calculate-time-before', true),
  ('933c5d1f-f232-4abd-be14-29d42a34038a', 'calculate-time-before', true),
  ('d1c96f31-9826-4d94-a0f1-58305dc12542', 'calculate-time-before', true),
  ('3abd9f5b-0495-416e-99fd-6aa98d479d2e', 'interpret-clock-hands', true),
  ('f6f49f34-4c96-498f-9cf9-8541983ecf22', 'correct-time-reasoning', true),
  ('67622ef9-7597-4c48-9d0e-ce6976689907', 'calculate-time-before', true),
  ('1e9c8732-9b47-4ae2-ae52-929c217c27d6', 'distinguish-am-pm', true),
  ('bb9d6456-8264-47a1-91e0-628563614abd', 'calculate-elapsed-time', true),
  ('bacb84f3-afe5-4a08-a5cc-551b6b928db1', 'correct-time-reasoning', true),
  ('3a7184e8-e2d5-4327-85ec-40055b8d0836', 'calculate-time-after', true),
  ('14f42b5c-af11-49c7-9f64-46d40a7f9f04', 'calculate-time-before', true),
  ('63cad63d-789c-481d-ac3f-0fe348ab9f29', 'interpret-clock-hands', true),
  ('81dd26c7-17f4-49dd-a852-a74cc47c0399', 'calculate-time-after', true);

select (public.publish_learning_content_version('81f5083b-44b5-4344-8457-9522dbe74c97'::uuid)).id;

commit;
