-- Generated by scripts/generate-learning-content-migration.js.
-- Source: content/learning/math/grade2-multiplication-tables-v1.json
-- Canonical content SHA-256: 7c1b81091398d0e00c97d82dd1c431e399a1f4caa56f9cdf869887e638e65282
-- Content-only and additive: no assignment, attempt, progress, first-pass, ledger, ACL, or Realtime changes.

begin;

do $preflight$
begin
  if exists (
    select 1 from public.learning_courses
    where (id = '51000000-0000-4000-8000-000000000001'::uuid or course_code = 'math-core')
      and not (
        id = '51000000-0000-4000-8000-000000000001'::uuid
        and course_code = 'math-core'
        and internal_name = '수학 기초 과정'
        and subject_name = '수학'
      )
  ) then
    raise exception using errcode = '23505', message = 'grade2_multiplication_tables_v1 course identifier conflicts with different content';
  end if;

  if not exists (
    select 1 from public.learning_courses
    where id = '51000000-0000-4000-8000-000000000001'::uuid
      and course_code = 'math-core'
      and internal_name = '수학 기초 과정'
      and subject_name = '수학'
      and status = 'published'
  ) then
    raise exception using errcode = 'P0002', message = 'grade2_multiplication_tables_v1 existing course is missing or changed';
  end if;

  if exists (
    select 1 from public.learning_units
    where id = '362cafc9-09b4-4582-a5dd-d6e868e573d6'::uuid
       or unit_code = 'grade2-multiplication-tables'
  ) then
    raise exception using errcode = '23505', message = 'grade2_multiplication_tables_v1 unit identifier already exists';
  end if;

  if exists (
    select 1 from public.learning_units
    where course_id = '51000000-0000-4000-8000-000000000001'::uuid
      and sort_order = 9
  ) then
    raise exception using errcode = '23505', message = 'grade2_multiplication_tables_v1 unit sort order already exists';
  end if;

  if to_regclass('public.learning_unit_recommendation_metadata') is null then
    raise exception using errcode = 'P0002', message = 'learning recommendation metadata table is missing';
  end if;

  if exists (
    select 1
    from public.learning_unit_recommendation_metadata metadata
    where metadata.unit_id = '362cafc9-09b4-4582-a5dd-d6e868e573d6'::uuid
      and (
        metadata.subject is distinct from 'math'
        or metadata.recommended_start_level_code is distinct from 'elementary_2'
        or metadata.recommended_end_level_code is distinct from 'elementary_2'
        or metadata.parent_sort_order is distinct from 8
      )
  ) then
    raise exception using errcode = '23505', message = 'learning unit recommendation metadata conflicts with different content';
  end if;

  if to_regclass('public.learning_skill_definitions') is null
     or to_regclass('public.learning_question_skills') is null then
    raise exception using errcode = 'P0002', message = 'learning skill metadata foundation is missing';
  end if;

  if exists (
    select 1
    from (values
  ('multiply-by-2'),
  ('multiply-by-5'),
  ('identify-multiplication-table-pattern'),
  ('multiply-by-3'),
  ('multiply-by-4'),
  ('infer-missing-multiplication-factor'),
  ('compare-multiplication-products'),
  ('model-multiplication-situation'),
  ('multiply-by-6'),
  ('multiply-by-7'),
  ('multiply-by-8'),
  ('multiply-by-9'),
  ('reason-about-multiplication-facts'),
  ('correct-multiplication-reasoning')
    ) expected_skill(skill_code)
    where not exists (
      select 1 from public.learning_skill_definitions definition
      where definition.skill_code = expected_skill.skill_code
    )
  ) then
    raise exception using errcode = 'P0002', message = 'learning skill definition is missing';
  end if;

  if exists (
    select 1 from public.learning_content_versions
    where id = 'db13b15e-752d-4491-832d-75feb9b9eb21'::uuid
       or content_hash = '7c1b81091398d0e00c97d82dd1c431e399a1f4caa56f9cdf869887e638e65282'
  ) then
    raise exception using errcode = '23505', message = 'grade2_multiplication_tables_v1 content version already exists';
  end if;

  if exists (
    select 1 from (
      values
  ('fcfdae70-f84c-47c4-8558-cde9ac381187'::uuid),
  ('e79a7bb8-879e-42c0-865e-f14278841162'::uuid),
  ('fe288080-9edb-4420-9faa-27e90f3fcb77'::uuid),
  ('5a07eeac-894c-4e77-8598-9aab40ea44c5'::uuid),
  ('6d061a04-a11d-4e96-a95f-fe99bdbce39d'::uuid),
  ('a43e3789-7db5-4c9d-bc8d-16d4b9df3d4c'::uuid),
  ('f3eafca7-b748-47d3-a44f-483a1f88fcc9'::uuid),
  ('1a299e0f-4d64-493f-bf06-8b2fe831ba52'::uuid),
  ('0ef3e74f-ad8c-4c63-9a4c-5340a6a6ba66'::uuid),
  ('f60d6ca8-de60-4d66-8b1b-5815ff277f00'::uuid),
  ('715abbba-ef59-4bcf-8128-48a6a6c31748'::uuid),
  ('f43290fa-da02-46df-bbd7-f350d7ff5478'::uuid),
  ('6c10010d-ba70-47fa-b8de-161481d400a7'::uuid),
  ('0ac2fb54-0b88-49ad-8e72-e6bf479faa91'::uuid),
  ('0ddd41c0-5946-436f-a09e-2ce3de79dec0'::uuid),
  ('d13f6fe4-bacd-4542-a354-a032a54a4bea'::uuid),
  ('e9735267-4bc5-4dcc-92e1-d75c7182502d'::uuid),
  ('d909587c-6dac-43f2-82bf-f6170f4786ac'::uuid),
  ('3bf4f190-03f0-4a11-a94d-0926a2ac4773'::uuid),
  ('cdf30c28-d61a-4203-b954-b102c6014b54'::uuid),
  ('92068d41-150b-4585-8316-990e53db6602'::uuid),
  ('56d024fb-d0c4-4cc9-8260-1ff74f61f253'::uuid),
  ('a120b3af-fb9f-4cd2-8ae9-aba68ec14297'::uuid),
  ('12989413-5f95-4e0c-90d8-4335ca3718bb'::uuid),
  ('78ce78d9-6d15-4968-84ba-fe091871ce57'::uuid),
  ('4e6a0696-742f-4e40-96ac-fc394a4bd4ee'::uuid),
  ('aaa80252-6e8e-4f9e-a813-e2cd54541fc4'::uuid),
  ('28f2774a-2163-443c-8258-679ed4af3311'::uuid),
  ('f9a03926-831d-43a7-bc6f-6c8a30198b4a'::uuid),
  ('2540bda6-e257-4638-a18c-daede68cb593'::uuid),
  ('eb695d4a-be93-4d13-af18-9ae866ffd5be'::uuid),
  ('1bed5f23-1cbe-4a51-a9e1-0b6d9fc731c3'::uuid),
  ('51f243fd-04e5-49f3-8daa-28ff26c366c0'::uuid),
  ('671565bd-924e-4b79-b9d1-48e31685c594'::uuid),
  ('37e194a3-1b9f-42af-8c1e-90bf1bc038c0'::uuid),
  ('2efed665-4b28-4355-b67b-07db1b28ec68'::uuid),
  ('6be4ae8c-d973-4b4f-a61c-a9bc1bdad77f'::uuid),
  ('bba4724e-cc51-4769-a268-748195ca0f27'::uuid),
  ('d992467c-51fe-443d-83e8-d562a3e15e1b'::uuid),
  ('85975377-7e54-4ebb-b773-7dde1df43717'::uuid),
  ('f1c936b3-b8da-4f23-9fcd-f0bd8ccec4b3'::uuid),
  ('70cf1187-5f25-4b96-b3ca-d65c3f904f22'::uuid),
  ('8568ac74-cfb5-4b98-a122-76c551e60d32'::uuid),
  ('a9ed729c-94b0-492c-a0f3-d8ea6ae49222'::uuid),
  ('1407bbc5-dc20-43c2-b0b7-d9ffa53928b6'::uuid),
  ('7bc33228-2c5f-4b2b-ae27-f9bb92c4e758'::uuid),
  ('58c757bf-ab3f-491d-938b-4fd49bcdcd4d'::uuid),
  ('8f040604-849d-444b-beee-9c4f55d1e205'::uuid),
  ('b5658913-3fe4-4aeb-b229-30e8ea566392'::uuid),
  ('dbb02d73-be77-4a7f-a23a-309d121f6146'::uuid),
  ('897834ed-547c-45bd-ae6b-6d6e657f36b5'::uuid),
  ('351e99e1-6360-41ae-bae0-f1f121179028'::uuid),
  ('6c02621d-d7e5-4af9-a486-dba7b0ae48eb'::uuid),
  ('3f693cff-4e77-4971-bcf1-992990503565'::uuid),
  ('9c8a32ed-1926-4432-b316-c7b600c21578'::uuid),
  ('3391c7a4-2456-49ea-a02b-ccdba012deb0'::uuid),
  ('6d50364c-aa40-4498-b5d0-0a7035f17271'::uuid),
  ('55d9b8b5-1176-4dfd-a33d-65ef4e76c104'::uuid),
  ('c08e411f-53fe-494f-8bcd-97c7d1984c9a'::uuid),
  ('1db76670-4367-4aa2-9989-fa02736d8dbe'::uuid),
  ('29d47eb0-a858-4501-837c-b162e8f7d927'::uuid),
  ('1d927c67-c034-46af-b60a-8ae9166ee770'::uuid),
  ('9a0d64ae-6511-4d53-9d84-884237ccd50a'::uuid),
  ('101c2afa-df93-4f50-86dc-441f1d08b78f'::uuid),
  ('5a8c9d57-6694-4513-bd94-e7c710ae18ad'::uuid),
  ('bec09180-5a9a-4766-85e9-deb08add427f'::uuid),
  ('cc840754-1ba6-4eb2-99bb-f13645dd8974'::uuid),
  ('a4a1605a-2c75-42c7-a120-37212a884098'::uuid),
  ('2d8aff86-90ea-4755-884e-9be6e9e43fd8'::uuid),
  ('18bcd40f-a75e-4354-81a4-b21342f7d958'::uuid),
  ('7185bd93-0a58-4135-a6de-95c6d7fd749d'::uuid),
  ('9fb7d786-dced-4994-abeb-79968b51425a'::uuid),
  ('ccc8ce48-3d09-4d2c-82dd-1209457815ba'::uuid),
  ('2d09e07c-10f4-4490-85fe-8d42eff20fc9'::uuid),
  ('1d12a5c4-8a35-4b20-ac3d-682aee9b7467'::uuid),
  ('9c8fdffc-a73a-4f7a-9c52-1f303eaedcf2'::uuid),
  ('a563b845-2566-4d8b-9b92-337d5e893040'::uuid),
  ('19cfb0c4-17fe-4d21-b182-8aa843cf5a94'::uuid),
  ('7937b64e-677f-4581-aafd-9cd881e3610e'::uuid),
  ('edaf3b62-aed5-4014-961a-e291dbb6d64e'::uuid),
  ('8bd3536a-ec34-482f-acf1-944687243b32'::uuid),
  ('dfa25a61-c49d-4b9c-b1d1-6e94de23f05b'::uuid),
  ('6a296cf4-16b0-4ae5-a84b-d98fb2e926b5'::uuid),
  ('20db72f3-58a2-4b7b-b8ca-c851ce666ff7'::uuid),
  ('79ff2a2e-8d60-4509-94f2-7a7e191b7f73'::uuid),
  ('88ee5224-dda3-4e5d-acf5-831c4b7c2b69'::uuid),
  ('1ba7a1e2-e518-43b6-bf70-4a5c846d78cd'::uuid),
  ('a102d383-2200-4226-9f97-bcebd20dc75d'::uuid),
  ('85f6d044-9e37-4c6b-9916-badd9931f4a3'::uuid),
  ('a3a62147-960a-48bd-a553-6302c90a3c75'::uuid),
  ('23a1cc9c-898c-4c70-9ffc-ba62ce5a862f'::uuid),
  ('8d0d4741-bea8-4048-bef5-67f47a53825e'::uuid),
  ('1dcce90e-9958-4893-9294-4f007771533b'::uuid),
  ('f758d8f9-47ed-4540-8ae6-d10806efa37c'::uuid),
  ('ac88c2cd-1405-4461-9d28-1f9598a7c940'::uuid),
  ('8d660e1b-e2ec-4aa7-acc9-8e1dbd944bd6'::uuid),
  ('07f3f927-31fb-4f15-9e00-af52eb0c1155'::uuid),
  ('a4589ab1-110e-49df-b864-e24d9b456a56'::uuid),
  ('7dc11932-9b62-41e3-8001-ad8a8cb53e56'::uuid),
  ('2ce30dd1-737c-4d41-978f-9d7b9a10a95c'::uuid),
  ('d1cb67bb-90b6-4be7-86ba-e823be62e0da'::uuid),
  ('e9af1b69-aae5-438a-84a6-2197988a6ed1'::uuid),
  ('859aa9a9-3cd7-40c7-9d1e-899d24317cfd'::uuid),
  ('812c297b-ead3-4d26-99db-9a38edf4c448'::uuid),
  ('bc0354ac-5a2a-41e0-aee2-48972418edcd'::uuid),
  ('b086031b-3bc8-409d-b361-12f0d99d400c'::uuid),
  ('cdf3e726-6465-4137-965c-6a337fc04545'::uuid),
  ('a7d36d38-0d0a-4843-b863-70eebd1354eb'::uuid),
  ('571474e8-4297-42a9-bea7-f0fbf1921de7'::uuid),
  ('922a8431-f57c-4e28-bf97-97a054fc4b14'::uuid),
  ('81a3079f-1333-4eaa-9a9a-4605aff9b0e9'::uuid),
  ('f9aab803-f204-4024-b70a-7b1cb33315db'::uuid),
  ('5240b40b-b557-48fa-a91c-c6ea8c580c24'::uuid),
  ('b1d1151e-292f-4797-aade-b59ca37281ca'::uuid),
  ('43ef8e4d-06da-4097-99dc-95494c0b6926'::uuid),
  ('dc588377-cc15-4b28-a592-8167a41fcd57'::uuid),
  ('cfa2a9db-fa89-4d78-82ec-2cef07add6f7'::uuid),
  ('fe9a4f7a-c2be-4f59-b69b-1788a5aee2a6'::uuid),
  ('a976df5b-ca0e-4ecf-a0bd-635750e1ed84'::uuid),
  ('aebf718a-e94e-41ca-a2d9-c78a89d8f271'::uuid),
  ('d1636a82-823c-4b4c-bad7-7d08b8afd053'::uuid),
  ('a47e3097-6f83-4473-af6e-6ee86650a5e0'::uuid),
  ('648a97ac-169d-4768-9e2e-45b14b54706c'::uuid),
  ('247f272b-ec18-449c-b829-e85721980d94'::uuid),
  ('fdbe9ecf-3f3c-415b-8222-c06282394f80'::uuid),
  ('4da6ed81-956c-4dd9-a7a6-ffaf33f520a9'::uuid),
  ('b17bce55-682d-4768-a4eb-474e8a209b8d'::uuid),
  ('842fa855-8173-4891-9583-da3daec2176b'::uuid),
  ('b73eae01-b349-4c33-a21f-2bc685762f8b'::uuid),
  ('67511979-8101-4d24-b0fe-abf32e293840'::uuid),
  ('68c2f1a7-5bd2-4316-99ff-f32a916ff9d9'::uuid),
  ('ebfbb124-ab7c-4f19-90d9-e4262d395e49'::uuid),
  ('d7fae798-c773-4408-97cb-8841c929e70b'::uuid),
  ('0e5d6272-7585-4936-aeac-05d6a69f44b1'::uuid),
  ('20ed8327-8537-40a8-be12-6889341b6b91'::uuid),
  ('a47cbf69-5685-417b-bfb9-573ab3487804'::uuid),
  ('3fe6628a-bca7-4031-9cb9-7dcdcb908cf2'::uuid),
  ('efc45c61-f4e7-4ac0-923c-9d0e0f5733c1'::uuid),
  ('fa2ab5c2-c52f-42a2-92e8-a41c0aed9fc2'::uuid),
  ('ead1aa87-9b59-4705-aed4-05d6d544c5d8'::uuid),
  ('00466354-749f-4bea-a79b-ff71854107e9'::uuid),
  ('871a0d57-f247-42b8-81fd-02d518a35136'::uuid),
  ('d310fdad-e760-4a09-9cce-dbaf7f453c46'::uuid),
  ('d3d77f8d-2688-42f6-85cd-cca25122a545'::uuid),
  ('b78cdfad-50a8-455e-b6f8-367a50c8d3b6'::uuid),
  ('c2bd71f9-7c3c-47c7-82f4-36b82ca7dca1'::uuid),
  ('00c53da7-e17a-45b5-adb7-2ea686951a8c'::uuid),
  ('d73ad3d1-c576-49e3-a1c7-74b63f39c2ba'::uuid),
  ('69af8249-2732-441d-b667-3e83813bb232'::uuid),
  ('dde54f56-464a-484e-a9b5-d7b242bd99bf'::uuid),
  ('1c6bd2bf-c52f-4503-a50d-05a8ddfc2481'::uuid),
  ('8e88e01b-9876-4c2e-b6fd-b7af5841fd3e'::uuid),
  ('963f7367-b26d-4c9d-ba7e-e2d435298972'::uuid),
  ('1d250c6d-c5e8-48ef-b5f7-306f70898bfc'::uuid),
  ('d6aa0a62-572c-4173-8d8c-8a25130d1406'::uuid),
  ('8171b5fe-1263-446a-994f-379c7e3f1279'::uuid),
  ('08e09f19-9016-4572-84fb-e5008634f3ac'::uuid),
  ('f7d81e29-9b5d-4849-83ea-dbd9478c264b'::uuid),
  ('2a969b97-18b6-4089-afd3-5337251c85d7'::uuid),
  ('25561046-f32b-4da2-a2b2-ac437e16fc59'::uuid),
  ('edbf63c0-50e8-4052-9526-501fe69195e8'::uuid),
  ('9f83e54c-2a92-4aac-884e-baa6a9585837'::uuid),
  ('e4c23f26-e057-403a-8710-f3fead390ca1'::uuid),
  ('4be1164d-2a76-434c-8823-8b96ed8cfab6'::uuid),
  ('9ae8e1b5-ddf8-4b40-93a3-f2c36ad816f7'::uuid),
  ('9b6615e1-f79d-439a-bfcb-83e838635ce8'::uuid),
  ('7a17fb4d-6297-43b4-bcd5-4be9ed5fbb9a'::uuid),
  ('3b2ecd89-56a2-4a87-961f-08c0e94197c7'::uuid),
  ('0ed7040c-becb-4782-80c2-f148eb283de1'::uuid),
  ('995ed56d-dd7a-4121-9856-bfac0d6eb69e'::uuid),
  ('b41d77cb-6d85-4920-aa06-de9b72e7b9e9'::uuid),
  ('cdac4369-df35-43f8-aa45-0de700470ce3'::uuid),
  ('c0926896-5d02-47bb-9656-c6d5ab6ad6e7'::uuid),
  ('4a67e4de-b5bf-4d49-a761-9b85564bf57b'::uuid),
  ('fcd5a1fd-f66f-4221-adbd-2fb349f0677a'::uuid),
  ('7f8c4c37-d3a2-4d16-ac91-ddf0dcc53b41'::uuid),
  ('7ca4cbba-8442-4010-a074-954e598a9520'::uuid),
  ('1261c8cf-88aa-46e8-9f44-93aa84c6da8e'::uuid),
  ('9fd882da-006b-4bc9-8c25-d37e6dcae03e'::uuid),
  ('4687ce22-d399-4d34-bca6-c16d01b59ecb'::uuid),
  ('3d29df10-4af2-4c36-a044-9200dd5dbb07'::uuid),
  ('0c1e0b9e-8148-4030-958e-b505c9efebe2'::uuid),
  ('fda34eb3-924b-4c60-a0b5-6a225a53fcec'::uuid),
  ('7f83c4a8-9beb-49ce-8906-479b38f8c671'::uuid),
  ('ed89e919-6ae4-4b9c-bd3e-338e3a21958f'::uuid),
  ('ebdd47c1-dd9e-4fe8-bd02-5ac545514f20'::uuid),
  ('5f2e92ca-69be-42fe-8198-73246068bd0a'::uuid),
  ('08393693-c674-4b1c-bc8d-ab7ca1c98087'::uuid),
  ('2ba1766e-cad2-4cd4-9570-e670b843cfcc'::uuid),
  ('002cf8ac-f789-4d44-ad22-30535f4207d0'::uuid),
  ('b3ec5455-1773-415b-b0ed-d1252a98f541'::uuid),
  ('2983b040-4e32-4669-aa09-c79c919681ee'::uuid),
  ('843b257f-5e57-495e-a2b5-2959c2a1bb30'::uuid),
  ('e361ca6f-5355-4138-90bd-ae1d2c37be96'::uuid),
  ('f0df9f25-1b1a-4e11-bdff-e6fdb0046b95'::uuid),
  ('bb8e50ea-c4e4-4112-93af-87129a3daf5e'::uuid),
  ('46e950a8-e1a4-4537-8bd0-6d7c595708f1'::uuid),
  ('bce0adf5-7c77-4693-a4cb-34c947ba9c70'::uuid),
  ('eefcb257-f14f-4bfc-b137-8865df42beb1'::uuid),
  ('9910482d-ede6-44dd-a5eb-4a52e923a2cf'::uuid),
  ('10df567a-3f2d-43d4-aa28-9326c4b96da7'::uuid),
  ('a73a4f93-5ef5-4a7d-bb0f-2b295e8d6b65'::uuid),
  ('42280f09-234e-47c0-bdd0-46c417a1b4d3'::uuid),
  ('e0d56565-6c7d-4628-ad80-f7b7e6725dea'::uuid)
    ) as expected_id(id)
    where exists (
      select 1 from public.learning_stages where id = expected_id.id
      union all
      select 1 from public.learning_questions where id = expected_id.id
      union all
      select 1 from public.learning_question_options where id = expected_id.id
    )
  ) then
    raise exception using errcode = '23505', message = 'grade2_multiplication_tables_v1 child content identifier already exists';
  end if;
end
$preflight$;

insert into public.learning_units (id, course_id, unit_code, display_title, sort_order)
values ('362cafc9-09b4-4582-a5dd-d6e868e573d6', '51000000-0000-4000-8000-000000000001', 'grade2-multiplication-tables', '곱셈구구를 익혀요', 9);

insert into public.learning_unit_recommendation_metadata (
  unit_id, subject, recommended_start_level_code, recommended_end_level_code, parent_sort_order
)
select '362cafc9-09b4-4582-a5dd-d6e868e573d6'::uuid, 'math', 'elementary_2', 'elementary_2', 8
where not exists (
  select 1
  from public.learning_unit_recommendation_metadata metadata
  where metadata.unit_id = '362cafc9-09b4-4582-a5dd-d6e868e573d6'::uuid
);

insert into public.learning_content_versions (id, unit_id, version_no, content_hash)
values ('db13b15e-752d-4491-832d-75feb9b9eb21', '362cafc9-09b4-4582-a5dd-d6e868e573d6', 1, '7c1b81091398d0e00c97d82dd1c431e399a1f4caa56f9cdf869887e638e65282');

insert into public.learning_stages (id, content_version_id, display_order, display_title, difficulty)
values
  ('fcfdae70-f84c-47c4-8558-cde9ac381187', 'db13b15e-752d-4491-832d-75feb9b9eb21', 1, '입문', 'seed'),
  ('e79a7bb8-879e-42c0-865e-f14278841162', 'db13b15e-752d-4491-832d-75feb9b9eb21', 2, '기초', 'leaf'),
  ('fe288080-9edb-4420-9faa-27e90f3fcb77', 'db13b15e-752d-4491-832d-75feb9b9eb21', 3, '심화', 'tree'),
  ('5a07eeac-894c-4e77-8598-9aab40ea44c5', 'db13b15e-752d-4491-832d-75feb9b9eb21', 4, '최상위 도전!', 'crown');

insert into public.learning_questions (id, stage_id, display_order, prompt, explanation)
values
  ('6d061a04-a11d-4e96-a95f-fe99bdbce39d', 'fcfdae70-f84c-47c4-8558-cde9ac381187', 1, '2×3의 값은 얼마입니까?', '2를 3번 더하면 2+2+2=6이므로 2×3=6입니다.'),
  ('a43e3789-7db5-4c9d-bc8d-16d4b9df3d4c', 'fcfdae70-f84c-47c4-8558-cde9ac381187', 2, '5×4의 값은 얼마입니까?', '5를 4번 더하면 5+5+5+5=20이므로 5×4=20입니다.'),
  ('f3eafca7-b748-47d3-a44f-483a1f88fcc9', 'fcfdae70-f84c-47c4-8558-cde9ac381187', 3, '2×7의 알맞은 곱은?', '2씩 7묶음은 2를 7번 더한 14이므로 2×7=14입니다.'),
  ('1a299e0f-4d64-493f-bf06-8b2fe831ba52', 'fcfdae70-f84c-47c4-8558-cde9ac381187', 4, '5×6을 바르게 계산한 것은?', '5씩 6묶음은 30이므로 5×6=30입니다.'),
  ('0ef3e74f-ad8c-4c63-9a4c-5340a6a6ba66', 'fcfdae70-f84c-47c4-8558-cde9ac381187', 5, '2×4=8 다음에 이어지는 2단 식은?', '묶음 수가 하나 늘면 2만큼 커지므로 2×5=10입니다.'),
  ('f60d6ca8-de60-4d66-8b1b-5815ff277f00', 'fcfdae70-f84c-47c4-8558-cde9ac381187', 6, '5×8의 값은 얼마입니까?', '5를 8번 더한 값은 40이므로 5×8=40입니다.'),
  ('715abbba-ef59-4bcf-8128-48a6a6c31748', 'fcfdae70-f84c-47c4-8558-cde9ac381187', 7, '2×9의 계산 결과는?', '2씩 9묶음은 18이므로 2×9=18입니다.'),
  ('f43290fa-da02-46df-bbd7-f350d7ff5478', 'fcfdae70-f84c-47c4-8558-cde9ac381187', 8, '5×7에 알맞은 값은?', '5씩 7묶음은 35이므로 5×7=35입니다.'),
  ('6c10010d-ba70-47fa-b8de-161481d400a7', 'fcfdae70-f84c-47c4-8558-cde9ac381187', 9, '2×6을 바르게 계산한 것은?', '2를 6번 더하면 12이므로 2×6=12입니다.'),
  ('0ac2fb54-0b88-49ad-8e72-e6bf479faa91', 'fcfdae70-f84c-47c4-8558-cde9ac381187', 10, '5×9의 값은 얼마입니까?', '5를 9번 더한 값은 45이므로 5×9=45입니다.'),
  ('0ddd41c0-5946-436f-a09e-2ce3de79dec0', 'e79a7bb8-879e-42c0-865e-f14278841162', 1, '3×4의 값은 얼마입니까?', '3을 4번 더하면 3+3+3+3=12이므로 3×4=12입니다.'),
  ('d13f6fe4-bacd-4542-a354-a032a54a4bea', 'e79a7bb8-879e-42c0-865e-f14278841162', 2, '4×6을 바르게 계산한 것은?', '4씩 6묶음은 24이므로 4×6=24입니다.'),
  ('e9735267-4bc5-4dcc-92e1-d75c7182502d', 'e79a7bb8-879e-42c0-865e-f14278841162', 3, '3×□=21에서 □에 알맞은 수는?', '3×7=21이므로 빈칸에는 7이 들어갑니다.'),
  ('d909587c-6dac-43f2-82bf-f6170f4786ac', 'e79a7bb8-879e-42c0-865e-f14278841162', 4, '4×5와 3×6의 크기를 바르게 비교한 것은?', '4×5=20이고 3×6=18이므로 4×5가 더 큽니다.'),
  ('3bf4f190-03f0-4a11-a94d-0926a2ac4773', 'e79a7bb8-879e-42c0-865e-f14278841162', 5, '연필을 한 사람에게 3자루씩 8명에게 줍니다. 필요한 연필 수를 구하는 식과 답은?', '한 묶음의 수 3을 앞에 쓰고 사람 수 8을 뒤에 써서 3×8=24입니다.'),
  ('cdf30c28-d61a-4203-b954-b102c6014b54', 'e79a7bb8-879e-42c0-865e-f14278841162', 6, '4×7에 알맞은 상황은?', '4×7은 한 묶음에 4개씩 7묶음이므로 바구니 7개에 사과가 4개씩 있는 상황입니다.'),
  ('92068d41-150b-4585-8316-990e53db6602', 'e79a7bb8-879e-42c0-865e-f14278841162', 7, '3×5=15에서 묶음 수가 하나 늘어난 식은?', '묶음 수가 5에서 6으로 하나 늘면 곱은 3만큼 커져 3×6=18입니다.'),
  ('56d024fb-d0c4-4cc9-8260-1ff74f61f253', 'e79a7bb8-879e-42c0-865e-f14278841162', 8, '4×□=32에서 □에 알맞은 수는?', '4×8=32이므로 빈칸에는 8이 들어갑니다.'),
  ('a120b3af-fb9f-4cd2-8ae9-aba68ec14297', 'e79a7bb8-879e-42c0-865e-f14278841162', 9, '3×9의 값은 얼마입니까?', '3을 9번 더한 값은 27이므로 3×9=27입니다.'),
  ('12989413-5f95-4e0c-90d8-4335ca3718bb', 'e79a7bb8-879e-42c0-865e-f14278841162', 10, '상자마다 스티커가 4장씩 있고 상자가 9개입니다. 스티커는 모두 몇 장입니까?', '한 상자의 4장이 한 묶음이고 상자가 9개이므로 4×9=36장입니다.'),
  ('78ce78d9-6d15-4968-84ba-fe091871ce57', 'fe288080-9edb-4420-9faa-27e90f3fcb77', 1, '6×7의 값은 얼마입니까?', '6씩 7묶음은 42이므로 6×7=42입니다.'),
  ('4e6a0696-742f-4e40-96ac-fc394a4bd4ee', 'fe288080-9edb-4420-9faa-27e90f3fcb77', 2, '7×8을 바르게 계산한 것은?', '7씩 8묶음은 56이므로 7×8=56입니다.'),
  ('aaa80252-6e8e-4f9e-a813-e2cd54541fc4', 'fe288080-9edb-4420-9faa-27e90f3fcb77', 3, '8×9의 계산 결과는?', '8씩 9묶음은 72이므로 8×9=72입니다.'),
  ('28f2774a-2163-443c-8258-679ed4af3311', 'fe288080-9edb-4420-9faa-27e90f3fcb77', 4, '9×6의 값은 얼마입니까?', '9를 6번 더한 값은 54이므로 9×6=54입니다.'),
  ('f9a03926-831d-43a7-bc6f-6c8a30198b4a', 'fe288080-9edb-4420-9faa-27e90f3fcb77', 5, '6×□=48에서 □에 알맞은 수는?', '6×8=48이므로 빈칸에는 8이 들어갑니다.'),
  ('2540bda6-e257-4638-a18c-daede68cb593', 'fe288080-9edb-4420-9faa-27e90f3fcb77', 6, '7×6과 8×5의 크기를 바르게 비교한 것은?', '7×6=42이고 8×5=40이므로 7×6이 더 큽니다.'),
  ('eb695d4a-be93-4d13-af18-9ae866ffd5be', 'fe288080-9edb-4420-9faa-27e90f3fcb77', 7, '8×6과 같은 결과를 만드는 식은?', '8×6=48이고 6×8=48이므로 두 식의 결과가 같습니다.'),
  ('1bed5f23-1cbe-4a51-a9e1-0b6d9fc731c3', 'fe288080-9edb-4420-9faa-27e90f3fcb77', 8, '9×4=36에서 묶음 수가 하나 늘면 곱은 어떻게 됩니까?', '9단에서 묶음 수가 하나 늘면 곱은 9만큼 커져 9×5=45가 됩니다.'),
  ('51f243fd-04e5-49f3-8daa-28ff26c366c0', 'fe288080-9edb-4420-9faa-27e90f3fcb77', 9, '다음 곱셈식 중 결과가 가장 큰 것은?', '7×9=63이고 나머지는 56 또는 54이므로 7×9의 결과가 가장 큽니다.'),
  ('671565bd-924e-4b79-b9d1-48e31685c594', 'fe288080-9edb-4420-9faa-27e90f3fcb77', 10, '9×□=72에서 □에 알맞은 수는?', '9×8=72이므로 빈칸에는 8이 들어갑니다.'),
  ('37e194a3-1b9f-42af-8c1e-90bf1bc038c0', '5a07eeac-894c-4e77-8598-9aab40ea44c5', 1, '6×8=46이라고 계산했습니다. 바르게 고친 것은?', '6씩 8묶음은 48이므로 46이 아니라 6×8=48입니다.'),
  ('2efed665-4b28-4355-b67b-07db1b28ec68', '5a07eeac-894c-4e77-8598-9aab40ea44c5', 2, '봉지마다 구슬이 7개씩 있고 봉지가 6개입니다. 구슬 수를 구한 식과 설명이 알맞은 것은?', '한 봉지의 7개가 한 묶음이고 봉지가 6개이므로 7×6=42입니다.'),
  ('6be4ae8c-d973-4b4f-a61c-a9bc1bdad77f', '5a07eeac-894c-4e77-8598-9aab40ea44c5', 3, '9×4와 같은 결과를 만드는 곱셈식은?', '9×4=36이고 6×6=36이므로 두 식의 결과가 같습니다.'),
  ('bba4724e-cc51-4769-a268-748195ca0f27', '5a07eeac-894c-4e77-8598-9aab40ea44c5', 4, '8×7의 결과와 설명이 모두 알맞은 것은?', '8×7=56이고 8×6=48이므로 묶음 수가 하나 늘어 8만큼 큽니다.'),
  ('d992467c-51fe-443d-83e8-d562a3e15e1b', '5a07eeac-894c-4e77-8598-9aab40ea44c5', 5, '접시 5개에 쿠키가 9개씩 있습니다. 5×9라고 쓴 생각을 바르게 고친 것은?', '한 접시의 쿠키 9개가 한 묶음이고 접시가 5개이므로 9×5=45로 씁니다.'),
  ('85975377-7e54-4ebb-b773-7dde1df43717', '5a07eeac-894c-4e77-8598-9aab40ea44c5', 6, '7단에서 묶음 수가 하나씩 늘어날 때의 규칙은?', '7씩 묶인 묶음이 하나 늘 때마다 7이 더해지므로 곱은 7씩 커집니다.'),
  ('f1c936b3-b8da-4f23-9fcd-f0bd8ccec4b3', '5a07eeac-894c-4e77-8598-9aab40ea44c5', 7, '다음 중 잘못 계산한 식은?', '8×7은 56이므로 8×7=54가 잘못된 계산입니다.'),
  ('70cf1187-5f25-4b96-b3ca-d65c3f904f22', '5a07eeac-894c-4e77-8598-9aab40ea44c5', 8, '결과가 50보다 크고 9단인 식은?', '9×6=54는 9단이면서 결과가 50보다 큽니다.'),
  ('8568ac74-cfb5-4b98-a122-76c551e60d32', '5a07eeac-894c-4e77-8598-9aab40ea44c5', 9, '□×8=64에서 □에 알맞은 수와 까닭은?', '8×8=64이므로 빈칸에 알맞은 수는 8입니다.'),
  ('a9ed729c-94b0-492c-a0f3-d8ea6ae49222', '5a07eeac-894c-4e77-8598-9aab40ea44c5', 10, '6×8과 8×6을 바르게 설명한 것은?', '6×8은 6씩 8묶음이고 8×6은 8씩 6묶음이어서 뜻은 다르지만 결과는 모두 48입니다.');

insert into public.learning_question_options (id, question_id, display_order, option_text, is_correct)
values
  ('1407bbc5-dc20-43c2-b0b7-d9ffa53928b6', '6d061a04-a11d-4e96-a95f-fe99bdbce39d', 1, '6', true),
  ('7bc33228-2c5f-4b2b-ae27-f9bb92c4e758', '6d061a04-a11d-4e96-a95f-fe99bdbce39d', 2, '5', false),
  ('58c757bf-ab3f-491d-938b-4fd49bcdcd4d', '6d061a04-a11d-4e96-a95f-fe99bdbce39d', 3, '8', false),
  ('8f040604-849d-444b-beee-9c4f55d1e205', '6d061a04-a11d-4e96-a95f-fe99bdbce39d', 4, '9', false),
  ('b5658913-3fe4-4aeb-b229-30e8ea566392', 'a43e3789-7db5-4c9d-bc8d-16d4b9df3d4c', 1, '25', false),
  ('dbb02d73-be77-4a7f-a23a-309d121f6146', 'a43e3789-7db5-4c9d-bc8d-16d4b9df3d4c', 2, '20', true),
  ('897834ed-547c-45bd-ae6b-6d6e657f36b5', 'a43e3789-7db5-4c9d-bc8d-16d4b9df3d4c', 3, '15', false),
  ('351e99e1-6360-41ae-bae0-f1f121179028', 'a43e3789-7db5-4c9d-bc8d-16d4b9df3d4c', 4, '9', false),
  ('6c02621d-d7e5-4af9-a486-dba7b0ae48eb', 'f3eafca7-b748-47d3-a44f-483a1f88fcc9', 1, '12', false),
  ('3f693cff-4e77-4971-bcf1-992990503565', 'f3eafca7-b748-47d3-a44f-483a1f88fcc9', 2, '16', false),
  ('9c8a32ed-1926-4432-b316-c7b600c21578', 'f3eafca7-b748-47d3-a44f-483a1f88fcc9', 3, '14', true),
  ('3391c7a4-2456-49ea-a02b-ccdba012deb0', 'f3eafca7-b748-47d3-a44f-483a1f88fcc9', 4, '9', false),
  ('6d50364c-aa40-4498-b5d0-0a7035f17271', '1a299e0f-4d64-493f-bf06-8b2fe831ba52', 1, '25', false),
  ('55d9b8b5-1176-4dfd-a33d-65ef4e76c104', '1a299e0f-4d64-493f-bf06-8b2fe831ba52', 2, '35', false),
  ('c08e411f-53fe-494f-8bcd-97c7d1984c9a', '1a299e0f-4d64-493f-bf06-8b2fe831ba52', 3, '11', false),
  ('1db76670-4367-4aa2-9989-fa02736d8dbe', '1a299e0f-4d64-493f-bf06-8b2fe831ba52', 4, '30', true),
  ('29d47eb0-a858-4501-837c-b162e8f7d927', '0ef3e74f-ad8c-4c63-9a4c-5340a6a6ba66', 1, '2×5=10', true),
  ('1d927c67-c034-46af-b60a-8ae9166ee770', '0ef3e74f-ad8c-4c63-9a4c-5340a6a6ba66', 2, '2×5=8', false),
  ('9a0d64ae-6511-4d53-9d84-884237ccd50a', '0ef3e74f-ad8c-4c63-9a4c-5340a6a6ba66', 3, '2×6=10', false),
  ('101c2afa-df93-4f50-86dc-441f1d08b78f', '0ef3e74f-ad8c-4c63-9a4c-5340a6a6ba66', 4, '2×4=10', false),
  ('5a8c9d57-6694-4513-bd94-e7c710ae18ad', 'f60d6ca8-de60-4d66-8b1b-5815ff277f00', 1, '35', false),
  ('bec09180-5a9a-4766-85e9-deb08add427f', 'f60d6ca8-de60-4d66-8b1b-5815ff277f00', 2, '40', true),
  ('cc840754-1ba6-4eb2-99bb-f13645dd8974', 'f60d6ca8-de60-4d66-8b1b-5815ff277f00', 3, '45', false),
  ('a4a1605a-2c75-42c7-a120-37212a884098', 'f60d6ca8-de60-4d66-8b1b-5815ff277f00', 4, '13', false),
  ('2d8aff86-90ea-4755-884e-9be6e9e43fd8', '715abbba-ef59-4bcf-8128-48a6a6c31748', 1, '16', false),
  ('18bcd40f-a75e-4354-81a4-b21342f7d958', '715abbba-ef59-4bcf-8128-48a6a6c31748', 2, '20', false),
  ('7185bd93-0a58-4135-a6de-95c6d7fd749d', '715abbba-ef59-4bcf-8128-48a6a6c31748', 3, '18', true),
  ('9fb7d786-dced-4994-abeb-79968b51425a', '715abbba-ef59-4bcf-8128-48a6a6c31748', 4, '11', false),
  ('ccc8ce48-3d09-4d2c-82dd-1209457815ba', 'f43290fa-da02-46df-bbd7-f350d7ff5478', 1, '30', false),
  ('2d09e07c-10f4-4490-85fe-8d42eff20fc9', 'f43290fa-da02-46df-bbd7-f350d7ff5478', 2, '40', false),
  ('1d12a5c4-8a35-4b20-ac3d-682aee9b7467', 'f43290fa-da02-46df-bbd7-f350d7ff5478', 3, '12', false),
  ('9c8fdffc-a73a-4f7a-9c52-1f303eaedcf2', 'f43290fa-da02-46df-bbd7-f350d7ff5478', 4, '35', true),
  ('a563b845-2566-4d8b-9b92-337d5e893040', '6c10010d-ba70-47fa-b8de-161481d400a7', 1, '12', true),
  ('19cfb0c4-17fe-4d21-b182-8aa843cf5a94', '6c10010d-ba70-47fa-b8de-161481d400a7', 2, '10', false),
  ('7937b64e-677f-4581-aafd-9cd881e3610e', '6c10010d-ba70-47fa-b8de-161481d400a7', 3, '14', false),
  ('edaf3b62-aed5-4014-961a-e291dbb6d64e', '6c10010d-ba70-47fa-b8de-161481d400a7', 4, '8', false),
  ('8bd3536a-ec34-482f-acf1-944687243b32', '0ac2fb54-0b88-49ad-8e72-e6bf479faa91', 1, '40', false),
  ('dfa25a61-c49d-4b9c-b1d1-6e94de23f05b', '0ac2fb54-0b88-49ad-8e72-e6bf479faa91', 2, '45', true),
  ('6a296cf4-16b0-4ae5-a84b-d98fb2e926b5', '0ac2fb54-0b88-49ad-8e72-e6bf479faa91', 3, '50', false),
  ('20db72f3-58a2-4b7b-b8ca-c851ce666ff7', '0ac2fb54-0b88-49ad-8e72-e6bf479faa91', 4, '14', false),
  ('79ff2a2e-8d60-4509-94f2-7a7e191b7f73', '0ddd41c0-5946-436f-a09e-2ce3de79dec0', 1, '12', true),
  ('88ee5224-dda3-4e5d-acf5-831c4b7c2b69', '0ddd41c0-5946-436f-a09e-2ce3de79dec0', 2, '9', false),
  ('1ba7a1e2-e518-43b6-bf70-4a5c846d78cd', '0ddd41c0-5946-436f-a09e-2ce3de79dec0', 3, '16', false),
  ('a102d383-2200-4226-9f97-bcebd20dc75d', '0ddd41c0-5946-436f-a09e-2ce3de79dec0', 4, '7', false),
  ('85f6d044-9e37-4c6b-9916-badd9931f4a3', 'd13f6fe4-bacd-4542-a354-a032a54a4bea', 1, '20', false),
  ('a3a62147-960a-48bd-a553-6302c90a3c75', 'd13f6fe4-bacd-4542-a354-a032a54a4bea', 2, '24', true),
  ('23a1cc9c-898c-4c70-9ffc-ba62ce5a862f', 'd13f6fe4-bacd-4542-a354-a032a54a4bea', 3, '28', false),
  ('8d0d4741-bea8-4048-bef5-67f47a53825e', 'd13f6fe4-bacd-4542-a354-a032a54a4bea', 4, '10', false),
  ('1dcce90e-9958-4893-9294-4f007771533b', 'e9735267-4bc5-4dcc-92e1-d75c7182502d', 1, '6', false),
  ('f758d8f9-47ed-4540-8ae6-d10806efa37c', 'e9735267-4bc5-4dcc-92e1-d75c7182502d', 2, '8', false),
  ('ac88c2cd-1405-4461-9d28-1f9598a7c940', 'e9735267-4bc5-4dcc-92e1-d75c7182502d', 3, '7', true),
  ('8d660e1b-e2ec-4aa7-acc9-8e1dbd944bd6', 'e9735267-4bc5-4dcc-92e1-d75c7182502d', 4, '9', false),
  ('07f3f927-31fb-4f15-9e00-af52eb0c1155', 'd909587c-6dac-43f2-82bf-f6170f4786ac', 1, '4×5<3×6', false),
  ('a4589ab1-110e-49df-b864-e24d9b456a56', 'd909587c-6dac-43f2-82bf-f6170f4786ac', 2, '4×5=3×6', false),
  ('7dc11932-9b62-41e3-8001-ad8a8cb53e56', 'd909587c-6dac-43f2-82bf-f6170f4786ac', 3, '20<18', false),
  ('2ce30dd1-737c-4d41-978f-9d7b9a10a95c', 'd909587c-6dac-43f2-82bf-f6170f4786ac', 4, '4×5>3×6', true),
  ('d1cb67bb-90b6-4be7-86ba-e823be62e0da', '3bf4f190-03f0-4a11-a94d-0926a2ac4773', 1, '3×8=24', true),
  ('e9af1b69-aae5-438a-84a6-2197988a6ed1', '3bf4f190-03f0-4a11-a94d-0926a2ac4773', 2, '8×3=24', false),
  ('859aa9a9-3cd7-40c7-9d1e-899d24317cfd', '3bf4f190-03f0-4a11-a94d-0926a2ac4773', 3, '3+8=11', false),
  ('812c297b-ead3-4d26-99db-9a38edf4c448', '3bf4f190-03f0-4a11-a94d-0926a2ac4773', 4, '3×7=21', false),
  ('bc0354ac-5a2a-41e0-aee2-48972418edcd', 'cdf30c28-d61a-4203-b954-b102c6014b54', 1, '바구니 4개에 사과가 7개씩 있음', false),
  ('b086031b-3bc8-409d-b361-12f0d99d400c', 'cdf30c28-d61a-4203-b954-b102c6014b54', 2, '바구니 7개에 사과가 4개씩 있음', true),
  ('cdf3e726-6465-4137-965c-6a337fc04545', 'cdf30c28-d61a-4203-b954-b102c6014b54', 3, '사과 4개와 7개를 더함', false),
  ('a7d36d38-0d0a-4843-b863-70eebd1354eb', 'cdf30c28-d61a-4203-b954-b102c6014b54', 4, '바구니마다 사과 수가 다름', false),
  ('571474e8-4297-42a9-bea7-f0fbf1921de7', '92068d41-150b-4585-8316-990e53db6602', 1, '3×4=12', false),
  ('922a8431-f57c-4e28-bf97-97a054fc4b14', '92068d41-150b-4585-8316-990e53db6602', 2, '3×5=18', false),
  ('81a3079f-1333-4eaa-9a9a-4605aff9b0e9', '92068d41-150b-4585-8316-990e53db6602', 3, '3×6=18', true),
  ('f9aab803-f204-4024-b70a-7b1cb33315db', '92068d41-150b-4585-8316-990e53db6602', 4, '3×6=15', false),
  ('5240b40b-b557-48fa-a91c-c6ea8c580c24', '56d024fb-d0c4-4cc9-8260-1ff74f61f253', 1, '6', false),
  ('b1d1151e-292f-4797-aade-b59ca37281ca', '56d024fb-d0c4-4cc9-8260-1ff74f61f253', 2, '7', false),
  ('43ef8e4d-06da-4097-99dc-95494c0b6926', '56d024fb-d0c4-4cc9-8260-1ff74f61f253', 3, '9', false),
  ('dc588377-cc15-4b28-a592-8167a41fcd57', '56d024fb-d0c4-4cc9-8260-1ff74f61f253', 4, '8', true),
  ('cfa2a9db-fa89-4d78-82ec-2cef07add6f7', 'a120b3af-fb9f-4cd2-8ae9-aba68ec14297', 1, '24', false),
  ('fe9a4f7a-c2be-4f59-b69b-1788a5aee2a6', 'a120b3af-fb9f-4cd2-8ae9-aba68ec14297', 2, '30', false),
  ('a976df5b-ca0e-4ecf-a0bd-635750e1ed84', 'a120b3af-fb9f-4cd2-8ae9-aba68ec14297', 3, '27', true),
  ('aebf718a-e94e-41ca-a2d9-c78a89d8f271', 'a120b3af-fb9f-4cd2-8ae9-aba68ec14297', 4, '12', false),
  ('d1636a82-823c-4b4c-bad7-7d08b8afd053', '12989413-5f95-4e0c-90d8-4335ca3718bb', 1, '13장', false),
  ('a47e3097-6f83-4473-af6e-6ee86650a5e0', '12989413-5f95-4e0c-90d8-4335ca3718bb', 2, '32장', false),
  ('648a97ac-169d-4768-9e2e-45b14b54706c', '12989413-5f95-4e0c-90d8-4335ca3718bb', 3, '40장', false),
  ('247f272b-ec18-449c-b829-e85721980d94', '12989413-5f95-4e0c-90d8-4335ca3718bb', 4, '36장', true),
  ('fdbe9ecf-3f3c-415b-8222-c06282394f80', '78ce78d9-6d15-4968-84ba-fe091871ce57', 1, '42', true),
  ('4da6ed81-956c-4dd9-a7a6-ffaf33f520a9', '78ce78d9-6d15-4968-84ba-fe091871ce57', 2, '36', false),
  ('b17bce55-682d-4768-a4eb-474e8a209b8d', '78ce78d9-6d15-4968-84ba-fe091871ce57', 3, '48', false),
  ('842fa855-8173-4891-9583-da3daec2176b', '78ce78d9-6d15-4968-84ba-fe091871ce57', 4, '13', false),
  ('b73eae01-b349-4c33-a21f-2bc685762f8b', '4e6a0696-742f-4e40-96ac-fc394a4bd4ee', 1, '49', false),
  ('67511979-8101-4d24-b0fe-abf32e293840', '4e6a0696-742f-4e40-96ac-fc394a4bd4ee', 2, '56', true),
  ('68c2f1a7-5bd2-4316-99ff-f32a916ff9d9', '4e6a0696-742f-4e40-96ac-fc394a4bd4ee', 3, '64', false),
  ('ebfbb124-ab7c-4f19-90d9-e4262d395e49', '4e6a0696-742f-4e40-96ac-fc394a4bd4ee', 4, '15', false),
  ('d7fae798-c773-4408-97cb-8841c929e70b', 'aaa80252-6e8e-4f9e-a813-e2cd54541fc4', 1, '64', false),
  ('0e5d6272-7585-4936-aeac-05d6a69f44b1', 'aaa80252-6e8e-4f9e-a813-e2cd54541fc4', 2, '81', false),
  ('20ed8327-8537-40a8-be12-6889341b6b91', 'aaa80252-6e8e-4f9e-a813-e2cd54541fc4', 3, '72', true),
  ('a47cbf69-5685-417b-bfb9-573ab3487804', 'aaa80252-6e8e-4f9e-a813-e2cd54541fc4', 4, '17', false),
  ('3fe6628a-bca7-4031-9cb9-7dcdcb908cf2', '28f2774a-2163-443c-8258-679ed4af3311', 1, '45', false),
  ('efc45c61-f4e7-4ac0-923c-9d0e0f5733c1', '28f2774a-2163-443c-8258-679ed4af3311', 2, '63', false),
  ('fa2ab5c2-c52f-42a2-92e8-a41c0aed9fc2', '28f2774a-2163-443c-8258-679ed4af3311', 3, '15', false),
  ('ead1aa87-9b59-4705-aed4-05d6d544c5d8', '28f2774a-2163-443c-8258-679ed4af3311', 4, '54', true),
  ('00466354-749f-4bea-a79b-ff71854107e9', 'f9a03926-831d-43a7-bc6f-6c8a30198b4a', 1, '8', true),
  ('871a0d57-f247-42b8-81fd-02d518a35136', 'f9a03926-831d-43a7-bc6f-6c8a30198b4a', 2, '7', false),
  ('d310fdad-e760-4a09-9cce-dbaf7f453c46', 'f9a03926-831d-43a7-bc6f-6c8a30198b4a', 3, '9', false),
  ('d3d77f8d-2688-42f6-85cd-cca25122a545', 'f9a03926-831d-43a7-bc6f-6c8a30198b4a', 4, '6', false),
  ('b78cdfad-50a8-455e-b6f8-367a50c8d3b6', '2540bda6-e257-4638-a18c-daede68cb593', 1, '7×6<8×5', false),
  ('c2bd71f9-7c3c-47c7-82f4-36b82ca7dca1', '2540bda6-e257-4638-a18c-daede68cb593', 2, '7×6>8×5', true),
  ('00c53da7-e17a-45b5-adb7-2ea686951a8c', '2540bda6-e257-4638-a18c-daede68cb593', 3, '7×6=8×5', false),
  ('d73ad3d1-c576-49e3-a1c7-74b63f39c2ba', '2540bda6-e257-4638-a18c-daede68cb593', 4, '42<40', false),
  ('69af8249-2732-441d-b667-3e83813bb232', 'eb695d4a-be93-4d13-af18-9ae866ffd5be', 1, '7×6', false),
  ('dde54f56-464a-484e-a9b5-d7b242bd99bf', 'eb695d4a-be93-4d13-af18-9ae866ffd5be', 2, '8×5', false),
  ('1c6bd2bf-c52f-4503-a50d-05a8ddfc2481', 'eb695d4a-be93-4d13-af18-9ae866ffd5be', 3, '6×8', true),
  ('8e88e01b-9876-4c2e-b6fd-b7af5841fd3e', 'eb695d4a-be93-4d13-af18-9ae866ffd5be', 4, '9×6', false),
  ('963f7367-b26d-4c9d-ba7e-e2d435298972', '1bed5f23-1cbe-4a51-a9e1-0b6d9fc731c3', 1, '4만큼 커져 40', false),
  ('1d250c6d-c5e8-48ef-b5f7-306f70898bfc', '1bed5f23-1cbe-4a51-a9e1-0b6d9fc731c3', 2, '9만큼 작아져 27', false),
  ('d6aa0a62-572c-4173-8d8c-8a25130d1406', '1bed5f23-1cbe-4a51-a9e1-0b6d9fc731c3', 3, '4만큼 작아져 32', false),
  ('8171b5fe-1263-446a-994f-379c7e3f1279', '1bed5f23-1cbe-4a51-a9e1-0b6d9fc731c3', 4, '9만큼 커져 45', true),
  ('08e09f19-9016-4572-84fb-e5008634f3ac', '51f243fd-04e5-49f3-8daa-28ff26c366c0', 1, '7×9', true),
  ('f7d81e29-9b5d-4849-83ea-dbd9478c264b', '51f243fd-04e5-49f3-8daa-28ff26c366c0', 2, '8×7', false),
  ('2a969b97-18b6-4089-afd3-5337251c85d7', '51f243fd-04e5-49f3-8daa-28ff26c366c0', 3, '6×9', false),
  ('25561046-f32b-4da2-a2b2-ac437e16fc59', '51f243fd-04e5-49f3-8daa-28ff26c366c0', 4, '9×6', false),
  ('edbf63c0-50e8-4052-9526-501fe69195e8', '671565bd-924e-4b79-b9d1-48e31685c594', 1, '7', false),
  ('9f83e54c-2a92-4aac-884e-baa6a9585837', '671565bd-924e-4b79-b9d1-48e31685c594', 2, '8', true),
  ('e4c23f26-e057-403a-8710-f3fead390ca1', '671565bd-924e-4b79-b9d1-48e31685c594', 3, '9', false),
  ('4be1164d-2a76-434c-8823-8b96ed8cfab6', '671565bd-924e-4b79-b9d1-48e31685c594', 4, '6', false),
  ('9ae8e1b5-ddf8-4b40-93a3-f2c36ad816f7', '37e194a3-1b9f-42af-8c1e-90bf1bc038c0', 1, '6×8=48', true),
  ('9b6615e1-f79d-439a-bfcb-83e838635ce8', '37e194a3-1b9f-42af-8c1e-90bf1bc038c0', 2, '6×8=42', false),
  ('7a17fb4d-6297-43b4-bcd5-4be9ed5fbb9a', '37e194a3-1b9f-42af-8c1e-90bf1bc038c0', 3, '6×8=54', false),
  ('3b2ecd89-56a2-4a87-961f-08c0e94197c7', '37e194a3-1b9f-42af-8c1e-90bf1bc038c0', 4, '6×8=14', false),
  ('0ed7040c-becb-4782-80c2-f148eb283de1', '2efed665-4b28-4355-b67b-07db1b28ec68', 1, '6×7=42이고 봉지 수를 앞에 씁니다.', false),
  ('995ed56d-dd7a-4121-9856-bfac0d6eb69e', '2efed665-4b28-4355-b67b-07db1b28ec68', 2, '7×6=42이고 한 봉지의 수를 앞에 씁니다.', true),
  ('b41d77cb-6d85-4920-aa06-de9b72e7b9e9', '2efed665-4b28-4355-b67b-07db1b28ec68', 3, '7+6=13이고 두 수를 더합니다.', false),
  ('cdac4369-df35-43f8-aa45-0de700470ce3', '2efed665-4b28-4355-b67b-07db1b28ec68', 4, '7×5=35이고 봉지 하나를 뺍니다.', false),
  ('c0926896-5d02-47bb-9656-c6d5ab6ad6e7', '6be4ae8c-d973-4b4f-a61c-a9bc1bdad77f', 1, '8×4', false),
  ('4a67e4de-b5bf-4d49-a761-9b85564bf57b', '6be4ae8c-d973-4b4f-a61c-a9bc1bdad77f', 2, '7×5', false),
  ('fcd5a1fd-f66f-4221-adbd-2fb349f0677a', '6be4ae8c-d973-4b4f-a61c-a9bc1bdad77f', 3, '6×6', true),
  ('7f8c4c37-d3a2-4d16-ac91-ddf0dcc53b41', '6be4ae8c-d973-4b4f-a61c-a9bc1bdad77f', 4, '5×6', false),
  ('7ca4cbba-8442-4010-a074-954e598a9520', 'bba4724e-cc51-4769-a268-748195ca0f27', 1, '48이며 8×6보다 8만큼 작습니다.', false),
  ('1261c8cf-88aa-46e8-9f44-93aa84c6da8e', 'bba4724e-cc51-4769-a268-748195ca0f27', 2, '54이며 8과 7을 더했습니다.', false),
  ('9fd882da-006b-4bc9-8c25-d37e6dcae03e', 'bba4724e-cc51-4769-a268-748195ca0f27', 3, '64이며 8×8과 같습니다.', false),
  ('4687ce22-d399-4d34-bca6-c16d01b59ecb', 'bba4724e-cc51-4769-a268-748195ca0f27', 4, '56이며 8×6보다 8만큼 큽니다.', true),
  ('3d29df10-4af2-4c36-a044-9200dd5dbb07', 'd992467c-51fe-443d-83e8-d562a3e15e1b', 1, '한 묶음의 수 9를 앞에 써서 9×5=45입니다.', true),
  ('0c1e0b9e-8148-4030-958e-b505c9efebe2', 'd992467c-51fe-443d-83e8-d562a3e15e1b', 2, '접시 수 5를 앞에 썼으므로 그대로 맞습니다.', false),
  ('fda34eb3-924b-4c60-a0b5-6a225a53fcec', 'd992467c-51fe-443d-83e8-d562a3e15e1b', 3, '두 수를 더해 5+9=14입니다.', false),
  ('7f83c4a8-9beb-49ce-8906-479b38f8c671', 'd992467c-51fe-443d-83e8-d562a3e15e1b', 4, '전체 수를 앞에 써서 45×1입니다.', false),
  ('ed89e919-6ae4-4b9c-bd3e-338e3a21958f', '85975377-7e54-4ebb-b773-7dde1df43717', 1, '곱이 1씩 커집니다.', false),
  ('ebdd47c1-dd9e-4fe8-bd02-5ac545514f20', '85975377-7e54-4ebb-b773-7dde1df43717', 2, '곱이 7씩 커집니다.', true),
  ('5f2e92ca-69be-42fe-8198-73246068bd0a', '85975377-7e54-4ebb-b773-7dde1df43717', 3, '곱이 7씩 작아집니다.', false),
  ('08393693-c674-4b1c-bc8d-ab7ca1c98087', '85975377-7e54-4ebb-b773-7dde1df43717', 4, '곱이 항상 같습니다.', false),
  ('2ba1766e-cad2-4cd4-9570-e670b843cfcc', 'f1c936b3-b8da-4f23-9fcd-f0bd8ccec4b3', 1, '6×9=54', false),
  ('002cf8ac-f789-4d44-ad22-30535f4207d0', 'f1c936b3-b8da-4f23-9fcd-f0bd8ccec4b3', 2, '7×7=49', false),
  ('b3ec5455-1773-415b-b0ed-d1252a98f541', 'f1c936b3-b8da-4f23-9fcd-f0bd8ccec4b3', 3, '8×7=54', true),
  ('2983b040-4e32-4669-aa09-c79c919681ee', 'f1c936b3-b8da-4f23-9fcd-f0bd8ccec4b3', 4, '9×8=72', false),
  ('843b257f-5e57-495e-a2b5-2959c2a1bb30', '70cf1187-5f25-4b96-b3ca-d65c3f904f22', 1, '9×5=45', false),
  ('e361ca6f-5355-4138-90bd-ae1d2c37be96', '70cf1187-5f25-4b96-b3ca-d65c3f904f22', 2, '8×7=56', false),
  ('f0df9f25-1b1a-4e11-bdff-e6fdb0046b95', '70cf1187-5f25-4b96-b3ca-d65c3f904f22', 3, '6×8=48', false),
  ('bb8e50ea-c4e4-4112-93af-87129a3daf5e', '70cf1187-5f25-4b96-b3ca-d65c3f904f22', 4, '9×6=54', true),
  ('46e950a8-e1a4-4537-8bd0-6d7c595708f1', '8568ac74-cfb5-4b98-a122-76c551e60d32', 1, '7이며 7×8=56이기 때문입니다.', false),
  ('bce0adf5-7c77-4693-a4cb-34c947ba9c70', '8568ac74-cfb5-4b98-a122-76c551e60d32', 2, '9이며 9×8=72이기 때문입니다.', false),
  ('eefcb257-f14f-4bfc-b137-8865df42beb1', '8568ac74-cfb5-4b98-a122-76c551e60d32', 3, '8이며 8×8=64이기 때문입니다.', true),
  ('9910482d-ede6-44dd-a5eb-4a52e923a2cf', '8568ac74-cfb5-4b98-a122-76c551e60d32', 4, '6이며 6×8=48이기 때문입니다.', false),
  ('10df567a-3f2d-43d4-aa28-9326c4b96da7', 'a9ed729c-94b0-492c-a0f3-d8ea6ae49222', 1, '두 식은 뜻과 결과가 모두 다릅니다.', false),
  ('a73a4f93-5ef5-4a7d-bb0f-2b295e8d6b65', 'a9ed729c-94b0-492c-a0f3-d8ea6ae49222', 2, '두 식은 뜻이 같고 결과만 다릅니다.', false),
  ('42280f09-234e-47c0-bdd0-46c417a1b4d3', 'a9ed729c-94b0-492c-a0f3-d8ea6ae49222', 3, '6×8만 올바른 곱셈식입니다.', false),
  ('e0d56565-6c7d-4628-ad80-f7b7e6725dea', 'a9ed729c-94b0-492c-a0f3-d8ea6ae49222', 4, '한 묶음의 수와 묶음 수는 다르지만 결과는 모두 48입니다.', true);

insert into public.learning_question_skills (
  question_id, skill_code, is_primary
)
values
  ('6d061a04-a11d-4e96-a95f-fe99bdbce39d', 'multiply-by-2', true),
  ('a43e3789-7db5-4c9d-bc8d-16d4b9df3d4c', 'multiply-by-5', true),
  ('f3eafca7-b748-47d3-a44f-483a1f88fcc9', 'multiply-by-2', true),
  ('1a299e0f-4d64-493f-bf06-8b2fe831ba52', 'multiply-by-5', true),
  ('0ef3e74f-ad8c-4c63-9a4c-5340a6a6ba66', 'identify-multiplication-table-pattern', true),
  ('f60d6ca8-de60-4d66-8b1b-5815ff277f00', 'multiply-by-5', true),
  ('715abbba-ef59-4bcf-8128-48a6a6c31748', 'multiply-by-2', true),
  ('f43290fa-da02-46df-bbd7-f350d7ff5478', 'multiply-by-5', true),
  ('6c10010d-ba70-47fa-b8de-161481d400a7', 'multiply-by-2', true),
  ('0ac2fb54-0b88-49ad-8e72-e6bf479faa91', 'multiply-by-5', true),
  ('0ddd41c0-5946-436f-a09e-2ce3de79dec0', 'multiply-by-3', true),
  ('d13f6fe4-bacd-4542-a354-a032a54a4bea', 'multiply-by-4', true),
  ('e9735267-4bc5-4dcc-92e1-d75c7182502d', 'infer-missing-multiplication-factor', true),
  ('d909587c-6dac-43f2-82bf-f6170f4786ac', 'compare-multiplication-products', true),
  ('3bf4f190-03f0-4a11-a94d-0926a2ac4773', 'model-multiplication-situation', true),
  ('cdf30c28-d61a-4203-b954-b102c6014b54', 'model-multiplication-situation', true),
  ('92068d41-150b-4585-8316-990e53db6602', 'identify-multiplication-table-pattern', true),
  ('56d024fb-d0c4-4cc9-8260-1ff74f61f253', 'infer-missing-multiplication-factor', true),
  ('a120b3af-fb9f-4cd2-8ae9-aba68ec14297', 'multiply-by-3', true),
  ('12989413-5f95-4e0c-90d8-4335ca3718bb', 'model-multiplication-situation', true),
  ('78ce78d9-6d15-4968-84ba-fe091871ce57', 'multiply-by-6', true),
  ('4e6a0696-742f-4e40-96ac-fc394a4bd4ee', 'multiply-by-7', true),
  ('aaa80252-6e8e-4f9e-a813-e2cd54541fc4', 'multiply-by-8', true),
  ('28f2774a-2163-443c-8258-679ed4af3311', 'multiply-by-9', true),
  ('f9a03926-831d-43a7-bc6f-6c8a30198b4a', 'infer-missing-multiplication-factor', true),
  ('2540bda6-e257-4638-a18c-daede68cb593', 'compare-multiplication-products', true),
  ('eb695d4a-be93-4d13-af18-9ae866ffd5be', 'reason-about-multiplication-facts', true),
  ('1bed5f23-1cbe-4a51-a9e1-0b6d9fc731c3', 'identify-multiplication-table-pattern', true),
  ('51f243fd-04e5-49f3-8daa-28ff26c366c0', 'compare-multiplication-products', true),
  ('671565bd-924e-4b79-b9d1-48e31685c594', 'infer-missing-multiplication-factor', true),
  ('37e194a3-1b9f-42af-8c1e-90bf1bc038c0', 'reason-about-multiplication-facts', true),
  ('2efed665-4b28-4355-b67b-07db1b28ec68', 'model-multiplication-situation', true),
  ('6be4ae8c-d973-4b4f-a61c-a9bc1bdad77f', 'reason-about-multiplication-facts', true),
  ('bba4724e-cc51-4769-a268-748195ca0f27', 'identify-multiplication-table-pattern', true),
  ('d992467c-51fe-443d-83e8-d562a3e15e1b', 'correct-multiplication-reasoning', true),
  ('85975377-7e54-4ebb-b773-7dde1df43717', 'identify-multiplication-table-pattern', true),
  ('f1c936b3-b8da-4f23-9fcd-f0bd8ccec4b3', 'reason-about-multiplication-facts', true),
  ('70cf1187-5f25-4b96-b3ca-d65c3f904f22', 'reason-about-multiplication-facts', true),
  ('8568ac74-cfb5-4b98-a122-76c551e60d32', 'infer-missing-multiplication-factor', true),
  ('a9ed729c-94b0-492c-a0f3-d8ea6ae49222', 'reason-about-multiplication-facts', true);

select (public.publish_learning_content_version('db13b15e-752d-4491-832d-75feb9b9eb21'::uuid)).id;

commit;
