-- Generated by scripts/generate-learning-content-migration.js.
-- Source: content/learning/math/grade2-measuring-length-v1.json
-- Canonical content SHA-256: 7920a5b05c79553cefd7fe985c69d17a14cb522564125465842a07530451ce11
-- Content-only and additive: no assignment, attempt, progress, first-pass, ledger, ACL, or Realtime changes.

begin;

do $preflight$
begin
  if exists (
    select 1 from public.learning_courses
    where (id = '51000000-0000-4000-8000-000000000001'::uuid or course_code = 'math-core')
      and not (
        id = '51000000-0000-4000-8000-000000000001'::uuid
        and course_code = 'math-core'
        and internal_name = '수학 기초 과정'
        and subject_name = '수학'
      )
  ) then
    raise exception using errcode = '23505', message = 'grade2_measuring_length_v1 course identifier conflicts with different content';
  end if;

  if not exists (
    select 1 from public.learning_courses
    where id = '51000000-0000-4000-8000-000000000001'::uuid
      and course_code = 'math-core'
      and internal_name = '수학 기초 과정'
      and subject_name = '수학'
      and status = 'published'
  ) then
    raise exception using errcode = 'P0002', message = 'grade2_measuring_length_v1 existing course is missing or changed';
  end if;

  if exists (
    select 1 from public.learning_units
    where id = 'ab61feac-d390-4542-9eea-d049b007096d'::uuid
       or unit_code = 'grade2-measuring-length'
  ) then
    raise exception using errcode = '23505', message = 'grade2_measuring_length_v1 unit identifier already exists';
  end if;

  if exists (
    select 1 from public.learning_units
    where course_id = '51000000-0000-4000-8000-000000000001'::uuid
      and sort_order = 5
  ) then
    raise exception using errcode = '23505', message = 'grade2_measuring_length_v1 unit sort order already exists';
  end if;

  if to_regclass('public.learning_unit_recommendation_metadata') is null then
    raise exception using errcode = 'P0002', message = 'learning recommendation metadata table is missing';
  end if;

  if exists (
    select 1
    from public.learning_unit_recommendation_metadata metadata
    where metadata.unit_id = 'ab61feac-d390-4542-9eea-d049b007096d'::uuid
      and (
        metadata.subject is distinct from 'math'
        or metadata.recommended_start_level_code is distinct from 'elementary_2'
        or metadata.recommended_end_level_code is distinct from 'elementary_2'
        or metadata.parent_sort_order is distinct from 4
      )
  ) then
    raise exception using errcode = '23505', message = 'learning unit recommendation metadata conflicts with different content';
  end if;

  if to_regclass('public.learning_skill_definitions') is null
     or to_regclass('public.learning_question_skills') is null then
    raise exception using errcode = 'P0002', message = 'learning skill metadata foundation is missing';
  end if;

  if exists (
    select 1
    from (values
  ('measure-length-with-ruler'),
  ('read-ruler-scale'),
  ('choose-length-unit'),
  ('compare-lengths'),
  ('estimate-length'),
  ('measure-from-nonzero-start'),
  ('infer-length-from-measurement'),
  ('correct-measurement-reasoning')
    ) expected_skill(skill_code)
    where not exists (
      select 1 from public.learning_skill_definitions definition
      where definition.skill_code = expected_skill.skill_code
    )
  ) then
    raise exception using errcode = 'P0002', message = 'learning skill definition is missing';
  end if;

  if exists (
    select 1 from public.learning_content_versions
    where id = '29ac4fe6-847f-4c01-a402-ffce3440fad7'::uuid
       or content_hash = '7920a5b05c79553cefd7fe985c69d17a14cb522564125465842a07530451ce11'
  ) then
    raise exception using errcode = '23505', message = 'grade2_measuring_length_v1 content version already exists';
  end if;

  if exists (
    select 1 from (
      values
  ('902ecc11-bdc2-4b6c-89df-12044de2b6b7'::uuid),
  ('2a42e139-d700-4f69-bab7-8afbca9f01fa'::uuid),
  ('158c3fa0-e476-48d8-aa52-063429845367'::uuid),
  ('8029ea54-cecc-4e97-8932-45ae40a5a17c'::uuid),
  ('d455811a-b35c-4630-a81a-56b6ce3729fe'::uuid),
  ('c7e88799-6435-44f9-968d-8186202f008d'::uuid),
  ('af7b2b2e-3a49-4a51-9cba-3ef725e96eb9'::uuid),
  ('7f2ed8da-2739-4d88-8719-28447cddba76'::uuid),
  ('ab7431cb-3a55-4573-9f06-d820225c777d'::uuid),
  ('84e488d3-628b-42f3-8589-60c1646bb1f5'::uuid),
  ('e67c66d9-9f22-40bc-bdea-140571780fa1'::uuid),
  ('8e81456d-01eb-4c15-886f-b9af817e8610'::uuid),
  ('7b586413-f98a-494e-ac26-e67b08a9a3d6'::uuid),
  ('af2ca815-8222-4cab-b937-15a2c76b392d'::uuid),
  ('4986b4a7-fcba-4521-9363-b3fc4fbf51d3'::uuid),
  ('728d191c-68f5-4baa-9e45-5f813bcff8c9'::uuid),
  ('b5a624e9-ceda-4a45-95e2-2acba8718f39'::uuid),
  ('dd1752a1-d975-42da-89c4-85d3d8450da0'::uuid),
  ('5473fbc8-b011-4282-98ca-cc9acdf2589f'::uuid),
  ('78ae29a8-4da9-45b4-ae20-ac6a67298038'::uuid),
  ('79b95acf-a7f9-4a11-a0d1-99dce63065d3'::uuid),
  ('0566963d-c57e-4884-ae2b-e28ecacf0544'::uuid),
  ('7a9ae9af-6ca4-44a1-a776-37b467ce4dfa'::uuid),
  ('c64e80b7-ac89-4dab-b18f-c66b51b5cfdd'::uuid),
  ('6943fcc1-0d74-4661-9574-a8f38b6405ab'::uuid),
  ('12c33111-9536-475d-9c1e-d24ccb9abde6'::uuid),
  ('777c9b3f-c7a2-4023-8f6b-2057b8e21f9a'::uuid),
  ('e4914597-adff-45a6-9fe1-eb2afb0cc9ad'::uuid),
  ('a6ce38ea-ef4d-4bf5-b7e5-5d724b90fd08'::uuid),
  ('7df5b633-b8f2-4dcf-ba21-c39891b6bb4d'::uuid),
  ('2bf3a716-fe4c-4b25-85b1-0d316fe1d1ad'::uuid),
  ('6382a9f8-026a-4437-b308-5b3b556da05a'::uuid),
  ('a55763cd-ad23-4d39-96f3-58e9c60e4fe3'::uuid),
  ('0b42e785-047e-437c-a070-0173b341ec8e'::uuid),
  ('b860e868-5512-439f-8d73-42346835673e'::uuid),
  ('affb99e5-e509-424c-8b6c-94c44c903d4d'::uuid),
  ('6dc74739-176e-47c7-a67b-c9b96c41cad2'::uuid),
  ('6c88e334-fb08-42fd-be41-f80579a96bb7'::uuid),
  ('eaf32cbc-d9e4-4610-96ab-44022b7c2486'::uuid),
  ('315d6ef5-296c-4fd9-8446-7ec24014fd34'::uuid),
  ('e05e9df5-d67a-4eb4-b07a-7de617c67bbd'::uuid),
  ('3c24c97a-b47b-4619-b126-c52620390d6f'::uuid),
  ('286c2a44-9d61-43f9-94d5-2b2b4b575496'::uuid),
  ('583f0f27-2dfe-4f6f-b157-6a2a90152385'::uuid),
  ('10a0da2c-0db7-4011-a868-04bcf701ed03'::uuid),
  ('71885671-1e65-40a1-8295-961957bc7b6a'::uuid),
  ('bd4d2f2a-38bf-4c4c-8c84-5e7b130449b0'::uuid),
  ('5a9043b5-fc3f-4755-843b-42ebac22bb16'::uuid),
  ('1f0ea652-6ba7-424f-82b7-f81b7c28160c'::uuid),
  ('67451159-7f3e-47cd-897c-58c7ba5487bf'::uuid),
  ('fedd327f-5303-4333-bb38-3111dfc988b0'::uuid),
  ('07377e6d-2110-497b-b850-5ea3ca84cdb7'::uuid),
  ('520933ef-0d8c-429b-9785-ea9a28043b13'::uuid),
  ('5b60878b-ed57-41ae-af54-ac2077e348ba'::uuid),
  ('a63e2279-34a2-486d-9b76-3d32dfe9e524'::uuid),
  ('56245314-1380-4b55-8c6a-60c9c50620a9'::uuid),
  ('84187ff8-a64c-4261-a3d2-9beba9e84583'::uuid),
  ('4f8da9f3-3054-4864-8872-f45896d8affa'::uuid),
  ('51e9a4fb-b03b-4895-828a-6cfad31e4b9a'::uuid),
  ('e8b2b1e0-26ca-4ae5-8142-77474a3c0b5d'::uuid),
  ('46993b5d-6899-46d5-8dfd-14b9ff258580'::uuid),
  ('e63e2699-ad43-4de4-adf5-ae2e77de34a4'::uuid),
  ('baa4d742-9edb-466c-879c-bac24287f155'::uuid),
  ('2ce7a094-ccc3-470c-bdef-15ad34311f66'::uuid),
  ('f65defa2-a1d0-4bc5-85c3-397c1da1a484'::uuid),
  ('af2dbb15-d10d-4851-a9f1-11636f5e7526'::uuid),
  ('1df30114-a673-4635-b982-b5d05458a9fe'::uuid),
  ('45cda228-3fe2-40a8-90ec-a0ebf391ee42'::uuid),
  ('463f7304-fce6-434b-b772-2893d9debf44'::uuid),
  ('c28fade8-8f30-42d9-a203-09029618266c'::uuid),
  ('964baddb-ed7f-4593-ac4f-a5af46410f77'::uuid),
  ('1ca46ec3-917c-4abc-95d3-e6345508317b'::uuid),
  ('ba524343-08d2-48ec-a790-65f2cfe04c78'::uuid),
  ('b23f315e-748f-4491-ac13-2e0c48d0b9f2'::uuid),
  ('0ab08379-b08e-4116-b1e0-5d3e07ff53ba'::uuid),
  ('a3134448-2dc9-4e1b-8ed8-2f9c86a1e1e5'::uuid),
  ('703af5b6-55c8-4c2d-9975-be5ea60e4951'::uuid),
  ('ef0434ec-d32e-4c0a-afc6-b215bb4624cc'::uuid),
  ('ff9a7568-9660-4b73-99bc-e575ba7641f2'::uuid),
  ('0ae16048-13fa-418f-9141-eb8681185eda'::uuid),
  ('f1077315-f44a-425b-a4eb-b3f52af6534f'::uuid),
  ('9b6bf262-289b-4a1b-9b39-9e91295a5227'::uuid),
  ('46cc91b9-1a0a-42d1-bfb8-30dae7f91c8c'::uuid),
  ('855720e9-a133-4ef1-9e72-6cb5f3b36dad'::uuid),
  ('083bb00c-f42d-4ddb-9ea2-ea47ce5ae4ef'::uuid),
  ('e5bb15e4-1f64-44cf-99c5-fcc903df3c87'::uuid),
  ('c3cd6055-ee42-4f4f-8e83-247d43a55170'::uuid),
  ('7857f2c0-99c2-4672-83ae-fec290352083'::uuid),
  ('b66d75d0-f548-4d4b-843e-c84e7846c874'::uuid),
  ('014241cf-1160-44ce-842e-04f2c2860c53'::uuid),
  ('aa52e8ae-63ba-4150-974b-04074b48e691'::uuid),
  ('397fc327-e4f3-4001-917c-18f1119e6ae8'::uuid),
  ('b1c730a1-0b97-4853-b1df-007e37bde39d'::uuid),
  ('b85a5ec5-5714-40f7-9126-6e9291520780'::uuid),
  ('0fe929ad-5d90-445f-9e49-339d9f4f4197'::uuid),
  ('686c3355-d10c-4bfd-bc09-5d1fa32d0d8d'::uuid),
  ('496a5af3-2654-475e-a049-822833f1f30a'::uuid),
  ('cce70bd9-74e3-49d3-86b9-c63df3b4e9e1'::uuid),
  ('04220a2c-9c16-4d67-8538-467528605c4e'::uuid),
  ('e01d956f-b4ab-49d9-840b-91e8a394beec'::uuid),
  ('02840bf6-0b04-4a9d-af56-0aa9eb6e04e4'::uuid),
  ('4828ec85-ed14-4132-9282-f0af10a3dad9'::uuid),
  ('b0050fe4-7e84-495b-bf87-622ec8b753f2'::uuid),
  ('abad7a3d-0bd1-4557-83ac-25cfc144b824'::uuid),
  ('fb0ffa98-ceb8-4dd7-bf74-202f3e6f9273'::uuid),
  ('33fbfe69-e632-4a64-9bd6-908cfc5f7a79'::uuid),
  ('37084958-1181-47db-a448-e3ee02d974ef'::uuid),
  ('0105cc52-2593-4195-9a3d-ea4971c7f313'::uuid),
  ('00520ac9-19a7-496d-93cc-25c0f551edfe'::uuid),
  ('86656f92-b880-4c3c-b8b3-3e8d7a2c91a6'::uuid),
  ('ab700b87-701b-4f79-9096-39d2d26f7982'::uuid),
  ('eba16e35-8f52-4c6a-903e-bac0a6e0aad0'::uuid),
  ('a39cf361-4951-446f-aff9-fbfe0e521b26'::uuid),
  ('7a65dbf2-641b-4462-85f7-7c73d99a506e'::uuid),
  ('e5fe42ba-abd2-45c5-bd85-dc038e5db8a3'::uuid),
  ('7221ee82-94d0-4a9f-ae6c-e22079556533'::uuid),
  ('4a699506-ca70-44af-afc8-0e8fd5ab352d'::uuid),
  ('b897bb74-523e-459e-9cf3-95c1cab2c823'::uuid),
  ('466d60a6-d133-47ba-b90e-52b9ba25733f'::uuid),
  ('f38cd3ca-ea63-402c-8620-6e0e6039f3cc'::uuid),
  ('11d1cce7-9b55-441a-8774-9db6cdefb9cb'::uuid),
  ('6894236c-1111-49ba-9bf3-2a908a3ae1ee'::uuid),
  ('9cca9e6e-01cb-47b3-afbb-8ce69d41de94'::uuid),
  ('101fc011-130b-43ae-bdc2-db652acf4c5e'::uuid),
  ('32698200-85cc-410b-a94a-8aef2968083a'::uuid),
  ('70e048d3-f75f-4444-8c28-88e09538024b'::uuid),
  ('5242ebce-b006-45fb-89d1-dc2c408ee89b'::uuid),
  ('9414f1af-f1fd-4fd0-92f7-37c6b20446cb'::uuid),
  ('2dee3a9c-2faf-4082-a643-34ddfd88da7f'::uuid),
  ('7660d51a-aa3d-4d00-8417-2d3ee43f809c'::uuid),
  ('3613e667-1cfa-497d-b3f9-8e9c6df282e1'::uuid),
  ('7ac2940e-2d2f-4f56-8dee-29db1b5875d5'::uuid),
  ('75b981f6-6a5b-45dc-8586-0d7272df120d'::uuid),
  ('8c88195f-56c7-4f2d-a614-bee52195faba'::uuid),
  ('c7b64d41-5e5e-4f87-a5b6-e0a51e24bca6'::uuid),
  ('e346cb7b-764e-4d71-9ea3-dadeb97cdfcf'::uuid),
  ('374ffdfc-1b4e-486a-861c-1cb199901a4c'::uuid),
  ('9eb47f92-a027-4d2a-9a4c-b2d0860ee941'::uuid),
  ('d1188358-2fba-47c3-b51b-f1b2d57776e6'::uuid),
  ('bab5208e-a589-488f-9149-9e6ac5a63e7d'::uuid),
  ('39d0ef82-9c44-494f-916a-8c4516cc84b1'::uuid),
  ('f3a55fcd-219d-4117-9ba3-3b67841bc6f0'::uuid),
  ('40d32ff8-4b38-4eb6-aa11-73639b278324'::uuid),
  ('bff6c717-2cc3-4864-b091-76b61fca2cbb'::uuid),
  ('929332a6-4546-409b-9f82-3a2aa61a68bd'::uuid),
  ('d7ec7526-3fef-4cb9-97da-2f52f83136e1'::uuid),
  ('6ddf163f-02cc-4868-b490-07c578338f40'::uuid),
  ('d8a8fc3d-5a72-48f2-bc39-54aea7bf220e'::uuid),
  ('6630745e-7149-42d2-b264-20fbeeb42d8e'::uuid),
  ('38981071-fbed-4d87-84c3-e80ae089c917'::uuid),
  ('3e9eb578-b652-4317-9e47-d42815178462'::uuid),
  ('5e741035-8610-4de5-8aa3-76b7f2cd1175'::uuid),
  ('d61e62a5-a790-4024-8df8-824ad13dfa05'::uuid),
  ('99c0da39-bc1c-40b8-a902-074572e001a9'::uuid),
  ('73db810a-0d1c-4bb0-9066-9a78cd9d033a'::uuid),
  ('757fc668-ca89-4b37-990e-aea293d21f0e'::uuid),
  ('80e64e00-4e37-4c63-997c-37a59859c3c6'::uuid),
  ('d6937396-3e52-4beb-8bc4-1146daaa60e3'::uuid),
  ('a883129c-aef0-44a7-abc5-5d8a90c820c9'::uuid),
  ('595abf2a-4369-4fa1-a018-967b581fe583'::uuid),
  ('f8c25e68-5595-456c-bc29-f13b4d7d6460'::uuid),
  ('59ed19d2-7e82-41b8-ae3b-beb14a0e1dca'::uuid),
  ('9f232fbf-2e99-4842-9cdb-c4754659299b'::uuid),
  ('ad822337-4dab-4317-98f9-8a3419a2c54c'::uuid),
  ('6d4fe7a3-c8a0-474f-953d-243e7c59258d'::uuid),
  ('34e2e9d8-42ac-490c-b55d-18c4724b98dd'::uuid),
  ('cde114bf-2a53-4f28-938c-dc644b9ad000'::uuid),
  ('711ea380-85c3-445b-8468-f78c8e7234fa'::uuid),
  ('ca4980f9-682e-4802-8f0a-7d0dfd9e70af'::uuid),
  ('cf95a265-cdc4-49a9-95a4-6f6c3d6ddea6'::uuid),
  ('cddf11db-5a41-42bf-985a-551c04fe3788'::uuid),
  ('ebb276ac-e696-4573-96b2-894407274f5f'::uuid),
  ('eba796d5-33c5-4cc5-9ccb-d7b40449cfc9'::uuid),
  ('f7785695-d329-4750-af81-4a0b101cbcc9'::uuid),
  ('5f7646a1-fef2-42e8-8753-2368320d016d'::uuid),
  ('3253d350-0aff-475f-9229-fc45de815644'::uuid),
  ('9ceb308c-2150-42ac-9962-db7ea49aa496'::uuid),
  ('33d9d0a4-db06-4960-84c5-d858095fddf6'::uuid),
  ('5f866675-4e27-4dd8-af98-b7a215a711d4'::uuid),
  ('e35cec10-e3bc-44f1-ab63-ed6bbf1e9dc7'::uuid),
  ('2f8f1b69-f524-4042-9de1-b6c057c87156'::uuid),
  ('99e714e6-c87d-468c-b624-60e78ab98a34'::uuid),
  ('d8376516-9c10-43a8-a179-dbbf451684af'::uuid),
  ('028e399b-81b8-4dfe-bc0b-b021a3619454'::uuid),
  ('a62ceb5d-9b8e-4aee-b05b-33be59c85da8'::uuid),
  ('44af8e29-1588-4741-90d2-ad4ba9ffaad3'::uuid),
  ('7f31c8c7-35f0-40c2-86ec-10c42ab1959f'::uuid),
  ('af7bbeff-11b5-453b-ba4c-235abb0cee35'::uuid),
  ('8fda4772-2ef7-436a-a6d2-b22d32df712a'::uuid),
  ('97bb8de1-1752-43cf-b4b2-95bcd70c0564'::uuid),
  ('7debeae5-a3f6-4a7d-bbf6-fef8f7067461'::uuid),
  ('bf0d4ead-aa28-4dec-9f2c-3ffe7d3d9fc5'::uuid),
  ('f38b8592-f5e9-4e75-bde1-4ca5ecde0c1e'::uuid),
  ('bad79b81-8ce3-4d5b-8e35-9d86f283897f'::uuid),
  ('0cec3fbf-e34d-43e0-a14c-34bcdbe93e46'::uuid),
  ('c0a1156a-44a5-4df0-b6d1-83ba0bc6c0ba'::uuid),
  ('361aaf20-c3ea-4a21-b0f3-87aa2c3ad4dc'::uuid),
  ('addee060-bc1c-4fb1-8be2-781c0f53fd74'::uuid),
  ('6a86754c-6ca7-4120-b00d-f151cfc354c9'::uuid),
  ('0a10f919-3711-401d-9ead-f26b886a1d6b'::uuid),
  ('12f7af0a-0465-4d94-86be-443f7413f2dd'::uuid),
  ('81cea5a8-293e-4792-ab18-6a82ebde080a'::uuid),
  ('eeb30db1-3fae-469f-9944-9c36bf7511d2'::uuid),
  ('b52666d1-52e9-4808-87c8-b7e80adee129'::uuid)
    ) as expected_id(id)
    where exists (
      select 1 from public.learning_stages where id = expected_id.id
      union all
      select 1 from public.learning_questions where id = expected_id.id
      union all
      select 1 from public.learning_question_options where id = expected_id.id
    )
  ) then
    raise exception using errcode = '23505', message = 'grade2_measuring_length_v1 child content identifier already exists';
  end if;
end
$preflight$;

insert into public.learning_units (id, course_id, unit_code, display_title, sort_order)
values ('ab61feac-d390-4542-9eea-d049b007096d', '51000000-0000-4000-8000-000000000001', 'grade2-measuring-length', '길이를 재어 봐요', 5);

insert into public.learning_unit_recommendation_metadata (
  unit_id, subject, recommended_start_level_code, recommended_end_level_code, parent_sort_order
)
select 'ab61feac-d390-4542-9eea-d049b007096d'::uuid, 'math', 'elementary_2', 'elementary_2', 4
where not exists (
  select 1
  from public.learning_unit_recommendation_metadata metadata
  where metadata.unit_id = 'ab61feac-d390-4542-9eea-d049b007096d'::uuid
);

insert into public.learning_content_versions (id, unit_id, version_no, content_hash)
values ('29ac4fe6-847f-4c01-a402-ffce3440fad7', 'ab61feac-d390-4542-9eea-d049b007096d', 1, '7920a5b05c79553cefd7fe985c69d17a14cb522564125465842a07530451ce11');

insert into public.learning_stages (id, content_version_id, display_order, display_title, difficulty)
values
  ('902ecc11-bdc2-4b6c-89df-12044de2b6b7', '29ac4fe6-847f-4c01-a402-ffce3440fad7', 1, '입문', 'seed'),
  ('2a42e139-d700-4f69-bab7-8afbca9f01fa', '29ac4fe6-847f-4c01-a402-ffce3440fad7', 2, '기초', 'leaf'),
  ('158c3fa0-e476-48d8-aa52-063429845367', '29ac4fe6-847f-4c01-a402-ffce3440fad7', 3, '심화', 'tree'),
  ('8029ea54-cecc-4e97-8932-45ae40a5a17c', '29ac4fe6-847f-4c01-a402-ffce3440fad7', 4, '최상위 도전!', 'crown');

insert into public.learning_questions (id, stage_id, display_order, prompt, explanation)
values
  ('d455811a-b35c-4630-a81a-56b6ce3729fe', '902ecc11-bdc2-4b6c-89df-12044de2b6b7', 1, '물체의 한쪽 끝을 자의 0cm 눈금에 맞추고 다른 끝이 6cm 눈금에 있습니다. 물체의 길이는?', '0cm에서 시작해 6cm 눈금에서 끝나므로 물체의 길이는 6cm입니다.'),
  ('c7e88799-6435-44f9-968d-8186202f008d', '902ecc11-bdc2-4b6c-89df-12044de2b6b7', 2, '자의 3cm 눈금과 4cm 눈금 사이 한 칸의 길이는?', '4cm에서 3cm를 빼면 1cm이므로 두 눈금 사이 한 칸은 1cm입니다.'),
  ('af7b2b2e-3a49-4a51-9cba-3ef725e96eb9', '902ecc11-bdc2-4b6c-89df-12044de2b6b7', 3, '공책의 짧은 쪽 길이를 나타내기에 알맞은 단위는?', '공책처럼 작은 물체의 길이는 cm로 나타내는 것이 알맞습니다.'),
  ('7f2ed8da-2739-4d88-8719-28447cddba76', '902ecc11-bdc2-4b6c-89df-12044de2b6b7', 4, '교실 앞쪽에서 뒤쪽까지의 길이를 나타내기에 알맞은 단위는?', '교실처럼 긴 공간의 길이는 m로 나타내는 것이 알맞습니다.'),
  ('ab7431cb-3a55-4573-9f06-d820225c777d', '902ecc11-bdc2-4b6c-89df-12044de2b6b7', 5, '빨간 리본은 8cm이고 파란 리본은 5cm입니다. 더 긴 리본은?', '8cm는 5cm보다 크므로 빨간 리본이 더 깁니다.'),
  ('84e488d3-628b-42f3-8589-60c1646bb1f5', '902ecc11-bdc2-4b6c-89df-12044de2b6b7', 6, '연필의 한쪽 끝을 자의 0cm 눈금에 맞추었더니 다른 끝이 9cm 눈금에 있습니다. 연필의 길이는?', '0cm에서 시작해 9cm 눈금에서 끝나므로 연필의 길이는 9cm입니다.'),
  ('e67c66d9-9f22-40bc-bdea-140571780fa1', '902ecc11-bdc2-4b6c-89df-12044de2b6b7', 7, '손가락 한 마디의 길이로 가장 알맞은 것은?', '손가락 한 마디는 작은 길이이므로 약 2cm가 알맞습니다.'),
  ('8e81456d-01eb-4c15-886f-b9af817e8610', '902ecc11-bdc2-4b6c-89df-12044de2b6b7', 8, '운동장의 긴 쪽 길이를 나타내기에 알맞은 단위는?', '운동장처럼 긴 곳의 길이는 m로 나타내는 것이 알맞습니다.'),
  ('7b586413-f98a-494e-ac26-e67b08a9a3d6', '902ecc11-bdc2-4b6c-89df-12044de2b6b7', 9, '자의 7cm 눈금 바로 위에 점이 찍혀 있습니다. 점이 나타내는 길이는?', '점이 7cm 눈금에 있으므로 점이 나타내는 길이는 7cm입니다.'),
  ('af2ca815-8222-4cab-b937-15a2c76b392d', '902ecc11-bdc2-4b6c-89df-12044de2b6b7', 10, '연필은 12cm이고 지우개는 4cm입니다. 더 긴 것은?', '12cm는 4cm보다 크므로 연필이 더 깁니다.'),
  ('4986b4a7-fcba-4521-9363-b3fc4fbf51d3', '2a42e139-d700-4f69-bab7-8afbca9f01fa', 1, '막대의 한쪽 끝은 자의 2cm 눈금, 다른 끝은 9cm 눈금에 있습니다. 막대의 길이는?', '끝 눈금 9cm에서 시작 눈금 2cm를 빼면 7cm입니다.'),
  ('728d191c-68f5-4baa-9e45-5f813bcff8c9', '2a42e139-d700-4f69-bab7-8afbca9f01fa', 2, '종이띠의 한쪽 끝은 자의 4cm 눈금, 다른 끝은 11cm 눈금에 있습니다. 종이띠의 길이는?', '끝 눈금 11cm에서 시작 눈금 4cm를 빼면 7cm입니다.'),
  ('b5a624e9-ceda-4a45-95e2-2acba8718f39', '2a42e139-d700-4f69-bab7-8afbca9f01fa', 3, '빨간 끈은 14cm, 파란 끈은 9cm, 초록 끈은 12cm입니다. 가장 긴 끈은?', '14cm가 12cm와 9cm보다 크므로 빨간 끈이 가장 깁니다.'),
  ('dd1752a1-d975-42da-89c4-85d3d8450da0', '2a42e139-d700-4f69-bab7-8afbca9f01fa', 4, '가 막대는 6cm, 나 막대는 5cm, 다 막대는 8cm입니다. 가장 짧은 막대는?', '5cm가 6cm와 8cm보다 작으므로 나 막대가 가장 짧습니다.'),
  ('5473fbc8-b011-4282-98ca-cc9acdf2589f', '2a42e139-d700-4f69-bab7-8afbca9f01fa', 5, '보통 연필 한 자루의 길이로 가장 알맞은 것은?', '연필 한 자루의 길이는 약 15cm로 어림하는 것이 알맞습니다.'),
  ('78ae29a8-4da9-45b4-ae20-ac6a67298038', '2a42e139-d700-4f69-bab7-8afbca9f01fa', 6, '교실 문의 높이로 가장 알맞은 것은?', '교실 문의 높이는 사람의 키보다 조금 크므로 약 2m가 알맞습니다.'),
  ('79b95acf-a7f9-4a11-a0d1-99dce63065d3', '2a42e139-d700-4f69-bab7-8afbca9f01fa', 7, '자의 5cm 눈금에서 오른쪽으로 1cm씩 세 칸 이동한 눈금은?', '5cm에서 1cm씩 세 칸 이동하면 6cm, 7cm, 8cm 눈금에 차례로 닿습니다.'),
  ('0566963d-c57e-4884-ae2b-e28ecacf0544', '2a42e139-d700-4f69-bab7-8afbca9f01fa', 8, '줄의 한쪽 끝을 자의 0cm 눈금에 맞추었더니 다른 끝이 13cm 눈금에 있습니다. 줄의 길이는?', '0cm에서 시작해 13cm 눈금에서 끝나므로 줄의 길이는 13cm입니다.'),
  ('7a9ae9af-6ca4-44a1-a776-37b467ce4dfa', '2a42e139-d700-4f69-bab7-8afbca9f01fa', 9, '자의 눈금이 8cm, 9cm, 10cm, 11cm 순서로 있습니다. 화살표가 세 번째 눈금을 가리킬 때 나타내는 길이는?', '8cm부터 세 번째 눈금은 10cm이므로 화살표가 나타내는 길이는 10cm입니다.'),
  ('c64e80b7-ac89-4dab-b18f-c66b51b5cfdd', '2a42e139-d700-4f69-bab7-8afbca9f01fa', 10, '창문의 너비가 약 1일 때 빈칸에 알맞은 단위는?', '창문의 너비는 약 1m로 나타내는 것이 알맞습니다.'),
  ('6943fcc1-0d74-4661-9574-a8f38b6405ab', '158c3fa0-e476-48d8-aa52-063429845367', 1, '리본의 시작은 자의 3cm 눈금이고 끝은 14cm 눈금입니다. 리본의 길이는?', '끝 눈금 14cm에서 시작 눈금 3cm를 빼면 11cm입니다.'),
  ('12c33111-9536-475d-9c1e-d24ccb9abde6', '158c3fa0-e476-48d8-aa52-063429845367', 2, '빨대의 시작은 자의 7cm 눈금이고 끝은 16cm 눈금입니다. 빨대의 길이는?', '끝 눈금 16cm에서 시작 눈금 7cm를 빼면 9cm입니다.'),
  ('777c9b3f-c7a2-4023-8f6b-2057b8e21f9a', '158c3fa0-e476-48d8-aa52-063429845367', 3, '가 막대는 0cm부터 12cm까지, 나 막대는 2cm부터 15cm까지, 다 막대는 5cm부터 16cm까지 놓였습니다. 가장 긴 막대는?', '가 막대는 12cm, 나 막대는 13cm, 다 막대는 11cm이므로 나 막대가 가장 깁니다.'),
  ('e4914597-adff-45a6-9fe1-eb2afb0cc9ad', '158c3fa0-e476-48d8-aa52-063429845367', 4, '가 막대는 2cm부터 10cm까지, 나 막대는 4cm부터 13cm까지, 다 막대는 6cm부터 12cm까지 놓였습니다. 가장 짧은 막대는?', '가 막대는 8cm, 나 막대는 9cm, 다 막대는 6cm이므로 다 막대가 가장 짧습니다.'),
  ('a6ce38ea-ef4d-4bf5-b7e5-5d724b90fd08', '158c3fa0-e476-48d8-aa52-063429845367', 5, '테이프의 끝 눈금은 13cm이고 길이는 8cm입니다. 시작 눈금은?', '끝 눈금 13cm에서 길이 8cm를 빼면 시작 눈금은 5cm입니다.'),
  ('7df5b633-b8f2-4dcf-ba21-c39891b6bb4d', '158c3fa0-e476-48d8-aa52-063429845367', 6, '끈의 시작 눈금은 4cm이고 길이는 9cm입니다. 끝 눈금은?', '시작 눈금 4cm에서 9cm만큼 이어지므로 끝 눈금은 13cm입니다.'),
  ('2bf3a716-fe4c-4b25-85b1-0d316fe1d1ad', '158c3fa0-e476-48d8-aa52-063429845367', 7, '부러진 자에서 물체의 양 끝이 6cm 눈금과 15cm 눈금에 있습니다. 물체의 길이는?', '끝 눈금 15cm에서 시작 눈금 6cm를 빼면 물체의 길이는 9cm입니다.'),
  ('6382a9f8-026a-4437-b308-5b3b556da05a', '158c3fa0-e476-48d8-aa52-063429845367', 8, '어떤 물체의 길이는 7cm보다 길고 10cm보다 짧은 짝수입니다. 물체의 길이는?', '7cm보다 크고 10cm보다 작은 수 중 짝수는 8이므로 길이는 8cm입니다.'),
  ('a55763cd-ad23-4d39-96f3-58e9c60e4fe3', '158c3fa0-e476-48d8-aa52-063429845367', 9, '빨간 막대는 2cm부터 11cm까지, 파란 막대는 5cm부터 13cm까지 놓였습니다. 알맞은 비교는?', '빨간 막대는 9cm이고 파란 막대는 8cm이므로 빨간 막대가 1cm 더 깁니다.'),
  ('0b42e785-047e-437c-a070-0173b341ec8e', '158c3fa0-e476-48d8-aa52-063429845367', 10, '길이와 단위를 바르게 짝 지은 것은?', '복도처럼 긴 공간은 m, 연필처럼 작은 물체는 cm로 나타내는 것이 알맞습니다.'),
  ('b860e868-5512-439f-8d73-42346835673e', '8029ea54-cecc-4e97-8932-45ae40a5a17c', 1, '수아는 자의 3cm 눈금부터 11cm 눈금까지 놓인 막대의 길이를 11cm라고 했습니다. 바른 설명은?', '0cm에서 시작하지 않았으므로 끝 눈금 11cm에서 시작 눈금 3cm를 빼야 합니다. 막대의 길이는 8cm입니다.'),
  ('affb99e5-e509-424c-8b6c-94c44c903d4d', '8029ea54-cecc-4e97-8932-45ae40a5a17c', 2, '책의 길이를 잴 때 자를 책의 옆에 비스듬히 놓았습니다. 올바르게 재는 방법은?', '길이를 정확히 재려면 자를 물체의 가장자리와 나란히 곧게 놓아야 합니다.'),
  ('6dc74739-176e-47c7-a67b-c9b96c41cad2', '8029ea54-cecc-4e97-8932-45ae40a5a17c', 3, '자의 긴 눈금에 0, 2, 4가 차례로 적혀 있습니다. 같은 간격으로 다음 긴 눈금이 나타내는 길이는?', '긴 눈금의 수가 2씩 커지므로 4 다음 긴 눈금은 6cm입니다.'),
  ('6c88e334-fb08-42fd-be41-f80579a96bb7', '8029ea54-cecc-4e97-8932-45ae40a5a17c', 4, '가 막대는 4cm부터 15cm까지, 나 막대는 0cm부터 12cm까지 놓였습니다. 바르게 비교한 것은?', '가 막대는 11cm이고 나 막대는 12cm이므로 나 막대가 1cm 더 깁니다.'),
  ('eaf32cbc-d9e4-4610-96ab-44022b7c2486', '8029ea54-cecc-4e97-8932-45ae40a5a17c', 5, '막대의 시작 눈금은 2cm이고 길이는 12cm입니다. 끝 눈금은?', '시작 눈금 2cm에서 12cm만큼 이어지므로 끝 눈금은 14cm입니다.'),
  ('315d6ef5-296c-4fd9-8446-7ec24014fd34', '8029ea54-cecc-4e97-8932-45ae40a5a17c', 6, '끈의 끝 눈금은 18cm이고 길이는 11cm입니다. 시작 눈금은?', '끝 눈금 18cm에서 길이 11cm를 빼면 시작 눈금은 7cm입니다.'),
  ('e05e9df5-d67a-4eb4-b07a-7de617c67bbd', '8029ea54-cecc-4e97-8932-45ae40a5a17c', 7, '어떤 막대의 길이는 9cm보다 길고 13cm보다 짧은 홀수입니다. 막대의 길이는?', '9cm보다 크고 13cm보다 작은 수 중 홀수는 11이므로 막대의 길이는 11cm입니다.'),
  ('3c24c97a-b47b-4619-b126-c52620390d6f', '8029ea54-cecc-4e97-8932-45ae40a5a17c', 8, '자를 사용해 물체의 길이를 재는 방법으로 옳은 것은?', '물체를 자와 나란히 놓고 한쪽 끝을 기준 눈금에 맞춘 뒤 다른 끝의 눈금을 읽어야 합니다.'),
  ('286c2a44-9d61-43f9-94d5-2b2b4b575496', '8029ea54-cecc-4e97-8932-45ae40a5a17c', 9, '민준이는 2cm 눈금부터 10cm 눈금까지 놓인 막대의 길이를 10cm라고 했습니다. 바른 결과는?', '끝 눈금 10cm에서 시작 눈금 2cm를 빼면 막대의 길이는 8cm입니다.'),
  ('583f0f27-2dfe-4f6f-b157-6a2a90152385', '8029ea54-cecc-4e97-8932-45ae40a5a17c', 10, '가 막대는 4cm부터 13cm까지 놓였습니다. 나 막대는 가 막대보다 2cm 더 길고 5cm 눈금에서 시작합니다. 나 막대의 끝 눈금은?', '가 막대는 9cm이고 나 막대는 11cm입니다. 나 막대가 5cm 눈금에서 시작하므로 끝 눈금은 16cm입니다.');

insert into public.learning_question_options (id, question_id, display_order, option_text, is_correct)
values
  ('10a0da2c-0db7-4011-a868-04bcf701ed03', 'd455811a-b35c-4630-a81a-56b6ce3729fe', 1, '6cm', true),
  ('71885671-1e65-40a1-8295-961957bc7b6a', 'd455811a-b35c-4630-a81a-56b6ce3729fe', 2, '5cm', false),
  ('bd4d2f2a-38bf-4c4c-8c84-5e7b130449b0', 'd455811a-b35c-4630-a81a-56b6ce3729fe', 3, '7cm', false),
  ('5a9043b5-fc3f-4755-843b-42ebac22bb16', 'd455811a-b35c-4630-a81a-56b6ce3729fe', 4, '8cm', false),
  ('1f0ea652-6ba7-424f-82b7-f81b7c28160c', 'c7e88799-6435-44f9-968d-8186202f008d', 1, '2cm', false),
  ('67451159-7f3e-47cd-897c-58c7ba5487bf', 'c7e88799-6435-44f9-968d-8186202f008d', 2, '1cm', true),
  ('fedd327f-5303-4333-bb38-3111dfc988b0', 'c7e88799-6435-44f9-968d-8186202f008d', 3, '3cm', false),
  ('07377e6d-2110-497b-b850-5ea3ca84cdb7', 'c7e88799-6435-44f9-968d-8186202f008d', 4, '4cm', false),
  ('520933ef-0d8c-429b-9785-ea9a28043b13', 'af7b2b2e-3a49-4a51-9cba-3ef725e96eb9', 1, 'm', false),
  ('5b60878b-ed57-41ae-af54-ac2077e348ba', 'af7b2b2e-3a49-4a51-9cba-3ef725e96eb9', 2, 'kg', false),
  ('a63e2279-34a2-486d-9b76-3d32dfe9e524', 'af7b2b2e-3a49-4a51-9cba-3ef725e96eb9', 3, 'cm', true),
  ('56245314-1380-4b55-8c6a-60c9c50620a9', 'af7b2b2e-3a49-4a51-9cba-3ef725e96eb9', 4, 'L', false),
  ('84187ff8-a64c-4261-a3d2-9beba9e84583', '7f2ed8da-2739-4d88-8719-28447cddba76', 1, 'cm', false),
  ('4f8da9f3-3054-4864-8872-f45896d8affa', '7f2ed8da-2739-4d88-8719-28447cddba76', 2, 'kg', false),
  ('51e9a4fb-b03b-4895-828a-6cfad31e4b9a', '7f2ed8da-2739-4d88-8719-28447cddba76', 3, 'L', false),
  ('e8b2b1e0-26ca-4ae5-8142-77474a3c0b5d', '7f2ed8da-2739-4d88-8719-28447cddba76', 4, 'm', true),
  ('46993b5d-6899-46d5-8dfd-14b9ff258580', 'ab7431cb-3a55-4573-9f06-d820225c777d', 1, '8cm인 빨간 리본', true),
  ('e63e2699-ad43-4de4-adf5-ae2e77de34a4', 'ab7431cb-3a55-4573-9f06-d820225c777d', 2, '5cm인 파란 리본', false),
  ('baa4d742-9edb-466c-879c-bac24287f155', 'ab7431cb-3a55-4573-9f06-d820225c777d', 3, '두 리본의 길이가 같습니다.', false),
  ('2ce7a094-ccc3-470c-bdef-15ad34311f66', 'ab7431cb-3a55-4573-9f06-d820225c777d', 4, '비교할 수 없습니다.', false),
  ('f65defa2-a1d0-4bc5-85c3-397c1da1a484', '84e488d3-628b-42f3-8589-60c1646bb1f5', 1, '8cm', false),
  ('af2dbb15-d10d-4851-a9f1-11636f5e7526', '84e488d3-628b-42f3-8589-60c1646bb1f5', 2, '9cm', true),
  ('1df30114-a673-4635-b982-b5d05458a9fe', '84e488d3-628b-42f3-8589-60c1646bb1f5', 3, '10cm', false),
  ('45cda228-3fe2-40a8-90ec-a0ebf391ee42', '84e488d3-628b-42f3-8589-60c1646bb1f5', 4, '0cm', false),
  ('463f7304-fce6-434b-b772-2893d9debf44', 'e67c66d9-9f22-40bc-bdea-140571780fa1', 1, '20m', false),
  ('c28fade8-8f30-42d9-a203-09029618266c', 'e67c66d9-9f22-40bc-bdea-140571780fa1', 2, '20cm', false),
  ('964baddb-ed7f-4593-ac4f-a5af46410f77', 'e67c66d9-9f22-40bc-bdea-140571780fa1', 3, '2cm', true),
  ('1ca46ec3-917c-4abc-95d3-e6345508317b', 'e67c66d9-9f22-40bc-bdea-140571780fa1', 4, '2m', false),
  ('ba524343-08d2-48ec-a790-65f2cfe04c78', '8e81456d-01eb-4c15-886f-b9af817e8610', 1, 'cm', false),
  ('b23f315e-748f-4491-ac13-2e0c48d0b9f2', '8e81456d-01eb-4c15-886f-b9af817e8610', 2, 'kg', false),
  ('0ab08379-b08e-4116-b1e0-5d3e07ff53ba', '8e81456d-01eb-4c15-886f-b9af817e8610', 3, 'L', false),
  ('a3134448-2dc9-4e1b-8ed8-2f9c86a1e1e5', '8e81456d-01eb-4c15-886f-b9af817e8610', 4, 'm', true),
  ('703af5b6-55c8-4c2d-9975-be5ea60e4951', '7b586413-f98a-494e-ac26-e67b08a9a3d6', 1, '7cm', true),
  ('ef0434ec-d32e-4c0a-afc6-b215bb4624cc', '7b586413-f98a-494e-ac26-e67b08a9a3d6', 2, '6cm', false),
  ('ff9a7568-9660-4b73-99bc-e575ba7641f2', '7b586413-f98a-494e-ac26-e67b08a9a3d6', 3, '8cm', false),
  ('0ae16048-13fa-418f-9141-eb8681185eda', '7b586413-f98a-494e-ac26-e67b08a9a3d6', 4, '9cm', false),
  ('f1077315-f44a-425b-a4eb-b3f52af6534f', 'af2ca815-8222-4cab-b937-15a2c76b392d', 1, '지우개', false),
  ('9b6bf262-289b-4a1b-9b39-9e91295a5227', 'af2ca815-8222-4cab-b937-15a2c76b392d', 2, '연필', true),
  ('46cc91b9-1a0a-42d1-bfb8-30dae7f91c8c', 'af2ca815-8222-4cab-b937-15a2c76b392d', 3, '두 물체의 길이가 같습니다.', false),
  ('855720e9-a133-4ef1-9e72-6cb5f3b36dad', 'af2ca815-8222-4cab-b937-15a2c76b392d', 4, '비교할 수 없습니다.', false),
  ('083bb00c-f42d-4ddb-9ea2-ea47ce5ae4ef', '4986b4a7-fcba-4521-9363-b3fc4fbf51d3', 1, '9cm', false),
  ('e5bb15e4-1f64-44cf-99c5-fcc903df3c87', '4986b4a7-fcba-4521-9363-b3fc4fbf51d3', 2, '11cm', false),
  ('c3cd6055-ee42-4f4f-8e83-247d43a55170', '4986b4a7-fcba-4521-9363-b3fc4fbf51d3', 3, '7cm', true),
  ('7857f2c0-99c2-4672-83ae-fec290352083', '4986b4a7-fcba-4521-9363-b3fc4fbf51d3', 4, '2cm', false),
  ('b66d75d0-f548-4d4b-843e-c84e7846c874', '728d191c-68f5-4baa-9e45-5f813bcff8c9', 1, '11cm', false),
  ('014241cf-1160-44ce-842e-04f2c2860c53', '728d191c-68f5-4baa-9e45-5f813bcff8c9', 2, '15cm', false),
  ('aa52e8ae-63ba-4150-974b-04074b48e691', '728d191c-68f5-4baa-9e45-5f813bcff8c9', 3, '4cm', false),
  ('397fc327-e4f3-4001-917c-18f1119e6ae8', '728d191c-68f5-4baa-9e45-5f813bcff8c9', 4, '7cm', true),
  ('b1c730a1-0b97-4853-b1df-007e37bde39d', 'b5a624e9-ceda-4a45-95e2-2acba8718f39', 1, '14cm인 빨간 끈', true),
  ('b85a5ec5-5714-40f7-9126-6e9291520780', 'b5a624e9-ceda-4a45-95e2-2acba8718f39', 2, '9cm인 파란 끈', false),
  ('0fe929ad-5d90-445f-9e49-339d9f4f4197', 'b5a624e9-ceda-4a45-95e2-2acba8718f39', 3, '12cm인 초록 끈', false),
  ('686c3355-d10c-4bfd-bc09-5d1fa32d0d8d', 'b5a624e9-ceda-4a45-95e2-2acba8718f39', 4, '세 끈의 길이가 같습니다.', false),
  ('496a5af3-2654-475e-a049-822833f1f30a', 'dd1752a1-d975-42da-89c4-85d3d8450da0', 1, '6cm인 가 막대', false),
  ('cce70bd9-74e3-49d3-86b9-c63df3b4e9e1', 'dd1752a1-d975-42da-89c4-85d3d8450da0', 2, '5cm인 나 막대', true),
  ('04220a2c-9c16-4d67-8538-467528605c4e', 'dd1752a1-d975-42da-89c4-85d3d8450da0', 3, '8cm인 다 막대', false),
  ('e01d956f-b4ab-49d9-840b-91e8a394beec', 'dd1752a1-d975-42da-89c4-85d3d8450da0', 4, '세 막대의 길이가 같습니다.', false),
  ('02840bf6-0b04-4a9d-af56-0aa9eb6e04e4', '5473fbc8-b011-4282-98ca-cc9acdf2589f', 1, '15m', false),
  ('4828ec85-ed14-4132-9282-f0af10a3dad9', '5473fbc8-b011-4282-98ca-cc9acdf2589f', 2, '1cm', false),
  ('b0050fe4-7e84-495b-bf87-622ec8b753f2', '5473fbc8-b011-4282-98ca-cc9acdf2589f', 3, '15cm', true),
  ('abad7a3d-0bd1-4557-83ac-25cfc144b824', '5473fbc8-b011-4282-98ca-cc9acdf2589f', 4, '150m', false),
  ('fb0ffa98-ceb8-4dd7-bf74-202f3e6f9273', '78ae29a8-4da9-45b4-ae20-ac6a67298038', 1, '2cm', false),
  ('33fbfe69-e632-4a64-9bd6-908cfc5f7a79', '78ae29a8-4da9-45b4-ae20-ac6a67298038', 2, '20cm', false),
  ('37084958-1181-47db-a448-e3ee02d974ef', '78ae29a8-4da9-45b4-ae20-ac6a67298038', 3, '20m', false),
  ('0105cc52-2593-4195-9a3d-ea4971c7f313', '78ae29a8-4da9-45b4-ae20-ac6a67298038', 4, '2m', true),
  ('00520ac9-19a7-496d-93cc-25c0f551edfe', '79b95acf-a7f9-4a11-a0d1-99dce63065d3', 1, '8cm', true),
  ('86656f92-b880-4c3c-b8b3-3e8d7a2c91a6', '79b95acf-a7f9-4a11-a0d1-99dce63065d3', 2, '6cm', false),
  ('ab700b87-701b-4f79-9096-39d2d26f7982', '79b95acf-a7f9-4a11-a0d1-99dce63065d3', 3, '7cm', false),
  ('eba16e35-8f52-4c6a-903e-bac0a6e0aad0', '79b95acf-a7f9-4a11-a0d1-99dce63065d3', 4, '9cm', false),
  ('a39cf361-4951-446f-aff9-fbfe0e521b26', '0566963d-c57e-4884-ae2b-e28ecacf0544', 1, '12cm', false),
  ('7a65dbf2-641b-4462-85f7-7c73d99a506e', '0566963d-c57e-4884-ae2b-e28ecacf0544', 2, '13cm', true),
  ('e5fe42ba-abd2-45c5-bd85-dc038e5db8a3', '0566963d-c57e-4884-ae2b-e28ecacf0544', 3, '14cm', false),
  ('7221ee82-94d0-4a9f-ae6c-e22079556533', '0566963d-c57e-4884-ae2b-e28ecacf0544', 4, '0cm', false),
  ('4a699506-ca70-44af-afc8-0e8fd5ab352d', '7a9ae9af-6ca4-44a1-a776-37b467ce4dfa', 1, '8cm', false),
  ('b897bb74-523e-459e-9cf3-95c1cab2c823', '7a9ae9af-6ca4-44a1-a776-37b467ce4dfa', 2, '9cm', false),
  ('466d60a6-d133-47ba-b90e-52b9ba25733f', '7a9ae9af-6ca4-44a1-a776-37b467ce4dfa', 3, '10cm', true),
  ('f38cd3ca-ea63-402c-8620-6e0e6039f3cc', '7a9ae9af-6ca4-44a1-a776-37b467ce4dfa', 4, '11cm', false),
  ('11d1cce7-9b55-441a-8774-9db6cdefb9cb', 'c64e80b7-ac89-4dab-b18f-c66b51b5cfdd', 1, 'cm', false),
  ('6894236c-1111-49ba-9bf3-2a908a3ae1ee', 'c64e80b7-ac89-4dab-b18f-c66b51b5cfdd', 2, 'kg', false),
  ('9cca9e6e-01cb-47b3-afbb-8ce69d41de94', 'c64e80b7-ac89-4dab-b18f-c66b51b5cfdd', 3, 'L', false),
  ('101fc011-130b-43ae-bdc2-db652acf4c5e', 'c64e80b7-ac89-4dab-b18f-c66b51b5cfdd', 4, 'm', true),
  ('32698200-85cc-410b-a94a-8aef2968083a', '6943fcc1-0d74-4661-9574-a8f38b6405ab', 1, '11cm', true),
  ('70e048d3-f75f-4444-8c28-88e09538024b', '6943fcc1-0d74-4661-9574-a8f38b6405ab', 2, '14cm', false),
  ('5242ebce-b006-45fb-89d1-dc2c408ee89b', '6943fcc1-0d74-4661-9574-a8f38b6405ab', 3, '17cm', false),
  ('9414f1af-f1fd-4fd0-92f7-37c6b20446cb', '6943fcc1-0d74-4661-9574-a8f38b6405ab', 4, '3cm', false),
  ('2dee3a9c-2faf-4082-a643-34ddfd88da7f', '12c33111-9536-475d-9c1e-d24ccb9abde6', 1, '23cm', false),
  ('7660d51a-aa3d-4d00-8417-2d3ee43f809c', '12c33111-9536-475d-9c1e-d24ccb9abde6', 2, '9cm', true),
  ('3613e667-1cfa-497d-b3f9-8e9c6df282e1', '12c33111-9536-475d-9c1e-d24ccb9abde6', 3, '16cm', false),
  ('7ac2940e-2d2f-4f56-8dee-29db1b5875d5', '12c33111-9536-475d-9c1e-d24ccb9abde6', 4, '7cm', false),
  ('75b981f6-6a5b-45dc-8586-0d7272df120d', '777c9b3f-c7a2-4023-8f6b-2057b8e21f9a', 1, '가 막대', false),
  ('8c88195f-56c7-4f2d-a614-bee52195faba', '777c9b3f-c7a2-4023-8f6b-2057b8e21f9a', 2, '다 막대', false),
  ('c7b64d41-5e5e-4f87-a5b6-e0a51e24bca6', '777c9b3f-c7a2-4023-8f6b-2057b8e21f9a', 3, '나 막대', true),
  ('e346cb7b-764e-4d71-9ea3-dadeb97cdfcf', '777c9b3f-c7a2-4023-8f6b-2057b8e21f9a', 4, '세 막대의 길이가 같습니다.', false),
  ('374ffdfc-1b4e-486a-861c-1cb199901a4c', 'e4914597-adff-45a6-9fe1-eb2afb0cc9ad', 1, '8cm인 가 막대', false),
  ('9eb47f92-a027-4d2a-9a4c-b2d0860ee941', 'e4914597-adff-45a6-9fe1-eb2afb0cc9ad', 2, '9cm인 나 막대', false),
  ('d1188358-2fba-47c3-b51b-f1b2d57776e6', 'e4914597-adff-45a6-9fe1-eb2afb0cc9ad', 3, '세 막대의 길이가 같습니다.', false),
  ('bab5208e-a589-488f-9149-9e6ac5a63e7d', 'e4914597-adff-45a6-9fe1-eb2afb0cc9ad', 4, '6cm인 다 막대', true),
  ('39d0ef82-9c44-494f-916a-8c4516cc84b1', 'a6ce38ea-ef4d-4bf5-b7e5-5d724b90fd08', 1, '5cm', true),
  ('f3a55fcd-219d-4117-9ba3-3b67841bc6f0', 'a6ce38ea-ef4d-4bf5-b7e5-5d724b90fd08', 2, '8cm', false),
  ('40d32ff8-4b38-4eb6-aa11-73639b278324', 'a6ce38ea-ef4d-4bf5-b7e5-5d724b90fd08', 3, '13cm', false),
  ('bff6c717-2cc3-4864-b091-76b61fca2cbb', 'a6ce38ea-ef4d-4bf5-b7e5-5d724b90fd08', 4, '21cm', false),
  ('929332a6-4546-409b-9f82-3a2aa61a68bd', '7df5b633-b8f2-4dcf-ba21-c39891b6bb4d', 1, '5cm', false),
  ('d7ec7526-3fef-4cb9-97da-2f52f83136e1', '7df5b633-b8f2-4dcf-ba21-c39891b6bb4d', 2, '13cm', true),
  ('6ddf163f-02cc-4868-b490-07c578338f40', '7df5b633-b8f2-4dcf-ba21-c39891b6bb4d', 3, '9cm', false),
  ('d8a8fc3d-5a72-48f2-bc39-54aea7bf220e', '7df5b633-b8f2-4dcf-ba21-c39891b6bb4d', 4, '36cm', false),
  ('6630745e-7149-42d2-b264-20fbeeb42d8e', '2bf3a716-fe4c-4b25-85b1-0d316fe1d1ad', 1, '15cm', false),
  ('38981071-fbed-4d87-84c3-e80ae089c917', '2bf3a716-fe4c-4b25-85b1-0d316fe1d1ad', 2, '21cm', false),
  ('3e9eb578-b652-4317-9e47-d42815178462', '2bf3a716-fe4c-4b25-85b1-0d316fe1d1ad', 3, '9cm', true),
  ('5e741035-8610-4de5-8aa3-76b7f2cd1175', '2bf3a716-fe4c-4b25-85b1-0d316fe1d1ad', 4, '6cm', false),
  ('d61e62a5-a790-4024-8df8-824ad13dfa05', '6382a9f8-026a-4437-b308-5b3b556da05a', 1, '7cm', false),
  ('99c0da39-bc1c-40b8-a902-074572e001a9', '6382a9f8-026a-4437-b308-5b3b556da05a', 2, '9cm', false),
  ('73db810a-0d1c-4bb0-9066-9a78cd9d033a', '6382a9f8-026a-4437-b308-5b3b556da05a', 3, '10cm', false),
  ('757fc668-ca89-4b37-990e-aea293d21f0e', '6382a9f8-026a-4437-b308-5b3b556da05a', 4, '8cm', true),
  ('80e64e00-4e37-4c63-997c-37a59859c3c6', 'a55763cd-ad23-4d39-96f3-58e9c60e4fe3', 1, '빨간 막대가 1cm 더 깁니다.', true),
  ('d6937396-3e52-4beb-8bc4-1146daaa60e3', 'a55763cd-ad23-4d39-96f3-58e9c60e4fe3', 2, '파란 막대가 1cm 더 깁니다.', false),
  ('a883129c-aef0-44a7-abc5-5d8a90c820c9', 'a55763cd-ad23-4d39-96f3-58e9c60e4fe3', 3, '두 막대의 길이가 같습니다.', false),
  ('595abf2a-4369-4fa1-a018-967b581fe583', 'a55763cd-ad23-4d39-96f3-58e9c60e4fe3', 4, '비교할 수 없습니다.', false),
  ('f8c25e68-5595-456c-bc29-f13b4d7d6460', '0b42e785-047e-437c-a070-0173b341ec8e', 1, '복도 12cm, 연필 18m', false),
  ('59ed19d2-7e82-41b8-ae3b-beb14a0e1dca', '0b42e785-047e-437c-a070-0173b341ec8e', 2, '복도 12m, 연필 18cm', true),
  ('9f232fbf-2e99-4842-9cdb-c4754659299b', '0b42e785-047e-437c-a070-0173b341ec8e', 3, '복도 12kg, 연필 18kg', false),
  ('ad822337-4dab-4317-98f9-8a3419a2c54c', '0b42e785-047e-437c-a070-0173b341ec8e', 4, '복도 12L, 연필 18m', false),
  ('6d4fe7a3-c8a0-474f-953d-243e7c59258d', 'b860e868-5512-439f-8d73-42346835673e', 1, '시작 눈금 3cm를 더해 14cm입니다.', false),
  ('34e2e9d8-42ac-490c-b55d-18c4724b98dd', 'b860e868-5512-439f-8d73-42346835673e', 2, '끝 눈금만 읽었으므로 11cm가 맞습니다.', false),
  ('cde114bf-2a53-4f28-938c-dc644b9ad000', 'b860e868-5512-439f-8d73-42346835673e', 3, '11cm에서 3cm를 빼야 하므로 8cm입니다.', true),
  ('711ea380-85c3-445b-8468-f78c8e7234fa', 'b860e868-5512-439f-8d73-42346835673e', 4, '눈금 수와 관계없이 3cm입니다.', false),
  ('ca4980f9-682e-4802-8f0a-7d0dfd9e70af', 'affb99e5-e509-424c-8b6c-94c44c903d4d', 1, '자를 책과 멀리 떨어뜨립니다.', false),
  ('cf95a265-cdc4-49a9-95a4-6f6c3d6ddea6', 'affb99e5-e509-424c-8b6c-94c44c903d4d', 2, '자의 뒷면만 사용합니다.', false),
  ('cddf11db-5a41-42bf-985a-551c04fe3788', 'affb99e5-e509-424c-8b6c-94c44c903d4d', 3, '책을 접어서 잽니다.', false),
  ('ebb276ac-e696-4573-96b2-894407274f5f', 'affb99e5-e509-424c-8b6c-94c44c903d4d', 4, '자를 책의 가장자리와 나란히 곧게 놓습니다.', true),
  ('eba796d5-33c5-4cc5-9ccb-d7b40449cfc9', '6dc74739-176e-47c7-a67b-c9b96c41cad2', 1, '6cm', true),
  ('f7785695-d329-4750-af81-4a0b101cbcc9', '6dc74739-176e-47c7-a67b-c9b96c41cad2', 2, '5cm', false),
  ('5f7646a1-fef2-42e8-8753-2368320d016d', '6dc74739-176e-47c7-a67b-c9b96c41cad2', 3, '8cm', false),
  ('3253d350-0aff-475f-9229-fc45de815644', '6dc74739-176e-47c7-a67b-c9b96c41cad2', 4, '4cm', false),
  ('9ceb308c-2150-42ac-9962-db7ea49aa496', '6c88e334-fb08-42fd-be41-f80579a96bb7', 1, '가 막대가 1cm 더 깁니다.', false),
  ('33d9d0a4-db06-4960-84c5-d858095fddf6', '6c88e334-fb08-42fd-be41-f80579a96bb7', 2, '나 막대가 1cm 더 깁니다.', true),
  ('5f866675-4e27-4dd8-af98-b7a215a711d4', '6c88e334-fb08-42fd-be41-f80579a96bb7', 3, '두 막대의 길이가 같습니다.', false),
  ('e35cec10-e3bc-44f1-ab63-ed6bbf1e9dc7', '6c88e334-fb08-42fd-be41-f80579a96bb7', 4, '가 막대가 4cm 더 깁니다.', false),
  ('2f8f1b69-f524-4042-9de1-b6c057c87156', 'eaf32cbc-d9e4-4610-96ab-44022b7c2486', 1, '10cm', false),
  ('99e714e6-c87d-468c-b624-60e78ab98a34', 'eaf32cbc-d9e4-4610-96ab-44022b7c2486', 2, '12cm', false),
  ('d8376516-9c10-43a8-a179-dbbf451684af', 'eaf32cbc-d9e4-4610-96ab-44022b7c2486', 3, '14cm', true),
  ('028e399b-81b8-4dfe-bc0b-b021a3619454', 'eaf32cbc-d9e4-4610-96ab-44022b7c2486', 4, '24cm', false),
  ('a62ceb5d-9b8e-4aee-b05b-33be59c85da8', '315d6ef5-296c-4fd9-8446-7ec24014fd34', 1, '29cm', false),
  ('44af8e29-1588-4741-90d2-ad4ba9ffaad3', '315d6ef5-296c-4fd9-8446-7ec24014fd34', 2, '18cm', false),
  ('7f31c8c7-35f0-40c2-86ec-10c42ab1959f', '315d6ef5-296c-4fd9-8446-7ec24014fd34', 3, '11cm', false),
  ('af7bbeff-11b5-453b-ba4c-235abb0cee35', '315d6ef5-296c-4fd9-8446-7ec24014fd34', 4, '7cm', true),
  ('8fda4772-2ef7-436a-a6d2-b22d32df712a', 'e05e9df5-d67a-4eb4-b07a-7de617c67bbd', 1, '11cm', true),
  ('97bb8de1-1752-43cf-b4b2-95bcd70c0564', 'e05e9df5-d67a-4eb4-b07a-7de617c67bbd', 2, '10cm', false),
  ('7debeae5-a3f6-4a7d-bbf6-fef8f7067461', 'e05e9df5-d67a-4eb4-b07a-7de617c67bbd', 3, '12cm', false),
  ('bf0d4ead-aa28-4dec-9f2c-3ffe7d3d9fc5', 'e05e9df5-d67a-4eb4-b07a-7de617c67bbd', 4, '13cm', false),
  ('f38b8592-f5e9-4e75-bde1-4ca5ecde0c1e', '3c24c97a-b47b-4619-b126-c52620390d6f', 1, '물체를 자와 비스듬하게 놓습니다.', false),
  ('bad79b81-8ce3-4d5b-8e35-9d86f283897f', '3c24c97a-b47b-4619-b126-c52620390d6f', 2, '물체의 한쪽 끝을 기준 눈금에 맞추고 자와 나란히 놓습니다.', true),
  ('0cec3fbf-e34d-43e0-a14c-34bcdbe93e46', '3c24c97a-b47b-4619-b126-c52620390d6f', 3, '끝 눈금 숫자는 보지 않습니다.', false),
  ('c0a1156a-44a5-4df0-b6d1-83ba0bc6c0ba', '3c24c97a-b47b-4619-b126-c52620390d6f', 4, '물체를 구부려 자에 맞춥니다.', false),
  ('361aaf20-c3ea-4a21-b0f3-87aa2c3ad4dc', '286c2a44-9d61-43f9-94d5-2b2b4b575496', 1, '12cm', false),
  ('addee060-bc1c-4fb1-8be2-781c0f53fd74', '286c2a44-9d61-43f9-94d5-2b2b4b575496', 2, '10cm', false),
  ('6a86754c-6ca7-4120-b00d-f151cfc354c9', '286c2a44-9d61-43f9-94d5-2b2b4b575496', 3, '8cm', true),
  ('0a10f919-3711-401d-9ead-f26b886a1d6b', '286c2a44-9d61-43f9-94d5-2b2b4b575496', 4, '2cm', false),
  ('12f7af0a-0465-4d94-86be-443f7413f2dd', '583f0f27-2dfe-4f6f-b157-6a2a90152385', 1, '11cm', false),
  ('81cea5a8-293e-4792-ab18-6a82ebde080a', '583f0f27-2dfe-4f6f-b157-6a2a90152385', 2, '14cm', false),
  ('eeb30db1-3fae-469f-9944-9c36bf7511d2', '583f0f27-2dfe-4f6f-b157-6a2a90152385', 3, '15cm', false),
  ('b52666d1-52e9-4808-87c8-b7e80adee129', '583f0f27-2dfe-4f6f-b157-6a2a90152385', 4, '16cm', true);

insert into public.learning_question_skills (
  question_id, skill_code, is_primary
)
values
  ('d455811a-b35c-4630-a81a-56b6ce3729fe', 'measure-length-with-ruler', true),
  ('c7e88799-6435-44f9-968d-8186202f008d', 'read-ruler-scale', true),
  ('af7b2b2e-3a49-4a51-9cba-3ef725e96eb9', 'choose-length-unit', true),
  ('7f2ed8da-2739-4d88-8719-28447cddba76', 'choose-length-unit', true),
  ('ab7431cb-3a55-4573-9f06-d820225c777d', 'compare-lengths', true),
  ('84e488d3-628b-42f3-8589-60c1646bb1f5', 'measure-length-with-ruler', true),
  ('e67c66d9-9f22-40bc-bdea-140571780fa1', 'estimate-length', true),
  ('8e81456d-01eb-4c15-886f-b9af817e8610', 'choose-length-unit', true),
  ('7b586413-f98a-494e-ac26-e67b08a9a3d6', 'read-ruler-scale', true),
  ('af2ca815-8222-4cab-b937-15a2c76b392d', 'compare-lengths', true),
  ('4986b4a7-fcba-4521-9363-b3fc4fbf51d3', 'measure-from-nonzero-start', true),
  ('728d191c-68f5-4baa-9e45-5f813bcff8c9', 'measure-from-nonzero-start', true),
  ('b5a624e9-ceda-4a45-95e2-2acba8718f39', 'compare-lengths', true),
  ('dd1752a1-d975-42da-89c4-85d3d8450da0', 'compare-lengths', true),
  ('5473fbc8-b011-4282-98ca-cc9acdf2589f', 'estimate-length', true),
  ('78ae29a8-4da9-45b4-ae20-ac6a67298038', 'estimate-length', true),
  ('79b95acf-a7f9-4a11-a0d1-99dce63065d3', 'read-ruler-scale', true),
  ('0566963d-c57e-4884-ae2b-e28ecacf0544', 'measure-length-with-ruler', true),
  ('7a9ae9af-6ca4-44a1-a776-37b467ce4dfa', 'read-ruler-scale', true),
  ('c64e80b7-ac89-4dab-b18f-c66b51b5cfdd', 'choose-length-unit', true),
  ('6943fcc1-0d74-4661-9574-a8f38b6405ab', 'measure-from-nonzero-start', true),
  ('12c33111-9536-475d-9c1e-d24ccb9abde6', 'measure-from-nonzero-start', true),
  ('777c9b3f-c7a2-4023-8f6b-2057b8e21f9a', 'compare-lengths', true),
  ('e4914597-adff-45a6-9fe1-eb2afb0cc9ad', 'compare-lengths', true),
  ('a6ce38ea-ef4d-4bf5-b7e5-5d724b90fd08', 'infer-length-from-measurement', true),
  ('7df5b633-b8f2-4dcf-ba21-c39891b6bb4d', 'infer-length-from-measurement', true),
  ('2bf3a716-fe4c-4b25-85b1-0d316fe1d1ad', 'measure-from-nonzero-start', true),
  ('6382a9f8-026a-4437-b308-5b3b556da05a', 'infer-length-from-measurement', true),
  ('a55763cd-ad23-4d39-96f3-58e9c60e4fe3', 'compare-lengths', true),
  ('0b42e785-047e-437c-a070-0173b341ec8e', 'choose-length-unit', true),
  ('b860e868-5512-439f-8d73-42346835673e', 'correct-measurement-reasoning', true),
  ('affb99e5-e509-424c-8b6c-94c44c903d4d', 'correct-measurement-reasoning', true),
  ('6dc74739-176e-47c7-a67b-c9b96c41cad2', 'read-ruler-scale', true),
  ('6c88e334-fb08-42fd-be41-f80579a96bb7', 'correct-measurement-reasoning', true),
  ('eaf32cbc-d9e4-4610-96ab-44022b7c2486', 'infer-length-from-measurement', true),
  ('315d6ef5-296c-4fd9-8446-7ec24014fd34', 'infer-length-from-measurement', true),
  ('e05e9df5-d67a-4eb4-b07a-7de617c67bbd', 'infer-length-from-measurement', true),
  ('3c24c97a-b47b-4619-b126-c52620390d6f', 'correct-measurement-reasoning', true),
  ('286c2a44-9d61-43f9-94d5-2b2b4b575496', 'correct-measurement-reasoning', true),
  ('583f0f27-2dfe-4f6f-b157-6a2a90152385', 'infer-length-from-measurement', true);

select (public.publish_learning_content_version('29ac4fe6-847f-4c01-a402-ffce3440fad7'::uuid)).id;

commit;
