-- Generated by scripts/generate-learning-content-migration.js.
-- Source: content/learning/math/grade2-three-digit-numbers-v1.json
-- Canonical content SHA-256: 7d079fa600b1c7e3b25a7eb08ff117fc5c174602fc3c04082637ca845f671a3b
-- Content-only and additive: no assignment, attempt, progress, first-pass, ledger, ACL, or Realtime changes.

begin;

do $preflight$
begin
  if exists (
    select 1 from public.learning_courses
    where (id = '51000000-0000-4000-8000-000000000001'::uuid or course_code = 'math-core')
      and not (
        id = '51000000-0000-4000-8000-000000000001'::uuid
        and course_code = 'math-core'
        and internal_name = '수학 기초 과정'
        and subject_name = '수학'
      )
  ) then
    raise exception using errcode = '23505', message = 'grade2_three_digit_numbers_v1 course identifier conflicts with different content';
  end if;

  if not exists (
    select 1 from public.learning_courses
    where id = '51000000-0000-4000-8000-000000000001'::uuid
      and course_code = 'math-core'
      and internal_name = '수학 기초 과정'
      and subject_name = '수학'
      and status = 'published'
  ) then
    raise exception using errcode = 'P0002', message = 'grade2_three_digit_numbers_v1 existing course is missing or changed';
  end if;

  if exists (
    select 1 from public.learning_units
    where id = 'fe8d3391-2563-4d3a-8b9b-89e19dbf0d79'::uuid
       or unit_code = 'grade2-three-digit-numbers'
  ) then
    raise exception using errcode = '23505', message = 'grade2_three_digit_numbers_v1 unit identifier already exists';
  end if;

  if exists (
    select 1 from public.learning_units
    where course_id = '51000000-0000-4000-8000-000000000001'::uuid
      and sort_order = 2
  ) then
    raise exception using errcode = '23505', message = 'grade2_three_digit_numbers_v1 unit sort order already exists';
  end if;

  if to_regclass('public.learning_unit_recommendation_metadata') is null then
    raise exception using errcode = 'P0002', message = 'learning recommendation metadata table is missing';
  end if;

  if exists (
    select 1
    from public.learning_unit_recommendation_metadata metadata
    where metadata.unit_id = 'fe8d3391-2563-4d3a-8b9b-89e19dbf0d79'::uuid
      and (
        metadata.subject is distinct from 'math'
        or metadata.recommended_start_level_code is distinct from 'elementary_2'
        or metadata.recommended_end_level_code is distinct from 'elementary_2'
        or metadata.parent_sort_order is distinct from 1
      )
  ) then
    raise exception using errcode = '23505', message = 'learning unit recommendation metadata conflicts with different content';
  end if;

  if exists (
    select 1 from public.learning_content_versions
    where id = '376377cb-4093-4f29-bc92-5ca42b27a726'::uuid
       or content_hash = '7d079fa600b1c7e3b25a7eb08ff117fc5c174602fc3c04082637ca845f671a3b'
  ) then
    raise exception using errcode = '23505', message = 'grade2_three_digit_numbers_v1 content version already exists';
  end if;

  if exists (
    select 1 from (
      values
  ('4d22bc1a-413c-42a0-8dc4-5b9b00b4bd79'::uuid),
  ('6fc97490-b295-4bcd-a138-36d53c5a7464'::uuid),
  ('cd4d5705-d872-417a-8d78-3a1f11463e37'::uuid),
  ('2494eb5c-86c4-47f8-8ae2-1d7b8026c240'::uuid),
  ('74cb7602-51a7-485d-a955-6cda8dca913c'::uuid),
  ('d52ef689-0ec4-4f00-8652-c3d149c8b4d6'::uuid),
  ('7ae7a5ad-57be-4c25-88b4-eb69693aa38f'::uuid),
  ('b3ee2305-6096-4854-8da1-6ee50bba443c'::uuid),
  ('418c89a8-fa82-4972-a286-672d8c7a5765'::uuid),
  ('8ee31fab-9744-4a60-bc14-e832b87bcc7e'::uuid),
  ('55025c0a-1104-416e-9f30-587b6882747a'::uuid),
  ('30aec327-ca9c-47d5-b510-df173ceead4b'::uuid),
  ('2e8187a3-bcc6-4eca-b142-d992cd6d6ed0'::uuid),
  ('fbef1249-082f-4d04-8603-a1eb1b1e217b'::uuid),
  ('2bb440ab-b0e5-4c62-85ef-8ac911682f7f'::uuid),
  ('58641795-7646-40c6-9e91-13debbb3c9f9'::uuid),
  ('2e3bc924-b52b-4121-8051-116932438076'::uuid),
  ('135de36a-13b2-4743-92b7-f2292508b397'::uuid),
  ('c50e3414-c0e6-4053-9a65-b38a451e362c'::uuid),
  ('7f42a33f-10d9-4a54-96c9-5f12f73e0237'::uuid),
  ('cfb0057a-b980-4963-9630-727d02904c3e'::uuid),
  ('e0bcbacd-8014-4ab4-9e46-df227d25a04f'::uuid),
  ('61720902-0df0-4b58-8470-bb251b4b6062'::uuid),
  ('ffe15a79-6f93-42d3-bbcc-fa5b8b29d0b4'::uuid),
  ('d35086fd-24e4-44a1-9013-590ac84ae7a9'::uuid),
  ('684be076-b409-4422-a53c-fa82ccadef81'::uuid),
  ('6a0b6177-848d-41be-8ee0-33c97584f654'::uuid),
  ('aab9216b-3e1c-4640-9344-802fedc1c218'::uuid),
  ('855c16ea-7bed-40f3-8566-dd9306212efc'::uuid),
  ('cb364720-372d-4cd4-832f-8c81e3f6627c'::uuid),
  ('cb16dc05-188e-4398-961c-005bc4965faf'::uuid),
  ('0d5a52ef-ef0b-4987-b7ce-d074ff26d762'::uuid),
  ('a0d84d53-0a52-4837-8601-41b4d7463441'::uuid),
  ('5d1da955-d9e2-44f4-a5ef-8005e56be778'::uuid),
  ('463be537-521e-4655-8298-c3d647ec5694'::uuid),
  ('b79b2ebe-3137-42e5-aadd-0711d2364b08'::uuid),
  ('dd91a344-f3e7-4084-ac0b-a2b4aa835633'::uuid),
  ('29c53182-563c-4465-a4fa-bc4af7f0853b'::uuid),
  ('1528bab3-d29c-419e-ad04-f311e8aeb846'::uuid),
  ('f8c47bf1-e8a1-4c3a-9b4c-b78f5307f4c1'::uuid),
  ('d9b6e341-7437-47e9-97fc-7bb9dbcd931e'::uuid),
  ('1311529f-6cfd-4e86-8f69-2003816ed4bc'::uuid),
  ('81025ee1-0713-452e-b075-43427981ca8b'::uuid),
  ('7fa874b1-15d0-401f-bcb3-45b1902d1f63'::uuid),
  ('a5a2f5a3-c7a5-44ec-be13-298d0fee24df'::uuid),
  ('dd57e04e-928f-4e8f-bfeb-11968e6722ee'::uuid),
  ('efebe57c-0a01-46f9-92fb-2a95b2cf0925'::uuid),
  ('78e6c0b6-26c1-4d45-bcdf-aea7d6495316'::uuid),
  ('d12f6874-a422-4a38-828b-7b97e8cb58de'::uuid),
  ('ddd55a35-01c9-437e-8c57-5c76143927db'::uuid),
  ('8e0246e9-3f12-4eb8-a989-575d2a2ee46d'::uuid),
  ('84e9fdbb-19c6-4424-b9bb-c6ebb31ac3c2'::uuid),
  ('1f741532-fcb4-4195-a570-4869fea1ef39'::uuid),
  ('08e202d0-a02e-477e-a60a-eb881b1d1f6b'::uuid),
  ('202a2494-a986-4070-8d3a-34a7d85c882a'::uuid),
  ('a18f62ef-6038-4456-abd2-70444c9476a6'::uuid),
  ('89378ac2-7fac-4687-88ae-62a38349b2b7'::uuid),
  ('121c59c9-3793-43aa-b808-397209d2c731'::uuid),
  ('173865a8-378e-4ab1-a11a-8dfdeb9a7e4e'::uuid),
  ('44918797-fb15-4f9f-b9ac-275f9c2130d1'::uuid),
  ('e3643260-12cb-49e9-b39c-b6b99e479d25'::uuid),
  ('c4658349-658c-43ed-a7b1-e450de1eac6c'::uuid),
  ('244596f5-f822-40e0-8e11-5028ec0ee2bc'::uuid),
  ('d4280586-baae-480f-8353-387d712cd2d0'::uuid),
  ('96fd0453-184c-4674-9538-ab103edaa4c3'::uuid),
  ('989c0021-bf9f-4dd3-89e1-d8997d4e22b1'::uuid),
  ('1ea5f709-ed6e-4f01-8132-9474f0df8015'::uuid),
  ('57c239b9-b4f2-4276-9d50-3fff9582e221'::uuid),
  ('7e8abbe9-c2b0-4ab0-a6fa-6d335b9b2245'::uuid),
  ('bdc380e8-bf94-4a48-be62-56e85aea5544'::uuid),
  ('a3bd958a-c9d7-445d-b17e-3be6f5fae9e6'::uuid),
  ('85aa9948-cd3a-43da-926a-88a1a58adf38'::uuid),
  ('0616980e-6180-422a-aabc-c2f2cd35b3cf'::uuid),
  ('4d72bd98-b5ab-4dcb-b545-948cc3cf46c7'::uuid),
  ('34bbee10-fe6c-4db0-9911-2a66f71f891f'::uuid),
  ('07807354-8132-4823-a1b6-0e3c50810a8a'::uuid),
  ('170cfba9-9ffd-4258-8b7d-dbe72f2cd7cd'::uuid),
  ('70f3c035-0a67-4516-a0ea-2a5ffdb6dfe1'::uuid),
  ('691c525d-57cd-48e4-9507-c506cfb36261'::uuid),
  ('3c90d2de-6f3c-477e-89e6-af143480dc61'::uuid),
  ('0325256e-878b-4dcb-a942-4bf0b6f1e8db'::uuid),
  ('38804556-fa0c-4559-b846-a1339b5b96fe'::uuid),
  ('fd510e2c-99a5-405d-9db3-a699a10c4b60'::uuid),
  ('7f8d395f-6c0e-4538-b88e-038d53617dfe'::uuid),
  ('042cb4a2-affe-43e1-a151-9b41e63a7af3'::uuid),
  ('73735389-9a58-4335-a184-c56545fd739c'::uuid),
  ('224600fa-2b93-44af-8ac9-f17a6c2af42d'::uuid),
  ('add99121-1ee0-4480-95d5-95d4930c924c'::uuid),
  ('81212197-870e-4586-b822-e9f8d91d90b8'::uuid),
  ('3e125ecf-5cda-4ced-9edc-98f4914a60ea'::uuid),
  ('ea27bbc6-55a0-49e5-90a1-4fcaff3e3a15'::uuid),
  ('e39c0a32-8045-43fe-8cae-92385f83216a'::uuid),
  ('5527c98e-3403-4203-8d6c-0710e3b89686'::uuid),
  ('65ef7869-d62f-470f-80d8-b7c14d233773'::uuid),
  ('24a25e17-bbd7-4764-b202-3be06368850f'::uuid),
  ('aae0ade9-8127-4fd7-8ca1-7f8377b84084'::uuid),
  ('d90eb8d6-339b-49f3-8c42-e9650e9552b7'::uuid),
  ('218f7a78-fb7a-4f61-8fd6-2cc67dadbde6'::uuid),
  ('1562be98-54c8-4439-b288-a750b83f1759'::uuid),
  ('0a858041-a23e-457e-b5cd-b4656082b9a2'::uuid),
  ('be28320d-86f2-4034-bfb5-6a98a5e9f7c6'::uuid),
  ('71ad5840-439f-46c7-b00c-139dc2a71496'::uuid),
  ('e8862274-19c6-4c5d-b818-8bf43cfbdbaa'::uuid),
  ('71a3ada4-4268-475d-beab-e7a079166348'::uuid),
  ('fc2fa835-d913-4d7f-a0e6-51df155570b8'::uuid),
  ('ab0f8899-90e8-4a28-a804-7fa876fb480b'::uuid),
  ('b4ae66c8-5fc0-4283-a3cf-f7a87ee63692'::uuid),
  ('a6084c2c-a4b5-4b00-9dbd-692d4e6280eb'::uuid),
  ('51fcb87d-d77c-4201-a69a-927fd5e12d95'::uuid),
  ('735b58f5-2b41-4414-a69b-78582ac811aa'::uuid),
  ('dec9e40a-5db7-4330-b26d-236610f2e8e4'::uuid),
  ('63239d6c-5de5-4353-9d6d-c8615d43f0d2'::uuid),
  ('4bcf9e34-9ec0-452c-a94a-12451a759e69'::uuid),
  ('ce4bb6c4-4c5e-497c-b58e-5663be3514d9'::uuid),
  ('7110d75a-fbc6-42f3-abc9-7f61edd9e64d'::uuid),
  ('e301d273-cc16-48bf-ae83-d2327647cccb'::uuid),
  ('e8b011e3-d3ea-4164-bbda-8997184aa542'::uuid),
  ('56ef1403-de19-4233-b683-b3c010667937'::uuid),
  ('71e3bfa1-9e43-4a87-bde2-0e583658a64f'::uuid),
  ('618e9cc1-8d0f-4ba3-9866-0d2702bf9683'::uuid),
  ('74363334-09d1-4cc5-8f8e-28c5cb364e3f'::uuid),
  ('1e6c5e82-5d8a-4828-a695-f3de7fd9d59d'::uuid),
  ('ee8e5d27-d78f-41a1-8b54-bbe0a093f3df'::uuid),
  ('98638495-4343-4cdc-a318-7cc00e5552d7'::uuid),
  ('232b8072-1a3d-43cb-851d-a24f05da136b'::uuid),
  ('38e1e779-a816-40df-814f-69916a956bc1'::uuid),
  ('b7d28c98-0a26-4342-9d17-28b884368a76'::uuid),
  ('115bfe1c-4c10-4f45-958b-afde22cf7410'::uuid),
  ('e3b704ce-3050-4341-9b62-09c4f31e64b8'::uuid),
  ('7753c30e-49e7-4d36-aa7f-7b2f741f52b6'::uuid),
  ('971534c8-fff8-42d6-8e6c-df9c3c3cda96'::uuid),
  ('255e9f8e-874f-4381-a8f4-a487faeabae5'::uuid),
  ('d39cd555-4634-4a80-b86f-54951e908cc3'::uuid),
  ('3e965309-f182-403c-a752-85b6cf72e726'::uuid),
  ('3b841d61-d523-43c9-8be0-f996c5489097'::uuid),
  ('d2a7c1ec-20fd-4e4c-a584-b017510b7696'::uuid),
  ('486be5d0-2f52-4295-a6ce-46c5360e7dcc'::uuid),
  ('81765c53-0f50-4b3a-81d2-6cd67bdc9897'::uuid),
  ('f9b74b36-7bb8-49ee-b77d-cc7470dd9d32'::uuid),
  ('9e4ce6cd-8684-41c9-8352-b278c8c73e19'::uuid),
  ('3c46c202-94da-4ca2-9ce6-bf45dae44078'::uuid),
  ('62a0200e-594a-4d8c-b1c6-f98002edaecf'::uuid),
  ('77876f7d-4eaa-4d9d-8e5d-b2342161d060'::uuid),
  ('63d074fe-cb53-402c-85ee-fb9fb81e5842'::uuid),
  ('b0523aa9-296c-4638-97b7-2a2ebdbab489'::uuid),
  ('4a70d9bd-6f3d-4e2d-b303-a9b781b90203'::uuid),
  ('4b89f109-055b-4712-8de9-c09b0b10a3dd'::uuid),
  ('076e51a5-5e7c-47c2-9a17-ec43cdb9bf1e'::uuid),
  ('41df98d9-b4a2-4286-93a5-e505a9700046'::uuid),
  ('53b41d35-8133-4d0c-b0f0-4942cbdd3f58'::uuid),
  ('9dcb7639-d697-45e7-bfd8-fa214d756f1c'::uuid),
  ('5612898f-2718-4eb3-bcdf-649574396d20'::uuid),
  ('ae6dcae9-abcf-42b6-8b1d-8ed97e4123b1'::uuid),
  ('ca30bafb-cdca-41a5-90df-d785174c88fd'::uuid),
  ('9644c3d3-229e-4d8e-aedd-c784d5fc2c8f'::uuid),
  ('25c6d4e7-0599-4960-b665-1ebc0688cac9'::uuid),
  ('7704f91b-6a8d-4725-bcdc-43091a887472'::uuid),
  ('2b87a589-f4d3-4d8b-8271-1aee9e82b6d3'::uuid),
  ('d88a1f39-a664-4a36-8b1a-50b8ad0684a1'::uuid),
  ('ee60fad6-bca2-41e9-b619-1cb0b4a5c83c'::uuid),
  ('8c41d846-cf14-4850-955b-1d94a0acf48d'::uuid),
  ('3468c0d4-0798-4f36-9ac5-515340f111b9'::uuid),
  ('c7102c58-b5b0-4ef0-a46c-9583d190e9df'::uuid),
  ('efce1265-281f-4884-ba96-8e288305c46d'::uuid),
  ('8ffb6318-adda-4457-b592-6b20e3760d45'::uuid),
  ('062dc9c1-5495-472e-8366-ceec2f53c05e'::uuid),
  ('6bd1fff6-ff21-40ad-9444-1017b146a7b5'::uuid),
  ('51f06edf-013d-4231-bf3a-deb611db98c3'::uuid),
  ('c864f71a-d92c-48a1-90fb-afabf04245f7'::uuid),
  ('027dcaf8-b7d8-42f4-b6d7-af6a49b02b3e'::uuid),
  ('12d6f81c-bbee-431a-97a9-dc6822f8d196'::uuid),
  ('b3ba38d7-3554-4684-a9f0-a6c6c519f2f7'::uuid),
  ('664ba395-7842-45f1-a6ab-7e5c2d9fb0c2'::uuid),
  ('5aef6f03-94c2-4f19-bf0c-91c55ae04aa8'::uuid),
  ('203761f6-909a-432a-838a-ae3a3d47a099'::uuid),
  ('d77e72d1-3009-45b4-959f-3965d53b3fb3'::uuid),
  ('651ae889-0777-444e-8ea4-e61307196ba8'::uuid),
  ('9969ac21-42dc-4562-9175-c45d5a92b965'::uuid),
  ('3bef1f1b-1f64-46ca-b5bd-2abb152cc64a'::uuid),
  ('ba09ae27-2358-490b-af82-2a46bf3c28c2'::uuid),
  ('19d95115-d247-408b-bed3-7b2aaffc8a8a'::uuid),
  ('a2247db0-4400-4c5c-956e-f20d6687bbaa'::uuid),
  ('66cb87a7-a22a-4fe9-b606-c4afd0626dd4'::uuid),
  ('b9b8e099-6b1a-4d34-af54-685af19c6050'::uuid),
  ('d5ce7866-2d19-47c1-b7ae-9c7974283439'::uuid),
  ('830c8924-4807-40c6-9d48-3c5abe57c0ad'::uuid),
  ('dc7e189e-71b8-4b4e-811c-73a6cbb09c70'::uuid),
  ('114fa42e-0149-4f92-becb-e91f8b05ef08'::uuid),
  ('3a8c0167-d41b-4be2-b227-6758565f356c'::uuid),
  ('cda1fc49-8fdd-4f11-abb2-3625a4f54cbd'::uuid),
  ('bebb3ecc-ddf7-400d-9398-3351e17638c4'::uuid),
  ('a3b98a0a-dc6c-47fe-959f-32d5fad60657'::uuid),
  ('6e81fb46-6e55-4765-a6b7-5b2379acc984'::uuid),
  ('be3fab36-1ab9-45a6-a06e-188174884468'::uuid),
  ('2043397a-55a0-4551-84d8-c90d703329aa'::uuid),
  ('99b0a0dc-d83a-46e2-bf8b-1489ce4c6f37'::uuid),
  ('e99280be-9024-431a-899a-cec925619cbf'::uuid),
  ('182e6c76-4ebf-4f49-99ab-1d327e463a9b'::uuid),
  ('71823cd7-8600-43b8-9563-276f8e716782'::uuid),
  ('0e412d7f-1f5c-4bfa-9395-5a9f8ec9656a'::uuid),
  ('552ead57-d823-4be1-afb2-91774f82533f'::uuid),
  ('3cec4b35-6b83-4d5e-bc0e-3c2102709902'::uuid),
  ('487d6df1-03fb-4e9a-bdde-9933f99b7aa6'::uuid),
  ('4fd24492-9f0d-4480-a130-a2b842dd9f02'::uuid)
    ) as expected_id(id)
    where exists (
      select 1 from public.learning_stages where id = expected_id.id
      union all
      select 1 from public.learning_questions where id = expected_id.id
      union all
      select 1 from public.learning_question_options where id = expected_id.id
    )
  ) then
    raise exception using errcode = '23505', message = 'grade2_three_digit_numbers_v1 child content identifier already exists';
  end if;
end
$preflight$;

insert into public.learning_units (id, course_id, unit_code, display_title, sort_order)
values ('fe8d3391-2563-4d3a-8b9b-89e19dbf0d79', '51000000-0000-4000-8000-000000000001', 'grade2-three-digit-numbers', '세 자리 수를 알아봐요', 2);

insert into public.learning_unit_recommendation_metadata (
  unit_id, subject, recommended_start_level_code, recommended_end_level_code, parent_sort_order
)
select 'fe8d3391-2563-4d3a-8b9b-89e19dbf0d79'::uuid, 'math', 'elementary_2', 'elementary_2', 1
where not exists (
  select 1
  from public.learning_unit_recommendation_metadata metadata
  where metadata.unit_id = 'fe8d3391-2563-4d3a-8b9b-89e19dbf0d79'::uuid
);

insert into public.learning_content_versions (id, unit_id, version_no, content_hash)
values ('376377cb-4093-4f29-bc92-5ca42b27a726', 'fe8d3391-2563-4d3a-8b9b-89e19dbf0d79', 1, '7d079fa600b1c7e3b25a7eb08ff117fc5c174602fc3c04082637ca845f671a3b');

insert into public.learning_stages (id, content_version_id, display_order, display_title, difficulty)
values
  ('4d22bc1a-413c-42a0-8dc4-5b9b00b4bd79', '376377cb-4093-4f29-bc92-5ca42b27a726', 1, '입문', 'seed'),
  ('6fc97490-b295-4bcd-a138-36d53c5a7464', '376377cb-4093-4f29-bc92-5ca42b27a726', 2, '기초', 'leaf'),
  ('cd4d5705-d872-417a-8d78-3a1f11463e37', '376377cb-4093-4f29-bc92-5ca42b27a726', 3, '심화', 'tree'),
  ('2494eb5c-86c4-47f8-8ae2-1d7b8026c240', '376377cb-4093-4f29-bc92-5ca42b27a726', 4, '최상위 도전!', 'crown');

insert into public.learning_questions (id, stage_id, display_order, prompt, explanation)
values
  ('74cb7602-51a7-485d-a955-6cda8dca913c', '4d22bc1a-413c-42a0-8dc4-5b9b00b4bd79', 1, '347을 읽은 것은?', '347은 백의 자리 3과 십의 자리 4와 일의 자리 7로 이루어져 삼백사십칠이라고 읽습니다.'),
  ('d52ef689-0ec4-4f00-8652-c3d149c8b4d6', '4d22bc1a-413c-42a0-8dc4-5b9b00b4bd79', 2, '608을 읽은 것은?', '608은 백이 6개이고 십이 0개이며 일이 8개이므로 육백팔이라고 읽습니다.'),
  ('7ae7a5ad-57be-4c25-88b4-eb69693aa38f', '4d22bc1a-413c-42a0-8dc4-5b9b00b4bd79', 3, '오백이십구를 숫자로 쓴 것은?', '오백은 500이고 이십은 20이며 구는 9이므로 529입니다.'),
  ('b3ee2305-6096-4854-8da1-6ee50bba443c', '4d22bc1a-413c-42a0-8dc4-5b9b00b4bd79', 4, '칠백사를 숫자로 쓴 것은?', '칠백사는 700과 4를 합한 수이므로 704입니다.'),
  ('418c89a8-fa82-4972-a286-672d8c7a5765', '4d22bc1a-413c-42a0-8dc4-5b9b00b4bd79', 5, '백이 4개이고 십이 2개이며 일이 6개인 수는?', '백 4개는 400이고 십 2개는 20이며 일 6개는 6이므로 426입니다.'),
  ('8ee31fab-9744-4a60-bc14-e832b87bcc7e', '4d22bc1a-413c-42a0-8dc4-5b9b00b4bd79', 6, '백이 7개이고 십이 0개이며 일이 3개인 수는?', '700에 십 묶음은 없고 일 3개를 더하므로 703입니다.'),
  ('55025c0a-1104-416e-9f30-587b6882747a', '4d22bc1a-413c-42a0-8dc4-5b9b00b4bd79', 7, '백 묶음 9개와 십 묶음 5개가 나타내는 수는?', '백 묶음 9개는 900이고 십 묶음 5개는 50이므로 950입니다.'),
  ('30aec327-ca9c-47d5-b510-df173ceead4b', '4d22bc1a-413c-42a0-8dc4-5b9b00b4bd79', 8, '352의 백의 자리 숫자는?', '352에서 백의 자리에 있는 숫자는 3입니다.'),
  ('2e8187a3-bcc6-4eca-b142-d992cd6d6ed0', '4d22bc1a-413c-42a0-8dc4-5b9b00b4bd79', 9, '681에서 십의 자리 숫자 8이 나타내는 값은?', '8은 십의 자리에 있으므로 8이 나타내는 값은 80입니다.'),
  ('fbef1249-082f-4d04-8603-a1eb1b1e217b', '4d22bc1a-413c-42a0-8dc4-5b9b00b4bd79', 10, '407의 일의 자리 숫자는?', '407에서 일의 자리에 있는 숫자는 7입니다.'),
  ('2bb440ab-b0e5-4c62-85ef-8ac911682f7f', '6fc97490-b295-4bcd-a138-36d53c5a7464', 1, '300과 40과 8을 합한 수는?', '300과 40과 8을 합하면 348입니다.'),
  ('58641795-7646-40c6-9e91-13debbb3c9f9', '6fc97490-b295-4bcd-a138-36d53c5a7464', 2, '백이 6개이고 일이 5개이며 십은 없는 수는?', '백 6개는 600이고 십은 0개이며 일 5개를 더하므로 605입니다.'),
  ('2e3bc924-b52b-4121-8051-116932438076', '6fc97490-b295-4bcd-a138-36d53c5a7464', 3, '백이 2개이고 십이 9개이며 일이 0개인 수는?', '200과 90을 합하고 일은 더하지 않으므로 290입니다.'),
  ('135de36a-13b2-4743-92b7-f2292508b397', '6fc97490-b295-4bcd-a138-36d53c5a7464', 4, '572를 바르게 나눈 것은?', '572는 백 5개와 십 7개와 일 2개이므로 500+70+2입니다.'),
  ('c50e3414-c0e6-4053-9a65-b38a451e362c', '6fc97490-b295-4bcd-a138-36d53c5a7464', 5, '406을 바르게 나눈 것은?', '406은 백 4개와 십 0개와 일 6개이므로 400+6입니다.'),
  ('7f42a33f-10d9-4a54-96c9-5f12f73e0237', '6fc97490-b295-4bcd-a138-36d53c5a7464', 6, '830을 바르게 나눈 것은?', '830은 백 8개와 십 3개와 일 0개이므로 800+30입니다.'),
  ('cfb0057a-b980-4963-9630-727d02904c3e', '6fc97490-b295-4bcd-a138-36d53c5a7464', 7, '764에서 숫자 7이 나타내는 값은?', '7은 백의 자리에 있으므로 700을 나타냅니다.'),
  ('e0bcbacd-8014-4ab4-9e46-df227d25a04f', '6fc97490-b295-4bcd-a138-36d53c5a7464', 8, '295에서 숫자 9가 나타내는 값은?', '9는 십의 자리에 있으므로 90을 나타냅니다.'),
  ('61720902-0df0-4b58-8470-bb251b4b6062', '6fc97490-b295-4bcd-a138-36d53c5a7464', 9, '509의 십의 자리 숫자는?', '509에는 십 묶음이 없으므로 십의 자리 숫자는 0입니다.'),
  ('ffe15a79-6f93-42d3-bbcc-fa5b8b29d0b4', '6fc97490-b295-4bcd-a138-36d53c5a7464', 10, '470을 나타내는 식은?', '470은 백 4개와 십 7개와 일 0개이므로 400+70입니다.'),
  ('d35086fd-24e4-44a1-9013-590ac84ae7a9', 'cd4d5705-d872-417a-8d78-3a1f11463e37', 1, '438과 483 중 더 큰 수는?', '백의 자리 수가 같으므로 십의 자리를 비교하면 8이 3보다 커서 483이 더 큽니다.'),
  ('684be076-b409-4422-a53c-fa82ccadef81', 'cd4d5705-d872-417a-8d78-3a1f11463e37', 2, '705와 750 중 더 작은 수는?', '백의 자리 수가 같고 십의 자리에서 0이 5보다 작으므로 705가 더 작습니다.'),
  ('6a0b6177-848d-41be-8ee0-33c97584f654', 'cd4d5705-d872-417a-8d78-3a1f11463e37', 3, '629보다 큰 수는?', '692는 백의 자리 수가 같고 십의 자리 9가 2보다 크므로 629보다 큽니다.'),
  ('aab9216b-3e1c-4640-9344-802fedc1c218', 'cd4d5705-d872-417a-8d78-3a1f11463e37', 4, '312와 321과 213을 작은 수부터 놓은 것은?', '백의 자리부터 비교하면 213이 가장 작고 이어서 312와 321의 순서입니다.'),
  ('855c16ea-7bed-40f3-8566-dd9306212efc', 'cd4d5705-d872-417a-8d78-3a1f11463e37', 5, '546과 465와 564를 큰 수부터 놓은 것은?', '백의 자리가 5인 수들이 먼저이고 그중 564가 546보다 크므로 564 → 546 → 465입니다.'),
  ('cb364720-372d-4cd4-832f-8c81e3f6627c', 'cd4d5705-d872-417a-8d78-3a1f11463e37', 6, '808과 880과 800을 작은 수부터 놓은 것은?', '백의 자리 수는 같고 십과 일의 자리를 차례로 비교하면 800 → 808 → 880입니다.'),
  ('cb16dc05-188e-4398-961c-005bc4965faf', 'cd4d5705-d872-417a-8d78-3a1f11463e37', 7, '500의 바로 앞 수는?', '500보다 1 작은 수는 499이므로 바로 앞 수는 499입니다.'),
  ('0d5a52ef-ef0b-4987-b7ce-d074ff26d762', 'cd4d5705-d872-417a-8d78-3a1f11463e37', 8, '799의 바로 뒤 수는?', '799보다 1 큰 수는 800이므로 바로 뒤 수는 800입니다.'),
  ('a0d84d53-0a52-4837-8601-41b4d7463441', 'cd4d5705-d872-417a-8d78-3a1f11463e37', 9, '320 → 330 → □ → 350에서 □에 알맞은 수는?', '10씩 커지는 배열이므로 330 다음은 340입니다.'),
  ('5d1da955-d9e2-44f4-a5ef-8005e56be778', 'cd4d5705-d872-417a-8d78-3a1f11463e37', 10, '905 → □ → 915 → 920에서 □에 알맞은 수는?', '5씩 커지는 배열이므로 905 다음은 910입니다.'),
  ('463be537-521e-4655-8298-c3d647ec5694', '2494eb5c-86c4-47f8-8ae2-1d7b8026c240', 1, '430보다 크고 470보다 작으며 일의 자리 숫자는 2입니다. 십의 자리 숫자가 일의 자리 숫자의 2배인 수는?', '범위와 일의 자리 조건으로 후보를 좁힙니다. 일의 자리 2의 2배인 4가 십의 자리에 오는 수는 442입니다.'),
  ('b79b2ebe-3137-42e5-aadd-0711d2364b08', '2494eb5c-86c4-47f8-8ae2-1d7b8026c240', 2, '600보다 크고 700보다 작은 수입니다. 십의 자리 숫자는 일의 자리 숫자보다 1 작고 두 숫자를 더하면 9입니다. 이 수는?', '십의 자리와 일의 자리의 합이 9인 이웃한 숫자는 4와 5입니다. 작은 4를 십의 자리에 놓으면 645입니다.'),
  ('dd91a344-f3e7-4084-ac0b-a2b4aa835633', '2494eb5c-86c4-47f8-8ae2-1d7b8026c240', 3, '숫자 카드 3과 6과 8을 각각 한 번씩 써서 세 자리 수를 만듭니다. 만들 수 있는 두 번째로 큰 수는?', '가장 큰 수는 863입니다. 그다음에는 백의 자리 8을 유지하고 남은 숫자를 3과 6의 순서로 놓은 836이 옵니다.'),
  ('29c53182-563c-4465-a4fa-bc4af7f0853b', '2494eb5c-86c4-47f8-8ae2-1d7b8026c240', 4, '숫자 카드 0과 4와 7을 각각 한 번씩 써서 400보다 큰 세 자리 수를 만듭니다. 그중 가장 작은 수는?', '400보다 크면서 가장 작게 하려면 백의 자리에 4를 놓습니다. 남은 숫자 중 작은 0을 십의 자리에 놓으면 407입니다.'),
  ('1528bab3-d29c-419e-ad04-f311e8aeb846', '2494eb5c-86c4-47f8-8ae2-1d7b8026c240', 5, '472의 십의 자리와 일의 자리 숫자를 서로 바꿨습니다. 바꾼 수를 바르게 설명한 것은?', '십의 자리 7과 일의 자리 2를 바꾸면 427입니다. 427은 420보다 크고 430보다 작습니다.'),
  ('f8c47bf1-e8a1-4c3a-9b4c-b78f5307f4c1', '2494eb5c-86c4-47f8-8ae2-1d7b8026c240', 6, '5□7에서 십의 자리와 일의 자리 숫자를 바꾸면 57□가 됩니다. 처음 수가 바꾼 수보다 크고 □가 짝수일 때 □에 알맞은 숫자는?', '처음 수가 더 크려면 십의 자리 □가 7보다 커야 합니다. 7보다 큰 짝수는 8이므로 □는 8입니다.'),
  ('d9b6e341-7437-47e9-97fc-7bb9dbcd931e', '2494eb5c-86c4-47f8-8ae2-1d7b8026c240', 7, '100개 묶음 3개와 10개 묶음 12개가 있습니다. 10개 묶음 10개를 100개 묶음 1개로 바꾼 결과는?', '10개 묶음 12개에서 10개를 꺼내 100개 묶음 1개로 바꿉니다. 따라서 100개 묶음은 4개가 되고 10개 묶음은 2개가 남습니다.'),
  ('1311529f-6cfd-4e86-8f69-2003816ed4bc', '2494eb5c-86c4-47f8-8ae2-1d7b8026c240', 8, '400+90+10에서 10개 묶음을 바르게 교환해 같은 수로 나타낸 것은?', '90과 10을 합하면 10개 묶음이 10개입니다. 이를 100개 묶음 1개로 바꾸면 400과 합해 100개 묶음 5개가 됩니다.'),
  ('81025ee1-0713-452e-b075-43427981ca8b', '2494eb5c-86c4-47f8-8ae2-1d7b8026c240', 9, '민수는 507에서 십의 자리 0을 빼고 57이라고 읽었습니다. 잘못된 생각을 바르게 고친 것은?', '십의 자리 0은 십 묶음이 없다는 뜻이지 다른 숫자의 자리를 옮기지 않습니다. 7은 일의 자리에 그대로 있으므로 507입니다.'),
  ('7fa874b1-15d0-401f-bcb3-45b1902d1f63', '2494eb5c-86c4-47f8-8ae2-1d7b8026c240', 10, '지수는 682와 619를 일의 자리부터 비교해 619가 더 크다고 했습니다. 잘못된 비교를 바르게 고친 것은?', '세 자리 수는 백의 자리부터 비교합니다. 백의 자리 6은 같고 십의 자리에서 8이 1보다 크므로 682가 더 큽니다.');

insert into public.learning_question_options (id, question_id, display_order, option_text, is_correct)
values
  ('a5a2f5a3-c7a5-44ec-be13-298d0fee24df', '74cb7602-51a7-485d-a955-6cda8dca913c', 1, '삼백사십칠', true),
  ('dd57e04e-928f-4e8f-bfeb-11968e6722ee', '74cb7602-51a7-485d-a955-6cda8dca913c', 2, '삼백칠십사', false),
  ('efebe57c-0a01-46f9-92fb-2a95b2cf0925', '74cb7602-51a7-485d-a955-6cda8dca913c', 3, '사백삼십칠', false),
  ('78e6c0b6-26c1-4d45-bcdf-aea7d6495316', '74cb7602-51a7-485d-a955-6cda8dca913c', 4, '삼백사십', false),
  ('d12f6874-a422-4a38-828b-7b97e8cb58de', 'd52ef689-0ec4-4f00-8652-c3d149c8b4d6', 1, '육백팔', true),
  ('ddd55a35-01c9-437e-8c57-5c76143927db', 'd52ef689-0ec4-4f00-8652-c3d149c8b4d6', 2, '육백팔십', false),
  ('8e0246e9-3f12-4eb8-a989-575d2a2ee46d', 'd52ef689-0ec4-4f00-8652-c3d149c8b4d6', 3, '육십팔', false),
  ('84e9fdbb-19c6-4424-b9bb-c6ebb31ac3c2', 'd52ef689-0ec4-4f00-8652-c3d149c8b4d6', 4, '팔백육', false),
  ('1f741532-fcb4-4195-a570-4869fea1ef39', '7ae7a5ad-57be-4c25-88b4-eb69693aa38f', 1, '592', false),
  ('08e202d0-a02e-477e-a60a-eb881b1d1f6b', '7ae7a5ad-57be-4c25-88b4-eb69693aa38f', 2, '509', false),
  ('202a2494-a986-4070-8d3a-34a7d85c882a', '7ae7a5ad-57be-4c25-88b4-eb69693aa38f', 3, '529', true),
  ('a18f62ef-6038-4456-abd2-70444c9476a6', '7ae7a5ad-57be-4c25-88b4-eb69693aa38f', 4, '259', false),
  ('89378ac2-7fac-4687-88ae-62a38349b2b7', 'b3ee2305-6096-4854-8da1-6ee50bba443c', 1, '740', false),
  ('121c59c9-3793-43aa-b808-397209d2c731', 'b3ee2305-6096-4854-8da1-6ee50bba443c', 2, '714', false),
  ('173865a8-378e-4ab1-a11a-8dfdeb9a7e4e', 'b3ee2305-6096-4854-8da1-6ee50bba443c', 3, '407', false),
  ('44918797-fb15-4f9f-b9ac-275f9c2130d1', 'b3ee2305-6096-4854-8da1-6ee50bba443c', 4, '704', true),
  ('e3643260-12cb-49e9-b39c-b6b99e479d25', '418c89a8-fa82-4972-a286-672d8c7a5765', 1, '246', false),
  ('c4658349-658c-43ed-a7b1-e450de1eac6c', '418c89a8-fa82-4972-a286-672d8c7a5765', 2, '462', false),
  ('244596f5-f822-40e0-8e11-5028ec0ee2bc', '418c89a8-fa82-4972-a286-672d8c7a5765', 3, '426', true),
  ('d4280586-baae-480f-8353-387d712cd2d0', '418c89a8-fa82-4972-a286-672d8c7a5765', 4, '406', false),
  ('96fd0453-184c-4674-9538-ab103edaa4c3', '8ee31fab-9744-4a60-bc14-e832b87bcc7e', 1, '730', false),
  ('989c0021-bf9f-4dd3-89e1-d8997d4e22b1', '8ee31fab-9744-4a60-bc14-e832b87bcc7e', 2, '73', false),
  ('1ea5f709-ed6e-4f01-8132-9474f0df8015', '8ee31fab-9744-4a60-bc14-e832b87bcc7e', 3, '700', false),
  ('57c239b9-b4f2-4276-9d50-3fff9582e221', '8ee31fab-9744-4a60-bc14-e832b87bcc7e', 4, '703', true),
  ('7e8abbe9-c2b0-4ab0-a6fa-6d335b9b2245', '55025c0a-1104-416e-9f30-587b6882747a', 1, '905', false),
  ('bdc380e8-bf94-4a48-be62-56e85aea5544', '55025c0a-1104-416e-9f30-587b6882747a', 2, '590', false),
  ('a3bd958a-c9d7-445d-b17e-3be6f5fae9e6', '55025c0a-1104-416e-9f30-587b6882747a', 3, '950', true),
  ('85aa9948-cd3a-43da-926a-88a1a58adf38', '55025c0a-1104-416e-9f30-587b6882747a', 4, '95', false),
  ('0616980e-6180-422a-aabc-c2f2cd35b3cf', '30aec327-ca9c-47d5-b510-df173ceead4b', 1, '2', false),
  ('4d72bd98-b5ab-4dcb-b545-948cc3cf46c7', '30aec327-ca9c-47d5-b510-df173ceead4b', 2, '5', false),
  ('34bbee10-fe6c-4db0-9911-2a66f71f891f', '30aec327-ca9c-47d5-b510-df173ceead4b', 3, '300', false),
  ('07807354-8132-4823-a1b6-0e3c50810a8a', '30aec327-ca9c-47d5-b510-df173ceead4b', 4, '3', true),
  ('170cfba9-9ffd-4258-8b7d-dbe72f2cd7cd', '2e8187a3-bcc6-4eca-b142-d992cd6d6ed0', 1, '8', false),
  ('70f3c035-0a67-4516-a0ea-2a5ffdb6dfe1', '2e8187a3-bcc6-4eca-b142-d992cd6d6ed0', 2, '80', true),
  ('691c525d-57cd-48e4-9507-c506cfb36261', '2e8187a3-bcc6-4eca-b142-d992cd6d6ed0', 3, '800', false),
  ('3c90d2de-6f3c-477e-89e6-af143480dc61', '2e8187a3-bcc6-4eca-b142-d992cd6d6ed0', 4, '60', false),
  ('0325256e-878b-4dcb-a942-4bf0b6f1e8db', 'fbef1249-082f-4d04-8603-a1eb1b1e217b', 1, '0', false),
  ('38804556-fa0c-4559-b846-a1339b5b96fe', 'fbef1249-082f-4d04-8603-a1eb1b1e217b', 2, '4', false),
  ('fd510e2c-99a5-405d-9db3-a699a10c4b60', 'fbef1249-082f-4d04-8603-a1eb1b1e217b', 3, '7', true),
  ('7f8d395f-6c0e-4538-b88e-038d53617dfe', 'fbef1249-082f-4d04-8603-a1eb1b1e217b', 4, '40', false),
  ('042cb4a2-affe-43e1-a151-9b41e63a7af3', '2bb440ab-b0e5-4c62-85ef-8ac911682f7f', 1, '348', true),
  ('73735389-9a58-4335-a184-c56545fd739c', '2bb440ab-b0e5-4c62-85ef-8ac911682f7f', 2, '384', false),
  ('224600fa-2b93-44af-8ac9-f17a6c2af42d', '2bb440ab-b0e5-4c62-85ef-8ac911682f7f', 3, '438', false),
  ('add99121-1ee0-4480-95d5-95d4930c924c', '2bb440ab-b0e5-4c62-85ef-8ac911682f7f', 4, '308', false),
  ('81212197-870e-4586-b822-e9f8d91d90b8', '58641795-7646-40c6-9e91-13debbb3c9f9', 1, '650', false),
  ('3e125ecf-5cda-4ced-9edc-98f4914a60ea', '58641795-7646-40c6-9e91-13debbb3c9f9', 2, '65', false),
  ('ea27bbc6-55a0-49e5-90a1-4fcaff3e3a15', '58641795-7646-40c6-9e91-13debbb3c9f9', 3, '600', false),
  ('e39c0a32-8045-43fe-8cae-92385f83216a', '58641795-7646-40c6-9e91-13debbb3c9f9', 4, '605', true),
  ('5527c98e-3403-4203-8d6c-0710e3b89686', '2e3bc924-b52b-4121-8051-116932438076', 1, '209', false),
  ('65ef7869-d62f-470f-80d8-b7c14d233773', '2e3bc924-b52b-4121-8051-116932438076', 2, '920', false),
  ('24a25e17-bbd7-4764-b202-3be06368850f', '2e3bc924-b52b-4121-8051-116932438076', 3, '29', false),
  ('aae0ade9-8127-4fd7-8ca1-7f8377b84084', '2e3bc924-b52b-4121-8051-116932438076', 4, '290', true),
  ('d90eb8d6-339b-49f3-8c42-e9650e9552b7', '135de36a-13b2-4743-92b7-f2292508b397', 1, '500+70+2', true),
  ('218f7a78-fb7a-4f61-8fd6-2cc67dadbde6', '135de36a-13b2-4743-92b7-f2292508b397', 2, '500+7+2', false),
  ('1562be98-54c8-4439-b288-a750b83f1759', '135de36a-13b2-4743-92b7-f2292508b397', 3, '50+70+2', false),
  ('0a858041-a23e-457e-b5cd-b4656082b9a2', '135de36a-13b2-4743-92b7-f2292508b397', 4, '500+72+2', false),
  ('be28320d-86f2-4034-bfb5-6a98a5e9f7c6', 'c50e3414-c0e6-4053-9a65-b38a451e362c', 1, '400+60', false),
  ('71ad5840-439f-46c7-b00c-139dc2a71496', 'c50e3414-c0e6-4053-9a65-b38a451e362c', 2, '40+6', false),
  ('e8862274-19c6-4c5d-b818-8bf43cfbdbaa', 'c50e3414-c0e6-4053-9a65-b38a451e362c', 3, '400+6', true),
  ('71a3ada4-4268-475d-beab-e7a079166348', 'c50e3414-c0e6-4053-9a65-b38a451e362c', 4, '400+60+6', false),
  ('fc2fa835-d913-4d7f-a0e6-51df155570b8', '7f42a33f-10d9-4a54-96c9-5f12f73e0237', 1, '800+3', false),
  ('ab0f8899-90e8-4a28-a804-7fa876fb480b', '7f42a33f-10d9-4a54-96c9-5f12f73e0237', 2, '80+30', false),
  ('b4ae66c8-5fc0-4283-a3cf-f7a87ee63692', '7f42a33f-10d9-4a54-96c9-5f12f73e0237', 3, '800+30+3', false),
  ('a6084c2c-a4b5-4b00-9dbd-692d4e6280eb', '7f42a33f-10d9-4a54-96c9-5f12f73e0237', 4, '800+30', true),
  ('51fcb87d-d77c-4201-a69a-927fd5e12d95', 'cfb0057a-b980-4963-9630-727d02904c3e', 1, '7', false),
  ('735b58f5-2b41-4414-a69b-78582ac811aa', 'cfb0057a-b980-4963-9630-727d02904c3e', 2, '70', false),
  ('dec9e40a-5db7-4330-b26d-236610f2e8e4', 'cfb0057a-b980-4963-9630-727d02904c3e', 3, '700', true),
  ('63239d6c-5de5-4353-9d6d-c8615d43f0d2', 'cfb0057a-b980-4963-9630-727d02904c3e', 4, '760', false),
  ('4bcf9e34-9ec0-452c-a94a-12451a759e69', 'e0bcbacd-8014-4ab4-9e46-df227d25a04f', 1, '9', false),
  ('ce4bb6c4-4c5e-497c-b58e-5663be3514d9', 'e0bcbacd-8014-4ab4-9e46-df227d25a04f', 2, '900', false),
  ('7110d75a-fbc6-42f3-abc9-7f61edd9e64d', 'e0bcbacd-8014-4ab4-9e46-df227d25a04f', 3, '20', false),
  ('e301d273-cc16-48bf-ae83-d2327647cccb', 'e0bcbacd-8014-4ab4-9e46-df227d25a04f', 4, '90', true),
  ('e8b011e3-d3ea-4164-bbda-8997184aa542', '61720902-0df0-4b58-8470-bb251b4b6062', 1, '0', true),
  ('56ef1403-de19-4233-b683-b3c010667937', '61720902-0df0-4b58-8470-bb251b4b6062', 2, '5', false),
  ('71e3bfa1-9e43-4a87-bde2-0e583658a64f', '61720902-0df0-4b58-8470-bb251b4b6062', 3, '9', false),
  ('618e9cc1-8d0f-4ba3-9866-0d2702bf9683', '61720902-0df0-4b58-8470-bb251b4b6062', 4, '50', false),
  ('74363334-09d1-4cc5-8f8e-28c5cb364e3f', 'ffe15a79-6f93-42d3-bbcc-fa5b8b29d0b4', 1, '400+7', false),
  ('1e6c5e82-5d8a-4828-a695-f3de7fd9d59d', 'ffe15a79-6f93-42d3-bbcc-fa5b8b29d0b4', 2, '400+70', true),
  ('ee8e5d27-d78f-41a1-8b54-bbe0a093f3df', 'ffe15a79-6f93-42d3-bbcc-fa5b8b29d0b4', 3, '40+70', false),
  ('98638495-4343-4cdc-a318-7cc00e5552d7', 'ffe15a79-6f93-42d3-bbcc-fa5b8b29d0b4', 4, '400+70+7', false),
  ('232b8072-1a3d-43cb-851d-a24f05da136b', 'd35086fd-24e4-44a1-9013-590ac84ae7a9', 1, '438', false),
  ('38e1e779-a816-40df-814f-69916a956bc1', 'd35086fd-24e4-44a1-9013-590ac84ae7a9', 2, '483', true),
  ('b7d28c98-0a26-4342-9d17-28b884368a76', 'd35086fd-24e4-44a1-9013-590ac84ae7a9', 3, '두 수는 같습니다', false),
  ('115bfe1c-4c10-4f45-958b-afde22cf7410', 'd35086fd-24e4-44a1-9013-590ac84ae7a9', 4, '알 수 없습니다', false),
  ('e3b704ce-3050-4341-9b62-09c4f31e64b8', '684be076-b409-4422-a53c-fa82ccadef81', 1, '705', true),
  ('7753c30e-49e7-4d36-aa7f-7b2f741f52b6', '684be076-b409-4422-a53c-fa82ccadef81', 2, '750', false),
  ('971534c8-fff8-42d6-8e6c-df9c3c3cda96', '684be076-b409-4422-a53c-fa82ccadef81', 3, '두 수는 같습니다', false),
  ('255e9f8e-874f-4381-a8f4-a487faeabae5', '684be076-b409-4422-a53c-fa82ccadef81', 4, '알 수 없습니다', false),
  ('d39cd555-4634-4a80-b86f-54951e908cc3', '6a0b6177-848d-41be-8ee0-33c97584f654', 1, '592', false),
  ('3e965309-f182-403c-a752-85b6cf72e726', '6a0b6177-848d-41be-8ee0-33c97584f654', 2, '620', false),
  ('3b841d61-d523-43c9-8be0-f996c5489097', '6a0b6177-848d-41be-8ee0-33c97584f654', 3, '628', false),
  ('d2a7c1ec-20fd-4e4c-a584-b017510b7696', '6a0b6177-848d-41be-8ee0-33c97584f654', 4, '692', true),
  ('486be5d0-2f52-4295-a6ce-46c5360e7dcc', 'aab9216b-3e1c-4640-9344-802fedc1c218', 1, '312 → 321 → 213', false),
  ('81765c53-0f50-4b3a-81d2-6cd67bdc9897', 'aab9216b-3e1c-4640-9344-802fedc1c218', 2, '213 → 312 → 321', true),
  ('f9b74b36-7bb8-49ee-b77d-cc7470dd9d32', 'aab9216b-3e1c-4640-9344-802fedc1c218', 3, '213 → 321 → 312', false),
  ('9e4ce6cd-8684-41c9-8352-b278c8c73e19', 'aab9216b-3e1c-4640-9344-802fedc1c218', 4, '321 → 312 → 213', false),
  ('3c46c202-94da-4ca2-9ce6-bf45dae44078', '855c16ea-7bed-40f3-8566-dd9306212efc', 1, '564 → 546 → 465', true),
  ('62a0200e-594a-4d8c-b1c6-f98002edaecf', '855c16ea-7bed-40f3-8566-dd9306212efc', 2, '546 → 564 → 465', false),
  ('77876f7d-4eaa-4d9d-8e5d-b2342161d060', '855c16ea-7bed-40f3-8566-dd9306212efc', 3, '465 → 546 → 564', false),
  ('63d074fe-cb53-402c-85ee-fb9fb81e5842', '855c16ea-7bed-40f3-8566-dd9306212efc', 4, '564 → 465 → 546', false),
  ('b0523aa9-296c-4638-97b7-2a2ebdbab489', 'cb364720-372d-4cd4-832f-8c81e3f6627c', 1, '800 → 808 → 880', true),
  ('4a70d9bd-6f3d-4e2d-b303-a9b781b90203', 'cb364720-372d-4cd4-832f-8c81e3f6627c', 2, '808 → 800 → 880', false),
  ('4b89f109-055b-4712-8de9-c09b0b10a3dd', 'cb364720-372d-4cd4-832f-8c81e3f6627c', 3, '880 → 808 → 800', false),
  ('076e51a5-5e7c-47c2-9a17-ec43cdb9bf1e', 'cb364720-372d-4cd4-832f-8c81e3f6627c', 4, '800 → 880 → 808', false),
  ('41df98d9-b4a2-4286-93a5-e505a9700046', 'cb16dc05-188e-4398-961c-005bc4965faf', 1, '499', true),
  ('53b41d35-8133-4d0c-b0f0-4942cbdd3f58', 'cb16dc05-188e-4398-961c-005bc4965faf', 2, '501', false),
  ('9dcb7639-d697-45e7-bfd8-fa214d756f1c', 'cb16dc05-188e-4398-961c-005bc4965faf', 3, '490', false),
  ('5612898f-2718-4eb3-bcdf-649574396d20', 'cb16dc05-188e-4398-961c-005bc4965faf', 4, '400', false),
  ('ae6dcae9-abcf-42b6-8b1d-8ed97e4123b1', '0d5a52ef-ef0b-4987-b7ce-d074ff26d762', 1, '798', false),
  ('ca30bafb-cdca-41a5-90df-d785174c88fd', '0d5a52ef-ef0b-4987-b7ce-d074ff26d762', 2, '790', false),
  ('9644c3d3-229e-4d8e-aedd-c784d5fc2c8f', '0d5a52ef-ef0b-4987-b7ce-d074ff26d762', 3, '800', true),
  ('25c6d4e7-0599-4960-b665-1ebc0688cac9', '0d5a52ef-ef0b-4987-b7ce-d074ff26d762', 4, '899', false),
  ('7704f91b-6a8d-4725-bcdc-43091a887472', 'a0d84d53-0a52-4837-8601-41b4d7463441', 1, '335', false),
  ('2b87a589-f4d3-4d8b-8271-1aee9e82b6d3', 'a0d84d53-0a52-4837-8601-41b4d7463441', 2, '340', true),
  ('d88a1f39-a664-4a36-8b1a-50b8ad0684a1', 'a0d84d53-0a52-4837-8601-41b4d7463441', 3, '345', false),
  ('ee60fad6-bca2-41e9-b619-1cb0b4a5c83c', 'a0d84d53-0a52-4837-8601-41b4d7463441', 4, '360', false),
  ('8c41d846-cf14-4850-955b-1d94a0acf48d', '5d1da955-d9e2-44f4-a5ef-8005e56be778', 1, '906', false),
  ('3468c0d4-0798-4f36-9ac5-515340f111b9', '5d1da955-d9e2-44f4-a5ef-8005e56be778', 2, '908', false),
  ('c7102c58-b5b0-4ef0-a46c-9583d190e9df', '5d1da955-d9e2-44f4-a5ef-8005e56be778', 3, '910', true),
  ('efce1265-281f-4884-ba96-8e288305c46d', '5d1da955-d9e2-44f4-a5ef-8005e56be778', 4, '925', false),
  ('8ffb6318-adda-4457-b592-6b20e3760d45', '463be537-521e-4655-8298-c3d647ec5694', 1, '442', true),
  ('062dc9c1-5495-472e-8366-ceec2f53c05e', '463be537-521e-4655-8298-c3d647ec5694', 2, '452', false),
  ('6bd1fff6-ff21-40ad-9444-1017b146a7b5', '463be537-521e-4655-8298-c3d647ec5694', 3, '462', false),
  ('51f06edf-013d-4231-bf3a-deb611db98c3', '463be537-521e-4655-8298-c3d647ec5694', 4, '432', false),
  ('c864f71a-d92c-48a1-90fb-afabf04245f7', 'b79b2ebe-3137-42e5-aadd-0711d2364b08', 1, '654', false),
  ('027dcaf8-b7d8-42f4-b6d7-af6a49b02b3e', 'b79b2ebe-3137-42e5-aadd-0711d2364b08', 2, '645', true),
  ('12d6f81c-bbee-431a-97a9-dc6822f8d196', 'b79b2ebe-3137-42e5-aadd-0711d2364b08', 3, '634', false),
  ('b3ba38d7-3554-4684-a9f0-a6c6c519f2f7', 'b79b2ebe-3137-42e5-aadd-0711d2364b08', 4, '643', false),
  ('664ba395-7842-45f1-a6ab-7e5c2d9fb0c2', 'dd91a344-f3e7-4084-ac0b-a2b4aa835633', 1, '638', false),
  ('5aef6f03-94c2-4f19-bf0c-91c55ae04aa8', 'dd91a344-f3e7-4084-ac0b-a2b4aa835633', 2, '683', false),
  ('203761f6-909a-432a-838a-ae3a3d47a099', 'dd91a344-f3e7-4084-ac0b-a2b4aa835633', 3, '836', true),
  ('d77e72d1-3009-45b4-959f-3965d53b3fb3', 'dd91a344-f3e7-4084-ac0b-a2b4aa835633', 4, '863', false),
  ('651ae889-0777-444e-8ea4-e61307196ba8', '29c53182-563c-4465-a4fa-bc4af7f0853b', 1, '047', false),
  ('9969ac21-42dc-4562-9175-c45d5a92b965', '29c53182-563c-4465-a4fa-bc4af7f0853b', 2, '470', false),
  ('3bef1f1b-1f64-46ca-b5bd-2abb152cc64a', '29c53182-563c-4465-a4fa-bc4af7f0853b', 3, '704', false),
  ('ba09ae27-2358-490b-af82-2a46bf3c28c2', '29c53182-563c-4465-a4fa-bc4af7f0853b', 4, '407', true),
  ('19d95115-d247-408b-bed3-7b2aaffc8a8a', '1528bab3-d29c-419e-ad04-f311e8aeb846', 1, '420보다 크고 430보다 작습니다.', true),
  ('a2247db0-4400-4c5c-956e-f20d6687bbaa', '1528bab3-d29c-419e-ad04-f311e8aeb846', 2, '470보다 크고 480보다 작습니다.', false),
  ('66cb87a7-a22a-4fe9-b606-c4afd0626dd4', '1528bab3-d29c-419e-ad04-f311e8aeb846', 3, '백의 자리 숫자가 2입니다.', false),
  ('b9b8e099-6b1a-4d34-af54-685af19c6050', '1528bab3-d29c-419e-ad04-f311e8aeb846', 4, '472보다 큽니다.', false),
  ('d5ce7866-2d19-47c1-b7ae-9c7974283439', 'f8c47bf1-e8a1-4c3a-9b4c-b78f5307f4c1', 1, '6', false),
  ('830c8924-4807-40c6-9d48-3c5abe57c0ad', 'f8c47bf1-e8a1-4c3a-9b4c-b78f5307f4c1', 2, '8', true),
  ('dc7e189e-71b8-4b4e-811c-73a6cbb09c70', 'f8c47bf1-e8a1-4c3a-9b4c-b78f5307f4c1', 3, '4', false),
  ('114fa42e-0149-4f92-becb-e91f8b05ef08', 'f8c47bf1-e8a1-4c3a-9b4c-b78f5307f4c1', 4, '2', false),
  ('3a8c0167-d41b-4be2-b227-6758565f356c', 'd9b6e341-7437-47e9-97fc-7bb9dbcd931e', 1, '100개 묶음 3개와 10개 묶음 2개', false),
  ('cda1fc49-8fdd-4f11-abb2-3625a4f54cbd', 'd9b6e341-7437-47e9-97fc-7bb9dbcd931e', 2, '100개 묶음 3개와 10개 묶음 12개', false),
  ('bebb3ecc-ddf7-400d-9398-3351e17638c4', 'd9b6e341-7437-47e9-97fc-7bb9dbcd931e', 3, '100개 묶음 4개와 10개 묶음 2개', true),
  ('a3b98a0a-dc6c-47fe-959f-32d5fad60657', 'd9b6e341-7437-47e9-97fc-7bb9dbcd931e', 4, '100개 묶음 4개와 10개 묶음 12개', false),
  ('6e81fb46-6e55-4765-a6b7-5b2379acc984', '1311529f-6cfd-4e86-8f69-2003816ed4bc', 1, '100개 묶음 5개', true),
  ('be3fab36-1ab9-45a6-a06e-188174884468', '1311529f-6cfd-4e86-8f69-2003816ed4bc', 2, '100개 묶음 4개와 10개 묶음 9개', false),
  ('2043397a-55a0-4551-84d8-c90d703329aa', '1311529f-6cfd-4e86-8f69-2003816ed4bc', 3, '100개 묶음 4개와 낱개 10개', false),
  ('99b0a0dc-d83a-46e2-bf8b-1489ce4c6f37', '1311529f-6cfd-4e86-8f69-2003816ed4bc', 4, '100개 묶음 5개와 10개 묶음 1개', false),
  ('e99280be-9024-431a-899a-cec925619cbf', '81025ee1-0713-452e-b075-43427981ca8b', 1, '5는 백의 자리이고 7은 십의 자리이므로 570입니다.', false),
  ('182e6c76-4ebf-4f49-99ab-1d327e463a9b', '81025ee1-0713-452e-b075-43427981ca8b', 2, '0인 자리는 지워도 되므로 57이 맞습니다.', false),
  ('71823cd7-8600-43b8-9563-276f8e716782', '81025ee1-0713-452e-b075-43427981ca8b', 3, '0은 일의 자리가 없다는 뜻이므로 500입니다.', false),
  ('0e412d7f-1f5c-4bfa-9395-5a9f8ec9656a', '81025ee1-0713-452e-b075-43427981ca8b', 4, '0은 십이 없다는 뜻이지만 7은 일의 자리에 남으므로 507입니다.', true),
  ('552ead57-d823-4be1-afb2-91774f82533f', '7fa874b1-15d0-401f-bcb3-45b1902d1f63', 1, '일의 자리 9가 2보다 크므로 619가 더 큽니다.', false),
  ('3cec4b35-6b83-4d5e-bc0e-3c2102709902', '7fa874b1-15d0-401f-bcb3-45b1902d1f63', 2, '백의 자리는 같고 십의 자리 8이 1보다 크므로 682가 더 큽니다.', true),
  ('487d6df1-03fb-4e9a-bdde-9933f99b7aa6', '7fa874b1-15d0-401f-bcb3-45b1902d1f63', 3, '백의 자리 6이 같으므로 두 수의 크기는 같습니다.', false),
  ('4fd24492-9f0d-4480-a130-a2b842dd9f02', '7fa874b1-15d0-401f-bcb3-45b1902d1f63', 4, '십의 자리보다 일의 자리를 먼저 비교해야 합니다.', false);

select (public.publish_learning_content_version('376377cb-4093-4f29-bc92-5ca42b27a726'::uuid)).id;

commit;
