-- Generated by scripts/generate-learning-content-migration.js.
-- Source: content/learning/math/grade2-shapes-v1.json
-- Canonical content SHA-256: 3e8d5602fce5d8722f535d633aa71a4628b2b36b7c95b208ce2bb1f6d5e5446e
-- Content-only and additive: no assignment, attempt, progress, first-pass, ledger, ACL, or Realtime changes.

begin;

do $preflight$
begin
  if exists (
    select 1 from public.learning_courses
    where (id = '51000000-0000-4000-8000-000000000001'::uuid or course_code = 'math-core')
      and not (
        id = '51000000-0000-4000-8000-000000000001'::uuid
        and course_code = 'math-core'
        and internal_name = '수학 기초 과정'
        and subject_name = '수학'
      )
  ) then
    raise exception using errcode = '23505', message = 'grade2_shapes_v1 course identifier conflicts with different content';
  end if;

  if not exists (
    select 1 from public.learning_courses
    where id = '51000000-0000-4000-8000-000000000001'::uuid
      and course_code = 'math-core'
      and internal_name = '수학 기초 과정'
      and subject_name = '수학'
      and status = 'published'
  ) then
    raise exception using errcode = 'P0002', message = 'grade2_shapes_v1 existing course is missing or changed';
  end if;

  if exists (
    select 1 from public.learning_units
    where id = 'd70914da-44d5-45a5-8f6f-3354227c0ee0'::uuid
       or unit_code = 'grade2-shapes'
  ) then
    raise exception using errcode = '23505', message = 'grade2_shapes_v1 unit identifier already exists';
  end if;

  if exists (
    select 1 from public.learning_units
    where course_id = '51000000-0000-4000-8000-000000000001'::uuid
      and sort_order = 3
  ) then
    raise exception using errcode = '23505', message = 'grade2_shapes_v1 unit sort order already exists';
  end if;

  if to_regclass('public.learning_unit_recommendation_metadata') is null then
    raise exception using errcode = 'P0002', message = 'learning recommendation metadata table is missing';
  end if;

  if exists (
    select 1
    from public.learning_unit_recommendation_metadata metadata
    where metadata.unit_id = 'd70914da-44d5-45a5-8f6f-3354227c0ee0'::uuid
      and (
        metadata.subject is distinct from 'math'
        or metadata.recommended_start_level_code is distinct from 'elementary_2'
        or metadata.recommended_end_level_code is distinct from 'elementary_2'
        or metadata.parent_sort_order is distinct from 2
      )
  ) then
    raise exception using errcode = '23505', message = 'learning unit recommendation metadata conflicts with different content';
  end if;

  if to_regclass('public.learning_skill_definitions') is null
     or to_regclass('public.learning_question_skills') is null then
    raise exception using errcode = 'P0002', message = 'learning skill metadata foundation is missing';
  end if;

  if exists (
    select 1
    from (values
  ('identify-plane-shape'),
  ('identify-solid-shape'),
  ('connect-object-to-shape'),
  ('classify-shapes'),
  ('describe-shape-properties'),
  ('compose-decompose-shapes'),
  ('infer-shape-from-properties'),
  ('correct-shape-reasoning')
    ) expected_skill(skill_code)
    where not exists (
      select 1 from public.learning_skill_definitions definition
      where definition.skill_code = expected_skill.skill_code
    )
  ) then
    raise exception using errcode = 'P0002', message = 'learning skill definition is missing';
  end if;

  if exists (
    select 1 from public.learning_content_versions
    where id = '8a600f52-61e6-4d6c-b6d0-b1f524b42df6'::uuid
       or content_hash = '3e8d5602fce5d8722f535d633aa71a4628b2b36b7c95b208ce2bb1f6d5e5446e'
  ) then
    raise exception using errcode = '23505', message = 'grade2_shapes_v1 content version already exists';
  end if;

  if exists (
    select 1 from (
      values
  ('c2339c35-8f13-4216-b2f7-4863e78f5e40'::uuid),
  ('af405f9e-df43-4527-b86f-9c4b63710601'::uuid),
  ('8eb84449-513b-42d9-8621-e99cf6277211'::uuid),
  ('c5117f97-4db5-4e8e-80a9-4a2126d90c6b'::uuid),
  ('87022f21-6038-4d55-9589-020bb261be67'::uuid),
  ('9ea72704-775a-46bf-9960-e1929cb31e34'::uuid),
  ('67d77a67-e13f-41c9-a63e-08356c4ba2f1'::uuid),
  ('ecb58153-936c-4a35-806e-929623dbd461'::uuid),
  ('2333208b-609d-4a5f-9a18-5fd89535251d'::uuid),
  ('9295dfa9-b265-4585-bf04-f34e1df6c381'::uuid),
  ('cedf957f-4c7d-4e2c-a394-1e72d91b9348'::uuid),
  ('8cd899c7-3ee4-44bd-bf51-befaa3d442fc'::uuid),
  ('d1f283a4-8edd-4e44-9ca8-672339699bdd'::uuid),
  ('52858e30-18b9-44be-9fcc-1d0b72511f74'::uuid),
  ('9b0c21ed-f0c7-47dd-b5c8-8f239b2b673a'::uuid),
  ('4d6bf528-80a5-40e0-a34d-581d0c166008'::uuid),
  ('79fde641-4f4a-41de-ab03-f953633a354e'::uuid),
  ('a8a0c74c-98cd-4125-be28-161badc9526b'::uuid),
  ('c9a671c3-c3e5-47c5-8da3-9b2986ef8186'::uuid),
  ('1cbcdf92-5a50-4027-8f16-d92cbd927c37'::uuid),
  ('b64801bd-1a16-41d0-b6e1-562aebb2b300'::uuid),
  ('6ff56548-4b0d-4fab-a06f-a884bb5d5515'::uuid),
  ('120bb469-7754-4975-90db-18817d3dfad3'::uuid),
  ('99e42892-f147-405a-81ea-370843ac71b4'::uuid),
  ('a194dd17-4984-4883-9e14-be827a5ad301'::uuid),
  ('6b797cf0-f0c7-484a-abd3-b6c1a7a303be'::uuid),
  ('a709ffed-9816-4082-8343-6a69c46f6882'::uuid),
  ('424eebfd-91dc-4dfc-964e-7725baeab501'::uuid),
  ('699d83ae-fb53-4a6b-8b42-722cbf45501c'::uuid),
  ('9153a8b7-eec8-426b-aee7-0334b98c5193'::uuid),
  ('ffd1bd60-cb57-461f-86be-4781084461cd'::uuid),
  ('e3563ab4-8d03-4817-a8d2-6835f2c487b7'::uuid),
  ('336b4350-d2a6-4dcf-a846-22392be148e2'::uuid),
  ('0c45bf1f-7b95-47ac-80f5-fa4b5ad41638'::uuid),
  ('67caac36-ec06-4526-ba7b-aba23dae5e06'::uuid),
  ('269c929d-b257-4a79-88e5-eb544ff72259'::uuid),
  ('3b4bdd4f-89c7-4249-8b78-a033112a1fd1'::uuid),
  ('dc28638b-23c3-491c-a872-58a9c1aa6761'::uuid),
  ('7059592e-a734-43a9-a618-311555049e23'::uuid),
  ('aadae9c6-c3f4-42d8-a620-f24fd5367e66'::uuid),
  ('08a8a211-6d93-4990-84ec-a70e1fd30c31'::uuid),
  ('325a3aba-91cf-4a8b-a790-5e99e9622d06'::uuid),
  ('eabb7c04-5eed-434a-8249-3c32017e2752'::uuid),
  ('ea03478f-8770-44db-ac13-5dd37aedd7de'::uuid),
  ('2cea5aac-20d3-4b22-83d2-a608f8d41919'::uuid),
  ('6fc35960-d34d-4628-83d0-ce16e22a6147'::uuid),
  ('ebc3f2dd-3fa7-4126-84fb-721ef3d0cd2d'::uuid),
  ('83b4231f-4620-45e2-a848-e4243c6d26b8'::uuid),
  ('57846c82-d1f1-4022-b11b-fa9067a71183'::uuid),
  ('0bd79e1b-9e0c-4f4f-a241-9ad15cd4f78a'::uuid),
  ('bfd34ea9-4777-4491-89ea-f9b5f0aa13de'::uuid),
  ('672e15db-bd99-41ba-8f8e-f93f3c901960'::uuid),
  ('27edab53-7c18-4c11-a8b4-d5aaef011a3d'::uuid),
  ('25b404c8-a88a-4b58-8933-77cbfc274f2d'::uuid),
  ('c81fc007-a0b1-4fde-9d81-58c53d50af4c'::uuid),
  ('79fba679-bd19-4c20-b434-be9014ffb1e3'::uuid),
  ('2026ceff-0086-471b-af0c-a71b0adad44e'::uuid),
  ('c09b924e-bda6-4af7-9d3a-0745229422eb'::uuid),
  ('0b8d3f7f-88a4-49f7-9830-7f51fb54bb8d'::uuid),
  ('0d938fe9-9d00-495a-b5cc-ebe04bb7d8d5'::uuid),
  ('0dbffac2-8e2b-4997-a63d-9cd5ee132e6e'::uuid),
  ('81d33706-1268-41ed-b50d-5c2178dde95f'::uuid),
  ('b7003b2b-00dd-4a28-a2d9-559bc49fadb0'::uuid),
  ('d2ed35af-c4f7-413d-8af6-ba4fc1fa020f'::uuid),
  ('f558f5af-76a0-4059-9a8a-88069e908927'::uuid),
  ('a70537b5-ef87-445c-a274-b6fc24c6e5a6'::uuid),
  ('d0c1b3b8-cf75-4d17-8cae-27fb50323548'::uuid),
  ('ef41c35f-e1aa-48a5-a7f8-e994d6959390'::uuid),
  ('5865fc14-5d2b-410a-b4ba-ef40292577e7'::uuid),
  ('c3b81fc6-f4a7-440e-90b9-27c7acfd0fe2'::uuid),
  ('8f780245-2045-45b7-bfae-37f18fc2f7d8'::uuid),
  ('85bea504-d3a4-4038-890c-07802287561f'::uuid),
  ('8de1a06d-e62e-45a9-9733-5fc8691072d4'::uuid),
  ('b3180161-12fa-489c-b994-cdc1cc034d3d'::uuid),
  ('1679b4f7-35af-4868-aac4-4a27f3b7aa9d'::uuid),
  ('aca48a8d-aee5-49c1-a81c-4a5824ed1311'::uuid),
  ('cb09f775-5576-4d4d-ba02-3f6696efbe84'::uuid),
  ('07b528a4-e899-40b0-8ace-a727de657beb'::uuid),
  ('f543d762-b36a-4b7a-8a27-1003ad6f8ba9'::uuid),
  ('6bf17ead-e1e1-4aec-b480-b803d7e0abce'::uuid),
  ('e2eb74ac-c6a8-4111-9d0b-7dbc397c3185'::uuid),
  ('d0382095-20a2-48a1-90f6-444c2eccd9f2'::uuid),
  ('af5843c7-9a35-4d24-b6f1-cd129ca094ed'::uuid),
  ('10f5c439-da4e-4efd-bf45-c165c1de81a9'::uuid),
  ('6e4065d0-649f-4aed-b973-21bedaef5706'::uuid),
  ('b15f4345-a7d7-4aa5-ace4-7e4aca41b227'::uuid),
  ('d36e5000-b88b-49b3-ba25-40d1bdd62845'::uuid),
  ('8308fca8-5e7f-40bb-a12e-218a858b5408'::uuid),
  ('7f59c1e8-e862-4fb6-9cf8-bb161a964403'::uuid),
  ('49ad59a4-07e8-49a0-bc14-668e771a3f00'::uuid),
  ('d7bc1b85-e97f-433c-a492-45cd360a4efd'::uuid),
  ('b1063f6e-5a4b-4652-8952-e165aa8a9367'::uuid),
  ('704493ab-7bdb-4e28-9734-9c64e169e5b6'::uuid),
  ('7ab93a67-5435-46ae-8657-21aee2f6100a'::uuid),
  ('31ba56a0-8707-4da5-ae64-ea645f0efb75'::uuid),
  ('35fb58cf-6bd8-4299-9044-53101a6cb557'::uuid),
  ('466ff45e-46a5-47d6-b665-82b62a25ef6d'::uuid),
  ('c8e989ce-e55f-4925-9db0-eb2eca1b4070'::uuid),
  ('e97d7c11-3c1d-4c86-ad43-f1b01a455963'::uuid),
  ('0d87f9f0-06b6-4da1-b7b7-14611745cc2a'::uuid),
  ('630cc3d2-e031-4c60-976b-68069f5aeff8'::uuid),
  ('91250dcf-78da-4f74-8cd4-0a060fb755df'::uuid),
  ('c7e69392-8d14-419d-8de8-3cd86f17ae61'::uuid),
  ('9b468ad1-5225-4e57-9a0e-793406327657'::uuid),
  ('1315f3e0-31a3-465d-b471-be20503d6ec6'::uuid),
  ('810a4bbb-cb8e-49bb-b9b5-820bafad416a'::uuid),
  ('6b779d0b-0e56-4b7b-a286-b32bf6623ca1'::uuid),
  ('8919b7fd-c21e-4fb5-be13-e882e242d9c4'::uuid),
  ('9efc5b2a-c2c6-41fc-a2bb-34139d49d44d'::uuid),
  ('a2eb32fb-511b-4992-8fe5-9cb43c0cfbce'::uuid),
  ('3344699a-e2e5-43f5-9198-dab24a985290'::uuid),
  ('f76ed2b7-9071-4a32-a1f5-22ec66ff4c31'::uuid),
  ('be712a28-a4f1-46f5-933c-cdf67af460cf'::uuid),
  ('01bbb6cb-28da-4ed5-a3f9-56e724a7a263'::uuid),
  ('f5c52932-3168-470c-b20c-a9b0e2606c3b'::uuid),
  ('50e87e69-84b9-45a7-81bb-648ba2e1617f'::uuid),
  ('e2e4c5c6-f04d-4152-a0be-b102954f7b40'::uuid),
  ('39ad8311-db90-4fa5-b638-2d23c2ff6110'::uuid),
  ('6ec35cc5-8127-480d-970c-66ac9d3b6db4'::uuid),
  ('4d40cebd-7010-4672-b6c9-41fe351388a2'::uuid),
  ('8b4f783c-0196-4a90-be60-edfc83391bef'::uuid),
  ('cee5b725-42dd-4f95-83c3-af69326c813f'::uuid),
  ('6f92a055-a9f3-4181-be1a-897e6882ba59'::uuid),
  ('f4b6ea39-c146-4454-9684-920e1789f5a1'::uuid),
  ('c47f348f-1eac-40f6-bd60-47a50be3aec3'::uuid),
  ('be2e7f70-c999-4666-9d51-0f16e9d6abf7'::uuid),
  ('749062c3-d994-4189-a174-db4955a44ff8'::uuid),
  ('13c20060-f96b-45c8-8e5b-143c18943995'::uuid),
  ('a6312f72-6e03-42f5-86e9-8b3027c1b49a'::uuid),
  ('30ce16ba-52de-47da-b407-1b8f131de510'::uuid),
  ('bb6f396d-5f5e-4f7f-898a-20bb59dee31a'::uuid),
  ('6b5dad0a-44ed-42b6-b697-10b89332acf0'::uuid),
  ('c5e8ef40-303f-43cd-a66e-049ded8dc7c4'::uuid),
  ('199f8a0d-5057-431f-a94a-3e81e227199e'::uuid),
  ('4e7365b5-ba4a-4d15-b70a-b6eb76450549'::uuid),
  ('b1a795e6-5813-4c68-9c7c-958a02d1c903'::uuid),
  ('0c322f90-048e-43bb-9484-c462eb62c687'::uuid),
  ('8fd1beaf-f852-4c33-88e1-e9c332e6e7e7'::uuid),
  ('b8fc63b0-b4f4-451a-a69b-b140b5867fc0'::uuid),
  ('60506006-2ef3-4206-b209-bf14cc29351f'::uuid),
  ('da115a0e-e860-4a79-8356-ca6613b2a75f'::uuid),
  ('9a19e506-51c7-4327-b2da-fa0ff66f55a2'::uuid),
  ('2d1886b9-90f4-461f-98dd-e72d241c4107'::uuid),
  ('ce0841c2-d961-41f4-aa12-1201b789a717'::uuid),
  ('b3e586b2-c767-4682-ac2d-baecbaf67f85'::uuid),
  ('27d55ba7-3b01-4ee1-b7b3-d095106d15ac'::uuid),
  ('82b440a9-080e-474f-9fa7-9c9e8abebb33'::uuid),
  ('bb4e18fc-6db1-40e4-a725-c4241aba6ffd'::uuid),
  ('03133869-45e4-400f-b551-6c40867de9e5'::uuid),
  ('e3a1add8-6aea-4d2f-9e2d-7aa8f5cd06b9'::uuid),
  ('b7527e50-0da6-4d41-8842-ecc57b7f733c'::uuid),
  ('ffd3afdf-61c4-4675-8d7a-7c7287d44189'::uuid),
  ('46601f4c-061c-4d8e-a603-63ec88cf5722'::uuid),
  ('651a5b53-d8a4-4fac-9ae1-75b01e95caeb'::uuid),
  ('8baf4afd-7bcc-4ce2-a594-a1f76ffcdf79'::uuid),
  ('ae0d5619-a220-4fef-8f43-8b821e9677ad'::uuid),
  ('08f703fb-a3bd-4e1b-9c83-fa3d35c33276'::uuid),
  ('36dd43bd-56c5-4ada-86cc-3d7486dc0fc5'::uuid),
  ('efd2d88d-85cf-42aa-91fa-47a9b8bfcae4'::uuid),
  ('49efe0dd-296e-4962-adbb-c17d100cb6b4'::uuid),
  ('fa4f7e1d-208d-451c-a5f7-bfe4ceaa52a2'::uuid),
  ('8c9c04ee-b40c-4824-90af-3d1fbed7f807'::uuid),
  ('0fab5cf7-88eb-4cdb-97e1-c810256c84e7'::uuid),
  ('e6e70085-42e9-4fd4-b7ca-79f3d2515f48'::uuid),
  ('20c144e8-e143-4aa1-afeb-4c6905f6af1c'::uuid),
  ('75665ddc-8df7-4b78-a2a3-74df08f70abe'::uuid),
  ('879e81a0-c38b-4b8f-9028-b5b754ae72f0'::uuid),
  ('de9dd70a-8937-4924-904c-98d344b5f91a'::uuid),
  ('02decf8e-2cb8-42d9-8aab-e6de66f52330'::uuid),
  ('4df34e6d-05f5-4143-813a-c2fb03ebb110'::uuid),
  ('c069d5c3-d885-48dd-bd10-e80a67d76b9c'::uuid),
  ('8e6b6936-eac4-4612-8b9f-9783c80c6015'::uuid),
  ('b66bafd3-d244-42ce-ae61-a99dce17dd62'::uuid),
  ('1bfe4785-ffc5-4004-9a22-b5ddc228ab46'::uuid),
  ('1b11b056-1bd1-463c-87b1-ca1989408369'::uuid),
  ('c6c06a1a-3ee7-4036-9020-b9028b4dd8f5'::uuid),
  ('a61f3a5d-5b1a-4f24-912a-eb014ae472fc'::uuid),
  ('b95b3b8c-3304-4532-a15c-b6bcfe173f72'::uuid),
  ('43048f0b-9f18-4b38-9393-b68ef1bfca15'::uuid),
  ('d2b6ff4a-1d66-4adf-baa0-a0558ddad3cd'::uuid),
  ('77906861-534a-4584-9536-dd0080220773'::uuid),
  ('3a822aae-2362-4b8c-965b-7e81248ceb85'::uuid),
  ('c76e8d0c-48c7-47a6-863e-c6be11676e03'::uuid),
  ('a62afe9b-89a6-42ef-96f6-8edfc8a56171'::uuid),
  ('c5799f51-251b-49e7-9d0b-9c1cbd2c08df'::uuid),
  ('6e9d20fe-129b-47ac-9cf6-b5aaeb050209'::uuid),
  ('81696b09-8706-4f77-935f-e05c41b3c79c'::uuid),
  ('98ce356e-aec0-42ef-91b6-8547e33ba499'::uuid),
  ('c6cd8885-e32f-493e-8277-437fb65b5f02'::uuid),
  ('c0d984ea-ac1f-4f7c-8264-8c2738be0e93'::uuid),
  ('85a0e473-85a5-4dd3-a71f-c4c2f2d3782d'::uuid),
  ('3a8ee3af-7b4c-4f28-9dea-2de04d5394e3'::uuid),
  ('5f7eff16-fbfa-4e10-9675-6a3efe79a952'::uuid),
  ('6650d75b-6529-44f3-85d9-c59bc0004a9b'::uuid),
  ('e1c7222d-bcc2-4b36-a0c0-c2d811224d21'::uuid),
  ('39fc8d77-2970-4778-9807-b6e6ae00e49e'::uuid),
  ('7356cc79-63d9-4d40-831b-503b13631f93'::uuid),
  ('681e03d1-f133-4e83-bee4-1208a8d942e0'::uuid),
  ('096d9a6d-49ef-403f-910d-5fe3ee8ae87f'::uuid),
  ('43ddc94b-c06b-45e9-8b71-249baab22762'::uuid),
  ('6a2aea19-a0c4-4740-b395-d7b35226502d'::uuid),
  ('adaa8e60-b130-48ce-891f-c6aa7fb9f156'::uuid),
  ('3264c093-250f-4155-ab24-84fca2556e88'::uuid),
  ('8547eae1-5ce0-438c-a281-cbfced5b8547'::uuid)
    ) as expected_id(id)
    where exists (
      select 1 from public.learning_stages where id = expected_id.id
      union all
      select 1 from public.learning_questions where id = expected_id.id
      union all
      select 1 from public.learning_question_options where id = expected_id.id
    )
  ) then
    raise exception using errcode = '23505', message = 'grade2_shapes_v1 child content identifier already exists';
  end if;
end
$preflight$;

insert into public.learning_units (id, course_id, unit_code, display_title, sort_order)
values ('d70914da-44d5-45a5-8f6f-3354227c0ee0', '51000000-0000-4000-8000-000000000001', 'grade2-shapes', '여러 가지 모양을 찾아요', 3);

insert into public.learning_unit_recommendation_metadata (
  unit_id, subject, recommended_start_level_code, recommended_end_level_code, parent_sort_order
)
select 'd70914da-44d5-45a5-8f6f-3354227c0ee0'::uuid, 'math', 'elementary_2', 'elementary_2', 2
where not exists (
  select 1
  from public.learning_unit_recommendation_metadata metadata
  where metadata.unit_id = 'd70914da-44d5-45a5-8f6f-3354227c0ee0'::uuid
);

insert into public.learning_content_versions (id, unit_id, version_no, content_hash)
values ('8a600f52-61e6-4d6c-b6d0-b1f524b42df6', 'd70914da-44d5-45a5-8f6f-3354227c0ee0', 1, '3e8d5602fce5d8722f535d633aa71a4628b2b36b7c95b208ce2bb1f6d5e5446e');

insert into public.learning_stages (id, content_version_id, display_order, display_title, difficulty)
values
  ('c2339c35-8f13-4216-b2f7-4863e78f5e40', '8a600f52-61e6-4d6c-b6d0-b1f524b42df6', 1, '입문', 'seed'),
  ('af405f9e-df43-4527-b86f-9c4b63710601', '8a600f52-61e6-4d6c-b6d0-b1f524b42df6', 2, '기초', 'leaf'),
  ('8eb84449-513b-42d9-8621-e99cf6277211', '8a600f52-61e6-4d6c-b6d0-b1f524b42df6', 3, '심화', 'tree'),
  ('c5117f97-4db5-4e8e-80a9-4a2126d90c6b', '8a600f52-61e6-4d6c-b6d0-b1f524b42df6', 4, '최상위 도전!', 'crown');

insert into public.learning_questions (id, stage_id, display_order, prompt, explanation)
values
  ('87022f21-6038-4d55-9589-020bb261be67', 'c2339c35-8f13-4216-b2f7-4863e78f5e40', 1, '곧은 선 3개로 둘러싸인 평면 모양은?', '세모 모양은 곧은 선 3개로 둘러싸여 있습니다.'),
  ('9ea72704-775a-46bf-9960-e1929cb31e34', 'c2339c35-8f13-4216-b2f7-4863e78f5e40', 2, '곧은 선 4개로 둘러싸인 평면 모양은?', '네모 모양은 곧은 선 4개로 둘러싸여 있습니다.'),
  ('67d77a67-e13f-41c9-a63e-08356c4ba2f1', 'c2339c35-8f13-4216-b2f7-4863e78f5e40', 3, '굽은 선으로 둘러싸이고 뾰족한 곳이 없는 평면 모양은?', '동그라미 모양은 굽은 선으로 둘러싸이고 뾰족한 곳이 없습니다.'),
  ('ecb58153-936c-4a35-806e-929623dbd461', 'c2339c35-8f13-4216-b2f7-4863e78f5e40', 4, '평면 모양이 아닌 것은?', '공 모양은 공간을 차지하는 입체 모양입니다.'),
  ('2333208b-609d-4a5f-9a18-5fd89535251d', 'c2339c35-8f13-4216-b2f7-4863e78f5e40', 5, '축구공과 가장 닮은 입체 모양은?', '축구공은 어느 쪽에서 보아도 둥근 공 모양과 닮았습니다.'),
  ('9295dfa9-b265-4585-bf04-f34e1df6c381', 'c2339c35-8f13-4216-b2f7-4863e78f5e40', 6, '주사위와 가장 닮은 입체 모양은?', '주사위는 평평한 네모 모양의 면들로 둘러싸인 상자 모양입니다.'),
  ('cedf957f-4c7d-4e2c-a394-1e72d91b9348', 'c2339c35-8f13-4216-b2f7-4863e78f5e40', 7, '음료수 캔과 가장 닮은 입체 모양은?', '음료수 캔은 위아래가 평평하고 옆이 굽은 통 모양입니다.'),
  ('8cd899c7-3ee4-44bd-bf51-befaa3d442fc', 'c2339c35-8f13-4216-b2f7-4863e78f5e40', 8, '입체 모양끼리 짝 지은 것은?', '상자 모양과 공 모양은 모두 공간을 차지하는 입체 모양입니다.'),
  ('d1f283a4-8edd-4e44-9ca8-672339699bdd', 'c2339c35-8f13-4216-b2f7-4863e78f5e40', 9, '네모난 창문 테두리에서 찾을 수 있는 평면 모양은?', '창문 테두리의 바깥선을 보면 네모 모양을 찾을 수 있습니다.'),
  ('52858e30-18b9-44be-9fcc-1d0b72511f74', 'c2339c35-8f13-4216-b2f7-4863e78f5e40', 10, '세모난 교통 표지판에서 찾을 수 있는 평면 모양은?', '표지판의 바깥선이 곧은 선 3개로 이어져 세모 모양입니다.'),
  ('9b0c21ed-f0c7-47dd-b5c8-8f239b2b673a', 'af405f9e-df43-4527-b86f-9c4b63710601', 1, '세모 모양을 둘러싼 곧은 선은 몇 개인가요?', '세모 모양은 곧은 선 3개로 둘러싸여 있습니다.'),
  ('4d6bf528-80a5-40e0-a34d-581d0c166008', 'af405f9e-df43-4527-b86f-9c4b63710601', 2, '네모 모양에서 두 곧은 선이 만나는 곳은 몇 개인가요?', '네모 모양에는 두 곧은 선이 만나는 곳이 4개 있습니다.'),
  ('79fde641-4f4a-41de-ab03-f953633a354e', 'af405f9e-df43-4527-b86f-9c4b63710601', 3, '동그라미 모양의 특징으로 알맞은 것은?', '동그라미 모양의 둘레는 굽은 선 하나로 이어져 있습니다.'),
  ('a8a0c74c-98cd-4125-be28-161badc9526b', 'af405f9e-df43-4527-b86f-9c4b63710601', 4, '통 모양의 특징으로 알맞은 것은?', '통 모양에는 위아래의 평평한 면과 옆의 굽은 면이 있습니다.'),
  ('c9a671c3-c3e5-47c5-8da3-9b2986ef8186', 'af405f9e-df43-4527-b86f-9c4b63710601', 5, '평면 모양만 모은 것은?', '세모 모양과 동그라미 모양은 모두 평면에서 찾는 모양입니다.'),
  ('1cbcdf92-5a50-4027-8f16-d92cbd927c37', 'af405f9e-df43-4527-b86f-9c4b63710601', 6, '입체 모양만 모은 것은?', '상자 모양과 통 모양은 모두 공간을 차지합니다.'),
  ('b64801bd-1a16-41d0-b6e1-562aebb2b300', 'af405f9e-df43-4527-b86f-9c4b63710601', 7, '나머지 셋과 종류가 다른 하나는?', '공 모양만 입체 모양이고 나머지는 평면 모양입니다.'),
  ('6ff56548-4b0d-4fab-a06f-a884bb5d5515', 'af405f9e-df43-4527-b86f-9c4b63710601', 8, '바닥에 놓았을 때 굴러가지 않고 차곡차곡 쌓기 쉬운 것은?', '상자 모양은 평평한 면이 있어 안정되게 쌓을 수 있습니다.'),
  ('120bb469-7754-4975-90db-18817d3dfad3', 'af405f9e-df43-4527-b86f-9c4b63710601', 9, '세모 모양과 네모 모양의 공통점은?', '두 모양은 모두 곧은 선들이 이어져 둘레를 만듭니다.'),
  ('99e42892-f147-405a-81ea-370843ac71b4', 'af405f9e-df43-4527-b86f-9c4b63710601', 10, '공 모양과 통 모양의 공통점은?', '공 모양과 통 모양에는 굽은 면이 있어 굴릴 수 있습니다.'),
  ('a194dd17-4984-4883-9e14-be827a5ad301', '8eb84449-513b-42d9-8621-e99cf6277211', 1, '네모 모양 종이를 한 꼭짓점에서 마주 보는 꼭짓점까지 곧게 잘랐습니다. 생기는 두 조각의 모양은?', '네모 모양을 대각선으로 자르면 세모 모양 2개가 생깁니다.'),
  ('6b797cf0-f0c7-484a-abd3-b6c1a7a303be', '8eb84449-513b-42d9-8621-e99cf6277211', 2, '같은 크기의 네모 모양 2개를 한 변 전체가 맞닿게 옆으로 붙였습니다. 바깥 테두리의 모양은?', '네모 모양 2개를 나란히 붙이면 바깥 테두리가 긴 네모 모양이 됩니다.'),
  ('a709ffed-9816-4082-8343-6a69c46f6882', '8eb84449-513b-42d9-8621-e99cf6277211', 3, '크기가 같은 세모 모양 조각으로 네모 모양 하나를 만들었습니다. 사용한 조각 수는?', '크기가 같은 세모 모양 2개를 알맞게 붙이면 네모 모양을 만들 수 있습니다.'),
  ('424eebfd-91dc-4dfc-964e-7725baeab501', '8eb84449-513b-42d9-8621-e99cf6277211', 4, '네모 모양 종이를 가로와 세로로 한 번씩 똑바로 잘라 같은 조각 4개를 만들었습니다. 각 조각의 모양은?', '가로와 세로로 똑바로 나누면 작은 네모 모양 4개가 생깁니다.'),
  ('699d83ae-fb53-4a6b-8b42-722cbf45501c', '8eb84449-513b-42d9-8621-e99cf6277211', 5, '상자 모양의 평평한 면을 종이에 대고 둘레를 그렸습니다. 가장 알맞은 모양은?', '상자 모양의 평평한 면을 따라 그리면 네모 모양이 됩니다.'),
  ('9153a8b7-eec8-426b-aee7-0334b98c5193', '8eb84449-513b-42d9-8621-e99cf6277211', 6, '통 모양의 동그란 밑면을 종이에 대고 둘레를 그렸습니다. 생기는 모양은?', '통 모양의 밑면 둘레를 따라 그리면 동그라미 모양이 됩니다.'),
  ('ffd1bd60-cb57-461f-86be-4781084461cd', '8eb84449-513b-42d9-8621-e99cf6277211', 7, '상자 모양을 펼쳤을 때 볼 수 있는 평평한 면의 모양은?', '상자 모양은 네모 모양의 평평한 면들로 둘러싸여 있습니다.'),
  ('e3563ab4-8d03-4817-a8d2-6835f2c487b7', '8eb84449-513b-42d9-8621-e99cf6277211', 8, '곧은 선 3개와 두 선이 만나는 곳 3개가 있는 평면 모양은?', '곧은 선과 만나는 곳이 각각 3개이면 세모 모양입니다.'),
  ('336b4350-d2a6-4dcf-a846-22392be148e2', '8eb84449-513b-42d9-8621-e99cf6277211', 9, '곧은 선이 없고 굽은 선으로만 둘러싸인 평면 모양은?', '굽은 선으로만 이어진 평면 모양은 동그라미 모양입니다.'),
  ('0c45bf1f-7b95-47ac-80f5-fa4b5ad41638', '8eb84449-513b-42d9-8621-e99cf6277211', 10, '동그란 평평한 면 2개와 굽은 면 1개가 있는 입체 모양은?', '위아래에 동그란 면이 있고 옆이 굽은 입체 모양은 통 모양입니다.'),
  ('67caac36-ec06-4526-ba7b-aba23dae5e06', 'c5117f97-4db5-4e8e-80a9-4a2126d90c6b', 1, '곧은 선 3개와 뾰족한 곳 3개를 모두 가진 모양은?', '세모 모양은 곧은 선 3개와 두 선이 만나는 곳 3개를 가집니다.'),
  ('269c929d-b257-4a79-88e5-eb544ff72259', 'c5117f97-4db5-4e8e-80a9-4a2126d90c6b', 2, '굽은 선으로 이어져 있고 뾰족한 곳이 하나도 없는 평면 모양은?', '동그라미 모양은 둘레가 굽은 선으로 이어지고 뾰족한 곳이 없습니다.'),
  ('3b4bdd4f-89c7-4249-8b78-a033112a1fd1', 'c5117f97-4db5-4e8e-80a9-4a2126d90c6b', 3, '민수는 동그라미 모양에 뾰족한 곳이 1개 있다고 말했습니다. 바르게 고친 것은?', '동그라미 모양에는 뾰족한 곳이 없습니다.'),
  ('dc28638b-23c3-491c-a872-58a9c1aa6761', 'c5117f97-4db5-4e8e-80a9-4a2126d90c6b', 4, '지우는 상자 모양의 모든 면이 동그라미 모양이라고 말했습니다. 바르게 고친 것은?', '상자 모양은 평평한 네모 모양의 면들로 둘러싸여 있습니다.'),
  ('7059592e-a734-43a9-a618-311555049e23', 'c5117f97-4db5-4e8e-80a9-4a2126d90c6b', 5, '세모 모양 3개와 네모 모양 1개를 곧은 선으로 둘러싸인 모양끼리 모았습니다. 잘못 들어간 모양은?', '세모 모양과 네모 모양은 모두 곧은 선으로 둘러싸여 있으므로 분류가 알맞습니다.'),
  ('aadae9c6-c3f4-42d8-a620-f24fd5367e66', 'c5117f97-4db5-4e8e-80a9-4a2126d90c6b', 6, '서연이는 세모 모양을 크게 그리면 네모 모양이 된다고 말했습니다. 바르게 설명한 것은?', '모양의 크기가 달라져도 곧은 선 3개로 둘러싸이면 세모 모양입니다.'),
  ('08a8a211-6d93-4990-84ec-a70e1fd30c31', 'c5117f97-4db5-4e8e-80a9-4a2126d90c6b', 7, '같은 크기의 세모 모양 2개를 알맞게 붙여 네모 모양을 만들었습니다. 알맞은 설명은?', '세모 모양 조각을 합쳐 네모 모양을 만든 경우입니다.'),
  ('325a3aba-91cf-4a8b-a790-5e99e9622d06', 'c5117f97-4db5-4e8e-80a9-4a2126d90c6b', 8, '현우는 통 모양은 굴러가기만 하고 쌓을 수 없다고 말했습니다. 바르게 고친 것은?', '통 모양은 굽은 면으로 굴릴 수 있고 평평한 면으로 세워 쌓을 수도 있습니다.'),
  ('eabb7c04-5eed-434a-8249-3c32017e2752', 'c5117f97-4db5-4e8e-80a9-4a2126d90c6b', 9, '가 모양은 곧은 선 3개이고 나 모양은 곧은 선 4개입니다. 가와 나의 모양은?', '곧은 선 3개인 가는 세모 모양이고 곧은 선 4개인 나는 네모 모양입니다.'),
  ('ea03478f-8770-44db-ac13-5dd37aedd7de', 'c5117f97-4db5-4e8e-80a9-4a2126d90c6b', 10, '어느 방향으로 밀어도 잘 굴러가고 평평한 면이 없는 입체 모양은?', '공 모양은 굽은 면으로만 둘러싸여 있어 어느 방향으로도 잘 굴러갑니다.');

insert into public.learning_question_options (id, question_id, display_order, option_text, is_correct)
values
  ('2cea5aac-20d3-4b22-83d2-a608f8d41919', '87022f21-6038-4d55-9589-020bb261be67', 1, '세모 모양', true),
  ('6fc35960-d34d-4628-83d0-ce16e22a6147', '87022f21-6038-4d55-9589-020bb261be67', 2, '네모 모양', false),
  ('ebc3f2dd-3fa7-4126-84fb-721ef3d0cd2d', '87022f21-6038-4d55-9589-020bb261be67', 3, '동그라미 모양', false),
  ('83b4231f-4620-45e2-a848-e4243c6d26b8', '87022f21-6038-4d55-9589-020bb261be67', 4, '공 모양', false),
  ('57846c82-d1f1-4022-b11b-fa9067a71183', '9ea72704-775a-46bf-9960-e1929cb31e34', 1, '동그라미 모양', false),
  ('0bd79e1b-9e0c-4f4f-a241-9ad15cd4f78a', '9ea72704-775a-46bf-9960-e1929cb31e34', 2, '네모 모양', true),
  ('bfd34ea9-4777-4491-89ea-f9b5f0aa13de', '9ea72704-775a-46bf-9960-e1929cb31e34', 3, '공 모양', false),
  ('672e15db-bd99-41ba-8f8e-f93f3c901960', '9ea72704-775a-46bf-9960-e1929cb31e34', 4, '통 모양', false),
  ('27edab53-7c18-4c11-a8b4-d5aaef011a3d', '67d77a67-e13f-41c9-a63e-08356c4ba2f1', 1, '세모 모양', false),
  ('25b404c8-a88a-4b58-8933-77cbfc274f2d', '67d77a67-e13f-41c9-a63e-08356c4ba2f1', 2, '네모 모양', false),
  ('c81fc007-a0b1-4fde-9d81-58c53d50af4c', '67d77a67-e13f-41c9-a63e-08356c4ba2f1', 3, '동그라미 모양', true),
  ('79fba679-bd19-4c20-b434-be9014ffb1e3', '67d77a67-e13f-41c9-a63e-08356c4ba2f1', 4, '상자 모양', false),
  ('2026ceff-0086-471b-af0c-a71b0adad44e', 'ecb58153-936c-4a35-806e-929623dbd461', 1, '세모 모양', false),
  ('c09b924e-bda6-4af7-9d3a-0745229422eb', 'ecb58153-936c-4a35-806e-929623dbd461', 2, '네모 모양', false),
  ('0b8d3f7f-88a4-49f7-9830-7f51fb54bb8d', 'ecb58153-936c-4a35-806e-929623dbd461', 3, '동그라미 모양', false),
  ('0d938fe9-9d00-495a-b5cc-ebe04bb7d8d5', 'ecb58153-936c-4a35-806e-929623dbd461', 4, '공 모양', true),
  ('0dbffac2-8e2b-4997-a63d-9cd5ee132e6e', '2333208b-609d-4a5f-9a18-5fd89535251d', 1, '공 모양', true),
  ('81d33706-1268-41ed-b50d-5c2178dde95f', '2333208b-609d-4a5f-9a18-5fd89535251d', 2, '상자 모양', false),
  ('b7003b2b-00dd-4a28-a2d9-559bc49fadb0', '2333208b-609d-4a5f-9a18-5fd89535251d', 3, '통 모양', false),
  ('d2ed35af-c4f7-413d-8af6-ba4fc1fa020f', '2333208b-609d-4a5f-9a18-5fd89535251d', 4, '세모 모양', false),
  ('f558f5af-76a0-4059-9a8a-88069e908927', '9295dfa9-b265-4585-bf04-f34e1df6c381', 1, '공 모양', false),
  ('a70537b5-ef87-445c-a274-b6fc24c6e5a6', '9295dfa9-b265-4585-bf04-f34e1df6c381', 2, '상자 모양', true),
  ('d0c1b3b8-cf75-4d17-8cae-27fb50323548', '9295dfa9-b265-4585-bf04-f34e1df6c381', 3, '통 모양', false),
  ('ef41c35f-e1aa-48a5-a7f8-e994d6959390', '9295dfa9-b265-4585-bf04-f34e1df6c381', 4, '동그라미 모양', false),
  ('5865fc14-5d2b-410a-b4ba-ef40292577e7', 'cedf957f-4c7d-4e2c-a394-1e72d91b9348', 1, '상자 모양', false),
  ('c3b81fc6-f4a7-440e-90b9-27c7acfd0fe2', 'cedf957f-4c7d-4e2c-a394-1e72d91b9348', 2, '공 모양', false),
  ('8f780245-2045-45b7-bfae-37f18fc2f7d8', 'cedf957f-4c7d-4e2c-a394-1e72d91b9348', 3, '통 모양', true),
  ('85bea504-d3a4-4038-890c-07802287561f', 'cedf957f-4c7d-4e2c-a394-1e72d91b9348', 4, '네모 모양', false),
  ('8de1a06d-e62e-45a9-9733-5fc8691072d4', '8cd899c7-3ee4-44bd-bf51-befaa3d442fc', 1, '세모 모양과 네모 모양', false),
  ('b3180161-12fa-489c-b994-cdc1cc034d3d', '8cd899c7-3ee4-44bd-bf51-befaa3d442fc', 2, '네모 모양과 동그라미 모양', false),
  ('1679b4f7-35af-4868-aac4-4a27f3b7aa9d', '8cd899c7-3ee4-44bd-bf51-befaa3d442fc', 3, '세모 모양과 공 모양', false),
  ('aca48a8d-aee5-49c1-a81c-4a5824ed1311', '8cd899c7-3ee4-44bd-bf51-befaa3d442fc', 4, '상자 모양과 공 모양', true),
  ('cb09f775-5576-4d4d-ba02-3f6696efbe84', 'd1f283a4-8edd-4e44-9ca8-672339699bdd', 1, '네모 모양', true),
  ('07b528a4-e899-40b0-8ace-a727de657beb', 'd1f283a4-8edd-4e44-9ca8-672339699bdd', 2, '공 모양', false),
  ('f543d762-b36a-4b7a-8a27-1003ad6f8ba9', 'd1f283a4-8edd-4e44-9ca8-672339699bdd', 3, '통 모양', false),
  ('6bf17ead-e1e1-4aec-b480-b803d7e0abce', 'd1f283a4-8edd-4e44-9ca8-672339699bdd', 4, '동그라미 모양', false),
  ('e2eb74ac-c6a8-4111-9d0b-7dbc397c3185', '52858e30-18b9-44be-9fcc-1d0b72511f74', 1, '공 모양', false),
  ('d0382095-20a2-48a1-90f6-444c2eccd9f2', '52858e30-18b9-44be-9fcc-1d0b72511f74', 2, '세모 모양', true),
  ('af5843c7-9a35-4d24-b6f1-cd129ca094ed', '52858e30-18b9-44be-9fcc-1d0b72511f74', 3, '통 모양', false),
  ('10f5c439-da4e-4efd-bf45-c165c1de81a9', '52858e30-18b9-44be-9fcc-1d0b72511f74', 4, '동그라미 모양', false),
  ('6e4065d0-649f-4aed-b973-21bedaef5706', '9b0c21ed-f0c7-47dd-b5c8-8f239b2b673a', 1, '1개', false),
  ('b15f4345-a7d7-4aa5-ace4-7e4aca41b227', '9b0c21ed-f0c7-47dd-b5c8-8f239b2b673a', 2, '2개', false),
  ('d36e5000-b88b-49b3-ba25-40d1bdd62845', '9b0c21ed-f0c7-47dd-b5c8-8f239b2b673a', 3, '3개', true),
  ('8308fca8-5e7f-40bb-a12e-218a858b5408', '9b0c21ed-f0c7-47dd-b5c8-8f239b2b673a', 4, '4개', false),
  ('7f59c1e8-e862-4fb6-9cf8-bb161a964403', '4d6bf528-80a5-40e0-a34d-581d0c166008', 1, '1개', false),
  ('49ad59a4-07e8-49a0-bc14-668e771a3f00', '4d6bf528-80a5-40e0-a34d-581d0c166008', 2, '2개', false),
  ('d7bc1b85-e97f-433c-a492-45cd360a4efd', '4d6bf528-80a5-40e0-a34d-581d0c166008', 3, '3개', false),
  ('b1063f6e-5a4b-4652-8952-e165aa8a9367', '4d6bf528-80a5-40e0-a34d-581d0c166008', 4, '4개', true),
  ('704493ab-7bdb-4e28-9734-9c64e169e5b6', '79fde641-4f4a-41de-ab03-f953633a354e', 1, '곧은 선이 없습니다.', true),
  ('7ab93a67-5435-46ae-8657-21aee2f6100a', '79fde641-4f4a-41de-ab03-f953633a354e', 2, '곧은 선이 3개입니다.', false),
  ('31ba56a0-8707-4da5-ae64-ea645f0efb75', '79fde641-4f4a-41de-ab03-f953633a354e', 3, '뾰족한 곳이 4개입니다.', false),
  ('35fb58cf-6bd8-4299-9044-53101a6cb557', '79fde641-4f4a-41de-ab03-f953633a354e', 4, '평평한 면이 6개입니다.', false),
  ('466ff45e-46a5-47d6-b665-82b62a25ef6d', 'a8a0c74c-98cd-4125-be28-161badc9526b', 1, '평평한 면만 있습니다.', false),
  ('c8e989ce-e55f-4925-9db0-eb2eca1b4070', 'a8a0c74c-98cd-4125-be28-161badc9526b', 2, '평평한 면과 굽은 면이 있습니다.', true),
  ('e97d7c11-3c1d-4c86-ad43-f1b01a455963', 'a8a0c74c-98cd-4125-be28-161badc9526b', 3, '굽은 면만 있습니다.', false),
  ('0d87f9f0-06b6-4da1-b7b7-14611745cc2a', 'a8a0c74c-98cd-4125-be28-161badc9526b', 4, '면이 없습니다.', false),
  ('630cc3d2-e031-4c60-976b-68069f5aeff8', 'c9a671c3-c3e5-47c5-8da3-9b2986ef8186', 1, '상자 모양과 공 모양', false),
  ('91250dcf-78da-4f74-8cd4-0a060fb755df', 'c9a671c3-c3e5-47c5-8da3-9b2986ef8186', 2, '통 모양과 세모 모양', false),
  ('c7e69392-8d14-419d-8de8-3cd86f17ae61', 'c9a671c3-c3e5-47c5-8da3-9b2986ef8186', 3, '세모 모양과 동그라미 모양', true),
  ('9b468ad1-5225-4e57-9a0e-793406327657', 'c9a671c3-c3e5-47c5-8da3-9b2986ef8186', 4, '공 모양과 네모 모양', false),
  ('1315f3e0-31a3-465d-b471-be20503d6ec6', '1cbcdf92-5a50-4027-8f16-d92cbd927c37', 1, '세모 모양과 네모 모양', false),
  ('810a4bbb-cb8e-49bb-b9b5-820bafad416a', '1cbcdf92-5a50-4027-8f16-d92cbd927c37', 2, '동그라미 모양과 공 모양', false),
  ('6b779d0b-0e56-4b7b-a286-b32bf6623ca1', '1cbcdf92-5a50-4027-8f16-d92cbd927c37', 3, '네모 모양과 통 모양', false),
  ('8919b7fd-c21e-4fb5-be13-e882e242d9c4', '1cbcdf92-5a50-4027-8f16-d92cbd927c37', 4, '상자 모양과 통 모양', true),
  ('9efc5b2a-c2c6-41fc-a2bb-34139d49d44d', 'b64801bd-1a16-41d0-b6e1-562aebb2b300', 1, '공 모양', true),
  ('a2eb32fb-511b-4992-8fe5-9cb43c0cfbce', 'b64801bd-1a16-41d0-b6e1-562aebb2b300', 2, '세모 모양', false),
  ('3344699a-e2e5-43f5-9198-dab24a985290', 'b64801bd-1a16-41d0-b6e1-562aebb2b300', 3, '네모 모양', false),
  ('f76ed2b7-9071-4a32-a1f5-22ec66ff4c31', 'b64801bd-1a16-41d0-b6e1-562aebb2b300', 4, '동그라미 모양', false),
  ('be712a28-a4f1-46f5-933c-cdf67af460cf', '6ff56548-4b0d-4fab-a06f-a884bb5d5515', 1, '공 모양', false),
  ('01bbb6cb-28da-4ed5-a3f9-56e724a7a263', '6ff56548-4b0d-4fab-a06f-a884bb5d5515', 2, '상자 모양', true),
  ('f5c52932-3168-470c-b20c-a9b0e2606c3b', '6ff56548-4b0d-4fab-a06f-a884bb5d5515', 3, '통 모양', false),
  ('50e87e69-84b9-45a7-81bb-648ba2e1617f', '6ff56548-4b0d-4fab-a06f-a884bb5d5515', 4, '동그라미 모양', false),
  ('e2e4c5c6-f04d-4152-a0be-b102954f7b40', '120bb469-7754-4975-90db-18817d3dfad3', 1, '모두 굽은 선만 있습니다.', false),
  ('39ad8311-db90-4fa5-b638-2d23c2ff6110', '120bb469-7754-4975-90db-18817d3dfad3', 2, '모두 입체 모양입니다.', false),
  ('6ec35cc5-8127-480d-970c-66ac9d3b6db4', '120bb469-7754-4975-90db-18817d3dfad3', 3, '모두 곧은 선으로 둘러싸여 있습니다.', true),
  ('4d40cebd-7010-4672-b6c9-41fe351388a2', '120bb469-7754-4975-90db-18817d3dfad3', 4, '모두 뾰족한 곳이 없습니다.', false),
  ('8b4f783c-0196-4a90-be60-edfc83391bef', '99e42892-f147-405a-81ea-370843ac71b4', 1, '모두 평평한 면만 있습니다.', false),
  ('cee5b725-42dd-4f95-83c3-af69326c813f', '99e42892-f147-405a-81ea-370843ac71b4', 2, '모두 네모 모양의 면이 있습니다.', false),
  ('6f92a055-a9f3-4181-be1a-897e6882ba59', '99e42892-f147-405a-81ea-370843ac71b4', 3, '모두 평면 모양입니다.', false),
  ('f4b6ea39-c146-4454-9684-920e1789f5a1', '99e42892-f147-405a-81ea-370843ac71b4', 4, '모두 굽은 면이 있어 굴릴 수 있습니다.', true),
  ('c47f348f-1eac-40f6-bd60-47a50be3aec3', 'a194dd17-4984-4883-9e14-be827a5ad301', 1, '세모 모양', true),
  ('be2e7f70-c999-4666-9d51-0f16e9d6abf7', 'a194dd17-4984-4883-9e14-be827a5ad301', 2, '네모 모양', false),
  ('749062c3-d994-4189-a174-db4955a44ff8', 'a194dd17-4984-4883-9e14-be827a5ad301', 3, '동그라미 모양', false),
  ('13c20060-f96b-45c8-8e5b-143c18943995', 'a194dd17-4984-4883-9e14-be827a5ad301', 4, '공 모양', false),
  ('a6312f72-6e03-42f5-86e9-8b3027c1b49a', '6b797cf0-f0c7-484a-abd3-b6c1a7a303be', 1, '동그라미 모양', false),
  ('30ce16ba-52de-47da-b407-1b8f131de510', '6b797cf0-f0c7-484a-abd3-b6c1a7a303be', 2, '긴 네모 모양', true),
  ('bb6f396d-5f5e-4f7f-898a-20bb59dee31a', '6b797cf0-f0c7-484a-abd3-b6c1a7a303be', 3, '공 모양', false),
  ('6b5dad0a-44ed-42b6-b697-10b89332acf0', '6b797cf0-f0c7-484a-abd3-b6c1a7a303be', 4, '통 모양', false),
  ('c5e8ef40-303f-43cd-a66e-049ded8dc7c4', 'a709ffed-9816-4082-8343-6a69c46f6882', 1, '1개', false),
  ('199f8a0d-5057-431f-a94a-3e81e227199e', 'a709ffed-9816-4082-8343-6a69c46f6882', 2, '3개', false),
  ('4e7365b5-ba4a-4d15-b70a-b6eb76450549', 'a709ffed-9816-4082-8343-6a69c46f6882', 3, '2개', true),
  ('b1a795e6-5813-4c68-9c7c-958a02d1c903', 'a709ffed-9816-4082-8343-6a69c46f6882', 4, '4개', false),
  ('0c322f90-048e-43bb-9484-c462eb62c687', '424eebfd-91dc-4dfc-964e-7725baeab501', 1, '세모 모양', false),
  ('8fd1beaf-f852-4c33-88e1-e9c332e6e7e7', '424eebfd-91dc-4dfc-964e-7725baeab501', 2, '동그라미 모양', false),
  ('b8fc63b0-b4f4-451a-a69b-b140b5867fc0', '424eebfd-91dc-4dfc-964e-7725baeab501', 3, '공 모양', false),
  ('60506006-2ef3-4206-b209-bf14cc29351f', '424eebfd-91dc-4dfc-964e-7725baeab501', 4, '네모 모양', true),
  ('da115a0e-e860-4a79-8356-ca6613b2a75f', '699d83ae-fb53-4a6b-8b42-722cbf45501c', 1, '네모 모양', true),
  ('9a19e506-51c7-4327-b2da-fa0ff66f55a2', '699d83ae-fb53-4a6b-8b42-722cbf45501c', 2, '공 모양', false),
  ('2d1886b9-90f4-461f-98dd-e72d241c4107', '699d83ae-fb53-4a6b-8b42-722cbf45501c', 3, '통 모양', false),
  ('ce0841c2-d961-41f4-aa12-1201b789a717', '699d83ae-fb53-4a6b-8b42-722cbf45501c', 4, '동그라미 모양', false),
  ('b3e586b2-c767-4682-ac2d-baecbaf67f85', '9153a8b7-eec8-426b-aee7-0334b98c5193', 1, '세모 모양', false),
  ('27d55ba7-3b01-4ee1-b7b3-d095106d15ac', '9153a8b7-eec8-426b-aee7-0334b98c5193', 2, '동그라미 모양', true),
  ('82b440a9-080e-474f-9fa7-9c9e8abebb33', '9153a8b7-eec8-426b-aee7-0334b98c5193', 3, '네모 모양', false),
  ('bb4e18fc-6db1-40e4-a725-c4241aba6ffd', '9153a8b7-eec8-426b-aee7-0334b98c5193', 4, '상자 모양', false),
  ('03133869-45e4-400f-b551-6c40867de9e5', 'ffd1bd60-cb57-461f-86be-4781084461cd', 1, '공 모양', false),
  ('e3a1add8-6aea-4d2f-9e2d-7aa8f5cd06b9', 'ffd1bd60-cb57-461f-86be-4781084461cd', 2, '통 모양', false),
  ('b7527e50-0da6-4d41-8842-ecc57b7f733c', 'ffd1bd60-cb57-461f-86be-4781084461cd', 3, '네모 모양', true),
  ('ffd3afdf-61c4-4675-8d7a-7c7287d44189', 'ffd1bd60-cb57-461f-86be-4781084461cd', 4, '동그라미 모양', false),
  ('46601f4c-061c-4d8e-a603-63ec88cf5722', 'e3563ab4-8d03-4817-a8d2-6835f2c487b7', 1, '동그라미 모양', false),
  ('651a5b53-d8a4-4fac-9ae1-75b01e95caeb', 'e3563ab4-8d03-4817-a8d2-6835f2c487b7', 2, '네모 모양', false),
  ('8baf4afd-7bcc-4ce2-a594-a1f76ffcdf79', 'e3563ab4-8d03-4817-a8d2-6835f2c487b7', 3, '공 모양', false),
  ('ae0d5619-a220-4fef-8f43-8b821e9677ad', 'e3563ab4-8d03-4817-a8d2-6835f2c487b7', 4, '세모 모양', true),
  ('08f703fb-a3bd-4e1b-9c83-fa3d35c33276', '336b4350-d2a6-4dcf-a846-22392be148e2', 1, '동그라미 모양', true),
  ('36dd43bd-56c5-4ada-86cc-3d7486dc0fc5', '336b4350-d2a6-4dcf-a846-22392be148e2', 2, '세모 모양', false),
  ('efd2d88d-85cf-42aa-91fa-47a9b8bfcae4', '336b4350-d2a6-4dcf-a846-22392be148e2', 3, '네모 모양', false),
  ('49efe0dd-296e-4962-adbb-c17d100cb6b4', '336b4350-d2a6-4dcf-a846-22392be148e2', 4, '상자 모양', false),
  ('fa4f7e1d-208d-451c-a5f7-bfe4ceaa52a2', '0c45bf1f-7b95-47ac-80f5-fa4b5ad41638', 1, '공 모양', false),
  ('8c9c04ee-b40c-4824-90af-3d1fbed7f807', '0c45bf1f-7b95-47ac-80f5-fa4b5ad41638', 2, '통 모양', true),
  ('0fab5cf7-88eb-4cdb-97e1-c810256c84e7', '0c45bf1f-7b95-47ac-80f5-fa4b5ad41638', 3, '상자 모양', false),
  ('e6e70085-42e9-4fd4-b7ca-79f3d2515f48', '0c45bf1f-7b95-47ac-80f5-fa4b5ad41638', 4, '네모 모양', false),
  ('20c144e8-e143-4aa1-afeb-4c6905f6af1c', '67caac36-ec06-4526-ba7b-aba23dae5e06', 1, '동그라미 모양', false),
  ('75665ddc-8df7-4b78-a2a3-74df08f70abe', '67caac36-ec06-4526-ba7b-aba23dae5e06', 2, '네모 모양', false),
  ('879e81a0-c38b-4b8f-9028-b5b754ae72f0', '67caac36-ec06-4526-ba7b-aba23dae5e06', 3, '세모 모양', true),
  ('de9dd70a-8937-4924-904c-98d344b5f91a', '67caac36-ec06-4526-ba7b-aba23dae5e06', 4, '공 모양', false),
  ('02decf8e-2cb8-42d9-8aab-e6de66f52330', '269c929d-b257-4a79-88e5-eb544ff72259', 1, '상자 모양', false),
  ('4df34e6d-05f5-4143-813a-c2fb03ebb110', '269c929d-b257-4a79-88e5-eb544ff72259', 2, '세모 모양', false),
  ('c069d5c3-d885-48dd-bd10-e80a67d76b9c', '269c929d-b257-4a79-88e5-eb544ff72259', 3, '네모 모양', false),
  ('8e6b6936-eac4-4612-8b9f-9783c80c6015', '269c929d-b257-4a79-88e5-eb544ff72259', 4, '동그라미 모양', true),
  ('b66bafd3-d244-42ce-ae61-a99dce17dd62', '3b4bdd4f-89c7-4249-8b78-a033112a1fd1', 1, '뾰족한 곳이 0개입니다.', true),
  ('1bfe4785-ffc5-4004-9a22-b5ddc228ab46', '3b4bdd4f-89c7-4249-8b78-a033112a1fd1', 2, '뾰족한 곳이 2개입니다.', false),
  ('1b11b056-1bd1-463c-87b1-ca1989408369', '3b4bdd4f-89c7-4249-8b78-a033112a1fd1', 3, '곧은 선이 3개입니다.', false),
  ('c6c06a1a-3ee7-4036-9020-b9028b4dd8f5', '3b4bdd4f-89c7-4249-8b78-a033112a1fd1', 4, '평평한 면이 1개입니다.', false),
  ('a61f3a5d-5b1a-4f24-912a-eb014ae472fc', 'dc28638b-23c3-491c-a872-58a9c1aa6761', 1, '굽은 면만 있습니다.', false),
  ('b95b3b8c-3304-4532-a15c-b6bcfe173f72', 'dc28638b-23c3-491c-a872-58a9c1aa6761', 2, '평평한 네모 모양의 면들이 있습니다.', true),
  ('43048f0b-9f18-4b38-9393-b68ef1bfca15', 'dc28638b-23c3-491c-a872-58a9c1aa6761', 3, '면이 하나도 없습니다.', false),
  ('d2b6ff4a-1d66-4adf-baa0-a0558ddad3cd', 'dc28638b-23c3-491c-a872-58a9c1aa6761', 4, '뾰족한 곳이 없습니다.', false),
  ('77906861-534a-4584-9536-dd0080220773', '7059592e-a734-43a9-a618-311555049e23', 1, '세모 모양', false),
  ('3a822aae-2362-4b8c-965b-7e81248ceb85', '7059592e-a734-43a9-a618-311555049e23', 2, '네모 모양', false),
  ('c76e8d0c-48c7-47a6-863e-c6be11676e03', '7059592e-a734-43a9-a618-311555049e23', 3, '잘못 들어간 모양이 없습니다.', true),
  ('a62afe9b-89a6-42ef-96f6-8edfc8a56171', '7059592e-a734-43a9-a618-311555049e23', 4, '모두 잘못 들어갔습니다.', false),
  ('c5799f51-251b-49e7-9d0b-9c1cbd2c08df', 'aadae9c6-c3f4-42d8-a620-f24fd5367e66', 1, '크기가 커지면 동그라미가 됩니다.', false),
  ('6e9d20fe-129b-47ac-9cf6-b5aaeb050209', 'aadae9c6-c3f4-42d8-a620-f24fd5367e66', 2, '색에 따라 모양이 바뀝니다.', false),
  ('81696b09-8706-4f77-935f-e05c41b3c79c', 'aadae9c6-c3f4-42d8-a620-f24fd5367e66', 3, '큰 세모에는 곧은 선이 4개입니다.', false),
  ('98ce356e-aec0-42ef-91b6-8547e33ba499', 'aadae9c6-c3f4-42d8-a620-f24fd5367e66', 4, '크기가 달라도 곧은 선 3개이면 세모 모양입니다.', true),
  ('c6cd8885-e32f-493e-8277-437fb65b5f02', '08a8a211-6d93-4990-84ec-a70e1fd30c31', 1, '작은 모양을 합쳐 새로운 모양을 만들었습니다.', true),
  ('c0d984ea-ac1f-4f7c-8264-8c2738be0e93', '08a8a211-6d93-4990-84ec-a70e1fd30c31', 2, '입체 모양을 평면 모양으로 바꾸었습니다.', false),
  ('85a0e473-85a5-4dd3-a71f-c4c2f2d3782d', '08a8a211-6d93-4990-84ec-a70e1fd30c31', 3, '동그라미를 두 부분으로 나누었습니다.', false),
  ('3a8ee3af-7b4c-4f28-9dea-2de04d5394e3', '08a8a211-6d93-4990-84ec-a70e1fd30c31', 4, '모양의 수가 줄지 않았습니다.', false),
  ('5f7eff16-fbfa-4e10-9675-6a3efe79a952', '325a3aba-91cf-4a8b-a790-5e99e9622d06', 1, '굽은 면이 없어 굴릴 수 없습니다.', false),
  ('6650d75b-6529-44f3-85d9-c59bc0004a9b', '325a3aba-91cf-4a8b-a790-5e99e9622d06', 2, '평평한 면으로 세우면 쌓을 수 있습니다.', true),
  ('e1c7222d-bcc2-4b36-a0c0-c2d811224d21', '325a3aba-91cf-4a8b-a790-5e99e9622d06', 3, '모든 면이 네모 모양입니다.', false),
  ('39fc8d77-2970-4778-9807-b6e6ae00e49e', '325a3aba-91cf-4a8b-a790-5e99e9622d06', 4, '공 모양과 완전히 같습니다.', false),
  ('7356cc79-63d9-4d40-831b-503b13631f93', 'eabb7c04-5eed-434a-8249-3c32017e2752', 1, '둘 다 동그라미 모양', false),
  ('681e03d1-f133-4e83-bee4-1208a8d942e0', 'eabb7c04-5eed-434a-8249-3c32017e2752', 2, '가는 네모 모양이고 나는 세모 모양', false),
  ('096d9a6d-49ef-403f-910d-5fe3ee8ae87f', 'eabb7c04-5eed-434a-8249-3c32017e2752', 3, '가는 세모 모양이고 나는 네모 모양', true),
  ('43ddc94b-c06b-45e9-8b71-249baab22762', 'eabb7c04-5eed-434a-8249-3c32017e2752', 4, '둘 다 공 모양', false),
  ('6a2aea19-a0c4-4740-b395-d7b35226502d', 'ea03478f-8770-44db-ac13-5dd37aedd7de', 1, '상자 모양', false),
  ('adaa8e60-b130-48ce-891f-c6aa7fb9f156', 'ea03478f-8770-44db-ac13-5dd37aedd7de', 2, '통 모양', false),
  ('3264c093-250f-4155-ab24-84fca2556e88', 'ea03478f-8770-44db-ac13-5dd37aedd7de', 3, '동그라미 모양', false),
  ('8547eae1-5ce0-438c-a281-cbfced5b8547', 'ea03478f-8770-44db-ac13-5dd37aedd7de', 4, '공 모양', true);

insert into public.learning_question_skills (
  question_id, skill_code, is_primary
)
values
  ('87022f21-6038-4d55-9589-020bb261be67', 'identify-plane-shape', true),
  ('9ea72704-775a-46bf-9960-e1929cb31e34', 'identify-plane-shape', true),
  ('67d77a67-e13f-41c9-a63e-08356c4ba2f1', 'identify-plane-shape', true),
  ('ecb58153-936c-4a35-806e-929623dbd461', 'identify-solid-shape', true),
  ('2333208b-609d-4a5f-9a18-5fd89535251d', 'connect-object-to-shape', true),
  ('9295dfa9-b265-4585-bf04-f34e1df6c381', 'connect-object-to-shape', true),
  ('cedf957f-4c7d-4e2c-a394-1e72d91b9348', 'connect-object-to-shape', true),
  ('8cd899c7-3ee4-44bd-bf51-befaa3d442fc', 'classify-shapes', true),
  ('d1f283a4-8edd-4e44-9ca8-672339699bdd', 'connect-object-to-shape', true),
  ('52858e30-18b9-44be-9fcc-1d0b72511f74', 'connect-object-to-shape', true),
  ('9b0c21ed-f0c7-47dd-b5c8-8f239b2b673a', 'describe-shape-properties', true),
  ('4d6bf528-80a5-40e0-a34d-581d0c166008', 'describe-shape-properties', true),
  ('79fde641-4f4a-41de-ab03-f953633a354e', 'describe-shape-properties', true),
  ('a8a0c74c-98cd-4125-be28-161badc9526b', 'describe-shape-properties', true),
  ('c9a671c3-c3e5-47c5-8da3-9b2986ef8186', 'classify-shapes', true),
  ('1cbcdf92-5a50-4027-8f16-d92cbd927c37', 'classify-shapes', true),
  ('b64801bd-1a16-41d0-b6e1-562aebb2b300', 'classify-shapes', true),
  ('6ff56548-4b0d-4fab-a06f-a884bb5d5515', 'describe-shape-properties', true),
  ('120bb469-7754-4975-90db-18817d3dfad3', 'describe-shape-properties', true),
  ('99e42892-f147-405a-81ea-370843ac71b4', 'describe-shape-properties', true),
  ('a194dd17-4984-4883-9e14-be827a5ad301', 'compose-decompose-shapes', true),
  ('6b797cf0-f0c7-484a-abd3-b6c1a7a303be', 'compose-decompose-shapes', true),
  ('a709ffed-9816-4082-8343-6a69c46f6882', 'compose-decompose-shapes', true),
  ('424eebfd-91dc-4dfc-964e-7725baeab501', 'compose-decompose-shapes', true),
  ('699d83ae-fb53-4a6b-8b42-722cbf45501c', 'compose-decompose-shapes', true),
  ('9153a8b7-eec8-426b-aee7-0334b98c5193', 'compose-decompose-shapes', true),
  ('ffd1bd60-cb57-461f-86be-4781084461cd', 'compose-decompose-shapes', true),
  ('e3563ab4-8d03-4817-a8d2-6835f2c487b7', 'infer-shape-from-properties', true),
  ('336b4350-d2a6-4dcf-a846-22392be148e2', 'infer-shape-from-properties', true),
  ('0c45bf1f-7b95-47ac-80f5-fa4b5ad41638', 'infer-shape-from-properties', true),
  ('67caac36-ec06-4526-ba7b-aba23dae5e06', 'infer-shape-from-properties', true),
  ('269c929d-b257-4a79-88e5-eb544ff72259', 'infer-shape-from-properties', true),
  ('3b4bdd4f-89c7-4249-8b78-a033112a1fd1', 'correct-shape-reasoning', true),
  ('dc28638b-23c3-491c-a872-58a9c1aa6761', 'correct-shape-reasoning', true),
  ('7059592e-a734-43a9-a618-311555049e23', 'correct-shape-reasoning', true),
  ('aadae9c6-c3f4-42d8-a620-f24fd5367e66', 'correct-shape-reasoning', true),
  ('08a8a211-6d93-4990-84ec-a70e1fd30c31', 'compose-decompose-shapes', true),
  ('325a3aba-91cf-4a8b-a790-5e99e9622d06', 'correct-shape-reasoning', true),
  ('eabb7c04-5eed-434a-8249-3c32017e2752', 'infer-shape-from-properties', true),
  ('ea03478f-8770-44db-ac13-5dd37aedd7de', 'infer-shape-from-properties', true);

select (public.publish_learning_content_version('8a600f52-61e6-4d6c-b6d0-b1f524b42df6'::uuid)).id;

commit;
