-- Generated by scripts/generate-learning-content-migration.js.
-- Source: content/learning/math/grade2-patterns-v1.json
-- Canonical content SHA-256: 1e59acc60adafd8c3ff1023a673927550be70bfa06bdd2907ccd5a651a0078b9
-- Content-only and additive: no assignment, attempt, progress, first-pass, ledger, ACL, or Realtime changes.

begin;

do $preflight$
begin
  if exists (
    select 1 from public.learning_courses
    where (id = '51000000-0000-4000-8000-000000000001'::uuid or course_code = 'math-core')
      and not (
        id = '51000000-0000-4000-8000-000000000001'::uuid
        and course_code = 'math-core'
        and internal_name = '수학 기초 과정'
        and subject_name = '수학'
      )
  ) then
    raise exception using errcode = '23505', message = 'grade2_patterns_v1 course identifier conflicts with different content';
  end if;

  if not exists (
    select 1 from public.learning_courses
    where id = '51000000-0000-4000-8000-000000000001'::uuid
      and course_code = 'math-core'
      and internal_name = '수학 기초 과정'
      and subject_name = '수학'
      and status = 'published'
  ) then
    raise exception using errcode = 'P0002', message = 'grade2_patterns_v1 existing course is missing or changed';
  end if;

  if exists (
    select 1 from public.learning_units
    where id = '09bafac3-9711-44dc-aa9d-88e5fc052d15'::uuid
       or unit_code = 'grade2-patterns'
  ) then
    raise exception using errcode = '23505', message = 'grade2_patterns_v1 unit identifier already exists';
  end if;

  if exists (
    select 1 from public.learning_units
    where course_id = '51000000-0000-4000-8000-000000000001'::uuid
      and sort_order = 13
  ) then
    raise exception using errcode = '23505', message = 'grade2_patterns_v1 unit sort order already exists';
  end if;

  if to_regclass('public.learning_unit_recommendation_metadata') is null then
    raise exception using errcode = 'P0002', message = 'learning recommendation metadata table is missing';
  end if;

  if exists (
    select 1
    from public.learning_unit_recommendation_metadata metadata
    where metadata.unit_id = '09bafac3-9711-44dc-aa9d-88e5fc052d15'::uuid
      and (
        metadata.subject is distinct from 'math'
        or metadata.recommended_start_level_code is distinct from 'elementary_2'
        or metadata.recommended_end_level_code is distinct from 'elementary_2'
        or metadata.parent_sort_order is distinct from 12
      )
  ) then
    raise exception using errcode = '23505', message = 'learning unit recommendation metadata conflicts with different content';
  end if;

  if to_regclass('public.learning_skill_definitions') is null
     or to_regclass('public.learning_question_skills') is null then
    raise exception using errcode = 'P0002', message = 'learning skill metadata foundation is missing';
  end if;

  if exists (
    select 1
    from (values
  ('continue-increasing-pattern'),
  ('continue-decreasing-pattern'),
  ('identify-repeating-cycle'),
  ('infer-missing-pattern-item'),
  ('extend-two-step-pattern'),
  ('explain-pattern-rule'),
  ('correct-pattern-reasoning')
    ) expected_skill(skill_code)
    where not exists (
      select 1 from public.learning_skill_definitions definition
      where definition.skill_code = expected_skill.skill_code
    )
  ) then
    raise exception using errcode = 'P0002', message = 'learning skill definition is missing';
  end if;

  if exists (
    select 1 from public.learning_content_versions
    where id = '5dad60cf-1889-4683-b135-667c885b6851'::uuid
       or content_hash = '1e59acc60adafd8c3ff1023a673927550be70bfa06bdd2907ccd5a651a0078b9'
  ) then
    raise exception using errcode = '23505', message = 'grade2_patterns_v1 content version already exists';
  end if;

  if exists (
    select 1 from (
      values
  ('53dd9e8a-c8a3-4eb6-9d29-f7f4da198ee7'::uuid),
  ('062ebd95-5c1e-4acb-b955-7d35c9f06546'::uuid),
  ('b856efa8-64e7-4b4b-a14e-adb108e2c7e8'::uuid),
  ('1a70471b-9e62-4fc9-9c8f-8f13fa0be476'::uuid),
  ('bcf7c4ce-c209-4963-b937-bf95cba1991e'::uuid),
  ('809ed509-13ba-4bb1-abec-e802d78e931b'::uuid),
  ('fe57f48c-94f0-4616-9f7e-989f1004d0ca'::uuid),
  ('3f266b2a-e293-4c35-9a2f-9b50a16b145c'::uuid),
  ('ac1d89a9-0ed5-4a8e-a763-cc4019dea98a'::uuid),
  ('dd858357-d6e2-4b29-8a42-e99e360f785e'::uuid),
  ('113af70b-9a1d-48c6-981b-f37673e3de6f'::uuid),
  ('0e62a840-9dc6-4b3b-bda7-2cbe6ef7ec1d'::uuid),
  ('a525d3e0-0e4c-4606-9da3-9a337eff9f0e'::uuid),
  ('a19d31a7-d747-4281-b995-48816cd10edf'::uuid),
  ('e00583d7-92a4-4d16-9481-6a4a4dc80b4e'::uuid),
  ('cc9cf0b9-8f42-43ae-af8e-2c8a7488fa28'::uuid),
  ('a0520efc-890b-45ab-94e6-082e1fa467b0'::uuid),
  ('b549f1c2-8c93-43ba-9e8f-aeffed4348b7'::uuid),
  ('01971220-8c4d-47c9-9065-6f78b331b8ae'::uuid),
  ('3e774a40-b0d8-4fd7-9211-ea81885af772'::uuid),
  ('f9523add-9dae-4883-bbc8-eaf5886495d2'::uuid),
  ('5eed51d1-7d25-4f1f-a013-4ef29ad4fa23'::uuid),
  ('48661048-edc6-4450-86e0-42f77e0a8ff2'::uuid),
  ('1db982b5-1b04-4381-9d0a-bf5bccc2fdaa'::uuid),
  ('5bdf19a0-203c-4f84-916e-8dc636252619'::uuid),
  ('0c969d53-c49e-4273-9959-b897721528cd'::uuid),
  ('9690eb97-df1c-4939-92da-53a784b436e0'::uuid),
  ('282b93cb-0c1e-41bc-b480-1c2902973f3b'::uuid),
  ('cade81f5-6b84-4aa9-9958-3cf3e68fc959'::uuid),
  ('1bef81e3-d76c-4694-b152-9fa39436ba7b'::uuid),
  ('caa2e723-2c14-443e-aeba-eb6f8e0fa1bd'::uuid),
  ('1e5cfa88-0627-41ed-a278-817e3d16327a'::uuid),
  ('f1af6863-e3f4-4ebb-ad92-f379b92a4af9'::uuid),
  ('342f3c51-d41e-4b85-86d6-e5a1f8226bc0'::uuid),
  ('39f5d8d4-5efa-49f7-a9cf-146d441a196b'::uuid),
  ('90c733ff-7cec-4ef2-b341-6773e956549c'::uuid),
  ('f9195dcb-a6d1-473e-b829-508047103fa0'::uuid),
  ('39605b8e-0e1a-46af-8230-1c1d92454af3'::uuid),
  ('d5495d4c-b1a0-447f-b317-895f138ccd12'::uuid),
  ('4484319c-c496-4426-a0f3-e7c1cede3e42'::uuid),
  ('4d2b5d1f-0316-4d63-893f-778dfad0d289'::uuid),
  ('05604d82-c37e-4c5e-8457-581f5872a93d'::uuid),
  ('470b06ce-ee69-4fa8-9f8c-c70ac565932b'::uuid),
  ('f498bb8d-342e-4abd-aeed-2270e9d1cf3e'::uuid),
  ('ed929f1c-817c-455f-b3ac-dff4274b815f'::uuid),
  ('b8767360-9a8f-47b5-b395-8b6d8df8a676'::uuid),
  ('6e7306ab-15a7-4e62-8c20-1ac7354d4bb4'::uuid),
  ('65be7336-0276-4202-bb8a-f574d29e46a9'::uuid),
  ('bbc9d5f5-8d97-49a3-8b96-cf0787d72d1c'::uuid),
  ('e41135fc-7f6d-411a-af97-7fff4056af67'::uuid),
  ('d6c1ea5b-1701-4262-863e-bcd4fb872f25'::uuid),
  ('1154fea4-1204-4228-93e9-5452c45a6305'::uuid),
  ('4ffeca28-888c-4282-a7a3-6cd66b3beeb7'::uuid),
  ('74e4a2fa-c37b-4a27-8c57-60134e1926df'::uuid),
  ('0c815712-2578-4e3e-b3fb-68f66f85d56c'::uuid),
  ('5a0c0672-d2da-4643-b2ae-a6c85f07e779'::uuid),
  ('9142fd35-7731-4157-8803-7c0571e06bfb'::uuid),
  ('48dad00f-1758-4f29-b570-c4fb7037a21d'::uuid),
  ('19b83544-1e82-4105-a0c6-787ce65b689c'::uuid),
  ('0e511397-4b94-4d4e-b197-456c3fecf309'::uuid),
  ('4f58ab25-e1d5-4ef2-9037-4daa4ad2bbe0'::uuid),
  ('fe18a0bd-eb38-4279-8b87-4183fb1e7db1'::uuid),
  ('bcd0a1fe-3f64-46ab-8ac9-8a368848014d'::uuid),
  ('d2a7c420-6e4e-4038-acde-2dad001978c5'::uuid),
  ('74c991c0-4a6e-4879-80f3-7a0291186b59'::uuid),
  ('40f617ad-041d-4f6f-b0d5-d88c1f3db536'::uuid),
  ('8b83ea28-eed5-4e9c-9b55-8b1f16572241'::uuid),
  ('c528f0f7-0e5e-4c5e-a982-655081de85f2'::uuid),
  ('5cd22757-7be7-4a07-be91-7a97427c6a20'::uuid),
  ('f7eee891-412b-4179-8859-12cb5d987ae8'::uuid),
  ('dc3e8909-b505-43f4-a06e-5398c099abe1'::uuid),
  ('fd364d82-2a82-46c8-9365-00ba93cd9b4a'::uuid),
  ('9e5fc67b-f672-4e3a-a75c-f87fdb528710'::uuid),
  ('a9b92687-0fa0-435e-8bbb-abc0f0433af3'::uuid),
  ('3dc6b87e-5a07-4c71-a25a-a79c4c16f967'::uuid),
  ('123d98d0-d948-4f2c-be5c-cccc5cdcb487'::uuid),
  ('45006352-5e08-4b90-9614-e9ebb649af59'::uuid),
  ('072e8043-5b96-4bd6-a85d-a0094364a72d'::uuid),
  ('1ddbfe14-1fba-40de-8d52-fb5500b1751a'::uuid),
  ('90f7faf3-623b-4b95-8960-c227e4f746fa'::uuid),
  ('243d7e29-43d0-4f0f-981d-a2da1e999125'::uuid),
  ('71f75633-a0b1-48c5-b24f-87c51f6e36e9'::uuid),
  ('706fe0ac-bbb4-47cf-baae-4d471e58681d'::uuid),
  ('f1af7789-a4c7-4448-af88-f3d8862cd4ef'::uuid),
  ('96f57080-43e9-48a5-b54a-d00ae172a29a'::uuid),
  ('809fe7f3-ecc4-4121-8a7e-77c8632f3e2b'::uuid),
  ('462ddb94-7afa-4da1-b19e-1ffe9864cce3'::uuid),
  ('c319152c-0f41-4787-80ea-75365c9df4ea'::uuid),
  ('f84d3773-b307-4857-9ef7-bc5f7781e35a'::uuid),
  ('a77dde54-d598-4e19-8ca1-d29900e902d2'::uuid),
  ('937bdcd8-4619-4c27-8124-65fdcf88e50d'::uuid),
  ('a7369f45-4b11-4b6d-a517-9ba4dbfb9299'::uuid),
  ('919b6735-55cd-4f44-a3a6-708c4177f900'::uuid),
  ('f11eef13-e85f-444e-ac6f-3a07b0abeea2'::uuid),
  ('d59a6196-3bd3-493d-b2c4-5b01fe964e9b'::uuid),
  ('8b3a42ee-e3ba-4fee-be1c-b2a508d05f03'::uuid),
  ('f39cc1d9-35b7-401b-96ae-1ebf68f8dc57'::uuid),
  ('98def6b1-dd30-47b8-9b89-c5c1c0bc2a0f'::uuid),
  ('3cfae5bd-e7dc-481e-8e1d-ce1724dfc158'::uuid),
  ('00fe64b4-70c1-441e-9946-dfb98ea8f892'::uuid),
  ('2f82704c-6326-4c6f-a027-74c957d9073a'::uuid),
  ('8945a971-2b76-4b0b-af2a-5afd5ef043e2'::uuid),
  ('96beb75a-7d42-41f9-ba2d-ecaa42e68518'::uuid),
  ('372c8c20-be3a-4ee7-bf01-4d2e15c8b3dc'::uuid),
  ('e73856bd-a6b6-4e4e-a98a-b925617bf90a'::uuid),
  ('b47f3645-f015-4327-ab0b-22ca8d3ad20c'::uuid),
  ('1af6bc76-7a45-4207-a474-0b6129fcce89'::uuid),
  ('52f647c1-1c78-4aca-96cf-526bd32d95d6'::uuid),
  ('1a421ec5-d4c6-4aa8-8a3b-5952e27d5949'::uuid),
  ('e07ea952-7bf4-4d38-9060-a53d50549643'::uuid),
  ('430fcd27-325b-4384-8d84-5b4a21026499'::uuid),
  ('b951c5d5-98ae-4e3b-91f5-b42317b001d2'::uuid),
  ('e76914e5-155b-4812-ab6f-7be88f1a6e81'::uuid),
  ('cdb2ef54-29d1-467a-8789-e2443a95abc5'::uuid),
  ('aca7fb54-bfdf-4eba-bb8f-871bff0188a0'::uuid),
  ('ab7bc50d-cebe-46f7-93f9-eae9fa4349b0'::uuid),
  ('4e333c44-a4a0-408b-b990-a975408b7510'::uuid),
  ('f49d983d-63da-480d-b329-f535f0fa6e2b'::uuid),
  ('bd6f80a6-5548-4d90-b14f-9227c41180a6'::uuid),
  ('62c2c138-248c-410f-97c6-03f4cf4530bf'::uuid),
  ('2ee96a33-f568-475f-ad7e-158465784d0e'::uuid),
  ('9ebb63b0-3ce5-44d7-a017-a1ced050b3b0'::uuid),
  ('1e0441ea-83b6-464d-bcc9-7e9eb32c591d'::uuid),
  ('a1996851-c713-42a9-8a31-519a470212ad'::uuid),
  ('ee5ac20d-b743-4071-aa04-4452510eced9'::uuid),
  ('6de1c3b1-cdb2-46df-9742-6230878f6e0d'::uuid),
  ('c43b9d61-dc10-4653-9cee-feb36b774f22'::uuid),
  ('b2d6c77c-02bf-4e44-aa00-a6bea43ddedb'::uuid),
  ('2d4d4cdf-69cd-41d3-9518-dfc0760c178f'::uuid),
  ('6299157b-6cab-4c1a-83fb-2a8264fac620'::uuid),
  ('121f05af-33b3-4349-8cf9-2aa1c01596de'::uuid),
  ('f1788c37-23db-4ad9-aa9e-007549fbeb5a'::uuid),
  ('db265fcf-0c35-4f04-9b84-0cda00f99667'::uuid),
  ('f7109bec-5637-423b-8c36-1984c9413ea5'::uuid),
  ('077a2eea-7757-48a4-8e03-f9eb6911101d'::uuid),
  ('c1ad0306-736d-4d55-8a28-b9570cedc06a'::uuid),
  ('89e62dfd-b1c3-4d32-9b60-a15dc3eddcfc'::uuid),
  ('c932e8a1-b069-4448-9939-70088ad02695'::uuid),
  ('a0b61660-1678-4aa1-bce7-9bfa683c2048'::uuid),
  ('35698092-98eb-4e15-b582-3b8c87b62d47'::uuid),
  ('9cbaf749-dd01-4ff9-a197-a3a7e2098290'::uuid),
  ('fddc1fb7-59d3-4016-bb78-b33ec8dac813'::uuid),
  ('4adba03d-7c1a-4b63-9d62-12ebb59ab6f3'::uuid),
  ('30750439-26af-407e-b5f8-c8002ff460a2'::uuid),
  ('7a412fb6-07f6-4904-8725-2dea133d2a73'::uuid),
  ('9d463e36-3304-4c4e-8fd9-1c670db585f2'::uuid),
  ('bbed6924-2988-4649-aadd-72ea23961947'::uuid),
  ('f186abed-228d-44ef-be85-f816c0a6fb8d'::uuid),
  ('0a52ae23-487c-4dc1-b28d-b8634a93bfb8'::uuid),
  ('06976c77-1cca-435e-b777-83844add29ff'::uuid),
  ('36d891d2-50f4-45b6-97a5-d3d383171209'::uuid),
  ('24517f38-73aa-4af5-a8c3-e2a1bd016403'::uuid),
  ('38e4aebe-9264-4e93-93a2-aa9d155060be'::uuid),
  ('82e9bbea-f7fc-4883-b40b-d6a76c934157'::uuid),
  ('159369c1-1ba8-4370-ad27-6620048ea36d'::uuid),
  ('28517169-268e-4701-9de5-8a9a61db54eb'::uuid),
  ('fc5507ed-a4e8-4544-bfb4-43b603869e20'::uuid),
  ('b14b9337-5954-4ba9-901f-9ec632d10b48'::uuid),
  ('8bf4f0c2-816c-4944-a0e5-0975703f8132'::uuid),
  ('b6e425d9-ed9b-4b6b-931a-599444fb34af'::uuid),
  ('83c7b46f-217a-4db1-bc2a-a55f0db2261c'::uuid),
  ('17db41ea-f1aa-4d04-a377-dd8b62246d01'::uuid),
  ('448a32ce-3d50-4891-9807-8bb2931cc3f4'::uuid),
  ('f42dc781-5f72-47a3-8fdf-fec9dc1be284'::uuid),
  ('31e60f8f-3ae9-4a98-83b8-b3faee308829'::uuid),
  ('8426a33e-05a8-4615-9b23-61325ec40793'::uuid),
  ('9e04bb0f-db6c-452f-a04b-f7a7df3ec979'::uuid),
  ('38bf6246-5bac-407f-b7b4-69636319805f'::uuid),
  ('a1a056cb-6f51-41f1-b368-3745261137f7'::uuid),
  ('21002500-ef26-4200-bbcf-00cdf5571ce3'::uuid),
  ('e0c8c09c-6c94-4a6c-8a55-72dc097a3e4e'::uuid),
  ('4f004dc8-3b20-497b-ac3f-7dd55aaea4e2'::uuid),
  ('6ff6dc91-ba9c-471c-b815-f28fb2ea81a7'::uuid),
  ('479ffc82-6e95-4377-ac09-5ea132b9c4b4'::uuid),
  ('44ff089d-3c88-4b41-8a9b-0cd3b099225d'::uuid),
  ('41ab21aa-8bf6-4f81-af5a-b09bb76cf497'::uuid),
  ('72de7b36-5a14-4d47-ad69-7b829adfe9fe'::uuid),
  ('28d462c8-dabf-4ca6-b364-99b24c396258'::uuid),
  ('99162def-58fe-4a49-833d-c0a5040a74d5'::uuid),
  ('ef197252-1024-452e-9464-962d377af431'::uuid),
  ('7b435861-44d0-4b51-a728-0a85dfbae22b'::uuid),
  ('8be36ef4-4e52-4f66-be0e-a549f44ee565'::uuid),
  ('779e00fc-9ac6-4e03-af8f-0228c8f22302'::uuid),
  ('bb1f15a9-8e7e-45ab-b87a-cd3214d192e9'::uuid),
  ('b5ad0d68-1423-446f-9b85-ebbebea4e623'::uuid),
  ('e8f02884-9e9e-4ddd-b7f4-da78cbcbac4f'::uuid),
  ('2d74e118-aa80-4f2e-a59d-0eaecc78e7f4'::uuid),
  ('55544ae8-b8a7-49e0-9dd5-e9970c1f4996'::uuid),
  ('bcf4b1de-29c8-4853-86ce-1a366b44f029'::uuid),
  ('113f64fd-8044-4c1c-ac2b-ba39bf137fac'::uuid),
  ('f6506a38-93b4-4afe-9b19-4b50659f6168'::uuid),
  ('7880695e-5857-411f-a3d9-1fa5f9c1e2aa'::uuid),
  ('db6fd7d5-6bc6-4153-836a-def5f6d69a70'::uuid),
  ('04ecddc6-6733-4a2d-997a-62e4047f7518'::uuid),
  ('238c618e-d17c-41ee-a239-2463710ea56c'::uuid),
  ('d198c6fe-21d4-491e-8a65-0b0d2132c164'::uuid),
  ('e533c5c4-ca68-4ef0-90e0-0bc1db6f7fc4'::uuid),
  ('cdaa534a-966b-4673-bebc-d1e15cd5dbdc'::uuid),
  ('8ab4a620-2a00-4b91-bb0f-32d5d4c3cfcb'::uuid),
  ('677bd11d-f4ca-4c61-b7b8-951712cfabb2'::uuid),
  ('b0473b7c-4b60-49f5-a080-b010a64f358d'::uuid),
  ('7dc0dd6c-a007-4464-9bc5-50a1f7e12a06'::uuid),
  ('afc1c6a3-9eb1-43ab-9702-0670e5c9eb57'::uuid),
  ('7c062d6d-6648-45e7-a958-6b6c961a7f5c'::uuid)
    ) as expected_id(id)
    where exists (
      select 1 from public.learning_stages where id = expected_id.id
      union all
      select 1 from public.learning_questions where id = expected_id.id
      union all
      select 1 from public.learning_question_options where id = expected_id.id
    )
  ) then
    raise exception using errcode = '23505', message = 'grade2_patterns_v1 child content identifier already exists';
  end if;
end
$preflight$;

insert into public.learning_units (id, course_id, unit_code, display_title, sort_order)
values ('09bafac3-9711-44dc-aa9d-88e5fc052d15', '51000000-0000-4000-8000-000000000001', 'grade2-patterns', '규칙을 찾아요', 13);

insert into public.learning_unit_recommendation_metadata (
  unit_id, subject, recommended_start_level_code, recommended_end_level_code, parent_sort_order
)
select '09bafac3-9711-44dc-aa9d-88e5fc052d15'::uuid, 'math', 'elementary_2', 'elementary_2', 12
where not exists (
  select 1
  from public.learning_unit_recommendation_metadata metadata
  where metadata.unit_id = '09bafac3-9711-44dc-aa9d-88e5fc052d15'::uuid
);

insert into public.learning_content_versions (id, unit_id, version_no, content_hash)
values ('5dad60cf-1889-4683-b135-667c885b6851', '09bafac3-9711-44dc-aa9d-88e5fc052d15', 1, '1e59acc60adafd8c3ff1023a673927550be70bfa06bdd2907ccd5a651a0078b9');

insert into public.learning_stages (id, content_version_id, display_order, display_title, difficulty)
values
  ('53dd9e8a-c8a3-4eb6-9d29-f7f4da198ee7', '5dad60cf-1889-4683-b135-667c885b6851', 1, '입문', 'seed'),
  ('062ebd95-5c1e-4acb-b955-7d35c9f06546', '5dad60cf-1889-4683-b135-667c885b6851', 2, '기초', 'leaf'),
  ('b856efa8-64e7-4b4b-a14e-adb108e2c7e8', '5dad60cf-1889-4683-b135-667c885b6851', 3, '심화', 'tree'),
  ('1a70471b-9e62-4fc9-9c8f-8f13fa0be476', '5dad60cf-1889-4683-b135-667c885b6851', 4, '최상위 도전!', 'crown');

insert into public.learning_questions (id, stage_id, display_order, prompt, explanation)
values
  ('bcf7c4ce-c209-4963-b937-bf95cba1991e', '53dd9e8a-c8a3-4eb6-9d29-f7f4da198ee7', 1, '2, 5, 8, 11, □의 규칙에서 다음 수는?', '앞 수에 3씩 더하므로 11+3=14입니다.'),
  ('809ed509-13ba-4bb1-abec-e802d78e931b', '53dd9e8a-c8a3-4eb6-9d29-f7f4da198ee7', 2, '5, 7, 9, 11, □의 규칙에서 다음 수는?', '앞 수에 2씩 더하므로 11+2=13입니다.'),
  ('fe57f48c-94f0-4616-9f7e-989f1004d0ca', '53dd9e8a-c8a3-4eb6-9d29-f7f4da198ee7', 3, '10, 15, 20, 25, □의 규칙에서 다음 수는?', '앞 수에 5씩 더하므로 25+5=30입니다.'),
  ('3f266b2a-e293-4c35-9a2f-9b50a16b145c', '53dd9e8a-c8a3-4eb6-9d29-f7f4da198ee7', 4, '4, 8, 12, 16, □의 규칙에서 다음 수는?', '앞 수에 4씩 더하므로 16+4=20입니다.'),
  ('ac1d89a9-0ed5-4a8e-a763-cc4019dea98a', '53dd9e8a-c8a3-4eb6-9d29-f7f4da198ee7', 5, '7, 10, 13, 16, □의 규칙에서 다음 수는?', '앞 수에 3씩 더하므로 16+3=19입니다.'),
  ('dd858357-d6e2-4b29-8a42-e99e360f785e', '53dd9e8a-c8a3-4eb6-9d29-f7f4da198ee7', 6, '20, 18, 16, 14, □의 규칙에서 다음 수는?', '앞 수에서 2씩 빼므로 14-2=12입니다.'),
  ('113af70b-9a1d-48c6-981b-f37673e3de6f', '53dd9e8a-c8a3-4eb6-9d29-f7f4da198ee7', 7, '35, 30, 25, 20, □의 규칙에서 다음 수는?', '앞 수에서 5씩 빼므로 20-5=15입니다.'),
  ('0e62a840-9dc6-4b3b-bda7-2cbe6ef7ec1d', '53dd9e8a-c8a3-4eb6-9d29-f7f4da198ee7', 8, '18, 15, 12, 9, □의 규칙에서 다음 수는?', '앞 수에서 3씩 빼므로 9-3=6입니다.'),
  ('a525d3e0-0e4c-4606-9da3-9a337eff9f0e', '53dd9e8a-c8a3-4eb6-9d29-f7f4da198ee7', 9, '40, 36, 32, 28, □의 규칙에서 다음 수는?', '앞 수에서 4씩 빼므로 28-4=24입니다.'),
  ('a19d31a7-d747-4281-b995-48816cd10edf', '53dd9e8a-c8a3-4eb6-9d29-f7f4da198ee7', 10, '27, 24, 21, 18, □의 규칙에서 다음 수는?', '앞 수에서 3씩 빼므로 18-3=15입니다.'),
  ('e00583d7-92a4-4d16-9481-6a4a4dc80b4e', '062ebd95-5c1e-4acb-b955-7d35c9f06546', 1, '○ △ ○ △ ○ △ ○ 다음에 올 것은?', '○ △가 반복되므로 다음에는 △이 옵니다.'),
  ('cc9cf0b9-8f42-43ae-af8e-2c8a7488fa28', '062ebd95-5c1e-4acb-b955-7d35c9f06546', 2, '★ ★ □ ★ ★ □ ★ 다음에 올 것은?', '★ ★ □가 반복되므로 다음에는 ★이 옵니다.'),
  ('a0520efc-890b-45ab-94e6-082e1fa467b0', '062ebd95-5c1e-4acb-b955-7d35c9f06546', 3, '가 나 다 가 나 다 가 다음에 올 것은?', '가 나 다가 반복되므로 다음에는 나이 옵니다.'),
  ('b549f1c2-8c93-43ba-9e8f-aeffed4348b7', '062ebd95-5c1e-4acb-b955-7d35c9f06546', 4, '빨강 파랑 빨강 파랑 빨강 파랑 빨강 다음에 올 것은?', '빨강 파랑가 반복되므로 다음에는 파랑이 옵니다.'),
  ('01971220-8c4d-47c9-9065-6f78b331b8ae', '062ebd95-5c1e-4acb-b955-7d35c9f06546', 5, '1 2 2 1 2 2 1 다음에 올 것은?', '1 2 2가 반복되므로 다음에는 2이 옵니다.'),
  ('3e774a40-b0d8-4fd7-9211-ea81885af772', '062ebd95-5c1e-4acb-b955-7d35c9f06546', 6, '3, 7, □, 15에서 빈칸은?', '4씩 커지는 규칙이므로 7+4=11입니다.'),
  ('f9523add-9dae-4883-bbc8-eaf5886495d2', '062ebd95-5c1e-4acb-b955-7d35c9f06546', 7, '6, 9, □, 15에서 빈칸은?', '3씩 커지는 규칙이므로 9+3=12입니다.'),
  ('5eed51d1-7d25-4f1f-a013-4ef29ad4fa23', '062ebd95-5c1e-4acb-b955-7d35c9f06546', 8, '2, 7, □, 17에서 빈칸은?', '5씩 커지는 규칙이므로 7+5=12입니다.'),
  ('48661048-edc6-4450-86e0-42f77e0a8ff2', '062ebd95-5c1e-4acb-b955-7d35c9f06546', 9, '10, 12, □, 16에서 빈칸은?', '2씩 커지는 규칙이므로 12+2=14입니다.'),
  ('1db982b5-1b04-4381-9d0a-bf5bccc2fdaa', '062ebd95-5c1e-4acb-b955-7d35c9f06546', 10, '1, 7, □, 19에서 빈칸은?', '6씩 커지는 규칙이므로 7+6=13입니다.'),
  ('5bdf19a0-203c-4f84-916e-8dc636252619', 'b856efa8-64e7-4b4b-a14e-adb108e2c7e8', 1, '1, 3, 4, 6, 7, □는 “2 더하기, 1 더하기”를 반복합니다. 다음 수는?', '7에서 2를 더할 차례이므로 9입니다.'),
  ('0c969d53-c49e-4273-9959-b897721528cd', 'b856efa8-64e7-4b4b-a14e-adb108e2c7e8', 2, '4, 7, 8, 11, 12, □는 “3 더하기, 1 더하기”를 반복합니다. 다음 수는?', '12에서 3를 더할 차례이므로 15입니다.'),
  ('9690eb97-df1c-4939-92da-53a784b436e0', 'b856efa8-64e7-4b4b-a14e-adb108e2c7e8', 3, '2, 6, 7, 11, 12, □는 “4 더하기, 1 더하기”를 반복합니다. 다음 수는?', '12에서 4를 더할 차례이므로 16입니다.'),
  ('282b93cb-0c1e-41bc-b480-1c2902973f3b', 'b856efa8-64e7-4b4b-a14e-adb108e2c7e8', 4, '5, 7, 8, 10, 11, □는 “2 더하기, 1 더하기”를 반복합니다. 다음 수는?', '11에서 2를 더할 차례이므로 13입니다.'),
  ('cade81f5-6b84-4aa9-9958-3cf3e68fc959', 'b856efa8-64e7-4b4b-a14e-adb108e2c7e8', 5, '5, 9, 13, 17의 규칙을 바르게 설명한 것은?', '이웃한 두 수의 차가 항상 4이므로 4씩 커집니다.'),
  ('1bef81e3-d76c-4694-b152-9fa39436ba7b', 'b856efa8-64e7-4b4b-a14e-adb108e2c7e8', 6, '30, 27, 24, 21의 규칙을 바르게 설명한 것은?', '이웃한 두 수의 차가 항상 3이므로 3씩 작아집니다.'),
  ('caa2e723-2c14-443e-aeba-eb6f8e0fa1bd', 'b856efa8-64e7-4b4b-a14e-adb108e2c7e8', 7, '2, 8, 14, 20의 규칙을 바르게 설명한 것은?', '이웃한 두 수의 차가 항상 6이므로 6씩 커집니다.'),
  ('1e5cfa88-0627-41ed-a278-817e3d16327a', 'b856efa8-64e7-4b4b-a14e-adb108e2c7e8', 8, '○ △ □가 반복됩니다. 11번째 항목은?', '반복 길이는 3이고 11번째는 주기의 2번째이므로 △입니다.'),
  ('f1af6863-e3f4-4ebb-ad92-f379b92a4af9', 'b856efa8-64e7-4b4b-a14e-adb108e2c7e8', 9, '★ □가 반복됩니다. 11번째 항목은?', '반복 길이는 2이고 11번째는 주기의 1번째이므로 ★입니다.'),
  ('342f3c51-d41e-4b85-86d6-e5a1f8226bc0', 'b856efa8-64e7-4b4b-a14e-adb108e2c7e8', 10, '가 나 나가 반복됩니다. 11번째 항목은?', '반복 길이는 3이고 11번째는 주기의 2번째이므로 나입니다.'),
  ('39f5d8d4-5efa-49f7-a9cf-146d441a196b', '1a70471b-9e62-4fc9-9c8f-8f13fa0be476', 1, '3, 6, 9, 13에서 규칙에 맞지 않는 수는?', '3씩 커지는 규칙이면 3, 6, 9, 12이므로 13이 잘못되었습니다.'),
  ('90c733ff-7cec-4ef2-b341-6773e956549c', '1a70471b-9e62-4fc9-9c8f-8f13fa0be476', 2, '20, 16, 12, 9를 바르게 고친 배열은?', '4씩 작아지는 규칙이므로 12 다음은 8입니다.'),
  ('f9195dcb-a6d1-473e-b829-508047103fa0', '1a70471b-9e62-4fc9-9c8f-8f13fa0be476', 3, '○ △ ○ ○ △ ○ ○ 다음 항목은?', '○ △ ○의 세 항목이 반복되므로 다음은 △입니다.'),
  ('39605b8e-0e1a-46af-8230-1c1d92454af3', '1a70471b-9e62-4fc9-9c8f-8f13fa0be476', 4, '2, 5, 6, 9, 10은 “3 더하기, 1 더하기” 규칙입니다. 다음 수는?', '10 다음에는 3을 더할 차례이므로 13입니다.'),
  ('d5495d4c-b1a0-447f-b317-895f138ccd12', '1a70471b-9e62-4fc9-9c8f-8f13fa0be476', 5, '□, 14, 18, 22가 4씩 커질 때 □는?', '14보다 4 작은 수는 10이므로 10, 14, 18, 22가 됩니다.'),
  ('4484319c-c496-4426-a0f3-e7c1cede3e42', '1a70471b-9e62-4fc9-9c8f-8f13fa0be476', 6, '★ ★ □가 반복될 때 8번째 항목과 까닭이 맞는 것은?', '반복 길이는 3이고 8번째는 두 번째 자리이므로 ★입니다.'),
  ('4d2b5d1f-0316-4d63-893f-778dfad0d289', '1a70471b-9e62-4fc9-9c8f-8f13fa0be476', 7, '7, 12, 17, 22의 규칙을 3번 더 이어 쓴 것은?', '5씩 커지므로 22 뒤에 27, 32, 37이 이어집니다.'),
  ('05604d82-c37e-4c5e-8457-581f5872a93d', '1a70471b-9e62-4fc9-9c8f-8f13fa0be476', 8, '40, 34, 28, 22에서 다음 두 수는?', '6씩 작아지므로 22-6=16, 16-6=10입니다.'),
  ('470b06ce-ee69-4fa8-9f8c-c70ac565932b', '1a70471b-9e62-4fc9-9c8f-8f13fa0be476', 9, '1, 3, 6, 8, 12에서 “2 더하기, 3 더하기” 규칙에 맞지 않는 수는?', '1+2=3, 3+3=6, 6+2=8 다음은 8+3=11이어야 하므로 12가 잘못되었습니다.'),
  ('f498bb8d-342e-4abd-aeed-2270e9d1cf3e', '1a70471b-9e62-4fc9-9c8f-8f13fa0be476', 10, '4, 7, 10, □, 16에서 빈칸과 규칙 설명이 모두 맞는 것은?', '이웃한 수가 3씩 커지므로 10+3=13이고 다음은 16입니다.');

insert into public.learning_question_options (id, question_id, display_order, option_text, is_correct)
values
  ('ed929f1c-817c-455f-b3ac-dff4274b815f', 'bcf7c4ce-c209-4963-b937-bf95cba1991e', 1, '14', true),
  ('b8767360-9a8f-47b5-b395-8b6d8df8a676', 'bcf7c4ce-c209-4963-b937-bf95cba1991e', 2, '15', false),
  ('6e7306ab-15a7-4e62-8c20-1ac7354d4bb4', 'bcf7c4ce-c209-4963-b937-bf95cba1991e', 3, '13', false),
  ('65be7336-0276-4202-bb8a-f574d29e46a9', 'bcf7c4ce-c209-4963-b937-bf95cba1991e', 4, '24', false),
  ('bbc9d5f5-8d97-49a3-8b96-cf0787d72d1c', '809ed509-13ba-4bb1-abec-e802d78e931b', 1, '14', false),
  ('e41135fc-7f6d-411a-af97-7fff4056af67', '809ed509-13ba-4bb1-abec-e802d78e931b', 2, '13', true),
  ('d6c1ea5b-1701-4262-863e-bcd4fb872f25', '809ed509-13ba-4bb1-abec-e802d78e931b', 3, '12', false),
  ('1154fea4-1204-4228-93e9-5452c45a6305', '809ed509-13ba-4bb1-abec-e802d78e931b', 4, '23', false),
  ('4ffeca28-888c-4282-a7a3-6cd66b3beeb7', 'fe57f48c-94f0-4616-9f7e-989f1004d0ca', 1, '31', false),
  ('74e4a2fa-c37b-4a27-8c57-60134e1926df', 'fe57f48c-94f0-4616-9f7e-989f1004d0ca', 2, '29', false),
  ('0c815712-2578-4e3e-b3fb-68f66f85d56c', 'fe57f48c-94f0-4616-9f7e-989f1004d0ca', 3, '30', true),
  ('5a0c0672-d2da-4643-b2ae-a6c85f07e779', 'fe57f48c-94f0-4616-9f7e-989f1004d0ca', 4, '40', false),
  ('9142fd35-7731-4157-8803-7c0571e06bfb', '3f266b2a-e293-4c35-9a2f-9b50a16b145c', 1, '21', false),
  ('48dad00f-1758-4f29-b570-c4fb7037a21d', '3f266b2a-e293-4c35-9a2f-9b50a16b145c', 2, '19', false),
  ('19b83544-1e82-4105-a0c6-787ce65b689c', '3f266b2a-e293-4c35-9a2f-9b50a16b145c', 3, '30', false),
  ('0e511397-4b94-4d4e-b197-456c3fecf309', '3f266b2a-e293-4c35-9a2f-9b50a16b145c', 4, '20', true),
  ('4f58ab25-e1d5-4ef2-9037-4daa4ad2bbe0', 'ac1d89a9-0ed5-4a8e-a763-cc4019dea98a', 1, '19', true),
  ('fe18a0bd-eb38-4279-8b87-4183fb1e7db1', 'ac1d89a9-0ed5-4a8e-a763-cc4019dea98a', 2, '20', false),
  ('bcd0a1fe-3f64-46ab-8ac9-8a368848014d', 'ac1d89a9-0ed5-4a8e-a763-cc4019dea98a', 3, '18', false),
  ('d2a7c420-6e4e-4038-acde-2dad001978c5', 'ac1d89a9-0ed5-4a8e-a763-cc4019dea98a', 4, '29', false),
  ('74c991c0-4a6e-4879-80f3-7a0291186b59', 'dd858357-d6e2-4b29-8a42-e99e360f785e', 1, '13', false),
  ('40f617ad-041d-4f6f-b0d5-d88c1f3db536', 'dd858357-d6e2-4b29-8a42-e99e360f785e', 2, '12', true),
  ('8b83ea28-eed5-4e9c-9b55-8b1f16572241', 'dd858357-d6e2-4b29-8a42-e99e360f785e', 3, '11', false),
  ('c528f0f7-0e5e-4c5e-a982-655081de85f2', 'dd858357-d6e2-4b29-8a42-e99e360f785e', 4, '22', false),
  ('5cd22757-7be7-4a07-be91-7a97427c6a20', '113af70b-9a1d-48c6-981b-f37673e3de6f', 1, '15', true),
  ('f7eee891-412b-4179-8859-12cb5d987ae8', '113af70b-9a1d-48c6-981b-f37673e3de6f', 2, '16', false),
  ('dc3e8909-b505-43f4-a06e-5398c099abe1', '113af70b-9a1d-48c6-981b-f37673e3de6f', 3, '14', false),
  ('fd364d82-2a82-46c8-9365-00ba93cd9b4a', '113af70b-9a1d-48c6-981b-f37673e3de6f', 4, '25', false),
  ('9e5fc67b-f672-4e3a-a75c-f87fdb528710', '0e62a840-9dc6-4b3b-bda7-2cbe6ef7ec1d', 1, '7', false),
  ('a9b92687-0fa0-435e-8bbb-abc0f0433af3', '0e62a840-9dc6-4b3b-bda7-2cbe6ef7ec1d', 2, '6', true),
  ('3dc6b87e-5a07-4c71-a25a-a79c4c16f967', '0e62a840-9dc6-4b3b-bda7-2cbe6ef7ec1d', 3, '5', false),
  ('123d98d0-d948-4f2c-be5c-cccc5cdcb487', '0e62a840-9dc6-4b3b-bda7-2cbe6ef7ec1d', 4, '16', false),
  ('45006352-5e08-4b90-9614-e9ebb649af59', 'a525d3e0-0e4c-4606-9da3-9a337eff9f0e', 1, '25', false),
  ('072e8043-5b96-4bd6-a85d-a0094364a72d', 'a525d3e0-0e4c-4606-9da3-9a337eff9f0e', 2, '23', false),
  ('1ddbfe14-1fba-40de-8d52-fb5500b1751a', 'a525d3e0-0e4c-4606-9da3-9a337eff9f0e', 3, '24', true),
  ('90f7faf3-623b-4b95-8960-c227e4f746fa', 'a525d3e0-0e4c-4606-9da3-9a337eff9f0e', 4, '34', false),
  ('243d7e29-43d0-4f0f-981d-a2da1e999125', 'a19d31a7-d747-4281-b995-48816cd10edf', 1, '16', false),
  ('71f75633-a0b1-48c5-b24f-87c51f6e36e9', 'a19d31a7-d747-4281-b995-48816cd10edf', 2, '14', false),
  ('706fe0ac-bbb4-47cf-baae-4d471e58681d', 'a19d31a7-d747-4281-b995-48816cd10edf', 3, '25', false),
  ('f1af7789-a4c7-4448-af88-f3d8862cd4ef', 'a19d31a7-d747-4281-b995-48816cd10edf', 4, '15', true),
  ('96f57080-43e9-48a5-b54a-d00ae172a29a', 'e00583d7-92a4-4d16-9481-6a4a4dc80b4e', 1, '△', true),
  ('809fe7f3-ecc4-4121-8a7e-77c8632f3e2b', 'e00583d7-92a4-4d16-9481-6a4a4dc80b4e', 2, '○', false),
  ('462ddb94-7afa-4da1-b19e-1ffe9864cce3', 'e00583d7-92a4-4d16-9481-6a4a4dc80b4e', 3, '★', false),
  ('c319152c-0f41-4787-80ea-75365c9df4ea', 'e00583d7-92a4-4d16-9481-6a4a4dc80b4e', 4, '가', false),
  ('f84d3773-b307-4857-9ef7-bc5f7781e35a', 'cc9cf0b9-8f42-43ae-af8e-2c8a7488fa28', 1, '○', false),
  ('a77dde54-d598-4e19-8ca1-d29900e902d2', 'cc9cf0b9-8f42-43ae-af8e-2c8a7488fa28', 2, '★', true),
  ('937bdcd8-4619-4c27-8124-65fdcf88e50d', 'cc9cf0b9-8f42-43ae-af8e-2c8a7488fa28', 3, '가', false),
  ('a7369f45-4b11-4b6d-a517-9ba4dbfb9299', 'cc9cf0b9-8f42-43ae-af8e-2c8a7488fa28', 4, '빨강', false),
  ('919b6735-55cd-4f44-a3a6-708c4177f900', 'a0520efc-890b-45ab-94e6-082e1fa467b0', 1, '○', false),
  ('f11eef13-e85f-444e-ac6f-3a07b0abeea2', 'a0520efc-890b-45ab-94e6-082e1fa467b0', 2, '★', false),
  ('d59a6196-3bd3-493d-b2c4-5b01fe964e9b', 'a0520efc-890b-45ab-94e6-082e1fa467b0', 3, '나', true),
  ('8b3a42ee-e3ba-4fee-be1c-b2a508d05f03', 'a0520efc-890b-45ab-94e6-082e1fa467b0', 4, '가', false),
  ('f39cc1d9-35b7-401b-96ae-1ebf68f8dc57', 'b549f1c2-8c93-43ba-9e8f-aeffed4348b7', 1, '○', false),
  ('98def6b1-dd30-47b8-9b89-c5c1c0bc2a0f', 'b549f1c2-8c93-43ba-9e8f-aeffed4348b7', 2, '★', false),
  ('3cfae5bd-e7dc-481e-8e1d-ce1724dfc158', 'b549f1c2-8c93-43ba-9e8f-aeffed4348b7', 3, '가', false),
  ('00fe64b4-70c1-441e-9946-dfb98ea8f892', 'b549f1c2-8c93-43ba-9e8f-aeffed4348b7', 4, '파랑', true),
  ('2f82704c-6326-4c6f-a027-74c957d9073a', '01971220-8c4d-47c9-9065-6f78b331b8ae', 1, '○', false),
  ('8945a971-2b76-4b0b-af2a-5afd5ef043e2', '01971220-8c4d-47c9-9065-6f78b331b8ae', 2, '★', false),
  ('96beb75a-7d42-41f9-ba2d-ecaa42e68518', '01971220-8c4d-47c9-9065-6f78b331b8ae', 3, '2', true),
  ('372c8c20-be3a-4ee7-bf01-4d2e15c8b3dc', '01971220-8c4d-47c9-9065-6f78b331b8ae', 4, '가', false),
  ('e73856bd-a6b6-4e4e-a98a-b925617bf90a', '3e774a40-b0d8-4fd7-9211-ea81885af772', 1, '7', false),
  ('b47f3645-f015-4327-ab0b-22ca8d3ad20c', '3e774a40-b0d8-4fd7-9211-ea81885af772', 2, '15', false),
  ('1af6bc76-7a45-4207-a474-0b6129fcce89', '3e774a40-b0d8-4fd7-9211-ea81885af772', 3, '12', false),
  ('52f647c1-1c78-4aca-96cf-526bd32d95d6', '3e774a40-b0d8-4fd7-9211-ea81885af772', 4, '11', true),
  ('1a421ec5-d4c6-4aa8-8a3b-5952e27d5949', 'f9523add-9dae-4883-bbc8-eaf5886495d2', 1, '12', true),
  ('e07ea952-7bf4-4d38-9060-a53d50549643', 'f9523add-9dae-4883-bbc8-eaf5886495d2', 2, '9', false),
  ('430fcd27-325b-4384-8d84-5b4a21026499', 'f9523add-9dae-4883-bbc8-eaf5886495d2', 3, '15', false),
  ('b951c5d5-98ae-4e3b-91f5-b42317b001d2', 'f9523add-9dae-4883-bbc8-eaf5886495d2', 4, '13', false),
  ('e76914e5-155b-4812-ab6f-7be88f1a6e81', '5eed51d1-7d25-4f1f-a013-4ef29ad4fa23', 1, '7', false),
  ('cdb2ef54-29d1-467a-8789-e2443a95abc5', '5eed51d1-7d25-4f1f-a013-4ef29ad4fa23', 2, '12', true),
  ('aca7fb54-bfdf-4eba-bb8f-871bff0188a0', '5eed51d1-7d25-4f1f-a013-4ef29ad4fa23', 3, '17', false),
  ('ab7bc50d-cebe-46f7-93f9-eae9fa4349b0', '5eed51d1-7d25-4f1f-a013-4ef29ad4fa23', 4, '13', false),
  ('4e333c44-a4a0-408b-b990-a975408b7510', '48661048-edc6-4450-86e0-42f77e0a8ff2', 1, '12', false),
  ('f49d983d-63da-480d-b329-f535f0fa6e2b', '48661048-edc6-4450-86e0-42f77e0a8ff2', 2, '16', false),
  ('bd6f80a6-5548-4d90-b14f-9227c41180a6', '48661048-edc6-4450-86e0-42f77e0a8ff2', 3, '14', true),
  ('62c2c138-248c-410f-97c6-03f4cf4530bf', '48661048-edc6-4450-86e0-42f77e0a8ff2', 4, '15', false),
  ('2ee96a33-f568-475f-ad7e-158465784d0e', '1db982b5-1b04-4381-9d0a-bf5bccc2fdaa', 1, '7', false),
  ('9ebb63b0-3ce5-44d7-a017-a1ced050b3b0', '1db982b5-1b04-4381-9d0a-bf5bccc2fdaa', 2, '19', false),
  ('1e0441ea-83b6-464d-bcc9-7e9eb32c591d', '1db982b5-1b04-4381-9d0a-bf5bccc2fdaa', 3, '14', false),
  ('a1996851-c713-42a9-8a31-519a470212ad', '1db982b5-1b04-4381-9d0a-bf5bccc2fdaa', 4, '13', true),
  ('ee5ac20d-b743-4071-aa04-4452510eced9', '5bdf19a0-203c-4f84-916e-8dc636252619', 1, '9', true),
  ('6de1c3b1-cdb2-46df-9742-6230878f6e0d', '5bdf19a0-203c-4f84-916e-8dc636252619', 2, '10', false),
  ('c43b9d61-dc10-4653-9cee-feb36b774f22', '5bdf19a0-203c-4f84-916e-8dc636252619', 3, '8', false),
  ('b2d6c77c-02bf-4e44-aa00-a6bea43ddedb', '5bdf19a0-203c-4f84-916e-8dc636252619', 4, '19', false),
  ('2d4d4cdf-69cd-41d3-9518-dfc0760c178f', '0c969d53-c49e-4273-9959-b897721528cd', 1, '16', false),
  ('6299157b-6cab-4c1a-83fb-2a8264fac620', '0c969d53-c49e-4273-9959-b897721528cd', 2, '15', true),
  ('121f05af-33b3-4349-8cf9-2aa1c01596de', '0c969d53-c49e-4273-9959-b897721528cd', 3, '14', false),
  ('f1788c37-23db-4ad9-aa9e-007549fbeb5a', '0c969d53-c49e-4273-9959-b897721528cd', 4, '25', false),
  ('db265fcf-0c35-4f04-9b84-0cda00f99667', '9690eb97-df1c-4939-92da-53a784b436e0', 1, '17', false),
  ('f7109bec-5637-423b-8c36-1984c9413ea5', '9690eb97-df1c-4939-92da-53a784b436e0', 2, '15', false),
  ('077a2eea-7757-48a4-8e03-f9eb6911101d', '9690eb97-df1c-4939-92da-53a784b436e0', 3, '16', true),
  ('c1ad0306-736d-4d55-8a28-b9570cedc06a', '9690eb97-df1c-4939-92da-53a784b436e0', 4, '26', false),
  ('89e62dfd-b1c3-4d32-9b60-a15dc3eddcfc', '282b93cb-0c1e-41bc-b480-1c2902973f3b', 1, '14', false),
  ('c932e8a1-b069-4448-9939-70088ad02695', '282b93cb-0c1e-41bc-b480-1c2902973f3b', 2, '12', false),
  ('a0b61660-1678-4aa1-bce7-9bfa683c2048', '282b93cb-0c1e-41bc-b480-1c2902973f3b', 3, '23', false),
  ('35698092-98eb-4e15-b582-3b8c87b62d47', '282b93cb-0c1e-41bc-b480-1c2902973f3b', 4, '13', true),
  ('9cbaf749-dd01-4ff9-a197-a3a7e2098290', 'cade81f5-6b84-4aa9-9958-3cf3e68fc959', 1, '4씩 커집니다.', true),
  ('fddc1fb7-59d3-4016-bb78-b33ec8dac813', 'cade81f5-6b84-4aa9-9958-3cf3e68fc959', 2, '5씩 커집니다.', false),
  ('4adba03d-7c1a-4b63-9d62-12ebb59ab6f3', 'cade81f5-6b84-4aa9-9958-3cf3e68fc959', 3, '항상 같은 수입니다.', false),
  ('30750439-26af-407e-b5f8-c8002ff460a2', 'cade81f5-6b84-4aa9-9958-3cf3e68fc959', 4, '4씩 작아집니다.', false),
  ('7a412fb6-07f6-4904-8725-2dea133d2a73', '1bef81e3-d76c-4694-b152-9fa39436ba7b', 1, '4씩 작아집니다.', false),
  ('9d463e36-3304-4c4e-8fd9-1c670db585f2', '1bef81e3-d76c-4694-b152-9fa39436ba7b', 2, '3씩 작아집니다.', true),
  ('bbed6924-2988-4649-aadd-72ea23961947', '1bef81e3-d76c-4694-b152-9fa39436ba7b', 3, '항상 같은 수입니다.', false),
  ('f186abed-228d-44ef-be85-f816c0a6fb8d', '1bef81e3-d76c-4694-b152-9fa39436ba7b', 4, '3씩 커집니다.', false),
  ('0a52ae23-487c-4dc1-b28d-b8634a93bfb8', 'caa2e723-2c14-443e-aeba-eb6f8e0fa1bd', 1, '6씩 커집니다.', true),
  ('06976c77-1cca-435e-b777-83844add29ff', 'caa2e723-2c14-443e-aeba-eb6f8e0fa1bd', 2, '7씩 커집니다.', false),
  ('36d891d2-50f4-45b6-97a5-d3d383171209', 'caa2e723-2c14-443e-aeba-eb6f8e0fa1bd', 3, '항상 같은 수입니다.', false),
  ('24517f38-73aa-4af5-a8c3-e2a1bd016403', 'caa2e723-2c14-443e-aeba-eb6f8e0fa1bd', 4, '6씩 작아집니다.', false),
  ('38e4aebe-9264-4e93-93a2-aa9d155060be', '1e5cfa88-0627-41ed-a278-817e3d16327a', 1, '○', false),
  ('82e9bbea-f7fc-4883-b40b-d6a76c934157', '1e5cfa88-0627-41ed-a278-817e3d16327a', 2, '△', true),
  ('159369c1-1ba8-4370-ad27-6620048ea36d', '1e5cfa88-0627-41ed-a278-817e3d16327a', 3, '★', false),
  ('28517169-268e-4701-9de5-8a9a61db54eb', '1e5cfa88-0627-41ed-a278-817e3d16327a', 4, '가', false),
  ('fc5507ed-a4e8-4544-bfb4-43b603869e20', 'f1af6863-e3f4-4ebb-ad92-f379b92a4af9', 1, '○', false),
  ('b14b9337-5954-4ba9-901f-9ec632d10b48', 'f1af6863-e3f4-4ebb-ad92-f379b92a4af9', 2, '가', false),
  ('8bf4f0c2-816c-4944-a0e5-0975703f8132', 'f1af6863-e3f4-4ebb-ad92-f379b92a4af9', 3, '★', true),
  ('b6e425d9-ed9b-4b6b-931a-599444fb34af', 'f1af6863-e3f4-4ebb-ad92-f379b92a4af9', 4, '빨강', false),
  ('83c7b46f-217a-4db1-bc2a-a55f0db2261c', '342f3c51-d41e-4b85-86d6-e5a1f8226bc0', 1, '○', false),
  ('17db41ea-f1aa-4d04-a377-dd8b62246d01', '342f3c51-d41e-4b85-86d6-e5a1f8226bc0', 2, '★', false),
  ('448a32ce-3d50-4891-9807-8bb2931cc3f4', '342f3c51-d41e-4b85-86d6-e5a1f8226bc0', 3, '가', false),
  ('f42dc781-5f72-47a3-8fdf-fec9dc1be284', '342f3c51-d41e-4b85-86d6-e5a1f8226bc0', 4, '나', true),
  ('31e60f8f-3ae9-4a98-83b8-b3faee308829', '39f5d8d4-5efa-49f7-a9cf-146d441a196b', 1, '13', true),
  ('8426a33e-05a8-4615-9b23-61325ec40793', '39f5d8d4-5efa-49f7-a9cf-146d441a196b', 2, '3', false),
  ('9e04bb0f-db6c-452f-a04b-f7a7df3ec979', '39f5d8d4-5efa-49f7-a9cf-146d441a196b', 3, '6', false),
  ('38bf6246-5bac-407f-b7b4-69636319805f', '39f5d8d4-5efa-49f7-a9cf-146d441a196b', 4, '9', false),
  ('a1a056cb-6f51-41f1-b368-3745261137f7', '90c733ff-7cec-4ef2-b341-6773e956549c', 1, '20, 17, 14, 11', false),
  ('21002500-ef26-4200-bbcf-00cdf5571ce3', '90c733ff-7cec-4ef2-b341-6773e956549c', 2, '20, 16, 12, 8', true),
  ('e0c8c09c-6c94-4a6c-8a55-72dc097a3e4e', '90c733ff-7cec-4ef2-b341-6773e956549c', 3, '20, 16, 12, 9', false),
  ('4f004dc8-3b20-497b-ac3f-7dd55aaea4e2', '90c733ff-7cec-4ef2-b341-6773e956549c', 4, '20, 15, 10, 5', false),
  ('6ff6dc91-ba9c-471c-b815-f28fb2ea81a7', 'f9195dcb-a6d1-473e-b829-508047103fa0', 1, '○', false),
  ('479ffc82-6e95-4377-ac09-5ea132b9c4b4', 'f9195dcb-a6d1-473e-b829-508047103fa0', 2, '□', false),
  ('44ff089d-3c88-4b41-8a9b-0cd3b099225d', 'f9195dcb-a6d1-473e-b829-508047103fa0', 3, '△', true),
  ('41ab21aa-8bf6-4f81-af5a-b09bb76cf497', 'f9195dcb-a6d1-473e-b829-508047103fa0', 4, '★', false),
  ('72de7b36-5a14-4d47-ad69-7b829adfe9fe', '39605b8e-0e1a-46af-8230-1c1d92454af3', 1, '11', false),
  ('28d462c8-dabf-4ca6-b364-99b24c396258', '39605b8e-0e1a-46af-8230-1c1d92454af3', 2, '12', false),
  ('99162def-58fe-4a49-833d-c0a5040a74d5', '39605b8e-0e1a-46af-8230-1c1d92454af3', 3, '14', false),
  ('ef197252-1024-452e-9464-962d377af431', '39605b8e-0e1a-46af-8230-1c1d92454af3', 4, '13', true),
  ('7b435861-44d0-4b51-a728-0a85dfbae22b', 'd5495d4c-b1a0-447f-b317-895f138ccd12', 1, '8', false),
  ('8be36ef4-4e52-4f66-be0e-a549f44ee565', 'd5495d4c-b1a0-447f-b317-895f138ccd12', 2, '12', false),
  ('779e00fc-9ac6-4e03-af8f-0228c8f22302', 'd5495d4c-b1a0-447f-b317-895f138ccd12', 3, '10', true),
  ('bb1f15a9-8e7e-45ab-b87a-cd3214d192e9', 'd5495d4c-b1a0-447f-b317-895f138ccd12', 4, '16', false),
  ('b5ad0d68-1423-446f-9b85-ebbebea4e623', '4484319c-c496-4426-a0f3-e7c1cede3e42', 1, '□이며 8번째는 주기의 세 번째입니다.', false),
  ('e8f02884-9e9e-4ddd-b7f4-da78cbcbac4f', '4484319c-c496-4426-a0f3-e7c1cede3e42', 2, '★이며 모든 항목이 같습니다.', false),
  ('2d74e118-aa80-4f2e-a59d-0eaecc78e7f4', '4484319c-c496-4426-a0f3-e7c1cede3e42', 3, '□이며 8을 2로 나눕니다.', false),
  ('55544ae8-b8a7-49e0-9dd5-e9970c1f4996', '4484319c-c496-4426-a0f3-e7c1cede3e42', 4, '★이며 8번째는 주기의 두 번째입니다.', true),
  ('bcf4b1de-29c8-4853-86ce-1a366b44f029', '4d2b5d1f-0316-4d63-893f-778dfad0d289', 1, '27, 32, 37', true),
  ('113f64fd-8044-4c1c-ac2b-ba39bf137fac', '4d2b5d1f-0316-4d63-893f-778dfad0d289', 2, '23, 24, 25', false),
  ('f6506a38-93b4-4afe-9b19-4b50659f6168', '4d2b5d1f-0316-4d63-893f-778dfad0d289', 3, '27, 31, 35', false),
  ('7880695e-5857-411f-a3d9-1fa5f9c1e2aa', '4d2b5d1f-0316-4d63-893f-778dfad0d289', 4, '17, 12, 7', false),
  ('db6fd7d5-6bc6-4153-836a-def5f6d69a70', '05604d82-c37e-4c5e-8457-581f5872a93d', 1, '18, 14', false),
  ('04ecddc6-6733-4a2d-997a-62e4047f7518', '05604d82-c37e-4c5e-8457-581f5872a93d', 2, '16, 10', true),
  ('238c618e-d17c-41ee-a239-2463710ea56c', '05604d82-c37e-4c5e-8457-581f5872a93d', 3, '16, 12', false),
  ('d198c6fe-21d4-491e-8a65-0b0d2132c164', '05604d82-c37e-4c5e-8457-581f5872a93d', 4, '28, 34', false),
  ('e533c5c4-ca68-4ef0-90e0-0bc1db6f7fc4', '470b06ce-ee69-4fa8-9f8c-c70ac565932b', 1, '3', false),
  ('cdaa534a-966b-4673-bebc-d1e15cd5dbdc', '470b06ce-ee69-4fa8-9f8c-c70ac565932b', 2, '6', false),
  ('8ab4a620-2a00-4b91-bb0f-32d5d4c3cfcb', '470b06ce-ee69-4fa8-9f8c-c70ac565932b', 3, '12', true),
  ('677bd11d-f4ca-4c61-b7b8-951712cfabb2', '470b06ce-ee69-4fa8-9f8c-c70ac565932b', 4, '8', false),
  ('b0473b7c-4b60-49f5-a080-b010a64f358d', 'f498bb8d-342e-4abd-aeed-2270e9d1cf3e', 1, '12이며 2씩 커집니다.', false),
  ('7dc0dd6c-a007-4464-9bc5-50a1f7e12a06', 'f498bb8d-342e-4abd-aeed-2270e9d1cf3e', 2, '13이며 3씩 작아집니다.', false),
  ('afc1c6a3-9eb1-43ab-9702-0670e5c9eb57', 'f498bb8d-342e-4abd-aeed-2270e9d1cf3e', 3, '14이며 4씩 커집니다.', false),
  ('7c062d6d-6648-45e7-a958-6b6c961a7f5c', 'f498bb8d-342e-4abd-aeed-2270e9d1cf3e', 4, '13이며 3씩 커집니다.', true);

insert into public.learning_question_skills (
  question_id, skill_code, is_primary
)
values
  ('bcf7c4ce-c209-4963-b937-bf95cba1991e', 'continue-increasing-pattern', true),
  ('809ed509-13ba-4bb1-abec-e802d78e931b', 'continue-increasing-pattern', true),
  ('fe57f48c-94f0-4616-9f7e-989f1004d0ca', 'continue-increasing-pattern', true),
  ('3f266b2a-e293-4c35-9a2f-9b50a16b145c', 'continue-increasing-pattern', true),
  ('ac1d89a9-0ed5-4a8e-a763-cc4019dea98a', 'continue-increasing-pattern', true),
  ('dd858357-d6e2-4b29-8a42-e99e360f785e', 'continue-decreasing-pattern', true),
  ('113af70b-9a1d-48c6-981b-f37673e3de6f', 'continue-decreasing-pattern', true),
  ('0e62a840-9dc6-4b3b-bda7-2cbe6ef7ec1d', 'continue-decreasing-pattern', true),
  ('a525d3e0-0e4c-4606-9da3-9a337eff9f0e', 'continue-decreasing-pattern', true),
  ('a19d31a7-d747-4281-b995-48816cd10edf', 'continue-decreasing-pattern', true),
  ('e00583d7-92a4-4d16-9481-6a4a4dc80b4e', 'identify-repeating-cycle', true),
  ('cc9cf0b9-8f42-43ae-af8e-2c8a7488fa28', 'identify-repeating-cycle', true),
  ('a0520efc-890b-45ab-94e6-082e1fa467b0', 'identify-repeating-cycle', true),
  ('b549f1c2-8c93-43ba-9e8f-aeffed4348b7', 'identify-repeating-cycle', true),
  ('01971220-8c4d-47c9-9065-6f78b331b8ae', 'identify-repeating-cycle', true),
  ('3e774a40-b0d8-4fd7-9211-ea81885af772', 'infer-missing-pattern-item', true),
  ('f9523add-9dae-4883-bbc8-eaf5886495d2', 'infer-missing-pattern-item', true),
  ('5eed51d1-7d25-4f1f-a013-4ef29ad4fa23', 'infer-missing-pattern-item', true),
  ('48661048-edc6-4450-86e0-42f77e0a8ff2', 'infer-missing-pattern-item', true),
  ('1db982b5-1b04-4381-9d0a-bf5bccc2fdaa', 'infer-missing-pattern-item', true),
  ('5bdf19a0-203c-4f84-916e-8dc636252619', 'extend-two-step-pattern', true),
  ('0c969d53-c49e-4273-9959-b897721528cd', 'extend-two-step-pattern', true),
  ('9690eb97-df1c-4939-92da-53a784b436e0', 'extend-two-step-pattern', true),
  ('282b93cb-0c1e-41bc-b480-1c2902973f3b', 'extend-two-step-pattern', true),
  ('cade81f5-6b84-4aa9-9958-3cf3e68fc959', 'explain-pattern-rule', true),
  ('1bef81e3-d76c-4694-b152-9fa39436ba7b', 'explain-pattern-rule', true),
  ('caa2e723-2c14-443e-aeba-eb6f8e0fa1bd', 'explain-pattern-rule', true),
  ('1e5cfa88-0627-41ed-a278-817e3d16327a', 'identify-repeating-cycle', true),
  ('f1af6863-e3f4-4ebb-ad92-f379b92a4af9', 'identify-repeating-cycle', true),
  ('342f3c51-d41e-4b85-86d6-e5a1f8226bc0', 'identify-repeating-cycle', true),
  ('39f5d8d4-5efa-49f7-a9cf-146d441a196b', 'correct-pattern-reasoning', true),
  ('90c733ff-7cec-4ef2-b341-6773e956549c', 'correct-pattern-reasoning', true),
  ('f9195dcb-a6d1-473e-b829-508047103fa0', 'identify-repeating-cycle', true),
  ('39605b8e-0e1a-46af-8230-1c1d92454af3', 'extend-two-step-pattern', true),
  ('d5495d4c-b1a0-447f-b317-895f138ccd12', 'infer-missing-pattern-item', true),
  ('4484319c-c496-4426-a0f3-e7c1cede3e42', 'identify-repeating-cycle', true),
  ('4d2b5d1f-0316-4d63-893f-778dfad0d289', 'continue-increasing-pattern', true),
  ('05604d82-c37e-4c5e-8457-581f5872a93d', 'continue-decreasing-pattern', true),
  ('470b06ce-ee69-4fa8-9f8c-c70ac565932b', 'correct-pattern-reasoning', true),
  ('f498bb8d-342e-4abd-aeed-2270e9d1cf3e', 'explain-pattern-rule', true);

select (public.publish_learning_content_version('5dad60cf-1889-4683-b135-667c885b6851'::uuid)).id;

commit;
