-- Generated by scripts/generate-learning-content-migration.js.
-- Source: content/learning/math/grade2-tables-graphs-v1.json
-- Canonical content SHA-256: 2c516217b25218b0cc29df4113a5dc4d70b9505ff48b7c7e61339b3d6bc7f16b
-- Content-only and additive: no assignment, attempt, progress, first-pass, ledger, ACL, or Realtime changes.

begin;

do $preflight$
begin
  if exists (
    select 1 from public.learning_courses
    where (id = '51000000-0000-4000-8000-000000000001'::uuid or course_code = 'math-core')
      and not (
        id = '51000000-0000-4000-8000-000000000001'::uuid
        and course_code = 'math-core'
        and internal_name = '수학 기초 과정'
        and subject_name = '수학'
      )
  ) then
    raise exception using errcode = '23505', message = 'grade2_tables_graphs_v1 course identifier conflicts with different content';
  end if;

  if not exists (
    select 1 from public.learning_courses
    where id = '51000000-0000-4000-8000-000000000001'::uuid
      and course_code = 'math-core'
      and internal_name = '수학 기초 과정'
      and subject_name = '수학'
      and status = 'published'
  ) then
    raise exception using errcode = 'P0002', message = 'grade2_tables_graphs_v1 existing course is missing or changed';
  end if;

  if exists (
    select 1 from public.learning_units
    where id = '41cf53c2-edf0-4585-958e-2d8804c5c443'::uuid
       or unit_code = 'grade2-tables-graphs'
  ) then
    raise exception using errcode = '23505', message = 'grade2_tables_graphs_v1 unit identifier already exists';
  end if;

  if exists (
    select 1 from public.learning_units
    where course_id = '51000000-0000-4000-8000-000000000001'::uuid
      and sort_order = 12
  ) then
    raise exception using errcode = '23505', message = 'grade2_tables_graphs_v1 unit sort order already exists';
  end if;

  if to_regclass('public.learning_unit_recommendation_metadata') is null then
    raise exception using errcode = 'P0002', message = 'learning recommendation metadata table is missing';
  end if;

  if exists (
    select 1
    from public.learning_unit_recommendation_metadata metadata
    where metadata.unit_id = '41cf53c2-edf0-4585-958e-2d8804c5c443'::uuid
      and (
        metadata.subject is distinct from 'math'
        or metadata.recommended_start_level_code is distinct from 'elementary_2'
        or metadata.recommended_end_level_code is distinct from 'elementary_2'
        or metadata.parent_sort_order is distinct from 11
      )
  ) then
    raise exception using errcode = '23505', message = 'learning unit recommendation metadata conflicts with different content';
  end if;

  if to_regclass('public.learning_skill_definitions') is null
     or to_regclass('public.learning_question_skills') is null then
    raise exception using errcode = 'P0002', message = 'learning skill metadata foundation is missing';
  end if;

  if exists (
    select 1
    from (values
  ('find-most-least-category'),
  ('read-data-table'),
  ('calculate-data-difference'),
  ('infer-missing-data'),
  ('connect-table-and-graph'),
  ('read-text-graph'),
  ('correct-data-interpretation'),
  ('classify-by-given-rule'),
  ('complete-data-table')
    ) expected_skill(skill_code)
    where not exists (
      select 1 from public.learning_skill_definitions definition
      where definition.skill_code = expected_skill.skill_code
    )
  ) then
    raise exception using errcode = 'P0002', message = 'learning skill definition is missing';
  end if;

  if exists (
    select 1 from public.learning_content_versions
    where id = 'f37533f2-54b2-4a3d-99da-88ba28dc7af9'::uuid
       or content_hash = '2c516217b25218b0cc29df4113a5dc4d70b9505ff48b7c7e61339b3d6bc7f16b'
  ) then
    raise exception using errcode = '23505', message = 'grade2_tables_graphs_v1 content version already exists';
  end if;

  if exists (
    select 1 from (
      values
  ('759bb6b4-b331-4ee9-b0ba-93503eaa0c32'::uuid),
  ('6f1ff2c3-ac67-4b71-b001-7f92c5159fb0'::uuid),
  ('3010579f-2808-4e34-b925-0985fd71f861'::uuid),
  ('19bb103e-bcc6-4ad1-9d30-5edd2e9fa4a8'::uuid),
  ('35a77e27-be3d-47f4-80ea-45788de71de1'::uuid),
  ('84e42979-4280-477b-81ba-5a4abc706afb'::uuid),
  ('f340beba-3490-4b0a-8ff3-07b6ab0f5cff'::uuid),
  ('ae6c8e7d-acca-4089-bc4a-020462c58222'::uuid),
  ('9dd39f79-6d2b-4c3b-8d56-b7e092be567f'::uuid),
  ('fbcab2eb-94fe-4155-8c3c-b45b07cb6c77'::uuid),
  ('0d0b9faf-7a78-4af2-9f94-0e920ef54818'::uuid),
  ('926c7c17-4ba1-42e0-bae3-4c357ddaf561'::uuid),
  ('1173fb20-ed89-48fa-993e-a47550faf348'::uuid),
  ('fabf9de0-b924-4b9b-853e-140a9d014175'::uuid),
  ('0e4a2adb-4935-48a1-b06f-006254a5658a'::uuid),
  ('60bac9ce-ee2d-4b90-af39-7fbc50168f67'::uuid),
  ('2fe691a0-008e-42ca-a7fb-dca2a18b04ef'::uuid),
  ('11d371da-5af0-472e-8773-8ef5f85bd918'::uuid),
  ('058cd8ea-4577-4ffc-bda3-60d96eadf603'::uuid),
  ('dd59ed44-e971-4d1c-bf55-fd8f26d97a63'::uuid),
  ('acac74bd-5289-49ce-a94e-cfc777cbcd69'::uuid),
  ('ccbd5ba7-bbd1-474d-bd66-fd68c794fabe'::uuid),
  ('f9f03be8-ba76-4dde-afbf-c01daa22f389'::uuid),
  ('f25e7093-61d4-4449-b13c-86d8bb9a2c35'::uuid),
  ('d3ef17d0-016f-4dce-89db-0b4b8499858d'::uuid),
  ('b2705a55-4316-4500-b111-acf2adbcdd75'::uuid),
  ('3879ee58-b9e7-47ee-937c-3210255f8440'::uuid),
  ('6465ac00-72da-413e-9d86-b2a58854f21d'::uuid),
  ('c2913ea9-78ef-4bea-9de2-a95a1e62959b'::uuid),
  ('b5abd324-fbd8-4408-89af-b489fc56415c'::uuid),
  ('aa0692d3-090b-4b64-a790-5e3cfe76004b'::uuid),
  ('7eb4abc7-5ea7-4aae-88a7-fbd4efcb4cb9'::uuid),
  ('117fa599-6fb3-4fe6-b0c0-cdbb0533ab34'::uuid),
  ('0695efd3-f02c-4e81-8150-ee2b5ce0991c'::uuid),
  ('6b3d8129-4e74-427d-8679-fec97a59edf9'::uuid),
  ('f3bd0d9e-e883-4e90-afff-f896f5ff7eed'::uuid),
  ('09ac151d-4d3d-4e10-abf3-dacd09ccc458'::uuid),
  ('9afe6d94-3d63-444f-86af-b67242ee5f2c'::uuid),
  ('353f9e44-bce1-4cb5-87bf-e07e0ff19720'::uuid),
  ('d7bfdda2-754a-4a30-bd02-c0f1ab0c7e5f'::uuid),
  ('07632fca-8008-416c-8153-6c67e7fae95e'::uuid),
  ('7436f2e6-7fa4-43ad-a398-ccea1590c1d9'::uuid),
  ('62989c87-515f-40b1-9e8b-6d3593d98b4a'::uuid),
  ('dc3a1b43-a420-4909-8a08-c8ab704109b9'::uuid),
  ('dbe03771-64c2-4371-bc3c-6d128546279e'::uuid),
  ('1d018053-75fb-495f-9f47-9697d382a793'::uuid),
  ('23b6ac08-96ed-4909-976c-38a19cbeb1b2'::uuid),
  ('deb3d972-fc5b-435a-843a-69e771af84af'::uuid),
  ('26e8c71e-1f5d-41e1-98e2-69db1a4c72d7'::uuid),
  ('f1628756-8769-4534-95f6-6103a6b92ced'::uuid),
  ('c84547b4-13af-4c59-b1e2-705b8e35f921'::uuid),
  ('fd44cc09-ad3a-4862-a8f3-358b09442100'::uuid),
  ('cebf09b7-e9ef-4acc-a88e-621172f217a2'::uuid),
  ('4c392015-0a3a-4ca2-ae9d-9a381d4f2f26'::uuid),
  ('00601f31-fce2-488c-b53b-bb06af1a5129'::uuid),
  ('b7dee7e9-6ec4-4479-833a-c35d69c0a720'::uuid),
  ('e609f1a4-6515-4a03-bf6c-ed7db7de9fa2'::uuid),
  ('8e162cbb-be27-4fa3-aed5-9de2ee1ef5e4'::uuid),
  ('78418c56-7ddc-4a5e-984a-ac75e59c52a5'::uuid),
  ('9df6abd4-376d-4a2b-ae85-259113bab70f'::uuid),
  ('158fc5f9-bc36-4e7b-8cbd-f15faa8c076c'::uuid),
  ('bde7160c-cd2c-48ef-b730-5c53208e24e6'::uuid),
  ('c53cac8e-6ec0-4d42-940e-5450a1c96800'::uuid),
  ('4abb51e6-8dd8-4114-8c8d-0d211b48e0cc'::uuid),
  ('42ecd94f-e127-49ea-a588-8614da54d3fa'::uuid),
  ('e1876216-f429-4c16-b5c1-99b1c635ae56'::uuid),
  ('45bb46c9-a17e-4ce9-8c09-89c24c2e7170'::uuid),
  ('59656c9f-bb6c-449a-b6f8-7c03d5a23893'::uuid),
  ('0f60a3c5-4a73-4275-b4ab-9f40a8256b13'::uuid),
  ('fae9962c-ce4e-4f82-a72a-9ee6393cb56b'::uuid),
  ('34747081-c419-4dbe-86b4-3b3ac5a9c436'::uuid),
  ('bf2bf7d7-2cc0-4172-af1a-52e44d1a4ad3'::uuid),
  ('18be3512-264e-445a-a9e5-0005cea90e69'::uuid),
  ('d6a21d73-d2d2-4f98-8cee-07a5df5065ef'::uuid),
  ('3eb5c351-2927-4b4c-895c-8f244bdd573a'::uuid),
  ('65a086fb-e8d8-4b30-9056-2f18c67c013c'::uuid),
  ('e065563c-e101-4e4c-952b-fff36e447ffb'::uuid),
  ('d3504920-8c12-488b-9859-7a440cbc69f4'::uuid),
  ('48b7750c-27a7-4f4e-aef8-c325c4e91f14'::uuid),
  ('a402f956-6ddb-468d-9728-7af994739cde'::uuid),
  ('0ea0b9c7-8d5d-4d89-91d3-f4e104cd4ac8'::uuid),
  ('0bc482e1-13db-4875-b0f6-5494a6674cae'::uuid),
  ('a50d2100-0917-42c4-a6fd-1139b9214ae1'::uuid),
  ('a5503bd4-d492-40c8-bedb-bfd4ff0731b8'::uuid),
  ('fc64c900-ca95-4bd5-b101-356ce6ad63a7'::uuid),
  ('9ae312a6-88f0-4491-8bd4-e9e4ca09ccdc'::uuid),
  ('5434b9df-6c8c-4b1c-b9be-393272c8903b'::uuid),
  ('eefc2e1a-2ac3-4367-9d71-9e6dbdf88493'::uuid),
  ('e7efecb6-7e9c-4f84-a7b0-5129b5cca36d'::uuid),
  ('555de5b0-381d-4e31-a8dd-c8d4b6f4c6bb'::uuid),
  ('52fb76bc-d97e-4f9d-9a90-61f4ae55ea7e'::uuid),
  ('220d4fcb-6fa1-4cb2-aec1-09c3bdc78dda'::uuid),
  ('04d9c613-fd20-43a1-bee6-663b76e63395'::uuid),
  ('725c74ad-4780-4b4b-80a2-ec8e815bbeeb'::uuid),
  ('126ff457-a951-4cb9-abd9-3b8680619f49'::uuid),
  ('296d0291-7c69-47c7-94d9-2b30bc3064f5'::uuid),
  ('4025734a-9909-45c4-98f2-7466ee26277b'::uuid),
  ('b59c3436-0b6c-4191-b5d5-f5be7dfd792a'::uuid),
  ('31d7a693-2c77-438a-85e1-10994af385e5'::uuid),
  ('f7aebcaa-dc7a-4e83-bd45-ca90cff45393'::uuid),
  ('7b92ad82-4675-4ef0-9030-e4ff3650e28f'::uuid),
  ('8cbea30a-72af-4330-a977-4ded8221bdf9'::uuid),
  ('6639320d-aff0-41cb-a1b5-67f47b20c36f'::uuid),
  ('030f41c1-5e44-4fe3-a39c-bfd8f8f886cd'::uuid),
  ('baa8441c-69df-4d77-90f4-7eb2238a3c65'::uuid),
  ('963bad2a-253e-4540-994d-78f49d25598d'::uuid),
  ('2ef7046b-7b04-4377-bada-7b90ca31318a'::uuid),
  ('17d6a67a-43bc-4a38-ac47-0d328ff89dab'::uuid),
  ('da7ec343-eb33-40ce-9ac7-ebe2558e74ec'::uuid),
  ('eff611e9-cc28-40db-b1f8-1933ba7057b9'::uuid),
  ('c71b1e92-2b71-4cf2-a11e-372fc3d8c823'::uuid),
  ('e1ddc8f7-b05d-4a27-87cf-9b211f3c37bc'::uuid),
  ('c79b3246-90d1-404b-8705-5ebf11138fbf'::uuid),
  ('66aa5733-12dd-445a-819f-4bcf1c511dda'::uuid),
  ('9d5cf1ed-a250-4425-9c51-44d0b604c38d'::uuid),
  ('b1fd1b7c-0333-4a06-b313-2328263bf2ae'::uuid),
  ('0de26fad-6655-4e3a-8757-b45413e99285'::uuid),
  ('e8574766-729c-479a-801e-d060b4864abc'::uuid),
  ('e9c4e013-0bf0-4647-8df6-50c064cc71b5'::uuid),
  ('bd909dd1-3f20-4c41-bfd6-2a1ab47447aa'::uuid),
  ('7e98b88b-18dc-4300-90b8-370a82278004'::uuid),
  ('6e1cfbfe-a234-47eb-a936-43619740b664'::uuid),
  ('9da60232-18d9-429f-9ca2-de80b11316dd'::uuid),
  ('0f8b942b-259d-47f4-b75a-e71adf47d834'::uuid),
  ('f5f99254-9a4f-4210-b10f-7c4a80ad9c86'::uuid),
  ('569a3d8f-969d-4376-ba9c-0545c0532750'::uuid),
  ('ed920f77-45b2-4f5d-b480-6fe3fd83ba2e'::uuid),
  ('4285786c-32bc-40d9-88c2-56f271faa14a'::uuid),
  ('4a97fd0c-ead1-40ff-b72b-f72db8db94f6'::uuid),
  ('89ac0110-629b-43a5-9091-7d3d6eb7be72'::uuid),
  ('e7897d3f-beda-49c9-a333-0fdae2599a75'::uuid),
  ('1fd7f1f7-dcb8-40e4-876e-ad115843efd6'::uuid),
  ('afece356-4b03-44c3-85bd-ab2f19867892'::uuid),
  ('f37c5e48-08c1-4bef-bd6c-6531e62ebdfb'::uuid),
  ('a37451a1-97ab-4ac1-ba4e-f881c73c5749'::uuid),
  ('9440c05e-4cbe-4342-b37a-edd4a793b4bf'::uuid),
  ('3a8c2c17-a4e3-4202-a677-81496f7e0208'::uuid),
  ('8089480e-46fd-4c79-82ba-a38331c0cd9f'::uuid),
  ('dac47af5-d7a6-4d37-8ded-8bd9038bd559'::uuid),
  ('c8522329-84a5-43e0-8255-d139a541d302'::uuid),
  ('5a91857e-95a0-4022-9ac2-4f4722989f53'::uuid),
  ('656b467d-6cee-41f7-b9d9-2c5849bb5ffc'::uuid),
  ('6e1cd4c4-1d4b-4a30-9f8e-e8d7881f64cc'::uuid),
  ('6fb4a9b3-8c6c-476c-8e37-439fea8d5047'::uuid),
  ('a642c71b-fd08-46cc-8fba-7667877055f5'::uuid),
  ('2eeee3d1-3a08-4fc5-bc76-0d3163deafda'::uuid),
  ('89952d94-72ed-42aa-8e3e-48ad3fb75c5f'::uuid),
  ('90a58e16-548c-4f7b-ad7e-9bc8d9da932d'::uuid),
  ('5c8c3fa8-1080-4fd3-8db9-e7b8463154ed'::uuid),
  ('7ba52bba-5855-42e7-b242-9156e2be8faf'::uuid),
  ('042f0804-fa32-4be5-a829-ba05895f65dc'::uuid),
  ('32e69eac-34f4-4095-85e4-063304d249a0'::uuid),
  ('05b61414-f506-45f1-9b3e-317da6da6e64'::uuid),
  ('1083a435-2bff-45e5-8512-fe67c8403e6f'::uuid),
  ('2fa8e0e8-198a-4a2e-a7b2-f1cd861ed997'::uuid),
  ('cbb3e490-d066-4e3d-89d2-3caa295cdb4e'::uuid),
  ('22fc917d-bd9b-4be1-a5f1-89ae763d9a68'::uuid),
  ('16d69729-1560-4eb3-8e72-76753140dd4f'::uuid),
  ('76af4e15-16a0-4a16-997d-290ae7d65d14'::uuid),
  ('40551a74-e203-410c-a374-af67730aac46'::uuid),
  ('3c68e420-9476-4657-bf0f-e59dd7759746'::uuid),
  ('cf749361-9261-4c6b-a885-b9c3f08421e0'::uuid),
  ('ab486413-4c41-4f14-857c-3b47d404d07c'::uuid),
  ('3983f17b-d4fb-48e7-b4c8-1fa7f546ae28'::uuid),
  ('b67ee73e-9eb0-4308-b92a-317f0c45e92c'::uuid),
  ('80c02d16-7c45-4dc6-9065-e45c99758991'::uuid),
  ('556e8e51-fd9d-43c6-b049-347a593e684b'::uuid),
  ('61ef1070-2f8b-42e3-a4bb-b74b5528d0d9'::uuid),
  ('14acf598-f540-4b72-9e83-a4cb73451db9'::uuid),
  ('fb79552e-7a5c-4050-9254-3a8c85a68573'::uuid),
  ('06ea3c29-177b-43a3-9cd9-8c122e02f540'::uuid),
  ('47bbab13-e3ac-4a62-899d-88dc00e48063'::uuid),
  ('0b491846-60e1-4ac8-93e9-9969f55140bb'::uuid),
  ('44998dc0-8121-4006-856d-71757e185814'::uuid),
  ('8a676679-0c1e-4b4d-8e82-9f5c6c3f68cf'::uuid),
  ('53df8d63-35ad-444d-98b3-bd781d511ffa'::uuid),
  ('06f6d413-f377-45d2-b1f1-9e95d8b71919'::uuid),
  ('0b4de322-97e5-431b-b1ef-ab6377f79739'::uuid),
  ('a443dbf8-67f1-40c0-8b8d-0a0690ddf9bd'::uuid),
  ('848df86b-424a-42a6-9afd-3af096f416b1'::uuid),
  ('78653d1f-7825-4a5c-89a9-8ba515e1e941'::uuid),
  ('7629a045-e5e0-42e8-8499-6716162a5d51'::uuid),
  ('c96be57b-42ce-452f-8527-c12d0c96268b'::uuid),
  ('6ff5701f-4a35-43d9-8f4c-6fbdb142f2fd'::uuid),
  ('4cfbd68d-787e-4b19-aa98-7df26d1324d8'::uuid),
  ('d6b94a80-0eb3-4ff7-99cb-5b4d8589f3e8'::uuid),
  ('4b1f2b57-d6dc-4eb4-852f-8396cdb0ca27'::uuid),
  ('c7a749c8-ed23-4911-a7c8-0be469e07f55'::uuid),
  ('fea2cf6b-c29d-497f-99e9-b693dafaf31d'::uuid),
  ('f45ebf64-c14f-4860-a706-4815440b8921'::uuid),
  ('de045df3-850c-416d-a3f0-0fadde4f93fe'::uuid),
  ('a700aebe-0672-4a38-9fbd-f84a651d2ef7'::uuid),
  ('21646383-d334-4c9f-8d4b-34797c527f15'::uuid),
  ('1b4e2ebd-dd6a-4b8a-a957-ebc507d595cc'::uuid),
  ('6d9f7ce1-f781-411c-b62b-f70fa6510184'::uuid),
  ('95792ce0-0268-4a97-917b-1f45c17fddc1'::uuid),
  ('d046cf39-14fa-4042-befc-471f1007c44a'::uuid),
  ('5e3b7635-4a07-4a6f-b59b-3e2f3f9d22b5'::uuid),
  ('4b549e60-7c61-4b56-a697-1a2155b0e591'::uuid),
  ('4063baae-506e-4e6c-aea6-2e67aa7f0e58'::uuid),
  ('e9c32138-a7ea-4bb2-9f25-8ecc703d22b5'::uuid),
  ('685c3519-d821-4933-b216-3e350f9a3f67'::uuid),
  ('ef30d153-4233-447e-8a0a-71642a4d95da'::uuid),
  ('a2af9153-3365-454a-a8ff-0a39b53c12f2'::uuid)
    ) as expected_id(id)
    where exists (
      select 1 from public.learning_stages where id = expected_id.id
      union all
      select 1 from public.learning_questions where id = expected_id.id
      union all
      select 1 from public.learning_question_options where id = expected_id.id
    )
  ) then
    raise exception using errcode = '23505', message = 'grade2_tables_graphs_v1 child content identifier already exists';
  end if;
end
$preflight$;

insert into public.learning_units (id, course_id, unit_code, display_title, sort_order)
values ('41cf53c2-edf0-4585-958e-2d8804c5c443', '51000000-0000-4000-8000-000000000001', 'grade2-tables-graphs', '표와 그래프로 나타내요', 12);

insert into public.learning_unit_recommendation_metadata (
  unit_id, subject, recommended_start_level_code, recommended_end_level_code, parent_sort_order
)
select '41cf53c2-edf0-4585-958e-2d8804c5c443'::uuid, 'math', 'elementary_2', 'elementary_2', 11
where not exists (
  select 1
  from public.learning_unit_recommendation_metadata metadata
  where metadata.unit_id = '41cf53c2-edf0-4585-958e-2d8804c5c443'::uuid
);

insert into public.learning_content_versions (id, unit_id, version_no, content_hash)
values ('f37533f2-54b2-4a3d-99da-88ba28dc7af9', '41cf53c2-edf0-4585-958e-2d8804c5c443', 1, '2c516217b25218b0cc29df4113a5dc4d70b9505ff48b7c7e61339b3d6bc7f16b');

insert into public.learning_stages (id, content_version_id, display_order, display_title, difficulty)
values
  ('759bb6b4-b331-4ee9-b0ba-93503eaa0c32', 'f37533f2-54b2-4a3d-99da-88ba28dc7af9', 1, '입문', 'seed'),
  ('6f1ff2c3-ac67-4b71-b001-7f92c5159fb0', 'f37533f2-54b2-4a3d-99da-88ba28dc7af9', 2, '기초', 'leaf'),
  ('3010579f-2808-4e34-b925-0985fd71f861', 'f37533f2-54b2-4a3d-99da-88ba28dc7af9', 3, '심화', 'tree'),
  ('19bb103e-bcc6-4ad1-9d30-5edd2e9fa4a8', 'f37533f2-54b2-4a3d-99da-88ba28dc7af9', 4, '최상위 도전!', 'crown');

insert into public.learning_questions (id, stage_id, display_order, prompt, explanation)
values
  ('35a77e27-be3d-47f4-80ea-45788de71de1', '759bb6b4-b331-4ee9-b0ba-93503eaa0c32', 1, '표: 사과 4개, 배 2개, 포도 3개. 가장 많은 것은?', '사과가 4개로 세 항목 중 가장 많습니다.'),
  ('84e42979-4280-477b-81ba-5a4abc706afb', '759bb6b4-b331-4ee9-b0ba-93503eaa0c32', 2, '표: 사과 5개, 배 3개, 포도 1개. 가장 많은 것은?', '사과가 5개로 세 항목 중 가장 많습니다.'),
  ('f340beba-3490-4b0a-8ff3-07b6ab0f5cff', '759bb6b4-b331-4ee9-b0ba-93503eaa0c32', 3, '표: 사과 2개, 배 6개, 포도 4개. 가장 많은 것은?', '배가 6개로 세 항목 중 가장 많습니다.'),
  ('ae6c8e7d-acca-4089-bc4a-020462c58222', '759bb6b4-b331-4ee9-b0ba-93503eaa0c32', 4, '표: 사과 7개, 배 3개, 포도 5개. 가장 많은 것은?', '사과가 7개로 세 항목 중 가장 많습니다.'),
  ('9dd39f79-6d2b-4c3b-8d56-b7e092be567f', '759bb6b4-b331-4ee9-b0ba-93503eaa0c32', 5, '표: 사과 3개, 배 4개, 포도 6개. 가장 많은 것은?', '포도가 6개로 세 항목 중 가장 많습니다.'),
  ('fbcab2eb-94fe-4155-8c3c-b45b07cb6c77', '759bb6b4-b331-4ee9-b0ba-93503eaa0c32', 6, '표: 사과 6개, 배 2개, 포도 5개. 가장 많은 것은?', '사과가 6개로 세 항목 중 가장 많습니다.'),
  ('0d0b9faf-7a78-4af2-9f94-0e920ef54818', '759bb6b4-b331-4ee9-b0ba-93503eaa0c32', 7, '표: 사과 4개, 배 7개, 포도 3개. 가장 많은 것은?', '배가 7개로 세 항목 중 가장 많습니다.'),
  ('926c7c17-4ba1-42e0-bae3-4c357ddaf561', '759bb6b4-b331-4ee9-b0ba-93503eaa0c32', 8, '표: 사과 5개, 배 1개, 포도 4개. 가장 많은 것은?', '사과가 5개로 세 항목 중 가장 많습니다.'),
  ('1173fb20-ed89-48fa-993e-a47550faf348', '759bb6b4-b331-4ee9-b0ba-93503eaa0c32', 9, '표: 사과 3개, 배 6개, 포도 2개. 가장 많은 것은?', '배가 6개로 세 항목 중 가장 많습니다.'),
  ('fabf9de0-b924-4b9b-853e-140a9d014175', '759bb6b4-b331-4ee9-b0ba-93503eaa0c32', 10, '표: 사과 8개, 배 4개, 포도 5개. 가장 많은 것은?', '사과가 8개로 세 항목 중 가장 많습니다.'),
  ('0e4a2adb-4935-48a1-b06f-006254a5658a', '6f1ff2c3-ac67-4b71-b001-7f92c5159fb0', 1, '표: 빨강 4명, 파랑 2명, 초록 3명. 조사한 사람은 모두 몇 명입니까?', '4+2+3=9이므로 모두 9명입니다.'),
  ('60bac9ce-ee2d-4b90-af39-7fbc50168f67', '6f1ff2c3-ac67-4b71-b001-7f92c5159fb0', 2, '표: 빨강 5명, 파랑 3명, 초록 1명. 조사한 사람은 모두 몇 명입니까?', '5+3+1=9이므로 모두 9명입니다.'),
  ('2fe691a0-008e-42ca-a7fb-dca2a18b04ef', '6f1ff2c3-ac67-4b71-b001-7f92c5159fb0', 3, '표: 빨강 2명, 파랑 6명, 초록 4명. 조사한 사람은 모두 몇 명입니까?', '2+6+4=12이므로 모두 12명입니다.'),
  ('11d371da-5af0-472e-8773-8ef5f85bd918', '6f1ff2c3-ac67-4b71-b001-7f92c5159fb0', 4, '표: 빨강 7명, 파랑 3명, 초록 5명. 조사한 사람은 모두 몇 명입니까?', '7+3+5=15이므로 모두 15명입니다.'),
  ('058cd8ea-4577-4ffc-bda3-60d96eadf603', '6f1ff2c3-ac67-4b71-b001-7f92c5159fb0', 5, '표: 빨강 3명, 파랑 4명, 초록 6명. 조사한 사람은 모두 몇 명입니까?', '3+4+6=13이므로 모두 13명입니다.'),
  ('dd59ed44-e971-4d1c-bf55-fd8f26d97a63', '6f1ff2c3-ac67-4b71-b001-7f92c5159fb0', 6, '표의 세 항목 수는 6개, 2개, 5개입니다. 가장 많은 것과 가장 적은 것의 차는?', '6-2=4이므로 차는 4개입니다.'),
  ('acac74bd-5289-49ce-a94e-cfc777cbcd69', '6f1ff2c3-ac67-4b71-b001-7f92c5159fb0', 7, '표의 세 항목 수는 4개, 7개, 3개입니다. 가장 많은 것과 가장 적은 것의 차는?', '7-3=4이므로 차는 4개입니다.'),
  ('ccbd5ba7-bbd1-474d-bd66-fd68c794fabe', '6f1ff2c3-ac67-4b71-b001-7f92c5159fb0', 8, '표의 세 항목 수는 5개, 1개, 4개입니다. 가장 많은 것과 가장 적은 것의 차는?', '5-1=4이므로 차는 4개입니다.'),
  ('f9f03be8-ba76-4dde-afbf-c01daa22f389', '6f1ff2c3-ac67-4b71-b001-7f92c5159fb0', 9, '표의 세 항목 수는 3개, 6개, 2개입니다. 가장 많은 것과 가장 적은 것의 차는?', '6-2=4이므로 차는 4개입니다.'),
  ('f25e7093-61d4-4449-b13c-86d8bb9a2c35', '6f1ff2c3-ac67-4b71-b001-7f92c5159fb0', 10, '표의 세 항목 수는 8개, 4개, 5개입니다. 가장 많은 것과 가장 적은 것의 차는?', '8-4=4이므로 차는 4개입니다.'),
  ('d3ef17d0-016f-4dce-89db-0b4b8499858d', '3010579f-2808-4e34-b925-0985fd71f861', 1, '표에서 A는 3개, B는 4개이고 전체는 12개입니다. C는 몇 개입니까?', '12-3-4=5이므로 C는 5개입니다.'),
  ('b2705a55-4316-4500-b111-acf2adbcdd75', '3010579f-2808-4e34-b925-0985fd71f861', 2, '표에서 A는 5개, B는 2개이고 전체는 11개입니다. C는 몇 개입니까?', '11-5-2=4이므로 C는 4개입니다.'),
  ('3879ee58-b9e7-47ee-937c-3210255f8440', '3010579f-2808-4e34-b925-0985fd71f861', 3, '표에서 A는 4개, B는 6개이고 전체는 15개입니다. C는 몇 개입니까?', '15-4-6=5이므로 C는 5개입니다.'),
  ('6465ac00-72da-413e-9d86-b2a58854f21d', '3010579f-2808-4e34-b925-0985fd71f861', 4, '표에서 A는 7개, B는 3개이고 전체는 14개입니다. C는 몇 개입니까?', '14-7-3=4이므로 C는 4개입니다.'),
  ('c2913ea9-78ef-4bea-9de2-a95a1e62959b', '3010579f-2808-4e34-b925-0985fd71f861', 5, '텍스트 그래프: 사과 ■■■■, 배 ■■, 포도 ■■■■■. 표로 옮긴 것은?', '■ 한 개가 1개를 뜻하므로 사과 4, 배 2, 포도 5입니다.'),
  ('b5abd324-fbd8-4408-89af-b489fc56415c', '3010579f-2808-4e34-b925-0985fd71f861', 6, '텍스트 그래프: 사과 ■■■, 배 ■■■■■■, 포도 ■. 표로 옮긴 것은?', '■ 한 개가 1개를 뜻하므로 사과 3, 배 6, 포도 1입니다.'),
  ('aa0692d3-090b-4b64-a790-5e3cfe76004b', '3010579f-2808-4e34-b925-0985fd71f861', 7, '텍스트 그래프: 사과 ■■■■■■■, 배 ■■■■, 포도 ■■. 표로 옮긴 것은?', '■ 한 개가 1개를 뜻하므로 사과 7, 배 4, 포도 2입니다.'),
  ('7eb4abc7-5ea7-4aae-88a7-fbd4efcb4cb9', '3010579f-2808-4e34-b925-0985fd71f861', 8, '그래프: A ■■, B ■■■■■, C ■■■■. 전체 표시 수는?', '2+5+4=11이므로 전체는 11개입니다.'),
  ('117fa599-6fb3-4fe6-b0c0-cdbb0533ab34', '3010579f-2808-4e34-b925-0985fd71f861', 9, '그래프: A ■■■■■■, B ■■■, C ■■■■■. 전체 표시 수는?', '6+3+5=14이므로 전체는 14개입니다.'),
  ('0695efd3-f02c-4e81-8150-ee2b5ce0991c', '3010579f-2808-4e34-b925-0985fd71f861', 10, '그래프: A ■■■■, B ■■■■■■■, C ■■. 전체 표시 수는?', '4+7+2=13이므로 전체는 13개입니다.'),
  ('6b3d8129-4e74-427d-8679-fec97a59edf9', '19bb103e-bcc6-4ad1-9d30-5edd2e9fa4a8', 1, '표: 축구 6명, 야구 4명, 농구 3명. “야구가 가장 많다”는 해석을 바르게 고친 것은?', '6이 4와 3보다 크므로 축구가 가장 많습니다.'),
  ('f3bd0d9e-e883-4e90-afff-f896f5ff7eed', '19bb103e-bcc6-4ad1-9d30-5edd2e9fa4a8', 2, '표의 합계가 15이고 A 5개, B 6개입니다. C를 5개라고 쓴 오류를 고친 것은?', '전체에서 A와 B를 빼면 15-5-6=4개입니다.'),
  ('09ac151d-4d3d-4e10-abf3-dacd09ccc458', '19bb103e-bcc6-4ad1-9d30-5edd2e9fa4a8', 3, '그래프에서 ■ 한 개가 1명을 뜻합니다. 민수 ■■■, 지우 ■■■■■일 때 바른 해석은?', '지우 5명에서 민수 3명을 빼면 2명이므로 지우가 2명 많습니다.'),
  ('9afe6d94-3d63-444f-86af-b67242ee5f2c', '19bb103e-bcc6-4ad1-9d30-5edd2e9fa4a8', 4, '자료 사과·사과·배·포도·사과를 표로 나타낸 것은?', '자료를 하나씩 세면 사과 3개, 배 1개, 포도 1개입니다.'),
  ('353f9e44-bce1-4cb5-87bf-e07e0ff19720', '19bb103e-bcc6-4ad1-9d30-5edd2e9fa4a8', 5, '표 A 4개, B 7개, C 5개와 같은 그래프는?', '표의 수만큼 ■를 대응시키면 A 4개, B 7개, C 5개입니다.'),
  ('d7bfdda2-754a-4a30-bd02-c0f1ab0c7e5f', '19bb103e-bcc6-4ad1-9d30-5edd2e9fa4a8', 6, '가장 많은 항목 8개와 가장 적은 항목 3개의 차를 11개라고 했습니다. 바른 설명은?', '차이는 더하지 않고 큰 수에서 작은 수를 빼므로 5개입니다.'),
  ('07632fca-8008-416c-8153-6c67e7fae95e', '19bb103e-bcc6-4ad1-9d30-5edd2e9fa4a8', 7, '표 A 2개, B □개, C 6개이고 전체 13개입니다. □와 설명이 맞는 것은?', '전체 13개에서 A 2개와 C 6개를 빼면 B는 5개입니다.'),
  ('7436f2e6-7fa4-43ad-a398-ccea1590c1d9', '19bb103e-bcc6-4ad1-9d30-5edd2e9fa4a8', 8, '그래프 A ■■■■■, B ■■, C ■■■■를 바르게 설명한 것은?', 'A는 5개로 가장 많고 B는 2개로 가장 적습니다.'),
  ('62989c87-515f-40b1-9e8b-6d3593d98b4a', '19bb103e-bcc6-4ad1-9d30-5edd2e9fa4a8', 9, '표를 만들 때 같은 항목을 빠뜨렸습니다. 가장 알맞은 점검 방법은?', '원자료의 개수와 표의 합계가 같아야 빠진 자료가 없는지 확인할 수 있습니다.'),
  ('dc3a1b43-a420-4909-8a08-c8ab704109b9', '19bb103e-bcc6-4ad1-9d30-5edd2e9fa4a8', 10, '표 A 3, B 5, C 4를 보고 “전체는 9”라고 했습니다. 바르게 고친 것은?', '전체는 모든 항목을 더해야 하므로 3+5+4=12입니다.');

insert into public.learning_question_options (id, question_id, display_order, option_text, is_correct)
values
  ('dbe03771-64c2-4371-bc3c-6d128546279e', '35a77e27-be3d-47f4-80ea-45788de71de1', 1, '사과', true),
  ('1d018053-75fb-495f-9f47-9697d382a793', '35a77e27-be3d-47f4-80ea-45788de71de1', 2, '배', false),
  ('23b6ac08-96ed-4909-976c-38a19cbeb1b2', '35a77e27-be3d-47f4-80ea-45788de71de1', 3, '포도', false),
  ('deb3d972-fc5b-435a-843a-69e771af84af', '35a77e27-be3d-47f4-80ea-45788de71de1', 4, '모두 같음', false),
  ('26e8c71e-1f5d-41e1-98e2-69db1a4c72d7', '84e42979-4280-477b-81ba-5a4abc706afb', 1, '배', false),
  ('f1628756-8769-4534-95f6-6103a6b92ced', '84e42979-4280-477b-81ba-5a4abc706afb', 2, '사과', true),
  ('c84547b4-13af-4c59-b1e2-705b8e35f921', '84e42979-4280-477b-81ba-5a4abc706afb', 3, '포도', false),
  ('fd44cc09-ad3a-4862-a8f3-358b09442100', '84e42979-4280-477b-81ba-5a4abc706afb', 4, '모두 같음', false),
  ('cebf09b7-e9ef-4acc-a88e-621172f217a2', 'f340beba-3490-4b0a-8ff3-07b6ab0f5cff', 1, '사과', false),
  ('4c392015-0a3a-4ca2-ae9d-9a381d4f2f26', 'f340beba-3490-4b0a-8ff3-07b6ab0f5cff', 2, '포도', false),
  ('00601f31-fce2-488c-b53b-bb06af1a5129', 'f340beba-3490-4b0a-8ff3-07b6ab0f5cff', 3, '배', true),
  ('b7dee7e9-6ec4-4479-833a-c35d69c0a720', 'f340beba-3490-4b0a-8ff3-07b6ab0f5cff', 4, '모두 같음', false),
  ('e609f1a4-6515-4a03-bf6c-ed7db7de9fa2', 'ae6c8e7d-acca-4089-bc4a-020462c58222', 1, '배', false),
  ('8e162cbb-be27-4fa3-aed5-9de2ee1ef5e4', 'ae6c8e7d-acca-4089-bc4a-020462c58222', 2, '포도', false),
  ('78418c56-7ddc-4a5e-984a-ac75e59c52a5', 'ae6c8e7d-acca-4089-bc4a-020462c58222', 3, '모두 같음', false),
  ('9df6abd4-376d-4a2b-ae85-259113bab70f', 'ae6c8e7d-acca-4089-bc4a-020462c58222', 4, '사과', true),
  ('158fc5f9-bc36-4e7b-8cbd-f15faa8c076c', '9dd39f79-6d2b-4c3b-8d56-b7e092be567f', 1, '포도', true),
  ('bde7160c-cd2c-48ef-b730-5c53208e24e6', '9dd39f79-6d2b-4c3b-8d56-b7e092be567f', 2, '사과', false),
  ('c53cac8e-6ec0-4d42-940e-5450a1c96800', '9dd39f79-6d2b-4c3b-8d56-b7e092be567f', 3, '배', false),
  ('4abb51e6-8dd8-4114-8c8d-0d211b48e0cc', '9dd39f79-6d2b-4c3b-8d56-b7e092be567f', 4, '모두 같음', false),
  ('42ecd94f-e127-49ea-a588-8614da54d3fa', 'fbcab2eb-94fe-4155-8c3c-b45b07cb6c77', 1, '배', false),
  ('e1876216-f429-4c16-b5c1-99b1c635ae56', 'fbcab2eb-94fe-4155-8c3c-b45b07cb6c77', 2, '사과', true),
  ('45bb46c9-a17e-4ce9-8c09-89c24c2e7170', 'fbcab2eb-94fe-4155-8c3c-b45b07cb6c77', 3, '포도', false),
  ('59656c9f-bb6c-449a-b6f8-7c03d5a23893', 'fbcab2eb-94fe-4155-8c3c-b45b07cb6c77', 4, '모두 같음', false),
  ('0f60a3c5-4a73-4275-b4ab-9f40a8256b13', '0d0b9faf-7a78-4af2-9f94-0e920ef54818', 1, '배', true),
  ('fae9962c-ce4e-4f82-a72a-9ee6393cb56b', '0d0b9faf-7a78-4af2-9f94-0e920ef54818', 2, '사과', false),
  ('34747081-c419-4dbe-86b4-3b3ac5a9c436', '0d0b9faf-7a78-4af2-9f94-0e920ef54818', 3, '포도', false),
  ('bf2bf7d7-2cc0-4172-af1a-52e44d1a4ad3', '0d0b9faf-7a78-4af2-9f94-0e920ef54818', 4, '모두 같음', false),
  ('18be3512-264e-445a-a9e5-0005cea90e69', '926c7c17-4ba1-42e0-bae3-4c357ddaf561', 1, '배', false),
  ('d6a21d73-d2d2-4f98-8cee-07a5df5065ef', '926c7c17-4ba1-42e0-bae3-4c357ddaf561', 2, '사과', true),
  ('3eb5c351-2927-4b4c-895c-8f244bdd573a', '926c7c17-4ba1-42e0-bae3-4c357ddaf561', 3, '포도', false),
  ('65a086fb-e8d8-4b30-9056-2f18c67c013c', '926c7c17-4ba1-42e0-bae3-4c357ddaf561', 4, '모두 같음', false),
  ('e065563c-e101-4e4c-952b-fff36e447ffb', '1173fb20-ed89-48fa-993e-a47550faf348', 1, '사과', false),
  ('d3504920-8c12-488b-9859-7a440cbc69f4', '1173fb20-ed89-48fa-993e-a47550faf348', 2, '포도', false),
  ('48b7750c-27a7-4f4e-aef8-c325c4e91f14', '1173fb20-ed89-48fa-993e-a47550faf348', 3, '배', true),
  ('a402f956-6ddb-468d-9728-7af994739cde', '1173fb20-ed89-48fa-993e-a47550faf348', 4, '모두 같음', false),
  ('0ea0b9c7-8d5d-4d89-91d3-f4e104cd4ac8', 'fabf9de0-b924-4b9b-853e-140a9d014175', 1, '배', false),
  ('0bc482e1-13db-4875-b0f6-5494a6674cae', 'fabf9de0-b924-4b9b-853e-140a9d014175', 2, '포도', false),
  ('a50d2100-0917-42c4-a6fd-1139b9214ae1', 'fabf9de0-b924-4b9b-853e-140a9d014175', 3, '모두 같음', false),
  ('a5503bd4-d492-40c8-bedb-bfd4ff0731b8', 'fabf9de0-b924-4b9b-853e-140a9d014175', 4, '사과', true),
  ('fc64c900-ca95-4bd5-b101-356ce6ad63a7', '0e4a2adb-4935-48a1-b06f-006254a5658a', 1, '9명', true),
  ('9ae312a6-88f0-4491-8bd4-e9e4ca09ccdc', '0e4a2adb-4935-48a1-b06f-006254a5658a', 2, '10명', false),
  ('5434b9df-6c8c-4b1c-b9be-393272c8903b', '0e4a2adb-4935-48a1-b06f-006254a5658a', 3, '8명', false),
  ('eefc2e1a-2ac3-4367-9d71-9e6dbdf88493', '0e4a2adb-4935-48a1-b06f-006254a5658a', 4, '19명', false),
  ('e7efecb6-7e9c-4f84-a7b0-5129b5cca36d', '60bac9ce-ee2d-4b90-af39-7fbc50168f67', 1, '10명', false),
  ('555de5b0-381d-4e31-a8dd-c8d4b6f4c6bb', '60bac9ce-ee2d-4b90-af39-7fbc50168f67', 2, '9명', true),
  ('52fb76bc-d97e-4f9d-9a90-61f4ae55ea7e', '60bac9ce-ee2d-4b90-af39-7fbc50168f67', 3, '8명', false),
  ('220d4fcb-6fa1-4cb2-aec1-09c3bdc78dda', '60bac9ce-ee2d-4b90-af39-7fbc50168f67', 4, '19명', false),
  ('04d9c613-fd20-43a1-bee6-663b76e63395', '2fe691a0-008e-42ca-a7fb-dca2a18b04ef', 1, '13명', false),
  ('725c74ad-4780-4b4b-80a2-ec8e815bbeeb', '2fe691a0-008e-42ca-a7fb-dca2a18b04ef', 2, '11명', false),
  ('126ff457-a951-4cb9-abd9-3b8680619f49', '2fe691a0-008e-42ca-a7fb-dca2a18b04ef', 3, '12명', true),
  ('296d0291-7c69-47c7-94d9-2b30bc3064f5', '2fe691a0-008e-42ca-a7fb-dca2a18b04ef', 4, '22명', false),
  ('4025734a-9909-45c4-98f2-7466ee26277b', '11d371da-5af0-472e-8773-8ef5f85bd918', 1, '16명', false),
  ('b59c3436-0b6c-4191-b5d5-f5be7dfd792a', '11d371da-5af0-472e-8773-8ef5f85bd918', 2, '14명', false),
  ('31d7a693-2c77-438a-85e1-10994af385e5', '11d371da-5af0-472e-8773-8ef5f85bd918', 3, '25명', false),
  ('f7aebcaa-dc7a-4e83-bd45-ca90cff45393', '11d371da-5af0-472e-8773-8ef5f85bd918', 4, '15명', true),
  ('7b92ad82-4675-4ef0-9030-e4ff3650e28f', '058cd8ea-4577-4ffc-bda3-60d96eadf603', 1, '14명', false),
  ('8cbea30a-72af-4330-a977-4ded8221bdf9', '058cd8ea-4577-4ffc-bda3-60d96eadf603', 2, '12명', false),
  ('6639320d-aff0-41cb-a1b5-67f47b20c36f', '058cd8ea-4577-4ffc-bda3-60d96eadf603', 3, '13명', true),
  ('030f41c1-5e44-4fe3-a39c-bfd8f8f886cd', '058cd8ea-4577-4ffc-bda3-60d96eadf603', 4, '23명', false),
  ('baa8441c-69df-4d77-90f4-7eb2238a3c65', 'dd59ed44-e971-4d1c-bf55-fd8f26d97a63', 1, '5개', false),
  ('963bad2a-253e-4540-994d-78f49d25598d', 'dd59ed44-e971-4d1c-bf55-fd8f26d97a63', 2, '3개', false),
  ('2ef7046b-7b04-4377-bada-7b90ca31318a', 'dd59ed44-e971-4d1c-bf55-fd8f26d97a63', 3, '14개', false),
  ('17d6a67a-43bc-4a38-ac47-0d328ff89dab', 'dd59ed44-e971-4d1c-bf55-fd8f26d97a63', 4, '4개', true),
  ('da7ec343-eb33-40ce-9ac7-ebe2558e74ec', 'acac74bd-5289-49ce-a94e-cfc777cbcd69', 1, '4개', true),
  ('eff611e9-cc28-40db-b1f8-1933ba7057b9', 'acac74bd-5289-49ce-a94e-cfc777cbcd69', 2, '5개', false),
  ('c71b1e92-2b71-4cf2-a11e-372fc3d8c823', 'acac74bd-5289-49ce-a94e-cfc777cbcd69', 3, '3개', false),
  ('e1ddc8f7-b05d-4a27-87cf-9b211f3c37bc', 'acac74bd-5289-49ce-a94e-cfc777cbcd69', 4, '14개', false),
  ('c79b3246-90d1-404b-8705-5ebf11138fbf', 'ccbd5ba7-bbd1-474d-bd66-fd68c794fabe', 1, '5개', false),
  ('66aa5733-12dd-445a-819f-4bcf1c511dda', 'ccbd5ba7-bbd1-474d-bd66-fd68c794fabe', 2, '4개', true),
  ('9d5cf1ed-a250-4425-9c51-44d0b604c38d', 'ccbd5ba7-bbd1-474d-bd66-fd68c794fabe', 3, '3개', false),
  ('b1fd1b7c-0333-4a06-b313-2328263bf2ae', 'ccbd5ba7-bbd1-474d-bd66-fd68c794fabe', 4, '14개', false),
  ('0de26fad-6655-4e3a-8757-b45413e99285', 'f9f03be8-ba76-4dde-afbf-c01daa22f389', 1, '5개', false),
  ('e8574766-729c-479a-801e-d060b4864abc', 'f9f03be8-ba76-4dde-afbf-c01daa22f389', 2, '3개', false),
  ('e9c4e013-0bf0-4647-8df6-50c064cc71b5', 'f9f03be8-ba76-4dde-afbf-c01daa22f389', 3, '4개', true),
  ('bd909dd1-3f20-4c41-bfd6-2a1ab47447aa', 'f9f03be8-ba76-4dde-afbf-c01daa22f389', 4, '14개', false),
  ('7e98b88b-18dc-4300-90b8-370a82278004', 'f25e7093-61d4-4449-b13c-86d8bb9a2c35', 1, '5개', false),
  ('6e1cfbfe-a234-47eb-a936-43619740b664', 'f25e7093-61d4-4449-b13c-86d8bb9a2c35', 2, '3개', false),
  ('9da60232-18d9-429f-9ca2-de80b11316dd', 'f25e7093-61d4-4449-b13c-86d8bb9a2c35', 3, '14개', false),
  ('0f8b942b-259d-47f4-b75a-e71adf47d834', 'f25e7093-61d4-4449-b13c-86d8bb9a2c35', 4, '4개', true),
  ('f5f99254-9a4f-4210-b10f-7c4a80ad9c86', 'd3ef17d0-016f-4dce-89db-0b4b8499858d', 1, '5개', true),
  ('569a3d8f-969d-4376-ba9c-0545c0532750', 'd3ef17d0-016f-4dce-89db-0b4b8499858d', 2, '6개', false),
  ('ed920f77-45b2-4f5d-b480-6fe3fd83ba2e', 'd3ef17d0-016f-4dce-89db-0b4b8499858d', 3, '4개', false),
  ('4285786c-32bc-40d9-88c2-56f271faa14a', 'd3ef17d0-016f-4dce-89db-0b4b8499858d', 4, '15개', false),
  ('4a97fd0c-ead1-40ff-b72b-f72db8db94f6', 'b2705a55-4316-4500-b111-acf2adbcdd75', 1, '5개', false),
  ('89ac0110-629b-43a5-9091-7d3d6eb7be72', 'b2705a55-4316-4500-b111-acf2adbcdd75', 2, '4개', true),
  ('e7897d3f-beda-49c9-a333-0fdae2599a75', 'b2705a55-4316-4500-b111-acf2adbcdd75', 3, '3개', false),
  ('1fd7f1f7-dcb8-40e4-876e-ad115843efd6', 'b2705a55-4316-4500-b111-acf2adbcdd75', 4, '14개', false),
  ('afece356-4b03-44c3-85bd-ab2f19867892', '3879ee58-b9e7-47ee-937c-3210255f8440', 1, '6개', false),
  ('f37c5e48-08c1-4bef-bd6c-6531e62ebdfb', '3879ee58-b9e7-47ee-937c-3210255f8440', 2, '4개', false),
  ('a37451a1-97ab-4ac1-ba4e-f881c73c5749', '3879ee58-b9e7-47ee-937c-3210255f8440', 3, '5개', true),
  ('9440c05e-4cbe-4342-b37a-edd4a793b4bf', '3879ee58-b9e7-47ee-937c-3210255f8440', 4, '15개', false),
  ('3a8c2c17-a4e3-4202-a677-81496f7e0208', '6465ac00-72da-413e-9d86-b2a58854f21d', 1, '5개', false),
  ('8089480e-46fd-4c79-82ba-a38331c0cd9f', '6465ac00-72da-413e-9d86-b2a58854f21d', 2, '3개', false),
  ('dac47af5-d7a6-4d37-8ded-8bd9038bd559', '6465ac00-72da-413e-9d86-b2a58854f21d', 3, '14개', false),
  ('c8522329-84a5-43e0-8255-d139a541d302', '6465ac00-72da-413e-9d86-b2a58854f21d', 4, '4개', true),
  ('5a91857e-95a0-4022-9ac2-4f4722989f53', 'c2913ea9-78ef-4bea-9de2-a95a1e62959b', 1, '사과 4, 배 2, 포도 5', true),
  ('656b467d-6cee-41f7-b9d9-2c5849bb5ffc', 'c2913ea9-78ef-4bea-9de2-a95a1e62959b', 2, '사과 2, 배 4, 포도 5', false),
  ('6e1cd4c4-1d4b-4a30-9f8e-e8d7881f64cc', 'c2913ea9-78ef-4bea-9de2-a95a1e62959b', 3, '사과 5, 배 2, 포도 5', false),
  ('6fb4a9b3-8c6c-476c-8e37-439fea8d5047', 'c2913ea9-78ef-4bea-9de2-a95a1e62959b', 4, '사과 4, 배 3, 포도 5', false),
  ('a642c71b-fd08-46cc-8fba-7667877055f5', 'b5abd324-fbd8-4408-89af-b489fc56415c', 1, '사과 6, 배 3, 포도 1', false),
  ('2eeee3d1-3a08-4fc5-bc76-0d3163deafda', 'b5abd324-fbd8-4408-89af-b489fc56415c', 2, '사과 3, 배 6, 포도 1', true),
  ('89952d94-72ed-42aa-8e3e-48ad3fb75c5f', 'b5abd324-fbd8-4408-89af-b489fc56415c', 3, '사과 4, 배 6, 포도 1', false),
  ('90a58e16-548c-4f7b-ad7e-9bc8d9da932d', 'b5abd324-fbd8-4408-89af-b489fc56415c', 4, '사과 3, 배 7, 포도 1', false),
  ('5c8c3fa8-1080-4fd3-8db9-e7b8463154ed', 'aa0692d3-090b-4b64-a790-5e3cfe76004b', 1, '사과 7, 배 4, 포도 2', true),
  ('7ba52bba-5855-42e7-b242-9156e2be8faf', 'aa0692d3-090b-4b64-a790-5e3cfe76004b', 2, '사과 4, 배 7, 포도 2', false),
  ('042f0804-fa32-4be5-a829-ba05895f65dc', 'aa0692d3-090b-4b64-a790-5e3cfe76004b', 3, '사과 8, 배 4, 포도 2', false),
  ('32e69eac-34f4-4095-85e4-063304d249a0', 'aa0692d3-090b-4b64-a790-5e3cfe76004b', 4, '사과 7, 배 5, 포도 2', false),
  ('05b61414-f506-45f1-9b3e-317da6da6e64', '7eb4abc7-5ea7-4aae-88a7-fbd4efcb4cb9', 1, '12개', false),
  ('1083a435-2bff-45e5-8512-fe67c8403e6f', '7eb4abc7-5ea7-4aae-88a7-fbd4efcb4cb9', 2, '11개', true),
  ('2fa8e0e8-198a-4a2e-a7b2-f1cd861ed997', '7eb4abc7-5ea7-4aae-88a7-fbd4efcb4cb9', 3, '10개', false),
  ('cbb3e490-d066-4e3d-89d2-3caa295cdb4e', '7eb4abc7-5ea7-4aae-88a7-fbd4efcb4cb9', 4, '21개', false),
  ('22fc917d-bd9b-4be1-a5f1-89ae763d9a68', '117fa599-6fb3-4fe6-b0c0-cdbb0533ab34', 1, '15개', false),
  ('16d69729-1560-4eb3-8e72-76753140dd4f', '117fa599-6fb3-4fe6-b0c0-cdbb0533ab34', 2, '13개', false),
  ('76af4e15-16a0-4a16-997d-290ae7d65d14', '117fa599-6fb3-4fe6-b0c0-cdbb0533ab34', 3, '14개', true),
  ('40551a74-e203-410c-a374-af67730aac46', '117fa599-6fb3-4fe6-b0c0-cdbb0533ab34', 4, '24개', false),
  ('3c68e420-9476-4657-bf0f-e59dd7759746', '0695efd3-f02c-4e81-8150-ee2b5ce0991c', 1, '14개', false),
  ('cf749361-9261-4c6b-a885-b9c3f08421e0', '0695efd3-f02c-4e81-8150-ee2b5ce0991c', 2, '12개', false),
  ('ab486413-4c41-4f14-857c-3b47d404d07c', '0695efd3-f02c-4e81-8150-ee2b5ce0991c', 3, '23개', false),
  ('3983f17b-d4fb-48e7-b4c8-1fa7f546ae28', '0695efd3-f02c-4e81-8150-ee2b5ce0991c', 4, '13개', true),
  ('b67ee73e-9eb0-4308-b92a-317f0c45e92c', '6b3d8129-4e74-427d-8679-fec97a59edf9', 1, '축구가 6명으로 가장 많습니다.', true),
  ('80c02d16-7c45-4dc6-9065-e45c99758991', '6b3d8129-4e74-427d-8679-fec97a59edf9', 2, '야구가 4명으로 가장 많습니다.', false),
  ('556e8e51-fd9d-43c6-b049-347a593e684b', '6b3d8129-4e74-427d-8679-fec97a59edf9', 3, '농구가 6명으로 가장 많습니다.', false),
  ('61ef1070-2f8b-42e3-a4bb-b74b5528d0d9', '6b3d8129-4e74-427d-8679-fec97a59edf9', 4, '세 운동은 모두 같습니다.', false),
  ('14acf598-f540-4b72-9e83-a4cb73451db9', 'f3bd0d9e-e883-4e90-afff-f896f5ff7eed', 1, 'C는 15+5+6=26개입니다.', false),
  ('fb79552e-7a5c-4050-9254-3a8c85a68573', 'f3bd0d9e-e883-4e90-afff-f896f5ff7eed', 2, 'C는 15-5-6=4개입니다.', true),
  ('06ea3c29-177b-43a3-9cd9-8c122e02f540', 'f3bd0d9e-e883-4e90-afff-f896f5ff7eed', 3, 'C는 6-5=1개입니다.', false),
  ('47bbab13-e3ac-4a62-899d-88dc00e48063', 'f3bd0d9e-e883-4e90-afff-f896f5ff7eed', 4, 'C는 5개가 맞습니다.', false),
  ('0b491846-60e1-4ac8-93e9-9969f55140bb', '09ac151d-4d3d-4e10-abf3-dacd09ccc458', 1, '민수가 2명 많습니다.', false),
  ('44998dc0-8121-4006-856d-71757e185814', '09ac151d-4d3d-4e10-abf3-dacd09ccc458', 2, '두 사람은 같습니다.', false),
  ('8a676679-0c1e-4b4d-8e82-9f5c6c3f68cf', '09ac151d-4d3d-4e10-abf3-dacd09ccc458', 3, '지우가 민수보다 2명 많습니다.', true),
  ('53df8d63-35ad-444d-98b3-bd781d511ffa', '09ac151d-4d3d-4e10-abf3-dacd09ccc458', 4, '지우가 8명 많습니다.', false),
  ('06f6d413-f377-45d2-b1f1-9e95d8b71919', '9afe6d94-3d63-444f-86af-b67242ee5f2c', 1, '사과 2, 배 2, 포도 1', false),
  ('0b4de322-97e5-431b-b1ef-ab6377f79739', '9afe6d94-3d63-444f-86af-b67242ee5f2c', 2, '사과 3, 배 2, 포도 0', false),
  ('a443dbf8-67f1-40c0-8b8d-0a0690ddf9bd', '9afe6d94-3d63-444f-86af-b67242ee5f2c', 3, '사과 1, 배 1, 포도 3', false),
  ('848df86b-424a-42a6-9afd-3af096f416b1', '9afe6d94-3d63-444f-86af-b67242ee5f2c', 4, '사과 3, 배 1, 포도 1', true),
  ('78653d1f-7825-4a5c-89a9-8ba515e1e941', '353f9e44-bce1-4cb5-87bf-e07e0ff19720', 1, 'A ■■■■■■■, B ■■■■, C ■■■■■', false),
  ('7629a045-e5e0-42e8-8499-6716162a5d51', '353f9e44-bce1-4cb5-87bf-e07e0ff19720', 2, 'A ■■■■, B ■■■■■■, C ■■■■■', false),
  ('c96be57b-42ce-452f-8527-c12d0c96268b', '353f9e44-bce1-4cb5-87bf-e07e0ff19720', 3, 'A ■■■■, B ■■■■■■■, C ■■■■■', true),
  ('6ff5701f-4a35-43d9-8f4c-6fbdb142f2fd', '353f9e44-bce1-4cb5-87bf-e07e0ff19720', 4, 'A ■■■■, B ■■■■■■■, C ■■■', false),
  ('4cfbd68d-787e-4b19-aa98-7df26d1324d8', 'd7bfdda2-754a-4a30-bd02-c0f1ab0c7e5f', 1, '차는 8+3=11개입니다.', false),
  ('d6b94a80-0eb3-4ff7-99cb-5b4d8589f3e8', 'd7bfdda2-754a-4a30-bd02-c0f1ab0c7e5f', 2, '차는 3-8=5명입니다.', false),
  ('4b1f2b57-d6dc-4eb4-852f-8396cdb0ca27', 'd7bfdda2-754a-4a30-bd02-c0f1ab0c7e5f', 3, '차는 8-3=6개입니다.', false),
  ('c7a749c8-ed23-4911-a7c8-0be469e07f55', 'd7bfdda2-754a-4a30-bd02-c0f1ab0c7e5f', 4, '차는 8-3=5개입니다.', true),
  ('fea2cf6b-c29d-497f-99e9-b693dafaf31d', '07632fca-8008-416c-8153-6c67e7fae95e', 1, '5개이며 13-2-6=5입니다.', true),
  ('f45ebf64-c14f-4860-a706-4815440b8921', '07632fca-8008-416c-8153-6c67e7fae95e', 2, '9개이며 13-2=11입니다.', false),
  ('de045df3-850c-416d-a3f0-0fadde4f93fe', '07632fca-8008-416c-8153-6c67e7fae95e', 3, '3개이며 6-2=4입니다.', false),
  ('a700aebe-0672-4a38-9fbd-f84a651d2ef7', '07632fca-8008-416c-8153-6c67e7fae95e', 4, '21개이며 모두 더합니다.', false),
  ('21646383-d334-4c9f-8d4b-34797c527f15', '7436f2e6-7fa4-43ad-a398-ccea1590c1d9', 1, 'B가 가장 많습니다.', false),
  ('1b4e2ebd-dd6a-4b8a-a957-ebc507d595cc', '7436f2e6-7fa4-43ad-a398-ccea1590c1d9', 2, 'A가 가장 많고 B가 가장 적습니다.', true),
  ('6d9f7ce1-f781-411c-b62b-f70fa6510184', '7436f2e6-7fa4-43ad-a398-ccea1590c1d9', 3, 'C가 가장 적습니다.', false),
  ('95792ce0-0268-4a97-917b-1f45c17fddc1', '7436f2e6-7fa4-43ad-a398-ccea1590c1d9', 4, 'A와 C가 같습니다.', false),
  ('d046cf39-14fa-4042-befc-471f1007c44a', '62989c87-515f-40b1-9e8b-6d3593d98b4a', 1, '가장 큰 수만 봅니다.', false),
  ('5e3b7635-4a07-4a6f-b59b-3e2f3f9d22b5', '62989c87-515f-40b1-9e8b-6d3593d98b4a', 2, '항목 이름을 모두 지웁니다.', false),
  ('4b549e60-7c61-4b56-a697-1a2155b0e591', '62989c87-515f-40b1-9e8b-6d3593d98b4a', 3, '원자료 수와 표의 전체 수를 비교합니다.', true),
  ('4063baae-506e-4e6c-aea6-2e67aa7f0e58', '62989c87-515f-40b1-9e8b-6d3593d98b4a', 4, '아무 수나 하나 더합니다.', false),
  ('e9c32138-a7ea-4bb2-9f25-8ecc703d22b5', 'dc3a1b43-a420-4909-8a08-c8ab704109b9', 1, '5+4=9이므로 맞습니다.', false),
  ('685c3519-d821-4933-b216-3e350f9a3f67', 'dc3a1b43-a420-4909-8a08-c8ab704109b9', 2, '3+5=8이므로 전체는 8입니다.', false),
  ('ef30d153-4233-447e-8a0a-71642a4d95da', 'dc3a1b43-a420-4909-8a08-c8ab704109b9', 3, '5-3=2이므로 전체는 2입니다.', false),
  ('a2af9153-3365-454a-a8ff-0a39b53c12f2', 'dc3a1b43-a420-4909-8a08-c8ab704109b9', 4, '3+5+4=12이므로 전체는 12입니다.', true);

insert into public.learning_question_skills (
  question_id, skill_code, is_primary
)
values
  ('35a77e27-be3d-47f4-80ea-45788de71de1', 'find-most-least-category', true),
  ('84e42979-4280-477b-81ba-5a4abc706afb', 'find-most-least-category', true),
  ('f340beba-3490-4b0a-8ff3-07b6ab0f5cff', 'find-most-least-category', true),
  ('ae6c8e7d-acca-4089-bc4a-020462c58222', 'find-most-least-category', true),
  ('9dd39f79-6d2b-4c3b-8d56-b7e092be567f', 'find-most-least-category', true),
  ('fbcab2eb-94fe-4155-8c3c-b45b07cb6c77', 'find-most-least-category', true),
  ('0d0b9faf-7a78-4af2-9f94-0e920ef54818', 'find-most-least-category', true),
  ('926c7c17-4ba1-42e0-bae3-4c357ddaf561', 'find-most-least-category', true),
  ('1173fb20-ed89-48fa-993e-a47550faf348', 'find-most-least-category', true),
  ('fabf9de0-b924-4b9b-853e-140a9d014175', 'find-most-least-category', true),
  ('0e4a2adb-4935-48a1-b06f-006254a5658a', 'read-data-table', true),
  ('60bac9ce-ee2d-4b90-af39-7fbc50168f67', 'read-data-table', true),
  ('2fe691a0-008e-42ca-a7fb-dca2a18b04ef', 'read-data-table', true),
  ('11d371da-5af0-472e-8773-8ef5f85bd918', 'read-data-table', true),
  ('058cd8ea-4577-4ffc-bda3-60d96eadf603', 'read-data-table', true),
  ('dd59ed44-e971-4d1c-bf55-fd8f26d97a63', 'calculate-data-difference', true),
  ('acac74bd-5289-49ce-a94e-cfc777cbcd69', 'calculate-data-difference', true),
  ('ccbd5ba7-bbd1-474d-bd66-fd68c794fabe', 'calculate-data-difference', true),
  ('f9f03be8-ba76-4dde-afbf-c01daa22f389', 'calculate-data-difference', true),
  ('f25e7093-61d4-4449-b13c-86d8bb9a2c35', 'calculate-data-difference', true),
  ('d3ef17d0-016f-4dce-89db-0b4b8499858d', 'infer-missing-data', true),
  ('b2705a55-4316-4500-b111-acf2adbcdd75', 'infer-missing-data', true),
  ('3879ee58-b9e7-47ee-937c-3210255f8440', 'infer-missing-data', true),
  ('6465ac00-72da-413e-9d86-b2a58854f21d', 'infer-missing-data', true),
  ('c2913ea9-78ef-4bea-9de2-a95a1e62959b', 'connect-table-and-graph', true),
  ('b5abd324-fbd8-4408-89af-b489fc56415c', 'connect-table-and-graph', true),
  ('aa0692d3-090b-4b64-a790-5e3cfe76004b', 'connect-table-and-graph', true),
  ('7eb4abc7-5ea7-4aae-88a7-fbd4efcb4cb9', 'read-text-graph', true),
  ('117fa599-6fb3-4fe6-b0c0-cdbb0533ab34', 'read-text-graph', true),
  ('0695efd3-f02c-4e81-8150-ee2b5ce0991c', 'read-text-graph', true),
  ('6b3d8129-4e74-427d-8679-fec97a59edf9', 'correct-data-interpretation', true),
  ('f3bd0d9e-e883-4e90-afff-f896f5ff7eed', 'correct-data-interpretation', true),
  ('09ac151d-4d3d-4e10-abf3-dacd09ccc458', 'read-text-graph', true),
  ('9afe6d94-3d63-444f-86af-b67242ee5f2c', 'classify-by-given-rule', true),
  ('353f9e44-bce1-4cb5-87bf-e07e0ff19720', 'connect-table-and-graph', true),
  ('d7bfdda2-754a-4a30-bd02-c0f1ab0c7e5f', 'correct-data-interpretation', true),
  ('07632fca-8008-416c-8153-6c67e7fae95e', 'infer-missing-data', true),
  ('7436f2e6-7fa4-43ad-a398-ccea1590c1d9', 'find-most-least-category', true),
  ('62989c87-515f-40b1-9e8b-6d3593d98b4a', 'complete-data-table', true),
  ('dc3a1b43-a420-4909-8a08-c8ab704109b9', 'correct-data-interpretation', true);

select (public.publish_learning_content_version('f37533f2-54b2-4a3d-99da-88ba28dc7af9'::uuid)).id;

commit;
