-- Generated by scripts/generate-learning-content-migration.js.
-- Source: content/learning/math/grade2-multiplication-meaning-v1.json
-- Canonical content SHA-256: f97d31dbfa3be6b48d8836ebc31f947dae05a5df25bf05b6fcd5b37a8b666af1
-- Content-only and additive: no assignment, attempt, progress, first-pass, ledger, ACL, or Realtime changes.

begin;

do $preflight$
begin
  if exists (
    select 1 from public.learning_courses
    where (id = '51000000-0000-4000-8000-000000000001'::uuid or course_code = 'math-core')
      and not (
        id = '51000000-0000-4000-8000-000000000001'::uuid
        and course_code = 'math-core'
        and internal_name = '수학 기초 과정'
        and subject_name = '수학'
      )
  ) then
    raise exception using errcode = '23505', message = 'grade2_multiplication_meaning_v1 course identifier conflicts with different content';
  end if;

  if not exists (
    select 1 from public.learning_courses
    where id = '51000000-0000-4000-8000-000000000001'::uuid
      and course_code = 'math-core'
      and internal_name = '수학 기초 과정'
      and subject_name = '수학'
      and status = 'published'
  ) then
    raise exception using errcode = 'P0002', message = 'grade2_multiplication_meaning_v1 existing course is missing or changed';
  end if;

  if exists (
    select 1 from public.learning_units
    where id = '4c8f9c55-37a9-4bf6-a444-e4165f8f30fc'::uuid
       or unit_code = 'grade2-multiplication-meaning'
  ) then
    raise exception using errcode = '23505', message = 'grade2_multiplication_meaning_v1 unit identifier already exists';
  end if;

  if exists (
    select 1 from public.learning_units
    where course_id = '51000000-0000-4000-8000-000000000001'::uuid
      and sort_order = 7
  ) then
    raise exception using errcode = '23505', message = 'grade2_multiplication_meaning_v1 unit sort order already exists';
  end if;

  if to_regclass('public.learning_unit_recommendation_metadata') is null then
    raise exception using errcode = 'P0002', message = 'learning recommendation metadata table is missing';
  end if;

  if exists (
    select 1
    from public.learning_unit_recommendation_metadata metadata
    where metadata.unit_id = '4c8f9c55-37a9-4bf6-a444-e4165f8f30fc'::uuid
      and (
        metadata.subject is distinct from 'math'
        or metadata.recommended_start_level_code is distinct from 'elementary_2'
        or metadata.recommended_end_level_code is distinct from 'elementary_2'
        or metadata.parent_sort_order is distinct from 6
      )
  ) then
    raise exception using errcode = '23505', message = 'learning unit recommendation metadata conflicts with different content';
  end if;

  if to_regclass('public.learning_skill_definitions') is null
     or to_regclass('public.learning_question_skills') is null then
    raise exception using errcode = 'P0002', message = 'learning skill metadata foundation is missing';
  end if;

  if exists (
    select 1
    from (values
  ('identify-equal-groups'),
  ('count-equal-groups'),
  ('connect-repeated-addition-to-multiplication'),
  ('represent-equal-groups-as-multiplication'),
  ('model-multiplication-situation'),
  ('interpret-multiplication-expression'),
  ('infer-missing-group-value'),
  ('correct-multiplication-reasoning')
    ) expected_skill(skill_code)
    where not exists (
      select 1 from public.learning_skill_definitions definition
      where definition.skill_code = expected_skill.skill_code
    )
  ) then
    raise exception using errcode = 'P0002', message = 'learning skill definition is missing';
  end if;

  if exists (
    select 1 from public.learning_content_versions
    where id = '8eb41f37-e2f1-42e9-a1c8-657ca08c9302'::uuid
       or content_hash = 'f97d31dbfa3be6b48d8836ebc31f947dae05a5df25bf05b6fcd5b37a8b666af1'
  ) then
    raise exception using errcode = '23505', message = 'grade2_multiplication_meaning_v1 content version already exists';
  end if;

  if exists (
    select 1 from (
      values
  ('70a00c90-97e8-45ab-a7a8-33fa4430549d'::uuid),
  ('fa6ae6ea-128b-4559-9d63-cd26d951919d'::uuid),
  ('88c82137-760d-4e35-a407-046a5eb0ba6c'::uuid),
  ('6559b39d-f80a-4ed6-a5e7-01c5e800e210'::uuid),
  ('aaee2904-d460-458c-a536-6699ab430e33'::uuid),
  ('9ff12a7a-6bfa-4f9b-bf52-6455145d7927'::uuid),
  ('ec504283-f43e-4a52-a24d-e90103d6e59a'::uuid),
  ('ec5be058-8a68-4c33-a2ef-df7895ba2a66'::uuid),
  ('c04873bf-6a7f-406a-846c-ba947f4eb67e'::uuid),
  ('9076b1aa-e8fd-42bd-bfc5-b68426257391'::uuid),
  ('a5bf319d-9315-411d-812d-dbc27de2fab4'::uuid),
  ('c1e8d801-fdaf-403e-9d1c-c57a4d640256'::uuid),
  ('8bb07b1f-283d-406f-a59a-96daa86c7aa7'::uuid),
  ('5dc9058a-e43d-4cda-bfd0-6461fca6347b'::uuid),
  ('cd8c1fed-a137-48df-8433-fd5ccf0532e7'::uuid),
  ('7ba7b97a-7971-44b6-91d9-b647090c8962'::uuid),
  ('22d2d91d-3ca4-4941-8986-a9ff05fa09a2'::uuid),
  ('97e93bbe-c0af-48ad-b00c-aa90675401d6'::uuid),
  ('b086b7a4-b374-4954-8c25-e3064b345661'::uuid),
  ('15acd98c-4120-4c51-9cc7-282d920319c5'::uuid),
  ('847f1c1f-5d0b-4e83-bab9-81bbdcde32dd'::uuid),
  ('0d4e0904-f748-4b03-b0ce-d0e829948f3b'::uuid),
  ('b2003b05-45fa-420a-b461-d67a5e675498'::uuid),
  ('07d91a08-cb18-4301-8cda-5d19670f260b'::uuid),
  ('07694bd8-16a5-43a4-8eb5-92cf1f5323c0'::uuid),
  ('cc865498-8cea-49a5-b943-97962a857c50'::uuid),
  ('82d3f527-70f3-409a-a44b-5052aaece093'::uuid),
  ('1a514908-00cd-4e91-ae68-3e63383e14b1'::uuid),
  ('c5637ee5-6a05-4ffa-8744-fea68afd3106'::uuid),
  ('467a824e-bf92-44bc-9994-fc97f0d9200a'::uuid),
  ('d2ea8a50-a9b2-4fb3-9183-1a7586563c24'::uuid),
  ('b5809bd6-765c-4f8f-9d04-730530eff3b0'::uuid),
  ('176534b3-274d-441d-9733-5fd6a3731c1b'::uuid),
  ('fe4b5d39-cd09-422e-8855-8785342c5a72'::uuid),
  ('2e03ece4-bcca-4c15-b01d-7921fee22ae0'::uuid),
  ('99dbcb22-524b-4231-b16c-ff4f188a29d2'::uuid),
  ('c3a4ebc2-f202-4310-a9fd-a77691af74e8'::uuid),
  ('6e7062b1-f082-43d2-93f8-250d9c139610'::uuid),
  ('e6f9b58a-0b52-463f-a0b7-36561a74952e'::uuid),
  ('d85b9399-dd4c-454e-b039-3fcc665b4399'::uuid),
  ('f1c4c7b6-8f54-4bd2-83a2-d106ed25a761'::uuid),
  ('9ad06fd3-3ac8-4aae-96a8-943445542a62'::uuid),
  ('ad8c349d-bf63-4abd-b7a5-4146136a8151'::uuid),
  ('914ed9cc-704f-431e-aa39-0a764c46aee9'::uuid),
  ('85b2eec0-a59d-430e-b0af-195f4737f93b'::uuid),
  ('27d7e148-8d2b-4566-918d-26be79515ce6'::uuid),
  ('4ea86124-229e-465c-ae7e-40f637c900d5'::uuid),
  ('7ff094c8-90e4-444d-835b-1276e89f728a'::uuid),
  ('ad6b8462-2b3a-4f5c-8aa8-777ac354c5c3'::uuid),
  ('06e0c847-9327-48e7-80b5-2c730908f8f0'::uuid),
  ('be79d81d-cfb1-4d7e-ad43-09ed42e9bf86'::uuid),
  ('cbf4dab0-79db-4311-a139-68cd93affa93'::uuid),
  ('b837bc4c-b6a9-47cd-8e13-73c705f030f8'::uuid),
  ('a0e72d0f-17c8-4fb3-bcd4-23d05fed3db4'::uuid),
  ('da7cc38b-1390-4a07-a618-5608223458b5'::uuid),
  ('057696c8-a610-4bb1-be47-7f84d78c5d1b'::uuid),
  ('0d51e48a-764f-4bce-9189-881baab24179'::uuid),
  ('c9808d40-411f-4c5e-b0bc-f00358614cb7'::uuid),
  ('51934eb2-f217-464f-ba5d-c0167b1309cd'::uuid),
  ('f6f701ed-8165-46c5-94da-2c5a5235e111'::uuid),
  ('ed2b9e1b-6b00-4312-84da-55725575f5dc'::uuid),
  ('eea9834c-fb65-4d6f-96cd-deef1f3695c5'::uuid),
  ('0cecbc90-bb38-4b95-b4ce-0f0613eb1f78'::uuid),
  ('3611472c-1ca9-460e-9617-efe5d0df0681'::uuid),
  ('a2145680-da7f-4a10-b55a-92f33d11cc28'::uuid),
  ('9c335ff2-d352-4b37-973a-df0ff9e584da'::uuid),
  ('861f8bb3-ad6c-4547-b31a-b6e3295287c7'::uuid),
  ('be7c763a-05da-40bf-8c11-03725059be30'::uuid),
  ('dabad4c6-dde7-41a3-9d7d-67d922adfbda'::uuid),
  ('04611732-6bde-4505-bba9-aa1340078387'::uuid),
  ('a601c74b-aa57-46db-a7d3-8cd241feb6a0'::uuid),
  ('860cad88-26bc-4cad-9712-9fb9964052b6'::uuid),
  ('5e01afb4-eb5c-4671-97e7-bcfaf7589505'::uuid),
  ('0f137d1d-ff7c-44c5-ac85-04bae4220c5c'::uuid),
  ('8ea13bc5-7631-4338-a8a2-1944ebd27de2'::uuid),
  ('5305fc83-9973-4dc9-88c2-5ba2d9331ec4'::uuid),
  ('2efde2be-97c8-4266-9f44-c0ddbac4a69c'::uuid),
  ('a08990ac-15e0-4980-8344-14c6ed326dab'::uuid),
  ('8a6b6783-85c5-4b22-9e23-ca10ab98ad3b'::uuid),
  ('f572748c-d5b8-424a-a4be-45ef19724903'::uuid),
  ('694dd60a-abf1-42fa-bc17-d044097ac851'::uuid),
  ('555873c2-f134-48cb-a076-84c76fb8aa75'::uuid),
  ('47cc3e0b-9e43-428f-b87d-c0b204282069'::uuid),
  ('689e7f8b-b4b7-4213-b8bf-446639fa0b9d'::uuid),
  ('3e371089-3561-47ce-9cc9-930c65eee0ec'::uuid),
  ('aa11b57e-dd9e-4c82-b5d7-75cdb066563d'::uuid),
  ('9e527e51-c0ac-4ec5-ae3a-1f7e3f743cec'::uuid),
  ('3f5191cf-330b-4eea-a7f0-300cb61e4c73'::uuid),
  ('6d904641-ce97-4578-881e-6cec7bec8a7f'::uuid),
  ('7e2ea69b-33e6-40e1-81d6-a34684a8ea6b'::uuid),
  ('d0fc8508-44a3-4850-8302-d0456bbbd388'::uuid),
  ('49034d17-f840-4ae4-80a5-d8fde3f7b1ea'::uuid),
  ('24d357a9-e6a7-4ee2-bfb4-bb98d8af8647'::uuid),
  ('af5c8271-ce5b-4a20-9b3b-e66c5334fff2'::uuid),
  ('aea5a38a-973e-42a8-9ebb-2964c882fb71'::uuid),
  ('2e4d3993-9d88-4610-9f0b-9c372cb9e992'::uuid),
  ('e31656e5-6d7c-45cb-a0e9-cb605e37af3a'::uuid),
  ('1a505fdc-b29b-4b24-a92a-6134e4d53596'::uuid),
  ('43e502ae-8999-4753-8392-74dfd72e1bf8'::uuid),
  ('6304ce16-997f-4657-83a1-bcca038cbc10'::uuid),
  ('9e7d4532-d8a6-40b8-a064-39a33f53ab40'::uuid),
  ('31fbbb57-57c2-454d-972c-e755befbd97b'::uuid),
  ('1f4eb11a-6448-4c6a-aeeb-6c2376690872'::uuid),
  ('66572987-6123-4159-ae53-0dd4e3b5b93c'::uuid),
  ('0e38f238-0a0b-4687-8bf7-633a973b6286'::uuid),
  ('d230e661-0232-4525-b031-613806a30f34'::uuid),
  ('44e1d785-b130-4a7f-b317-bd7ea3150dfe'::uuid),
  ('cc0ba994-a92d-4375-a84d-43a53c2d66db'::uuid),
  ('dfd425c1-793c-4240-bf2f-90d23351108f'::uuid),
  ('4a2d069f-aad6-45c9-bf6d-4a7f703686d1'::uuid),
  ('3b71e567-c45a-42c6-a1fc-9db6d58f7bd8'::uuid),
  ('999baf8d-a41b-4c69-abcf-777e284519ad'::uuid),
  ('5b71c2e9-2742-4992-a583-8fd9efa60834'::uuid),
  ('50ba07d8-1510-4528-abde-3a822e172311'::uuid),
  ('3b573e37-bc3e-4ceb-ad5d-904f1b9503be'::uuid),
  ('a603f20e-3894-4193-84b1-4068d0d1f420'::uuid),
  ('5402dca0-555c-42b2-9142-f231177e9d03'::uuid),
  ('6133b1d2-1493-49c6-abd5-307eebc5f556'::uuid),
  ('27c980dd-b38f-425e-b2c5-82f72cfd12c2'::uuid),
  ('d0636c9d-b619-4ffe-8580-ee7315accea0'::uuid),
  ('d90f999d-5441-4f0f-a543-e89589da2b50'::uuid),
  ('5e54cada-9728-40c4-b57a-9391fb61cf96'::uuid),
  ('fd2167d9-2442-47b1-91ff-d6e6f4b543be'::uuid),
  ('31b45a81-4d96-4ea2-9c9b-fee5e02f92c0'::uuid),
  ('07a69945-e6c7-46b4-8658-1e66bc11b799'::uuid),
  ('b235097d-9382-45b5-b70f-27e7f846ebc2'::uuid),
  ('a26a7700-703b-4b49-a260-67ef2dddb5d4'::uuid),
  ('65be096a-53ca-46c7-b78d-640368b9e177'::uuid),
  ('f28844e3-919e-4e90-a387-24815c21092c'::uuid),
  ('0402ed1d-41b0-4471-9559-f05c28d117f0'::uuid),
  ('6da54355-5f5a-4e26-a57b-3572d6108225'::uuid),
  ('d4be3d6f-ab65-428a-9c28-5d9f4e99cd49'::uuid),
  ('8853844d-ec3f-486b-b166-b50e74242bf1'::uuid),
  ('499711dd-3038-4487-bb80-712c5ef9091b'::uuid),
  ('12a2a45b-8470-4970-bb83-07b5cd300a7a'::uuid),
  ('bbf60b4e-ebe1-44f6-8d0e-d82a1e4d707b'::uuid),
  ('b925d5a8-d2e3-4f6d-b264-cb5593c6af11'::uuid),
  ('594e8816-e14f-467c-8c96-b0232843f724'::uuid),
  ('5d307f76-ec4a-4de1-85a8-e4091bcc7754'::uuid),
  ('d222ebc6-fa47-4e21-9a78-285176e3a0a8'::uuid),
  ('a82c7cf8-7d7d-4e58-8f71-97e0438bce0b'::uuid),
  ('e706781d-6655-4e8e-9502-670f0af4699c'::uuid),
  ('b3d0c665-6b71-47cd-abfd-45d5aba8deb5'::uuid),
  ('dfda40d1-9b3f-458a-b90c-ecaf5f44f53b'::uuid),
  ('d6bc4758-a3d1-4ebd-a081-1c1db69cbb59'::uuid),
  ('17d1513b-a93d-4323-a5fc-9564dacf5f7f'::uuid),
  ('f9d84c7a-e7c1-4b84-9d9f-ddf8783ac91b'::uuid),
  ('27f3d077-964d-4232-972f-19f384e54732'::uuid),
  ('9f597b43-276d-4273-b631-f80d0440e37e'::uuid),
  ('487f4e8d-0384-4a93-8d83-0cea76b523e5'::uuid),
  ('0ce55430-831f-456a-af1f-6d94e8fd8192'::uuid),
  ('9b1efc94-f235-438c-ba11-92aa749dd100'::uuid),
  ('0f1a46a4-7116-4480-a9c7-e6939e31a673'::uuid),
  ('23474d4f-54ba-49d0-9c49-16f377d12dd3'::uuid),
  ('770dc7de-cacb-4f3d-96b6-f221bbb9ab84'::uuid),
  ('00a9bc69-a5b8-4ed4-82fc-f3dca11e5215'::uuid),
  ('f8d5a121-43f1-430e-af8a-c1585d9bdd5b'::uuid),
  ('f66e5041-d702-4d05-9d8b-92ba612b77ab'::uuid),
  ('fa3facc6-2603-4488-9e6b-91e8d4f31871'::uuid),
  ('f61c0ad2-aa51-445f-a470-488f3b3a6563'::uuid),
  ('80de439b-7fde-4e7b-b404-60bfe7fe9555'::uuid),
  ('08b2990b-23e5-4a83-a93d-ed7293f7bb5a'::uuid),
  ('031bef59-1cbf-4a89-83b9-294469dfd31a'::uuid),
  ('30d09c16-a39e-499b-a006-d72a72d6df82'::uuid),
  ('3a4957c0-3027-4807-80e8-f0507f4de748'::uuid),
  ('bef2884f-ea53-4609-92a3-c1a6c86cf67f'::uuid),
  ('78e8fe8c-2fc5-4196-9772-63f5d70430f3'::uuid),
  ('c3e10041-d3cd-44cb-824f-bc5f0829acdc'::uuid),
  ('33477ff6-df4e-477b-9fc1-1d0fd3fc0974'::uuid),
  ('1b2766d5-3b75-4083-950e-c9dbfdbb9b40'::uuid),
  ('8aff3fc9-87d5-47ef-ac51-506fb0d62010'::uuid),
  ('b926eeba-04c4-45da-aa75-97fda0323a53'::uuid),
  ('72688923-6fb1-4467-9544-386fc16025dd'::uuid),
  ('5ac884c7-ebdf-4121-b219-08a63b95ec20'::uuid),
  ('e3a815fc-b894-4552-adc3-5565b7c50689'::uuid),
  ('06abe4c0-bd01-48dd-b149-891153d937b9'::uuid),
  ('09d55526-f6f0-4fef-9fda-c3e542f1fad7'::uuid),
  ('79600135-61e6-44e2-832f-63f26c300d87'::uuid),
  ('13aa1205-c55c-4bfc-ac5d-bab190c1e48b'::uuid),
  ('e3181a70-9957-4109-b3a5-a0d93b90dec6'::uuid),
  ('d4daf6d7-cf04-46a1-a08e-f7b8f7b59944'::uuid),
  ('d9efae89-00b6-4892-afeb-5fad254a8d9c'::uuid),
  ('8b371207-285b-4c9d-ab4b-ee57608fc1dd'::uuid),
  ('74cb3215-505c-4ee1-9f31-e40e8ff41506'::uuid),
  ('eb48809e-2ada-4b28-8621-0206815cfef0'::uuid),
  ('b32dae5d-9fa8-4eb8-9a55-3fbb98ef87c7'::uuid),
  ('053a7ad2-82ac-4218-aac3-76d9369b4dc8'::uuid),
  ('b6331ab3-a347-4898-a44a-c9035a3bb571'::uuid),
  ('f8b48a06-b917-4a1e-ba78-148c4872e5dd'::uuid),
  ('96272985-6b10-4407-8d4b-6d289721c85f'::uuid),
  ('5a2e9ff9-d91d-4334-8357-f3bcab2c4305'::uuid),
  ('a9045256-19b6-475e-9152-51fd13544509'::uuid),
  ('d2820535-1185-44d9-89de-c5e01edd42ba'::uuid),
  ('06929f0e-a87b-49ad-9c5a-385ae39e4753'::uuid),
  ('8c8e3101-74ad-495f-9052-c891797bf981'::uuid),
  ('fa07c099-4d58-4dc7-b7f2-ed2c369ae4e4'::uuid),
  ('2e31c4f0-8169-4203-a247-428a0ebf3efe'::uuid),
  ('d0c742e5-60e3-4876-b5fa-120c1bbe3568'::uuid),
  ('d8321ab0-d3f3-4c82-b648-d809fcd91f2f'::uuid),
  ('8db61567-9df6-4433-98d9-612a38af80f9'::uuid),
  ('910a8dfa-a325-4645-840c-f702df9df66a'::uuid),
  ('0835d5e0-2d2b-4830-96ea-0186933721a8'::uuid),
  ('d8fe1da4-cbf8-44f8-af99-4b82dfd8ca14'::uuid),
  ('029994d3-8809-477d-b14d-997689f356d5'::uuid)
    ) as expected_id(id)
    where exists (
      select 1 from public.learning_stages where id = expected_id.id
      union all
      select 1 from public.learning_questions where id = expected_id.id
      union all
      select 1 from public.learning_question_options where id = expected_id.id
    )
  ) then
    raise exception using errcode = '23505', message = 'grade2_multiplication_meaning_v1 child content identifier already exists';
  end if;
end
$preflight$;

insert into public.learning_units (id, course_id, unit_code, display_title, sort_order)
values ('4c8f9c55-37a9-4bf6-a444-e4165f8f30fc', '51000000-0000-4000-8000-000000000001', 'grade2-multiplication-meaning', '곱셈의 뜻을 알아봐요', 7);

insert into public.learning_unit_recommendation_metadata (
  unit_id, subject, recommended_start_level_code, recommended_end_level_code, parent_sort_order
)
select '4c8f9c55-37a9-4bf6-a444-e4165f8f30fc'::uuid, 'math', 'elementary_2', 'elementary_2', 6
where not exists (
  select 1
  from public.learning_unit_recommendation_metadata metadata
  where metadata.unit_id = '4c8f9c55-37a9-4bf6-a444-e4165f8f30fc'::uuid
);

insert into public.learning_content_versions (id, unit_id, version_no, content_hash)
values ('8eb41f37-e2f1-42e9-a1c8-657ca08c9302', '4c8f9c55-37a9-4bf6-a444-e4165f8f30fc', 1, 'f97d31dbfa3be6b48d8836ebc31f947dae05a5df25bf05b6fcd5b37a8b666af1');

insert into public.learning_stages (id, content_version_id, display_order, display_title, difficulty)
values
  ('70a00c90-97e8-45ab-a7a8-33fa4430549d', '8eb41f37-e2f1-42e9-a1c8-657ca08c9302', 1, '입문', 'seed'),
  ('fa6ae6ea-128b-4559-9d63-cd26d951919d', '8eb41f37-e2f1-42e9-a1c8-657ca08c9302', 2, '기초', 'leaf'),
  ('88c82137-760d-4e35-a407-046a5eb0ba6c', '8eb41f37-e2f1-42e9-a1c8-657ca08c9302', 3, '심화', 'tree'),
  ('6559b39d-f80a-4ed6-a5e7-01c5e800e210', '8eb41f37-e2f1-42e9-a1c8-657ca08c9302', 4, '최상위 도전!', 'crown');

insert into public.learning_questions (id, stage_id, display_order, prompt, explanation)
values
  ('aaee2904-d460-458c-a536-6699ab430e33', '70a00c90-97e8-45ab-a7a8-33fa4430549d', 1, '사탕이 접시마다 3개씩 놓여 있습니다. 모든 접시에 같은 수씩 놓인 모습은?', '접시마다 사탕이 3개로 같으므로 3개씩 묶인 모습입니다.'),
  ('9ff12a7a-6bfa-4f9b-bf52-6455145d7927', '70a00c90-97e8-45ab-a7a8-33fa4430549d', 2, '연필이 한 묶음에 2자루씩 있고 이런 묶음이 4개 있습니다. 묶음 수는?', '한 묶음에는 2자루가 있고 같은 묶음이 4개이므로 묶음 수는 4입니다.'),
  ('ec504283-f43e-4a52-a24d-e90103d6e59a', '70a00c90-97e8-45ab-a7a8-33fa4430549d', 3, '별이 한 줄에 4개씩 있고 3줄 있습니다. 같은 수를 더한 식은?', '한 줄의 별 4개를 줄 수 3번 더하므로 4+4+4입니다.'),
  ('ec5be058-8a68-4c33-a2ef-df7895ba2a66', '70a00c90-97e8-45ab-a7a8-33fa4430549d', 4, '한 봉지에 귤이 5개씩 있고 2봉지 있습니다. ''몇씩 몇 묶음''으로 나타낸 것은?', '한 봉지의 귤이 5개이고 봉지가 2개이므로 5씩 2묶음입니다.'),
  ('c04873bf-6a7f-406a-846c-ba947f4eb67e', '70a00c90-97e8-45ab-a7a8-33fa4430549d', 5, '2+2+2+2를 같은 수씩 묶은 말로 나타낸 것은?', '2를 네 번 더했으므로 한 묶음에 2개씩 4묶음입니다.'),
  ('9076b1aa-e8fd-42bd-bfc5-b68426257391', '70a00c90-97e8-45ab-a7a8-33fa4430549d', 6, '공이 상자마다 3개씩 있고 상자가 5개 있습니다. 한 묶음의 수는?', '상자 하나가 한 묶음이므로 한 묶음의 공은 3개입니다.'),
  ('a5bf319d-9315-411d-812d-dbc27de2fab4', '70a00c90-97e8-45ab-a7a8-33fa4430549d', 7, '다음 중 같은 수씩 묶여 있어 곱셈으로 나타내기 알맞은 것은?', '쟁반마다 쿠키가 3개로 같고 이런 쟁반이 4개이므로 같은 수씩 묶였습니다.'),
  ('c1e8d801-fdaf-403e-9d1c-c57a4d640256', '70a00c90-97e8-45ab-a7a8-33fa4430549d', 8, '6씩 2묶음을 반복 덧셈으로 나타낸 것은?', '한 묶음의 수 6을 묶음 수 2번 더하므로 6+6입니다.'),
  ('8bb07b1f-283d-406f-a59a-96daa86c7aa7', '70a00c90-97e8-45ab-a7a8-33fa4430549d', 9, '한 줄에 의자가 2개씩 있고 5줄 있습니다. 알맞은 설명은?', '한 줄의 의자 2개가 한 묶음이고 줄이 5개이므로 2씩 5묶음입니다.'),
  ('5dc9058a-e43d-4cda-bfd0-6461fca6347b', '70a00c90-97e8-45ab-a7a8-33fa4430549d', 10, '4+4+4에서 더해지는 같은 수와 그 수를 더한 횟수는?', '4가 세 번 더해졌으므로 같은 수는 4이고 더한 횟수는 3입니다.'),
  ('cd8c1fed-a137-48df-8433-fd5ccf0532e7', 'fa6ae6ea-128b-4559-9d63-cd26d951919d', 1, '이 단원에서는 ''3씩 4묶음''을 한 묶음의 수 × 묶음 수로 씁니다. 알맞은 곱셈식은?', '한 묶음의 수 3을 앞에, 묶음 수 4를 뒤에 써서 3×4로 나타냅니다.'),
  ('7ba7b97a-7971-44b6-91d9-b647090c8962', 'fa6ae6ea-128b-4559-9d63-cd26d951919d', 2, '한 접시에 딸기가 4개씩 있고 접시가 3개 있습니다. 알맞은 곱셈식은?', '한 묶음의 수 4를 앞에, 접시 수 3을 뒤에 써서 4×3입니다.'),
  ('22d2d91d-3ca4-4941-8986-a9ff05fa09a2', 'fa6ae6ea-128b-4559-9d63-cd26d951919d', 3, '5+5+5+5를 곱셈식으로 나타낸 것은?', '5를 네 번 더했으므로 5씩 4묶음이고 곱셈식은 5×4입니다.'),
  ('97e93bbe-c0af-48ad-b00c-aa90675401d6', 'fa6ae6ea-128b-4559-9d63-cd26d951919d', 4, '2×6이 뜻하는 것은?', '앞 수 2는 한 묶음의 수이고 뒤 수 6은 묶음 수이므로 2씩 6묶음입니다.'),
  ('b086b7a4-b374-4954-8c25-e3064b345661', 'fa6ae6ea-128b-4559-9d63-cd26d951919d', 5, '바구니 4개에 사과가 3개씩 있습니다. 3×4에서 4가 뜻하는 것은?', '3×4의 뒤 수 4는 같은 묶음인 바구니가 4개라는 뜻입니다.'),
  ('15acd98c-4120-4c51-9cc7-282d920319c5', 'fa6ae6ea-128b-4559-9d63-cd26d951919d', 6, '6×3에 알맞은 상황은?', '6×3은 한 묶음에 6개씩 3묶음이므로 상자 3개에 공이 6개씩 있는 상황입니다.'),
  ('847f1c1f-5d0b-4e83-bab9-81bbdcde32dd', 'fa6ae6ea-128b-4559-9d63-cd26d951919d', 7, '한 줄에 화분이 5개씩 있고 3줄 있습니다. 반복 덧셈과 곱셈식이 모두 알맞은 것은?', '한 줄의 5개를 줄 수 3번 더한 5+5+5이고 곱셈식은 5×3입니다.'),
  ('0d4e0904-f748-4b03-b0ce-d0e829948f3b', 'fa6ae6ea-128b-4559-9d63-cd26d951919d', 8, '4×2를 읽고 뜻을 바르게 말한 것은?', '4×2는 ''사 곱하기 이''라고 읽고 4씩 2묶음을 뜻합니다.'),
  ('b2003b05-45fa-420a-b461-d67a5e675498', 'fa6ae6ea-128b-4559-9d63-cd26d951919d', 9, '공책을 2권씩 4명에게 나누어 줍니다. 알맞은 곱셈식은?', '한 사람에게 주는 2권이 한 묶음이고 사람이 4명이므로 2×4입니다.'),
  ('07d91a08-cb18-4301-8cda-5d19670f260b', 'fa6ae6ea-128b-4559-9d63-cd26d951919d', 10, '3×5에서 3이 뜻하는 것은?', '곱셈식의 앞 수 3은 한 묶음에 들어 있는 수를 뜻합니다.'),
  ('07694bd8-16a5-43a4-8eb5-92cf1f5323c0', '88c82137-760d-4e35-a407-046a5eb0ba6c', 1, '한 줄에 별이 4개씩 5줄 있습니다. 식과 설명이 알맞게 짝지어진 것은?', '한 줄의 4개가 5줄 있으므로 4씩 5묶음이고 식은 4×5입니다.'),
  ('cc865498-8cea-49a5-b943-97962a857c50', '88c82137-760d-4e35-a407-046a5eb0ba6c', 2, '사탕이 모두 18개이고 한 봉지에 6개씩 담았습니다. 봉지는 몇 개입니까?', '6개씩 3봉지는 6+6+6=18이므로 봉지는 3개입니다.'),
  ('82d3f527-70f3-409a-a44b-5052aaece093', '88c82137-760d-4e35-a407-046a5eb0ba6c', 3, '연필이 모두 20자루이고 4묶음에 똑같이 들어 있습니다. 한 묶음에는 몇 자루입니까?', '5자루씩 4묶음은 5+5+5+5=20이므로 한 묶음에는 5자루입니다.'),
  ('1a514908-00cd-4e91-ae68-3e63383e14b1', '88c82137-760d-4e35-a407-046a5eb0ba6c', 4, '3×4에 맞는 반복 덧셈은?', '3×4는 한 묶음의 수 3을 묶음 수 4번 더한 3+3+3+3입니다.'),
  ('c5637ee5-6a05-4ffa-8744-fea68afd3106', '88c82137-760d-4e35-a407-046a5eb0ba6c', 5, '다음 중 2×5로 나타낼 수 있는 상황은?', '꽃 2송이가 한 묶음이고 꽃병이 5개이므로 2씩 5묶음인 2×5입니다.'),
  ('467a824e-bf92-44bc-9994-fc97f0d9200a', '88c82137-760d-4e35-a407-046a5eb0ba6c', 6, '민수는 4씩 3묶음을 3×4라고 썼습니다. 잘못된 까닭은?', '이 단원에서는 한 묶음의 수를 앞에 쓰므로 4씩 3묶음은 4×3입니다.'),
  ('d2ea8a50-a9b2-4fb3-9183-1a7586563c24', '88c82137-760d-4e35-a407-046a5eb0ba6c', 7, '2+2+2+2+2를 2×4라고 쓴 설명에서 잘못된 부분은?', '2가 다섯 번 더해졌으므로 묶음 수는 5이고 알맞은 식은 2×5입니다.'),
  ('b5809bd6-765c-4f8f-9d04-730530eff3b0', '88c82137-760d-4e35-a407-046a5eb0ba6c', 8, '쟁반마다 쿠키가 4개씩 있습니다. 4×□=4+4+4에서 □에 알맞은 수는?', '오른쪽에서 4가 세 번 더해졌으므로 묶음 수를 나타내는 □는 3입니다.'),
  ('176534b3-274d-441d-9733-5fd6a3731c1b', '88c82137-760d-4e35-a407-046a5eb0ba6c', 9, '2씩 6묶음과 같은 전체 수를 만들지만 묶는 방법이 다른 것은?', '2씩 6묶음은 12이고 3씩 4묶음도 12이지만 한 묶음의 수와 묶음 수가 다릅니다.'),
  ('fe4b5d39-cd09-422e-8855-8785342c5a72', '88c82137-760d-4e35-a407-046a5eb0ba6c', 10, '컵이 15개이고 한 줄에 3개씩 놓습니다. 알맞은 곱셈식은?', '3개씩 놓은 줄이 5줄이므로 한 묶음의 수 × 묶음 수는 3×5입니다.'),
  ('2e03ece4-bcca-4c15-b01d-7921fee22ae0', '6559b39d-f80a-4ed6-a5e7-01c5e800e210', 1, '4×3을 나타내는 상황과 이유가 모두 알맞은 것은?', '4×3은 한 묶음에 4개씩 3묶음이고 반복 덧셈은 4+4+4입니다.'),
  ('99dbcb22-524b-4231-b16c-ff4f188a29d2', '6559b39d-f80a-4ed6-a5e7-01c5e800e210', 2, '상자 4개에 공이 3개씩 있습니다. 4×3이라고 쓴 학생의 생각을 바르게 고친 것은?', '한 묶음인 상자 하나의 공 3개를 앞에, 상자 수 4를 뒤에 써서 3×4입니다.'),
  ('c3a4ebc2-f202-4310-a9fd-a77691af74e8', '6559b39d-f80a-4ed6-a5e7-01c5e800e210', 3, '한 봉지에 구슬이 5개씩 있습니다. 구슬 20개를 모두 담으려면 식의 □는 얼마입니까? 5×□', '5개씩 4봉지는 5+5+5+5=20이므로 □는 4입니다.'),
  ('6e7062b1-f082-43d2-93f8-250d9c139610', '6559b39d-f80a-4ed6-a5e7-01c5e800e210', 4, '다음 중 3×4와 전체 수는 같지만 묶음의 뜻은 다른 설명은?', '4씩 3묶음도 전체는 12이지만 한 묶음의 수와 묶음 수가 3×4와 서로 다릅니다.'),
  ('e6f9b58a-0b52-463f-a0b7-36561a74952e', '6559b39d-f80a-4ed6-a5e7-01c5e800e210', 5, '한 줄에 2개씩 6줄 놓인 단추를 3개씩 다시 묶었습니다. 알맞은 설명은?', '처음 2씩 6묶음과 다시 만든 3씩 4묶음은 묶는 방법은 달라도 전체가 12개로 같습니다.'),
  ('d85b9399-dd4c-454e-b039-3fcc665b4399', '6559b39d-f80a-4ed6-a5e7-01c5e800e210', 6, '7×3을 설명한 것 중 잘못된 것은?', '3씩 7묶음은 3×7의 뜻입니다. 7×3은 7씩 3묶음입니다.'),
  ('f1c4c7b6-8f54-4bd2-83a2-d106ed25a761', '6559b39d-f80a-4ed6-a5e7-01c5e800e210', 7, '접시마다 빵이 같은 수씩 있고 접시는 4개입니다. 빵이 모두 24개라면 한 접시의 빵 수와 식은?', '24개를 4접시에 똑같이 놓으면 한 접시에 6개씩이고 식은 6×4입니다.'),
  ('9ad06fd3-3ac8-4aae-96a8-943445542a62', '6559b39d-f80a-4ed6-a5e7-01c5e800e210', 8, '''2×5는 2와 5를 더한 7이다''라는 설명을 바르게 고친 것은?', '2×5는 2씩 5묶음이므로 2를 다섯 번 더한 식으로 뜻을 설명합니다.'),
  ('ad8c349d-bf63-4abd-b7a5-4146136a8151', '6559b39d-f80a-4ed6-a5e7-01c5e800e210', 9, '한 칸에 별이 4개씩 있는 칸이 3개, 한 칸에 별이 2개씩 있는 칸이 6개입니다. 알맞은 설명은?', '4씩 3묶음과 2씩 6묶음은 모두 12개이지만 묶음의 모양은 다릅니다.'),
  ('914ed9cc-704f-431e-aa39-0a764c46aee9', '6559b39d-f80a-4ed6-a5e7-01c5e800e210', 10, '3+3+3+3과 어떤 상황을 연결한 설명이 가장 알맞습니까?', '3이 네 번 더해졌으므로 3씩 4묶음이고 곱셈식은 3×4입니다.');

insert into public.learning_question_options (id, question_id, display_order, option_text, is_correct)
values
  ('85b2eec0-a59d-430e-b0af-195f4737f93b', 'aaee2904-d460-458c-a536-6699ab430e33', 1, '접시마다 3개씩', true),
  ('27d7e148-8d2b-4566-918d-26be79515ce6', 'aaee2904-d460-458c-a536-6699ab430e33', 2, '한 접시에는 2개이고 다른 접시에는 3개', false),
  ('4ea86124-229e-465c-ae7e-40f637c900d5', 'aaee2904-d460-458c-a536-6699ab430e33', 3, '접시마다 개수가 다름', false),
  ('7ff094c8-90e4-444d-835b-1276e89f728a', 'aaee2904-d460-458c-a536-6699ab430e33', 4, '사탕을 모두 한 접시에 놓음', false),
  ('ad6b8462-2b3a-4f5c-8aa8-777ac354c5c3', '9ff12a7a-6bfa-4f9b-bf52-6455145d7927', 1, '2묶음', false),
  ('06e0c847-9327-48e7-80b5-2c730908f8f0', '9ff12a7a-6bfa-4f9b-bf52-6455145d7927', 2, '4묶음', true),
  ('be79d81d-cfb1-4d7e-ad43-09ed42e9bf86', '9ff12a7a-6bfa-4f9b-bf52-6455145d7927', 3, '6묶음', false),
  ('cbf4dab0-79db-4311-a139-68cd93affa93', '9ff12a7a-6bfa-4f9b-bf52-6455145d7927', 4, '8묶음', false),
  ('b837bc4c-b6a9-47cd-8e13-73c705f030f8', 'ec504283-f43e-4a52-a24d-e90103d6e59a', 1, '3+3+3+3', false),
  ('a0e72d0f-17c8-4fb3-bcd4-23d05fed3db4', 'ec504283-f43e-4a52-a24d-e90103d6e59a', 2, '4+3', false),
  ('da7cc38b-1390-4a07-a618-5608223458b5', 'ec504283-f43e-4a52-a24d-e90103d6e59a', 3, '4+4+4', true),
  ('057696c8-a610-4bb1-be47-7f84d78c5d1b', 'ec504283-f43e-4a52-a24d-e90103d6e59a', 4, '4+4+3', false),
  ('0d51e48a-764f-4bce-9189-881baab24179', 'ec5be058-8a68-4c33-a2ef-df7895ba2a66', 1, '2씩 5묶음', false),
  ('c9808d40-411f-4c5e-b0bc-f00358614cb7', 'ec5be058-8a68-4c33-a2ef-df7895ba2a66', 2, '5씩 5묶음', false),
  ('51934eb2-f217-464f-ba5d-c0167b1309cd', 'ec5be058-8a68-4c33-a2ef-df7895ba2a66', 3, '2씩 2묶음', false),
  ('f6f701ed-8165-46c5-94da-2c5a5235e111', 'ec5be058-8a68-4c33-a2ef-df7895ba2a66', 4, '5씩 2묶음', true),
  ('ed2b9e1b-6b00-4312-84da-55725575f5dc', 'c04873bf-6a7f-406a-846c-ba947f4eb67e', 1, '2씩 4묶음', true),
  ('eea9834c-fb65-4d6f-96cd-deef1f3695c5', 'c04873bf-6a7f-406a-846c-ba947f4eb67e', 2, '4씩 2묶음', false),
  ('0cecbc90-bb38-4b95-b4ce-0f0613eb1f78', 'c04873bf-6a7f-406a-846c-ba947f4eb67e', 3, '2씩 2묶음', false),
  ('3611472c-1ca9-460e-9617-efe5d0df0681', 'c04873bf-6a7f-406a-846c-ba947f4eb67e', 4, '4씩 4묶음', false),
  ('a2145680-da7f-4a10-b55a-92f33d11cc28', '9076b1aa-e8fd-42bd-bfc5-b68426257391', 1, '5개', false),
  ('9c335ff2-d352-4b37-973a-df0ff9e584da', '9076b1aa-e8fd-42bd-bfc5-b68426257391', 2, '3개', true),
  ('861f8bb3-ad6c-4547-b31a-b6e3295287c7', '9076b1aa-e8fd-42bd-bfc5-b68426257391', 3, '8개', false),
  ('be7c763a-05da-40bf-8c11-03725059be30', '9076b1aa-e8fd-42bd-bfc5-b68426257391', 4, '15개', false),
  ('dabad4c6-dde7-41a3-9d7d-67d922adfbda', 'a5bf319d-9315-411d-812d-dbc27de2fab4', 1, '한 접시에 2개, 다른 접시에 3개인 빵', false),
  ('04611732-6bde-4505-bba9-aa1340078387', 'a5bf319d-9315-411d-812d-dbc27de2fab4', 2, '봉지마다 개수가 다른 구슬', false),
  ('a601c74b-aa57-46db-a7d3-8cd241feb6a0', 'a5bf319d-9315-411d-812d-dbc27de2fab4', 3, '쟁반 4개에 쿠키가 각각 3개씩 있음', true),
  ('860cad88-26bc-4cad-9712-9fb9964052b6', 'a5bf319d-9315-411d-812d-dbc27de2fab4', 4, '연필 7자루를 크기가 다르게 늘어놓음', false),
  ('5e01afb4-eb5c-4671-97e7-bcfaf7589505', 'c1e8d801-fdaf-403e-9d1c-c57a4d640256', 1, '2+2+2+2+2+2', false),
  ('0f137d1d-ff7c-44c5-ac85-04bae4220c5c', 'c1e8d801-fdaf-403e-9d1c-c57a4d640256', 2, '6+2', false),
  ('8ea13bc5-7631-4338-a8a2-1944ebd27de2', 'c1e8d801-fdaf-403e-9d1c-c57a4d640256', 3, '6+6+2', false),
  ('5305fc83-9973-4dc9-88c2-5ba2d9331ec4', 'c1e8d801-fdaf-403e-9d1c-c57a4d640256', 4, '6+6', true),
  ('2efde2be-97c8-4266-9f44-c0ddbac4a69c', '8bb07b1f-283d-406f-a59a-96daa86c7aa7', 1, '2씩 5묶음', true),
  ('a08990ac-15e0-4980-8344-14c6ed326dab', '8bb07b1f-283d-406f-a59a-96daa86c7aa7', 2, '5씩 2묶음', false),
  ('8a6b6783-85c5-4b22-9e23-ca10ab98ad3b', '8bb07b1f-283d-406f-a59a-96daa86c7aa7', 3, '2와 5를 한 묶음', false),
  ('f572748c-d5b8-424a-a4be-45ef19724903', '8bb07b1f-283d-406f-a59a-96daa86c7aa7', 4, '7씩 1묶음', false),
  ('694dd60a-abf1-42fa-bc17-d044097ac851', '5dc9058a-e43d-4cda-bfd0-6461fca6347b', 1, '같은 수 3, 횟수 4', false),
  ('555873c2-f134-48cb-a076-84c76fb8aa75', '5dc9058a-e43d-4cda-bfd0-6461fca6347b', 2, '같은 수 4, 횟수 3', true),
  ('47cc3e0b-9e43-428f-b87d-c0b204282069', '5dc9058a-e43d-4cda-bfd0-6461fca6347b', 3, '같은 수 4, 횟수 4', false),
  ('689e7f8b-b4b7-4213-b8bf-446639fa0b9d', '5dc9058a-e43d-4cda-bfd0-6461fca6347b', 4, '같은 수 12, 횟수 1', false),
  ('3e371089-3561-47ce-9cc9-930c65eee0ec', 'cd8c1fed-a137-48df-8433-fd5ccf0532e7', 1, '4×3', false),
  ('aa11b57e-dd9e-4c82-b5d7-75cdb066563d', 'cd8c1fed-a137-48df-8433-fd5ccf0532e7', 2, '3+4', false),
  ('9e527e51-c0ac-4ec5-ae3a-1f7e3f743cec', 'cd8c1fed-a137-48df-8433-fd5ccf0532e7', 3, '3×4', true),
  ('3f5191cf-330b-4eea-a7f0-300cb61e4c73', 'cd8c1fed-a137-48df-8433-fd5ccf0532e7', 4, '4+4+4', false),
  ('6d904641-ce97-4578-881e-6cec7bec8a7f', '7ba7b97a-7971-44b6-91d9-b647090c8962', 1, '3×4', false),
  ('7e2ea69b-33e6-40e1-81d6-a34684a8ea6b', '7ba7b97a-7971-44b6-91d9-b647090c8962', 2, '4+3', false),
  ('d0fc8508-44a3-4850-8302-d0456bbbd388', '7ba7b97a-7971-44b6-91d9-b647090c8962', 3, '3+3+3+3', false),
  ('49034d17-f840-4ae4-80a5-d8fde3f7b1ea', '7ba7b97a-7971-44b6-91d9-b647090c8962', 4, '4×3', true),
  ('24d357a9-e6a7-4ee2-bfb4-bb98d8af8647', '22d2d91d-3ca4-4941-8986-a9ff05fa09a2', 1, '5×4', true),
  ('af5c8271-ce5b-4a20-9b3b-e66c5334fff2', '22d2d91d-3ca4-4941-8986-a9ff05fa09a2', 2, '4×5', false),
  ('aea5a38a-973e-42a8-9ebb-2964c882fb71', '22d2d91d-3ca4-4941-8986-a9ff05fa09a2', 3, '5×5', false),
  ('2e4d3993-9d88-4610-9f0b-9c372cb9e992', '22d2d91d-3ca4-4941-8986-a9ff05fa09a2', 4, '4×4', false),
  ('e31656e5-6d7c-45cb-a0e9-cb605e37af3a', '97e93bbe-c0af-48ad-b00c-aa90675401d6', 1, '6씩 2묶음', false),
  ('1a505fdc-b29b-4b24-a92a-6134e4d53596', '97e93bbe-c0af-48ad-b00c-aa90675401d6', 2, '2씩 6묶음', true),
  ('43e502ae-8999-4753-8392-74dfd72e1bf8', '97e93bbe-c0af-48ad-b00c-aa90675401d6', 3, '2와 6을 더한 것', false),
  ('6304ce16-997f-4657-83a1-bcca038cbc10', '97e93bbe-c0af-48ad-b00c-aa90675401d6', 4, '6개를 한 묶음으로만 둔 것', false),
  ('9e7d4532-d8a6-40b8-a064-39a33f53ab40', 'b086b7a4-b374-4954-8c25-e3064b345661', 1, '사과의 전체 수', false),
  ('31fbbb57-57c2-454d-972c-e755befbd97b', 'b086b7a4-b374-4954-8c25-e3064b345661', 2, '한 바구니의 사과 수', false),
  ('1f4eb11a-6448-4c6a-aeeb-6c2376690872', 'b086b7a4-b374-4954-8c25-e3064b345661', 3, '바구니의 수', true),
  ('66572987-6123-4159-ae53-0dd4e3b5b93c', 'b086b7a4-b374-4954-8c25-e3064b345661', 4, '사과와 바구니의 차', false),
  ('0e38f238-0a0b-4687-8bf7-633a973b6286', '15acd98c-4120-4c51-9cc7-282d920319c5', 1, '상자 6개에 공이 3개씩 있음', false),
  ('d230e661-0232-4525-b031-613806a30f34', '15acd98c-4120-4c51-9cc7-282d920319c5', 2, '상자마다 공의 수가 다름', false),
  ('44e1d785-b130-4a7f-b317-bd7ea3150dfe', '15acd98c-4120-4c51-9cc7-282d920319c5', 3, '공 6개와 상자 3개를 한곳에 둠', false),
  ('cc0ba994-a92d-4375-a84d-43a53c2d66db', '15acd98c-4120-4c51-9cc7-282d920319c5', 4, '상자 3개에 공이 6개씩 있음', true),
  ('dfd425c1-793c-4240-bf2f-90d23351108f', '847f1c1f-5d0b-4e83-bab9-81bbdcde32dd', 1, '5+5+5, 5×3', true),
  ('4a2d069f-aad6-45c9-bf6d-4a7f703686d1', '847f1c1f-5d0b-4e83-bab9-81bbdcde32dd', 2, '3+3+3+3+3, 5×3', false),
  ('3b71e567-c45a-42c6-a1fc-9db6d58f7bd8', '847f1c1f-5d0b-4e83-bab9-81bbdcde32dd', 3, '5+3, 3×5', false),
  ('999baf8d-a41b-4c69-abcf-777e284519ad', '847f1c1f-5d0b-4e83-bab9-81bbdcde32dd', 4, '5+5, 5×2', false),
  ('5b71c2e9-2742-4992-a583-8fd9efa60834', '0d4e0904-f748-4b03-b0ce-d0e829948f3b', 1, '사 곱하기 이는 2씩 4묶음입니다.', false),
  ('50ba07d8-1510-4528-abde-3a822e172311', '0d4e0904-f748-4b03-b0ce-d0e829948f3b', 2, '사 곱하기 이는 4씩 2묶음입니다.', true),
  ('3b573e37-bc3e-4ceb-ad5d-904f1b9503be', '0d4e0904-f748-4b03-b0ce-d0e829948f3b', 3, '사 곱하기 이는 4와 2를 이어 쓴 수입니다.', false),
  ('a603f20e-3894-4193-84b1-4068d0d1f420', '0d4e0904-f748-4b03-b0ce-d0e829948f3b', 4, '사 곱하기 이는 4씩 4묶음입니다.', false),
  ('5402dca0-555c-42b2-9142-f231177e9d03', 'b2003b05-45fa-420a-b461-d67a5e675498', 1, '4×2', false),
  ('6133b1d2-1493-49c6-abd5-307eebc5f556', 'b2003b05-45fa-420a-b461-d67a5e675498', 2, '2+4', false),
  ('27c980dd-b38f-425e-b2c5-82f72cfd12c2', 'b2003b05-45fa-420a-b461-d67a5e675498', 3, '2×4', true),
  ('d0636c9d-b619-4ffe-8580-ee7315accea0', 'b2003b05-45fa-420a-b461-d67a5e675498', 4, '4×4', false),
  ('d90f999d-5441-4f0f-a543-e89589da2b50', '07d91a08-cb18-4301-8cda-5d19670f260b', 1, '묶음 수', false),
  ('5e54cada-9728-40c4-b57a-9391fb61cf96', '07d91a08-cb18-4301-8cda-5d19670f260b', 2, '전체 수', false),
  ('fd2167d9-2442-47b1-91ff-d6e6f4b543be', '07d91a08-cb18-4301-8cda-5d19670f260b', 3, '더한 결과', false),
  ('31b45a81-4d96-4ea2-9c9b-fee5e02f92c0', '07d91a08-cb18-4301-8cda-5d19670f260b', 4, '한 묶음의 수', true),
  ('07a69945-e6c7-46b4-8658-1e66bc11b799', '07694bd8-16a5-43a4-8eb5-92cf1f5323c0', 1, '4×5, 4씩 5묶음', true),
  ('b235097d-9382-45b5-b70f-27e7f846ebc2', '07694bd8-16a5-43a4-8eb5-92cf1f5323c0', 2, '5×4, 4씩 5묶음', false),
  ('a26a7700-703b-4b49-a260-67ef2dddb5d4', '07694bd8-16a5-43a4-8eb5-92cf1f5323c0', 3, '4×4, 4씩 5묶음', false),
  ('65be096a-53ca-46c7-b78d-640368b9e177', '07694bd8-16a5-43a4-8eb5-92cf1f5323c0', 4, '4+5, 4씩 5묶음', false),
  ('f28844e3-919e-4e90-a387-24815c21092c', 'cc865498-8cea-49a5-b943-97962a857c50', 1, '2개', false),
  ('0402ed1d-41b0-4471-9559-f05c28d117f0', 'cc865498-8cea-49a5-b943-97962a857c50', 2, '3개', true),
  ('6da54355-5f5a-4e26-a57b-3572d6108225', 'cc865498-8cea-49a5-b943-97962a857c50', 3, '6개', false),
  ('d4be3d6f-ab65-428a-9c28-5d9f4e99cd49', 'cc865498-8cea-49a5-b943-97962a857c50', 4, '12개', false),
  ('8853844d-ec3f-486b-b166-b50e74242bf1', '82d3f527-70f3-409a-a44b-5052aaece093', 1, '4자루', false),
  ('499711dd-3038-4487-bb80-712c5ef9091b', '82d3f527-70f3-409a-a44b-5052aaece093', 2, '16자루', false),
  ('12a2a45b-8470-4970-bb83-07b5cd300a7a', '82d3f527-70f3-409a-a44b-5052aaece093', 3, '5자루', true),
  ('bbf60b4e-ebe1-44f6-8d0e-d82a1e4d707b', '82d3f527-70f3-409a-a44b-5052aaece093', 4, '24자루', false),
  ('b925d5a8-d2e3-4f6d-b264-cb5593c6af11', '1a514908-00cd-4e91-ae68-3e63383e14b1', 1, '4+4+4', false),
  ('594e8816-e14f-467c-8c96-b0232843f724', '1a514908-00cd-4e91-ae68-3e63383e14b1', 2, '3+4+3+4', false),
  ('5d307f76-ec4a-4de1-85a8-e4091bcc7754', '1a514908-00cd-4e91-ae68-3e63383e14b1', 3, '3+3+3', false),
  ('d222ebc6-fa47-4e21-9a78-285176e3a0a8', '1a514908-00cd-4e91-ae68-3e63383e14b1', 4, '3+3+3+3', true),
  ('a82c7cf8-7d7d-4e58-8f71-97e0438bce0b', 'c5637ee5-6a05-4ffa-8744-fea68afd3106', 1, '꽃병 5개에 꽃이 2송이씩 있음', true),
  ('e706781d-6655-4e8e-9502-670f0af4699c', 'c5637ee5-6a05-4ffa-8744-fea68afd3106', 2, '꽃병 2개에 꽃이 5송이씩 있음', false),
  ('b3d0c665-6b71-47cd-abfd-45d5aba8deb5', 'c5637ee5-6a05-4ffa-8744-fea68afd3106', 3, '꽃 2송이와 꽃병 5개를 한곳에 둠', false),
  ('dfda40d1-9b3f-458a-b90c-ecaf5f44f53b', 'c5637ee5-6a05-4ffa-8744-fea68afd3106', 4, '꽃병마다 꽃의 수가 다름', false),
  ('d6bc4758-a3d1-4ebd-a081-1c1db69cbb59', '467a824e-bf92-44bc-9994-fc97f0d9200a', 1, '곱셈은 사용할 수 없어서', false),
  ('17d1513b-a93d-4323-a5fc-9564dacf5f7f', '467a824e-bf92-44bc-9994-fc97f0d9200a', 2, '한 묶음의 수 4와 묶음 수 3의 순서를 바꾸어 썼기 때문에', true),
  ('f9d84c7a-e7c1-4b84-9d9f-ddf8783ac91b', '467a824e-bf92-44bc-9994-fc97f0d9200a', 3, '전체 수가 7이기 때문에', false),
  ('27f3d077-964d-4232-972f-19f384e54732', '467a824e-bf92-44bc-9994-fc97f0d9200a', 4, '묶음마다 수가 다르기 때문에', false),
  ('9f597b43-276d-4273-b631-f80d0440e37e', 'd2ea8a50-a9b2-4fb3-9183-1a7586563c24', 1, '한 묶음의 수가 2인 것', false),
  ('487f4e8d-0384-4a93-8d83-0cea76b523e5', 'd2ea8a50-a9b2-4fb3-9183-1a7586563c24', 2, '같은 수를 더한 것', false),
  ('0ce55430-831f-456a-af1f-6d94e8fd8192', 'd2ea8a50-a9b2-4fb3-9183-1a7586563c24', 3, '묶음 수를 4로 센 것', true),
  ('9b1efc94-f235-438c-ba11-92aa749dd100', 'd2ea8a50-a9b2-4fb3-9183-1a7586563c24', 4, '곱셈을 사용한 것', false),
  ('0f1a46a4-7116-4480-a9c7-e6939e31a673', 'b5809bd6-765c-4f8f-9d04-730530eff3b0', 1, '1', false),
  ('23474d4f-54ba-49d0-9c49-16f377d12dd3', 'b5809bd6-765c-4f8f-9d04-730530eff3b0', 2, '2', false),
  ('770dc7de-cacb-4f3d-96b6-f221bbb9ab84', 'b5809bd6-765c-4f8f-9d04-730530eff3b0', 3, '4', false),
  ('00a9bc69-a5b8-4ed4-82fc-f3dca11e5215', 'b5809bd6-765c-4f8f-9d04-730530eff3b0', 4, '3', true),
  ('f8d5a121-43f1-430e-af8a-c1585d9bdd5b', '176534b3-274d-441d-9733-5fd6a3731c1b', 1, '3씩 4묶음', true),
  ('f66e5041-d702-4d05-9d8b-92ba612b77ab', '176534b3-274d-441d-9733-5fd6a3731c1b', 2, '2씩 5묶음', false),
  ('fa3facc6-2603-4488-9e6b-91e8d4f31871', '176534b3-274d-441d-9733-5fd6a3731c1b', 3, '4씩 2묶음', false),
  ('f61c0ad2-aa51-445f-a470-488f3b3a6563', '176534b3-274d-441d-9733-5fd6a3731c1b', 4, '6씩 1묶음', false),
  ('80de439b-7fde-4e7b-b404-60bfe7fe9555', 'fe4b5d39-cd09-422e-8855-8785342c5a72', 1, '5×3', false),
  ('08b2990b-23e5-4a83-a93d-ed7293f7bb5a', 'fe4b5d39-cd09-422e-8855-8785342c5a72', 2, '3×5', true),
  ('031bef59-1cbf-4a89-83b9-294469dfd31a', 'fe4b5d39-cd09-422e-8855-8785342c5a72', 3, '3×15', false),
  ('30d09c16-a39e-499b-a006-d72a72d6df82', 'fe4b5d39-cd09-422e-8855-8785342c5a72', 4, '15×3', false),
  ('3a4957c0-3027-4807-80e8-f0507f4de748', '2e03ece4-bcca-4c15-b01d-7921fee22ae0', 1, '한 줄에 4개씩 3줄이며 4를 3번 더하기 때문입니다.', true),
  ('bef2884f-ea53-4609-92a3-c1a6c86cf67f', '2e03ece4-bcca-4c15-b01d-7921fee22ae0', 2, '한 줄에 3개씩 4줄이며 앞 수가 줄 수이기 때문입니다.', false),
  ('78e8fe8c-2fc5-4196-9772-63f5d70430f3', '2e03ece4-bcca-4c15-b01d-7921fee22ae0', 3, '4개와 3개를 한곳에 두며 두 수를 더하기 때문입니다.', false),
  ('c3e10041-d3cd-44cb-824f-bc5f0829acdc', '2e03ece4-bcca-4c15-b01d-7921fee22ae0', 4, '줄마다 개수가 다르지만 전체가 12이기 때문입니다.', false),
  ('33477ff6-df4e-477b-9fc1-1d0fd3fc0974', '99dbcb22-524b-4231-b16c-ff4f188a29d2', 1, '상자 수 4를 앞에 쓰므로 맞습니다.', false),
  ('1b2766d5-3b75-4083-950e-c9dbfdbb9b40', '99dbcb22-524b-4231-b16c-ff4f188a29d2', 2, '한 상자의 공 3을 앞에 써서 3×4로 고칩니다.', true),
  ('8aff3fc9-87d5-47ef-ac51-506fb0d62010', '99dbcb22-524b-4231-b16c-ff4f188a29d2', 3, '전체 수 12를 앞에 써서 12×1로 고칩니다.', false),
  ('b926eeba-04c4-45da-aa75-97fda0323a53', '99dbcb22-524b-4231-b16c-ff4f188a29d2', 4, '곱셈으로 나타낼 수 없습니다.', false),
  ('72688923-6fb1-4467-9544-386fc16025dd', 'c3a4ebc2-f202-4310-a9fd-a77691af74e8', 1, '2', false),
  ('5ac884c7-ebdf-4121-b219-08a63b95ec20', 'c3a4ebc2-f202-4310-a9fd-a77691af74e8', 2, '5', false),
  ('e3a815fc-b894-4552-adc3-5565b7c50689', 'c3a4ebc2-f202-4310-a9fd-a77691af74e8', 3, '4', true),
  ('06abe4c0-bd01-48dd-b149-891153d937b9', 'c3a4ebc2-f202-4310-a9fd-a77691af74e8', 4, '15', false),
  ('09d55526-f6f0-4fef-9fda-c3e542f1fad7', '6e7062b1-f082-43d2-93f8-250d9c139610', 1, '3씩 4묶음', false),
  ('79600135-61e6-44e2-832f-63f26c300d87', '6e7062b1-f082-43d2-93f8-250d9c139610', 2, '3을 네 번 더함', false),
  ('13aa1205-c55c-4bfc-ac5d-bab190c1e48b', '6e7062b1-f082-43d2-93f8-250d9c139610', 3, '한 묶음 3개가 4묶음', false),
  ('e3181a70-9957-4109-b3a5-a0d93b90dec6', '6e7062b1-f082-43d2-93f8-250d9c139610', 4, '4씩 3묶음', true),
  ('d4daf6d7-cf04-46a1-a08e-f7b8f7b59944', 'e6f9b58a-0b52-463f-a0b7-36561a74952e', 1, '처음은 2×6이고 다시 묶으면 3×4이며 전체는 모두 12개입니다.', true),
  ('d9efae89-00b6-4892-afeb-5fad254a8d9c', 'e6f9b58a-0b52-463f-a0b7-36561a74952e', 2, '처음과 다시 묶은 식은 모두 2×6입니다.', false),
  ('8b371207-285b-4c9d-ab4b-ee57608fc1dd', 'e6f9b58a-0b52-463f-a0b7-36561a74952e', 3, '다시 묶으면 6×3이고 전체는 18개입니다.', false),
  ('74cb3215-505c-4ee1-9f31-e40e8ff41506', 'e6f9b58a-0b52-463f-a0b7-36561a74952e', 4, '묶는 방법이 달라지면 전체 수도 달라집니다.', false),
  ('eb48809e-2ada-4b28-8621-0206815cfef0', 'd85b9399-dd4c-454e-b039-3fcc665b4399', 1, '7씩 3묶음', false),
  ('b32dae5d-9fa8-4eb8-9a55-3fbb98ef87c7', 'd85b9399-dd4c-454e-b039-3fcc665b4399', 2, '3씩 7묶음', true),
  ('053a7ad2-82ac-4218-aac3-76d9369b4dc8', 'd85b9399-dd4c-454e-b039-3fcc665b4399', 3, '7+7+7', false),
  ('b6331ab3-a347-4898-a44a-c9035a3bb571', 'd85b9399-dd4c-454e-b039-3fcc665b4399', 4, '한 묶음의 수는 7이고 묶음 수는 3입니다.', false),
  ('f8b48a06-b917-4a1e-ba78-148c4872e5dd', 'f1c4c7b6-8f54-4bd2-83a2-d106ed25a761', 1, '4개, 4×6', false),
  ('96272985-6b10-4407-8d4b-6d289721c85f', 'f1c4c7b6-8f54-4bd2-83a2-d106ed25a761', 2, '24개, 24×4', false),
  ('5a2e9ff9-d91d-4334-8357-f3bcab2c4305', 'f1c4c7b6-8f54-4bd2-83a2-d106ed25a761', 3, '6개, 6×4', true),
  ('a9045256-19b6-475e-9152-51fd13544509', 'f1c4c7b6-8f54-4bd2-83a2-d106ed25a761', 4, '6개, 4×6', false),
  ('d2820535-1185-44d9-89de-c5e01edd42ba', '9ad06fd3-3ac8-4aae-96a8-943445542a62', 1, '2에서 5를 뺍니다.', false),
  ('06929f0e-a87b-49ad-9c5a-385ae39e4753', '9ad06fd3-3ac8-4aae-96a8-943445542a62', 2, '2와 5를 이어 25로 씁니다.', false),
  ('8c8e3101-74ad-495f-9052-c891797bf981', '9ad06fd3-3ac8-4aae-96a8-943445542a62', 3, '5를 두 번만 더합니다.', false),
  ('fa07c099-4d58-4dc7-b7f2-ed2c369ae4e4', '9ad06fd3-3ac8-4aae-96a8-943445542a62', 4, '2를 다섯 번 더한 2+2+2+2+2로 생각합니다.', true),
  ('2e31c4f0-8169-4203-a247-428a0ebf3efe', 'ad8c349d-bf63-4abd-b7a5-4146136a8151', 1, '두 식은 한 묶음의 수와 묶음 수도 모두 같습니다.', false),
  ('d0c742e5-60e3-4876-b5fa-120c1bbe3568', 'ad8c349d-bf63-4abd-b7a5-4146136a8151', 2, '4×3만 곱셈이고 2×6은 곱셈이 아닙니다.', false),
  ('d8321ab0-d3f3-4c82-b648-d809fcd91f2f', 'ad8c349d-bf63-4abd-b7a5-4146136a8151', 3, '4×3과 2×6은 묶는 방법은 다르지만 전체는 같습니다.', true),
  ('8db61567-9df6-4433-98d9-612a38af80f9', 'ad8c349d-bf63-4abd-b7a5-4146136a8151', 4, '전체는 각각 7개와 8개입니다.', false),
  ('910a8dfa-a325-4645-840c-f702df9df66a', '914ed9cc-704f-431e-aa39-0a764c46aee9', 1, '4개씩 3묶음이므로 4×3입니다.', false),
  ('0835d5e0-2d2b-4830-96ea-0186933721a8', '914ed9cc-704f-431e-aa39-0a764c46aee9', 2, '전체 12개이므로 묶음 없이 12×12입니다.', false),
  ('d8fe1da4-cbf8-44f8-af99-4b82dfd8ca14', '914ed9cc-704f-431e-aa39-0a764c46aee9', 3, '3개와 4개를 더하므로 3+4입니다.', false),
  ('029994d3-8809-477d-b14d-997689f356d5', '914ed9cc-704f-431e-aa39-0a764c46aee9', 4, '3개씩 4묶음이므로 3×4입니다.', true);

insert into public.learning_question_skills (
  question_id, skill_code, is_primary
)
values
  ('aaee2904-d460-458c-a536-6699ab430e33', 'identify-equal-groups', true),
  ('9ff12a7a-6bfa-4f9b-bf52-6455145d7927', 'count-equal-groups', true),
  ('ec504283-f43e-4a52-a24d-e90103d6e59a', 'connect-repeated-addition-to-multiplication', true),
  ('ec5be058-8a68-4c33-a2ef-df7895ba2a66', 'count-equal-groups', true),
  ('c04873bf-6a7f-406a-846c-ba947f4eb67e', 'connect-repeated-addition-to-multiplication', true),
  ('9076b1aa-e8fd-42bd-bfc5-b68426257391', 'count-equal-groups', true),
  ('a5bf319d-9315-411d-812d-dbc27de2fab4', 'identify-equal-groups', true),
  ('c1e8d801-fdaf-403e-9d1c-c57a4d640256', 'connect-repeated-addition-to-multiplication', true),
  ('8bb07b1f-283d-406f-a59a-96daa86c7aa7', 'count-equal-groups', true),
  ('5dc9058a-e43d-4cda-bfd0-6461fca6347b', 'connect-repeated-addition-to-multiplication', true),
  ('cd8c1fed-a137-48df-8433-fd5ccf0532e7', 'represent-equal-groups-as-multiplication', true),
  ('7ba7b97a-7971-44b6-91d9-b647090c8962', 'model-multiplication-situation', true),
  ('22d2d91d-3ca4-4941-8986-a9ff05fa09a2', 'connect-repeated-addition-to-multiplication', true),
  ('97e93bbe-c0af-48ad-b00c-aa90675401d6', 'interpret-multiplication-expression', true),
  ('b086b7a4-b374-4954-8c25-e3064b345661', 'interpret-multiplication-expression', true),
  ('15acd98c-4120-4c51-9cc7-282d920319c5', 'model-multiplication-situation', true),
  ('847f1c1f-5d0b-4e83-bab9-81bbdcde32dd', 'connect-repeated-addition-to-multiplication', true),
  ('0d4e0904-f748-4b03-b0ce-d0e829948f3b', 'interpret-multiplication-expression', true),
  ('b2003b05-45fa-420a-b461-d67a5e675498', 'model-multiplication-situation', true),
  ('07d91a08-cb18-4301-8cda-5d19670f260b', 'interpret-multiplication-expression', true),
  ('07694bd8-16a5-43a4-8eb5-92cf1f5323c0', 'represent-equal-groups-as-multiplication', true),
  ('cc865498-8cea-49a5-b943-97962a857c50', 'infer-missing-group-value', true),
  ('82d3f527-70f3-409a-a44b-5052aaece093', 'infer-missing-group-value', true),
  ('1a514908-00cd-4e91-ae68-3e63383e14b1', 'connect-repeated-addition-to-multiplication', true),
  ('c5637ee5-6a05-4ffa-8744-fea68afd3106', 'model-multiplication-situation', true),
  ('467a824e-bf92-44bc-9994-fc97f0d9200a', 'correct-multiplication-reasoning', true),
  ('d2ea8a50-a9b2-4fb3-9183-1a7586563c24', 'correct-multiplication-reasoning', true),
  ('b5809bd6-765c-4f8f-9d04-730530eff3b0', 'infer-missing-group-value', true),
  ('176534b3-274d-441d-9733-5fd6a3731c1b', 'correct-multiplication-reasoning', true),
  ('fe4b5d39-cd09-422e-8855-8785342c5a72', 'infer-missing-group-value', true),
  ('2e03ece4-bcca-4c15-b01d-7921fee22ae0', 'model-multiplication-situation', true),
  ('99dbcb22-524b-4231-b16c-ff4f188a29d2', 'correct-multiplication-reasoning', true),
  ('c3a4ebc2-f202-4310-a9fd-a77691af74e8', 'infer-missing-group-value', true),
  ('6e7062b1-f082-43d2-93f8-250d9c139610', 'interpret-multiplication-expression', true),
  ('e6f9b58a-0b52-463f-a0b7-36561a74952e', 'correct-multiplication-reasoning', true),
  ('d85b9399-dd4c-454e-b039-3fcc665b4399', 'correct-multiplication-reasoning', true),
  ('f1c4c7b6-8f54-4bd2-83a2-d106ed25a761', 'infer-missing-group-value', true),
  ('9ad06fd3-3ac8-4aae-96a8-943445542a62', 'correct-multiplication-reasoning', true),
  ('ad8c349d-bf63-4abd-b7a5-4146136a8151', 'correct-multiplication-reasoning', true),
  ('914ed9cc-704f-431e-aa39-0a764c46aee9', 'connect-repeated-addition-to-multiplication', true);

select (public.publish_learning_content_version('8eb41f37-e2f1-42e9-a1c8-657ca08c9302'::uuid)).id;

commit;
