-- Generated by scripts/generate-learning-content-migration.js.
-- Source: content/learning/math/grade2-classification-v1.json
-- Canonical content SHA-256: 419cef16bc5930431a2ebe77191a20852bc16cf775bc9725706c34deec6e1e3a
-- Content-only and additive: no assignment, attempt, progress, first-pass, ledger, ACL, or Realtime changes.

begin;

do $preflight$
begin
  if exists (
    select 1 from public.learning_courses
    where (id = '51000000-0000-4000-8000-000000000001'::uuid or course_code = 'math-core')
      and not (
        id = '51000000-0000-4000-8000-000000000001'::uuid
        and course_code = 'math-core'
        and internal_name = '수학 기초 과정'
        and subject_name = '수학'
      )
  ) then
    raise exception using errcode = '23505', message = 'grade2_classification_v1 course identifier conflicts with different content';
  end if;

  if not exists (
    select 1 from public.learning_courses
    where id = '51000000-0000-4000-8000-000000000001'::uuid
      and course_code = 'math-core'
      and internal_name = '수학 기초 과정'
      and subject_name = '수학'
      and status = 'published'
  ) then
    raise exception using errcode = 'P0002', message = 'grade2_classification_v1 existing course is missing or changed';
  end if;

  if exists (
    select 1 from public.learning_units
    where id = '0a730ea3-c789-4933-8673-c4869b2a2d20'::uuid
       or unit_code = 'grade2-classification'
  ) then
    raise exception using errcode = '23505', message = 'grade2_classification_v1 unit identifier already exists';
  end if;

  if exists (
    select 1 from public.learning_units
    where course_id = '51000000-0000-4000-8000-000000000001'::uuid
      and sort_order = 6
  ) then
    raise exception using errcode = '23505', message = 'grade2_classification_v1 unit sort order already exists';
  end if;

  if to_regclass('public.learning_unit_recommendation_metadata') is null then
    raise exception using errcode = 'P0002', message = 'learning recommendation metadata table is missing';
  end if;

  if exists (
    select 1
    from public.learning_unit_recommendation_metadata metadata
    where metadata.unit_id = '0a730ea3-c789-4933-8673-c4869b2a2d20'::uuid
      and (
        metadata.subject is distinct from 'math'
        or metadata.recommended_start_level_code is distinct from 'elementary_2'
        or metadata.recommended_end_level_code is distinct from 'elementary_2'
        or metadata.parent_sort_order is distinct from 5
      )
  ) then
    raise exception using errcode = '23505', message = 'learning unit recommendation metadata conflicts with different content';
  end if;

  if to_regclass('public.learning_skill_definitions') is null
     or to_regclass('public.learning_question_skills') is null then
    raise exception using errcode = 'P0002', message = 'learning skill metadata foundation is missing';
  end if;

  if exists (
    select 1
    from (values
  ('identify-classification-rule'),
  ('classify-by-given-rule'),
  ('compare-classification-rules'),
  ('infer-rule-from-groups'),
  ('explain-classification-reasoning'),
  ('find-misclassified-item'),
  ('find-missing-classified-item'),
  ('classify-by-two-properties')
    ) expected_skill(skill_code)
    where not exists (
      select 1 from public.learning_skill_definitions definition
      where definition.skill_code = expected_skill.skill_code
    )
  ) then
    raise exception using errcode = 'P0002', message = 'learning skill definition is missing';
  end if;

  if exists (
    select 1 from public.learning_content_versions
    where id = 'bf3dd0af-3cff-4d29-bdd3-f12e2ef08d9d'::uuid
       or content_hash = '419cef16bc5930431a2ebe77191a20852bc16cf775bc9725706c34deec6e1e3a'
  ) then
    raise exception using errcode = '23505', message = 'grade2_classification_v1 content version already exists';
  end if;

  if exists (
    select 1 from (
      values
  ('297bdcac-d755-49d0-b4bd-09a839e0e4db'::uuid),
  ('de886921-0319-43c2-9577-2d6fdea09db0'::uuid),
  ('e77163a5-41bd-4b69-a30d-3f6e5f8e9bc7'::uuid),
  ('f1059363-160e-47d7-957c-bddd315676a6'::uuid),
  ('c3dadff8-a851-4b99-874b-43b527ae2ac4'::uuid),
  ('d2671053-580c-496a-9aae-75e8490e9227'::uuid),
  ('d383eaf6-61f2-4109-8b22-7dae50225ae8'::uuid),
  ('3f3ea6a6-b981-4f26-a8b3-4893e1028653'::uuid),
  ('7fb21abf-8b0c-4f82-adb2-b854990d121d'::uuid),
  ('0c2c9cd1-f350-4d9d-89e1-9589fe4f8953'::uuid),
  ('242f564a-a221-4ba2-97ee-f37122a3ca35'::uuid),
  ('05988807-5115-402f-a310-bb224cd910c1'::uuid),
  ('7014c2c5-a80d-44d1-8bd4-c024c060ff76'::uuid),
  ('24160d5b-e41c-43a5-acd5-8d3d38be2e7d'::uuid),
  ('90cc32ef-6232-4c84-b3de-298728557cfd'::uuid),
  ('1bd7749c-cb04-43af-a24a-a6162b0f4a72'::uuid),
  ('0e972622-b82a-4af6-95a1-9a91fcf181b7'::uuid),
  ('fded8424-b6f8-486a-baa3-aa1ff6c56132'::uuid),
  ('ad08071c-4a9e-4bbc-a961-3124f7c2613b'::uuid),
  ('4fe929fc-0832-4f74-88c2-81a8f155562f'::uuid),
  ('718cf3dc-ca79-46b8-9591-0eb135412805'::uuid),
  ('5638de18-500f-4742-a1e5-6e5c68d62125'::uuid),
  ('a771d0b4-0cc6-44a9-88aa-9d2b5798afee'::uuid),
  ('4a7ae45c-7152-4672-b5c5-a37cb2cedf76'::uuid),
  ('d71db0b0-f672-4d83-965d-a503146b9217'::uuid),
  ('d65135d7-3489-492d-88ae-8d9fd52e4d86'::uuid),
  ('c8b47fdb-2a56-41ac-8da6-ddab8c0a36b9'::uuid),
  ('8f89136e-8cb9-4525-b809-b6292aca67cf'::uuid),
  ('13b51c55-6aea-4848-bf78-5df48f927f8e'::uuid),
  ('ffed7c7c-0bab-4f37-9a62-5b2f62e1329e'::uuid),
  ('7d1a86e8-0c01-45f6-b903-4b0f64ea0e14'::uuid),
  ('37ca26ac-35f9-43ed-8ef4-6db548cb1d1d'::uuid),
  ('2b412b75-12f3-4216-9fc7-51885d8acec2'::uuid),
  ('9a1f7d65-07f8-4439-9aa8-68ad6a33eb47'::uuid),
  ('9e5663ef-86e5-454a-94c7-aa3d0adcb554'::uuid),
  ('1630075d-6852-4645-9141-104ba79af24e'::uuid),
  ('95658c4b-c31b-4e3b-aa88-50f87198b062'::uuid),
  ('cd3a0422-f38e-4968-9a61-15e0fadba95a'::uuid),
  ('ce19dbfb-683c-48f7-9026-5d0b5035c8ea'::uuid),
  ('06516ce7-7865-4105-9777-c6f2fe054ce5'::uuid),
  ('a993ac7d-ae20-45c2-bd5b-c1007650b521'::uuid),
  ('06427732-d3b5-4474-8488-604fc93a28f1'::uuid),
  ('10656aa7-f917-48d5-8148-6967121755c3'::uuid),
  ('c970faec-edd8-4fe7-b451-65398b5321ba'::uuid),
  ('a843ece1-7885-4e99-bc4e-422c1b76b91b'::uuid),
  ('8a34cd5a-28f9-439d-93cf-1ce140b1b0a6'::uuid),
  ('42c1df87-b825-4b9f-a00a-00c745da23c6'::uuid),
  ('e74d400e-3f02-41de-a332-6b30b7ecc042'::uuid),
  ('c6038263-6516-4267-8a6a-e5619dba790a'::uuid),
  ('279aac18-961d-43bd-b8a2-5f398f996f98'::uuid),
  ('2c39db67-c99e-4906-b60e-923315a653e3'::uuid),
  ('e9c651e7-0f03-4c97-926d-5ebe5b99a00d'::uuid),
  ('39d6a6b9-f64d-45bb-bd93-fecad2f0ea22'::uuid),
  ('dceb8e78-7692-4675-892b-c3eea9aac01f'::uuid),
  ('8c70bce2-b63c-49fd-a5d3-e29f7b7bec97'::uuid),
  ('d634fcc0-e759-421e-9ef5-c336817ce282'::uuid),
  ('df32fddf-ef85-4616-93dd-1dc46bb72b4c'::uuid),
  ('95581a2e-eecf-4c7f-a463-412904efdf0a'::uuid),
  ('73b9fae7-e8ef-404f-9c0d-69f810ca8d2b'::uuid),
  ('617ca236-10aa-4db0-8f62-237e161269b3'::uuid),
  ('b269512a-d5e1-4074-853f-f710f39b3ece'::uuid),
  ('0e3443ba-5594-4f31-80a7-6661cdeedc6c'::uuid),
  ('caa1152c-db99-4ab1-a842-eea4ce555f9c'::uuid),
  ('9a5b719b-001e-410d-b163-9f65dc75b4e0'::uuid),
  ('544bb3b6-8726-47ba-b232-527ce941ae92'::uuid),
  ('dee40ca5-841b-4d50-9b38-7eee3dc94e32'::uuid),
  ('12cf2e3b-edd8-44de-81dd-8920afa0c149'::uuid),
  ('684afc71-4032-473f-ab9a-84d43101a919'::uuid),
  ('301fca38-aaee-4784-a617-f33f5e686404'::uuid),
  ('d2ee5f23-0cb8-427e-b3c9-54fbe2467c29'::uuid),
  ('16a6f7b0-1ea6-4315-be37-03c9ee67a19a'::uuid),
  ('cd4e8463-58c1-45f5-8a07-3a2ca2f8a6db'::uuid),
  ('d392ca97-73c8-46fe-9339-b26752da73aa'::uuid),
  ('e3a907c9-5a4a-4cee-a637-9f0126862665'::uuid),
  ('3532c566-67fc-464a-aec7-d047c22198cb'::uuid),
  ('16f38fbb-01ab-4f73-9679-bacbce01ed1b'::uuid),
  ('5cc5ff4d-2a1e-421d-a859-bd95c23bf965'::uuid),
  ('125b0db1-291b-4cac-a6d4-d73bf2d2a77c'::uuid),
  ('c7915170-c055-4897-8ce7-988d196f1bcf'::uuid),
  ('db0b80ed-53b6-4100-9850-3f7de4f98ffc'::uuid),
  ('20dd0681-ee1c-4baa-8ae3-f43d56b5edcc'::uuid),
  ('5e405e70-ab5e-4df5-b8ea-a1039f304621'::uuid),
  ('f5ff02ce-1280-4139-8c57-6004e6e6f004'::uuid),
  ('767685fb-bbd4-4d84-b9d6-60da480fae3b'::uuid),
  ('b146f7a8-7b4d-47b4-81c8-76f874206bd6'::uuid),
  ('98d2d804-3876-4fd4-bbe5-4bee07516dbd'::uuid),
  ('7ea2f4b7-c57e-4ee7-93cb-848d5de6e8a9'::uuid),
  ('a7d93d62-7c13-4c6d-80f5-1ee1b8524b47'::uuid),
  ('2df3cdb8-a9eb-4849-ad7a-37c500a9a987'::uuid),
  ('745bda1a-1ef4-42ec-be54-717a55d39be8'::uuid),
  ('c38f0ed4-60f4-4f90-bed1-8192b79e10fb'::uuid),
  ('60c09039-37b2-41b8-8927-c1715dc3de86'::uuid),
  ('6044505f-6a68-4ee1-9e0f-e71062917c85'::uuid),
  ('597df483-6937-4195-bd6d-634255471329'::uuid),
  ('880c1794-9ea9-4134-98e9-d43f75be5cb9'::uuid),
  ('3d22f912-a41c-4a98-bc4d-7a3ce9f80439'::uuid),
  ('f717c7ed-b5a4-483c-bec8-df1759c95785'::uuid),
  ('cb0cbb11-31c8-48d1-962b-134fbe5d1388'::uuid),
  ('dace2bb0-9403-4619-8d68-9de25beebd11'::uuid),
  ('532e0635-2910-4285-a3a1-2ca9f004f9f3'::uuid),
  ('0d0727af-5175-438c-9430-9402b636a4b7'::uuid),
  ('2f5e67e9-aac2-403e-b3b5-a5f0ab045745'::uuid),
  ('7bb67582-3f79-48d4-a9f7-5d299f25e1ad'::uuid),
  ('830c3641-6f54-4360-b2f3-a3f1cc8910fd'::uuid),
  ('9a7b9ad2-e3a6-4a89-83dd-e550c4452cd9'::uuid),
  ('79419442-5916-467f-9456-3ec3133892d8'::uuid),
  ('f297406b-ce05-424d-ac61-083f9a7de5fa'::uuid),
  ('9bee59d7-24b8-4124-8bb5-b3eab59d52a0'::uuid),
  ('02b06781-cc70-4aa1-b3b2-970469854ce3'::uuid),
  ('948638eb-ed91-4806-a521-0996f6902953'::uuid),
  ('15634ead-af7a-481d-a99a-4d4e53849e84'::uuid),
  ('9446b806-0a7f-43d9-b95f-e10149c4d861'::uuid),
  ('d3c75fc3-d7e9-43ab-a383-626fbf26171b'::uuid),
  ('31e48c5f-bf7c-416f-86f9-7f9d70848dfd'::uuid),
  ('a4ffc02c-e207-43fc-8c64-2289c3460b1d'::uuid),
  ('b963fca5-b0f2-4dea-a314-0c05f95d8a1a'::uuid),
  ('549eb6e9-8381-4f20-8c46-a573ee0f35a0'::uuid),
  ('75b1efdc-1929-40db-9c55-677fd52b5ea2'::uuid),
  ('062fc554-ae22-4bb1-9f7a-f8e5f5c83158'::uuid),
  ('148df56d-bd12-4bbf-9067-22b27c7d3a45'::uuid),
  ('dc446c6b-85c2-4e27-8140-26f6b4a75d45'::uuid),
  ('b3d2491d-1cb8-4b8a-b411-ebe86cd21cbd'::uuid),
  ('14615013-bade-44ea-a0e7-12bf7bc286d7'::uuid),
  ('0d749311-5f4b-4d05-a2b0-c228b2b82f2b'::uuid),
  ('4bd1233a-f136-42fe-970c-a595ea625154'::uuid),
  ('79f9b59a-5a10-4365-b345-9046f7772ce2'::uuid),
  ('b0c2d109-c8a5-4edf-91da-3eeb0b004cd8'::uuid),
  ('430b517e-4c2c-4bcd-b424-cf8fdb43e5cb'::uuid),
  ('5552db00-04b1-4b0f-b830-7226909ec63f'::uuid),
  ('d97b3c68-46fb-4eeb-bfe1-19e126911cda'::uuid),
  ('dba69dbb-f214-437c-ba21-d949edd1ba43'::uuid),
  ('fd7b4b0b-31a8-4aa4-80ce-4b9fb0e6d5a2'::uuid),
  ('ef2aad6a-c45c-4585-a6c3-f7537f50af02'::uuid),
  ('1805975f-da92-470d-a111-b2dbeb095a14'::uuid),
  ('79376789-df28-4ddc-88de-4cb7e6197076'::uuid),
  ('8075cbbd-5dac-4e90-8406-28a0a21dd1fd'::uuid),
  ('2e97b46f-c3a6-4b14-85be-a50af48513f2'::uuid),
  ('e30adfc8-bb47-4d6b-bcc8-56ac50e29848'::uuid),
  ('b5c1fe0a-4569-4b34-bcda-f743d4d070b8'::uuid),
  ('203a79e7-67e9-453c-88b0-0a34d217f191'::uuid),
  ('288fa349-f5aa-4869-a28b-11f93d575137'::uuid),
  ('9c478dd1-d648-4c42-9363-216528faec51'::uuid),
  ('a62d452b-bdce-46a2-a01c-2f65ba47b199'::uuid),
  ('9d222a09-a672-4c37-a580-ba0398382608'::uuid),
  ('556c6149-cbbf-4092-8929-9c7155b36666'::uuid),
  ('ed599f22-3e7d-40b9-b87a-95e1b19372ff'::uuid),
  ('47ec71e5-68df-4dc4-80ac-46bd0eb6171c'::uuid),
  ('3093320c-92b0-4d2f-b7e6-dd21cab55d02'::uuid),
  ('5ccf0fc5-f17b-4ba2-adb9-259efbd55f9a'::uuid),
  ('2b90b6c7-28c2-4857-b254-33bc7fca6939'::uuid),
  ('1fd194e3-64c1-4b91-852d-29f531de5a10'::uuid),
  ('46304484-9de4-411a-bd66-b8dba7f29370'::uuid),
  ('69f6556a-8a97-499c-bbb8-33b72b598e0e'::uuid),
  ('92ac7578-e203-4dc9-b645-c7a4400b7e8c'::uuid),
  ('fba44793-b793-44a7-9fff-56cba55576e4'::uuid),
  ('077c9427-f3b6-4120-9ae0-e9067d7135dc'::uuid),
  ('3128ed59-0638-4134-a22b-a094ca5a6806'::uuid),
  ('a0f4fca9-51ea-4fd9-89bc-07f1fd7efce9'::uuid),
  ('e1782207-63d1-41bf-b250-d72c068e49d1'::uuid),
  ('a698b6da-c041-403f-a710-a8c3f8061ea7'::uuid),
  ('45f5ceca-de95-40ac-94f9-f74b8567c6d2'::uuid),
  ('d719cd8e-b4c4-491a-b7a9-c686af0d70e5'::uuid),
  ('a2af4115-1eb9-49fa-b7f0-0ec738898477'::uuid),
  ('fd107d8d-5e91-48fa-823f-1541bd7d52bc'::uuid),
  ('b2daa3af-1d54-4011-b146-427d756cc79d'::uuid),
  ('c113b111-0bef-47b3-82e0-cd144235b64e'::uuid),
  ('761f3ebe-ebb3-45a8-8c18-09f37eb8f932'::uuid),
  ('a940ebd7-d4a1-4ebb-8b1f-818b01425f17'::uuid),
  ('d0673441-fb43-41b2-a1b5-e3d290d17c3b'::uuid),
  ('eefca122-e722-4772-a27b-2871ee5fca86'::uuid),
  ('d8e20ce7-5627-4e62-bd7d-e6af857d4c91'::uuid),
  ('c129cfc2-6a3c-4c04-b2a7-bbe251ef8983'::uuid),
  ('501bd87b-1cb6-4444-ae6a-caa87772a6a7'::uuid),
  ('e980eb7e-4b32-4919-aa52-b0c8b3bbb43c'::uuid),
  ('82b2fc46-0c47-4cf9-be24-21fa06119e8d'::uuid),
  ('752eac4e-fed5-47c9-a1d2-d39eaada9200'::uuid),
  ('cd72f643-b3a8-4dbc-b4b7-796ff08b4003'::uuid),
  ('d3e40d1a-3c26-4fb7-8e15-943106a13036'::uuid),
  ('60a305fc-8e52-40b5-a4f7-33316613710d'::uuid),
  ('3f7a97f7-b4d9-4845-90cb-837b1e8ef508'::uuid),
  ('f95b950e-29fd-4ce0-97d4-ddb4ea0b5418'::uuid),
  ('71837364-5cf6-45cc-8e2e-572bf13ad5e5'::uuid),
  ('3f4f5830-c183-4e52-a579-3081334e7913'::uuid),
  ('ea383ea3-2f7f-46be-8235-373d95a372c6'::uuid),
  ('411f6b56-da1c-4e07-af3e-d4bdb8ab0cfc'::uuid),
  ('88a4127f-b00a-4ddb-a87f-1df901bc0285'::uuid),
  ('a8789164-b9f9-4410-b658-1b03ea620b3c'::uuid),
  ('da06aa21-e01d-4b73-a450-e57493189251'::uuid),
  ('b8883ecf-82b4-4ccf-8704-8b66ba54ed64'::uuid),
  ('fbc802d1-5737-4c8f-8691-ad5a43a477cb'::uuid),
  ('16e8a201-1ba5-46ed-a015-637623675f30'::uuid),
  ('40dd8a82-8c46-438b-a977-7f55fc87b17d'::uuid),
  ('e807ebb6-2b6e-470b-b04b-229c6288d072'::uuid),
  ('0f0108df-bba5-41a3-a909-fb11f51d448e'::uuid),
  ('74d1b05e-f85a-42e8-ab03-4ae46c358cd5'::uuid),
  ('e5435d71-9e1b-492f-b245-92b665acc60b'::uuid),
  ('9cddaff6-b0dd-49c8-b005-158dc3e0b8f7'::uuid),
  ('e906c480-a5b6-414c-9473-85575c4245a3'::uuid),
  ('42e46a6f-b4d1-4b14-b6d7-248e938584e2'::uuid),
  ('f54d3a34-097d-4d83-8b8c-eb680ef1a4d5'::uuid),
  ('c1f7cd49-a1cd-41c4-a7ad-5ed7299e22ed'::uuid),
  ('284c90fd-a9c9-47cd-ba4d-c0f8f909afa8'::uuid),
  ('d68862f4-eb25-402b-b883-c2ccd1068101'::uuid),
  ('028abab6-1a78-4887-8e37-0df9cd53b83d'::uuid)
    ) as expected_id(id)
    where exists (
      select 1 from public.learning_stages where id = expected_id.id
      union all
      select 1 from public.learning_questions where id = expected_id.id
      union all
      select 1 from public.learning_question_options where id = expected_id.id
    )
  ) then
    raise exception using errcode = '23505', message = 'grade2_classification_v1 child content identifier already exists';
  end if;
end
$preflight$;

insert into public.learning_units (id, course_id, unit_code, display_title, sort_order)
values ('0a730ea3-c789-4933-8673-c4869b2a2d20', '51000000-0000-4000-8000-000000000001', 'grade2-classification', '기준에 따라 분류해요', 6);

insert into public.learning_unit_recommendation_metadata (
  unit_id, subject, recommended_start_level_code, recommended_end_level_code, parent_sort_order
)
select '0a730ea3-c789-4933-8673-c4869b2a2d20'::uuid, 'math', 'elementary_2', 'elementary_2', 5
where not exists (
  select 1
  from public.learning_unit_recommendation_metadata metadata
  where metadata.unit_id = '0a730ea3-c789-4933-8673-c4869b2a2d20'::uuid
);

insert into public.learning_content_versions (id, unit_id, version_no, content_hash)
values ('bf3dd0af-3cff-4d29-bdd3-f12e2ef08d9d', '0a730ea3-c789-4933-8673-c4869b2a2d20', 1, '419cef16bc5930431a2ebe77191a20852bc16cf775bc9725706c34deec6e1e3a');

insert into public.learning_stages (id, content_version_id, display_order, display_title, difficulty)
values
  ('297bdcac-d755-49d0-b4bd-09a839e0e4db', 'bf3dd0af-3cff-4d29-bdd3-f12e2ef08d9d', 1, '입문', 'seed'),
  ('de886921-0319-43c2-9577-2d6fdea09db0', 'bf3dd0af-3cff-4d29-bdd3-f12e2ef08d9d', 2, '기초', 'leaf'),
  ('e77163a5-41bd-4b69-a30d-3f6e5f8e9bc7', 'bf3dd0af-3cff-4d29-bdd3-f12e2ef08d9d', 3, '심화', 'tree'),
  ('f1059363-160e-47d7-957c-bddd315676a6', 'bf3dd0af-3cff-4d29-bdd3-f12e2ef08d9d', 4, '최상위 도전!', 'crown');

insert into public.learning_questions (id, stage_id, display_order, prompt, explanation)
values
  ('c3dadff8-a851-4b99-874b-43b527ae2ac4', '297bdcac-d755-49d0-b4bd-09a839e0e4db', 1, '사과, 딸기, 수박을 한 모둠으로 묶었습니다. 알맞은 기준은?', '사과와 딸기와 수박은 모두 과일이므로 과일이라는 기준으로 묶었습니다.'),
  ('d2671053-580c-496a-9aae-75e8490e9227', '297bdcac-d755-49d0-b4bd-09a839e0e4db', 2, '빨간 공, 빨간 연필, 빨간 모자를 한 모둠으로 묶었습니다. 알맞은 기준은?', '세 물건은 모양과 쓰임은 다르지만 모두 빨간색입니다.'),
  ('d383eaf6-61f2-4109-8b22-7dae50225ae8', '297bdcac-d755-49d0-b4bd-09a839e0e4db', 3, '''네모 모양인 것'' 모둠에 들어갈 것은?', '책은 앞면이 네모 모양이므로 주어진 모둠에 들어갑니다.'),
  ('3f3ea6a6-b981-4f26-a8b3-4893e1028653', '297bdcac-d755-49d0-b4bd-09a839e0e4db', 4, '''학교에서 쓰는 물건'' 모둠에 들어갈 것은?', '공책은 학교에서 공부할 때 쓰는 물건입니다.'),
  ('7fb21abf-8b0c-4f82-adb2-b854990d121d', '297bdcac-d755-49d0-b4bd-09a839e0e4db', 5, '2, 4, 6, 8을 한 모둠으로 묶었습니다. 알맞은 기준은?', '2와 4와 6과 8은 모두 2로 나누어떨어지는 짝수입니다.'),
  ('0c2c9cd1-f350-4d9d-89e1-9589fe4f8953', '297bdcac-d755-49d0-b4bd-09a839e0e4db', 6, '''날개가 있는 동물'' 모둠에 들어갈 것은?', '참새는 날개가 있는 동물이고 나머지 동물은 날개가 없습니다.'),
  ('242f564a-a221-4ba2-97ee-f37122a3ca35', '297bdcac-d755-49d0-b4bd-09a839e0e4db', 7, '''물에 뜨는 물건''을 찾는 실험 결과에 따라 모둠에 넣을 것은?', '실험에서 물 위에 뜬 나무토막만 ''물에 뜨는 물건'' 모둠에 들어갑니다.'),
  ('05988807-5115-402f-a310-bb224cd910c1', '297bdcac-d755-49d0-b4bd-09a839e0e4db', 8, '''먹을 수 있는 것'' 모둠에 들어갈 것은?', '바나나는 먹을 수 있는 과일입니다.'),
  ('7014c2c5-a80d-44d1-8bd4-c024c060ff76', '297bdcac-d755-49d0-b4bd-09a839e0e4db', 9, '연필, 지우개, 자를 한 모둠으로 묶었습니다. 알맞은 기준은?', '연필과 지우개와 자는 모두 공부할 때 쓰는 학용품입니다.'),
  ('24160d5b-e41c-43a5-acd5-8d3d38be2e7d', '297bdcac-d755-49d0-b4bd-09a839e0e4db', 10, '''10보다 큰 수'' 모둠에 들어갈 것은?', '13은 10보다 크고 나머지 수는 10보다 크지 않습니다.'),
  ('90cc32ef-6232-4c84-b3de-298728557cfd', 'de886921-0319-43c2-9577-2d6fdea09db0', 1, '단추를 ''빨간색/파란색''으로 나누는 기준과 ''큰 것/작은 것''으로 나누는 기준을 비교했습니다. 색깔별 단추 수를 알고 싶을 때 알맞은 기준은?', '색깔별 수를 알려면 빨간색과 파란색처럼 색깔을 기준으로 나누어야 합니다.'),
  ('1bd7749c-cb04-43af-a24a-a6162b0f4a72', 'de886921-0319-43c2-9577-2d6fdea09db0', 2, '책을 ''동화책/과학책''과 ''큰 책/작은 책''으로 나눌 수 있습니다. 책의 내용을 찾기 쉽게 정리하려면 알맞은 기준은?', '읽고 싶은 내용을 찾기 쉽게 하려면 동화책과 과학책처럼 내용으로 나누는 것이 알맞습니다.'),
  ('0e972622-b82a-4af6-95a1-9a91fcf181b7', 'de886921-0319-43c2-9577-2d6fdea09db0', 3, '1모둠은 2, 4, 6이고 2모둠은 1, 3, 5입니다. 사용한 기준은?', '1모둠은 짝수이고 2모둠은 홀수이므로 짝수와 홀수로 나누었습니다.'),
  ('fded8424-b6f8-486a-baa3-aa1ff6c56132', 'de886921-0319-43c2-9577-2d6fdea09db0', 4, '1모둠은 버스와 기차이고 2모둠은 자전거와 킥보드입니다. 제시된 특징으로 알맞게 설명한 것은?', '버스와 기차는 많은 사람이 함께 타고 자전거와 킥보드는 주로 한 사람이 탑니다.'),
  ('ad08071c-4a9e-4bbc-a961-3124f7c2613b', 'de886921-0319-43c2-9577-2d6fdea09db0', 5, '빨간 블록은 5개, 파란 블록은 3개로 색깔에 따라 분류했습니다. 분류 결과로 알 수 있는 것은?', '빨간 블록 5개와 파란 블록 3개를 비교하면 빨간 블록이 2개 더 많습니다.'),
  ('4fe929fc-0832-4f74-88c2-81a8f155562f', 'de886921-0319-43c2-9577-2d6fdea09db0', 6, '동물 카드를 ''다리가 2개/다리가 4개''로 나누려고 합니다. 이 기준으로 분류할 때 먼저 확인할 특징은?', '주어진 기준이 다리 수이므로 각 동물의 다리가 몇 개인지 확인해야 합니다.'),
  ('718cf3dc-ca79-46b8-9591-0eb135412805', 'de886921-0319-43c2-9577-2d6fdea09db0', 7, '1모둠은 장미와 해바라기이고 2모둠은 소나무와 전나무입니다. 제시된 특징으로 알맞은 기준은?', '장미와 해바라기는 꽃이 피고 소나무와 전나무는 솔방울이 열리는 나무입니다.'),
  ('5638de18-500f-4742-a1e5-6e5c68d62125', 'de886921-0319-43c2-9577-2d6fdea09db0', 8, '숫자 카드 12, 7, 20, 9를 ''두 자리 수/한 자리 수''로 분류했습니다. 두 자리 수 모둠은?', '12와 20은 두 자리 수이고 7과 9는 한 자리 수입니다.'),
  ('a771d0b4-0cc6-44a9-88aa-9d2b5798afee', 'de886921-0319-43c2-9577-2d6fdea09db0', 9, '빨간 세모, 파란 세모, 빨간 네모, 파란 네모가 있습니다. 모양별 개수를 알고 싶을 때 알맞은 분류 기준은?', '모양별 개수를 알려면 세모와 네모처럼 모양을 기준으로 분류해야 합니다.'),
  ('4a7ae45c-7152-4672-b5c5-a37cb2cedf76', 'de886921-0319-43c2-9577-2d6fdea09db0', 10, '옷을 ''윗옷/아랫옷''으로 정리했습니다. 이 분류 기준과 가장 잘 연결되는 목적은?', '윗옷과 아랫옷은 입는 위치에 따라 옷을 찾기 쉽게 나눈 것입니다.'),
  ('d71db0b0-f672-4d83-965d-a503146b9217', 'e77163a5-41bd-4b69-a30d-3f6e5f8e9bc7', 1, '1모둠은 14, 18, 22이고 2모둠은 13, 17, 21입니다. 사용한 기준은?', '1모둠의 수는 모두 짝수이고 2모둠의 수는 모두 홀수입니다.'),
  ('d65135d7-3489-492d-88ae-8d9fd52e4d86', 'e77163a5-41bd-4b69-a30d-3f6e5f8e9bc7', 2, '''바퀴가 2개인 탈것'' 모둠에 자전거, 오토바이, 버스가 들어 있습니다. 잘못 분류된 것은?', '버스는 바퀴가 2개가 아니므로 이 모둠에 들어갈 수 없습니다.'),
  ('c8b47fdb-2a56-41ac-8da6-ddab8c0a36b9', 'e77163a5-41bd-4b69-a30d-3f6e5f8e9bc7', 3, '전체 카드는 사과, 배, 당근, 오이입니다. ''과일'' 모둠에 사과만 들어 있습니다. 빠진 것은?', '배는 과일이므로 과일 모둠에 빠져 있습니다.'),
  ('8f89136e-8cb9-4525-b809-b6292aca67cf', 'e77163a5-41bd-4b69-a30d-3f6e5f8e9bc7', 4, '빨간 세모, 빨간 네모, 파란 세모, 파란 네모 중 ''빨간색이면서 세모인 것''은?', '빨간 세모만 빨간색과 세모라는 두 조건을 모두 만족합니다.'),
  ('13b51c55-6aea-4848-bf78-5df48f927f8e', 'e77163a5-41bd-4b69-a30d-3f6e5f8e9bc7', 5, '''10보다 크고 짝수인 수'' 모둠에 들어갈 것은?', '14는 10보다 크면서 짝수인 두 조건을 모두 만족합니다.'),
  ('ffed7c7c-0bab-4f37-9a62-5b2f62e1329e', 'e77163a5-41bd-4b69-a30d-3f6e5f8e9bc7', 6, '''네모 모양인 학용품'' 모둠에 책, 공책, 축구공이 들어 있습니다. 잘못 분류된 것은?', '축구공은 학용품도 아니고 네모 모양도 아니므로 잘못 분류되었습니다.'),
  ('7d1a86e8-0c01-45f6-b903-4b0f64ea0e14', 'e77163a5-41bd-4b69-a30d-3f6e5f8e9bc7', 7, '전체 동물은 참새, 독수리, 토끼, 거북입니다. ''날개가 있는 동물'' 모둠에 참새만 있습니다. 빠진 동물은?', '독수리는 날개가 있으므로 날개가 있는 동물 모둠에 빠져 있습니다.'),
  ('37ca26ac-35f9-43ed-8ef4-6db548cb1d1d', 'e77163a5-41bd-4b69-a30d-3f6e5f8e9bc7', 8, '노란 큰 공, 노란 작은 공, 파란 큰 공, 파란 작은 공 중 ''파란색이면서 큰 것''은?', '파란 큰 공만 파란색과 큰 것이라는 두 조건을 모두 만족합니다.'),
  ('2b412b75-12f3-4216-9fc7-51885d8acec2', 'e77163a5-41bd-4b69-a30d-3f6e5f8e9bc7', 9, '1모둠은 숟가락, 젓가락, 포크이고 2모둠은 연필, 지우개, 자입니다. 사용한 기준은?', '1모둠은 식사할 때 쓰는 도구이고 2모둠은 공부할 때 쓰는 학용품입니다.'),
  ('9a1f7d65-07f8-4439-9aa8-68ad6a33eb47', 'e77163a5-41bd-4b69-a30d-3f6e5f8e9bc7', 10, '''20보다 작고 홀수인 수'' 모둠에 7, 13, 18이 들어 있습니다. 잘못 분류된 수는?', '18은 20보다 작지만 짝수이므로 두 조건을 모두 만족하지 않습니다.'),
  ('9e5663ef-86e5-454a-94c7-aa3d0adcb554', 'f1059363-160e-47d7-957c-bddd315676a6', 1, '민지는 빨간 세모, 빨간 네모, 파란 세모를 ''세모/네모''로 나누었습니다. 세모 모둠에 들어갈 항목을 모두 고른 것은?', '색깔과 관계없이 모양이 세모인 빨간 세모와 파란 세모가 함께 들어갑니다.'),
  ('1630075d-6852-4645-9141-104ba79af24e', 'f1059363-160e-47d7-957c-bddd315676a6', 2, '교실 물건을 ''글씨를 쓰는 데 쓰는 것/그 밖의 것''으로 나눕니다. 첫 모둠에 연필, 색연필, 지우개가 있습니다. 옮겨야 할 것은?', '지우개는 쓴 글씨를 지우는 물건이므로 글씨를 쓰는 물건 모둠에서 옮겨야 합니다.'),
  ('95658c4b-c31b-4e3b-aa88-50f87198b062', 'f1059363-160e-47d7-957c-bddd315676a6', 3, '숫자 카드 6, 12, 15, 21을 두 모둠으로 나누었습니다. 1모둠은 6, 12이고 2모둠은 15, 21입니다. 제시된 기준 중 알맞은 것은?', '6과 12는 짝수이고 15와 21은 홀수이므로 짝수와 홀수 기준이 모든 카드에 맞습니다.'),
  ('cd3a0422-f38e-4968-9a61-15e0fadba95a', 'f1059363-160e-47d7-957c-bddd315676a6', 4, '빨간 큰 단추, 빨간 작은 단추, 파란 큰 단추, 파란 작은 단추가 있습니다. ''큰 단추가 몇 개인지'' 알려면 가장 알맞은 첫 분류 기준은?', '큰 단추의 수를 알려면 크기를 기준으로 큰 것과 작은 것을 먼저 나누는 것이 알맞습니다.'),
  ('ce19dbfb-683c-48f7-9026-5d0b5035c8ea', 'f1059363-160e-47d7-957c-bddd315676a6', 5, '전체 카드는 빨간 세모, 빨간 네모, 파란 세모, 파란 네모입니다. ''빨간색인 것'' 모둠에는 빨간 세모만 있습니다. 분류를 완성하려면?', '빨간 네모도 빨간색이므로 빨간색 모둠에 더 넣어야 합니다.'),
  ('06516ce7-7865-4105-9777-c6f2fe054ce5', 'f1059363-160e-47d7-957c-bddd315676a6', 6, '''짝수이면서 20보다 큰 수''를 골랐습니다. 선택과 이유가 모두 알맞은 것은?', '24는 짝수이면서 20보다 크므로 두 조건과 이유를 모두 만족합니다.'),
  ('a993ac7d-ae20-45c2-bd5b-c1007650b521', 'f1059363-160e-47d7-957c-bddd315676a6', 7, '1모둠은 빨간 사과, 빨간 자동차, 빨간 모자이고 2모둠은 파란 공, 파란 연필, 파란 컵입니다. 사용한 기준과 관계없는 특징은?', '두 모둠은 색깔로 나누었으므로 먹을 수 있는지는 사용한 기준과 관계없습니다.'),
  ('06427732-d3b5-4474-8488-604fc93a28f1', 'f1059363-160e-47d7-957c-bddd315676a6', 8, '동물 카드가 오리, 참새, 고양이, 토끼입니다. ''날개가 있음/날개가 없음''으로 나눈 결과로 알맞은 것은?', '오리와 참새는 날개가 있고 고양이와 토끼는 날개가 없습니다.'),
  ('10656aa7-f917-48d5-8148-6967121755c3', 'f1059363-160e-47d7-957c-bddd315676a6', 9, '빨간 큰 상자, 빨간 작은 상자, 파란 큰 상자, 파란 작은 상자 중 ''빨간색이거나 큰 것''에 해당하지 않는 것은?', '파란 작은 상자는 빨간색도 아니고 큰 것도 아니므로 두 조건 중 어느 것도 만족하지 않습니다.'),
  ('c970faec-edd8-4fe7-b451-65398b5321ba', 'f1059363-160e-47d7-957c-bddd315676a6', 10, '학급 물건을 찾기 쉽게 정리하려고 합니다. 가장 알맞은 분류와 이유는?', '학급 물건은 쓰임이 같은 것끼리 나누면 필요한 물건을 빠르게 찾을 수 있습니다.');

insert into public.learning_question_options (id, question_id, display_order, option_text, is_correct)
values
  ('a843ece1-7885-4e99-bc4e-422c1b76b91b', 'c3dadff8-a851-4b99-874b-43b527ae2ac4', 1, '과일', true),
  ('8a34cd5a-28f9-439d-93cf-1ce140b1b0a6', 'c3dadff8-a851-4b99-874b-43b527ae2ac4', 2, '탈것', false),
  ('42c1df87-b825-4b9f-a00a-00c745da23c6', 'c3dadff8-a851-4b99-874b-43b527ae2ac4', 3, '학용품', false),
  ('e74d400e-3f02-41de-a332-6b30b7ecc042', 'c3dadff8-a851-4b99-874b-43b527ae2ac4', 4, '동물', false),
  ('c6038263-6516-4267-8a6a-e5619dba790a', 'd2671053-580c-496a-9aae-75e8490e9227', 1, '동그란 것', false),
  ('279aac18-961d-43bd-b8a2-5f398f996f98', 'd2671053-580c-496a-9aae-75e8490e9227', 2, '빨간색인 것', true),
  ('2c39db67-c99e-4906-b60e-923315a653e3', 'd2671053-580c-496a-9aae-75e8490e9227', 3, '먹을 수 있는 것', false),
  ('e9c651e7-0f03-4c97-926d-5ebe5b99a00d', 'd2671053-580c-496a-9aae-75e8490e9227', 4, '나무로 만든 것', false),
  ('39d6a6b9-f64d-45bb-bd93-fecad2f0ea22', 'd383eaf6-61f2-4109-8b22-7dae50225ae8', 1, '동그란 접시', false),
  ('dceb8e78-7692-4675-892b-c3eea9aac01f', 'd383eaf6-61f2-4109-8b22-7dae50225ae8', 2, '세모 깃발', false),
  ('8c70bce2-b63c-49fd-a5d3-e29f7b7bec97', 'd383eaf6-61f2-4109-8b22-7dae50225ae8', 3, '네모난 책', true),
  ('d634fcc0-e759-421e-9ef5-c336817ce282', 'd383eaf6-61f2-4109-8b22-7dae50225ae8', 4, '공 모양 풍선', false),
  ('df32fddf-ef85-4616-93dd-1dc46bb72b4c', '3f3ea6a6-b981-4f26-a8b3-4893e1028653', 1, '프라이팬', false),
  ('95581a2e-eecf-4c7f-a463-412904efdf0a', '3f3ea6a6-b981-4f26-a8b3-4893e1028653', 2, '베개', false),
  ('73b9fae7-e8ef-404f-9c0d-69f810ca8d2b', '3f3ea6a6-b981-4f26-a8b3-4893e1028653', 3, '칫솔', false),
  ('617ca236-10aa-4db0-8f62-237e161269b3', '3f3ea6a6-b981-4f26-a8b3-4893e1028653', 4, '공책', true),
  ('b269512a-d5e1-4074-853f-f710f39b3ece', '7fb21abf-8b0c-4f82-adb2-b854990d121d', 1, '짝수', true),
  ('0e3443ba-5594-4f31-80a7-6661cdeedc6c', '7fb21abf-8b0c-4f82-adb2-b854990d121d', 2, '홀수', false),
  ('caa1152c-db99-4ab1-a842-eea4ce555f9c', '7fb21abf-8b0c-4f82-adb2-b854990d121d', 3, '10보다 큰 수', false),
  ('9a5b719b-001e-410d-b163-9f65dc75b4e0', '7fb21abf-8b0c-4f82-adb2-b854990d121d', 4, '한 자리 홀수', false),
  ('544bb3b6-8726-47ba-b232-527ce941ae92', '0c2c9cd1-f350-4d9d-89e1-9589fe4f8953', 1, '고양이', false),
  ('dee40ca5-841b-4d50-9b38-7eee3dc94e32', '0c2c9cd1-f350-4d9d-89e1-9589fe4f8953', 2, '참새', true),
  ('12cf2e3b-edd8-44de-81dd-8920afa0c149', '0c2c9cd1-f350-4d9d-89e1-9589fe4f8953', 3, '토끼', false),
  ('684afc71-4032-473f-ab9a-84d43101a919', '0c2c9cd1-f350-4d9d-89e1-9589fe4f8953', 4, '거북', false),
  ('301fca38-aaee-4784-a617-f33f5e686404', '242f564a-a221-4ba2-97ee-f37122a3ca35', 1, '물속에 가라앉은 쇠구슬', false),
  ('d2ee5f23-0cb8-427e-b3c9-54fbe2467c29', '242f564a-a221-4ba2-97ee-f37122a3ca35', 2, '물속에 가라앉은 돌', false),
  ('16a6f7b0-1ea6-4315-be37-03c9ee67a19a', '242f564a-a221-4ba2-97ee-f37122a3ca35', 3, '물 위에 뜬 나무토막', true),
  ('cd4e8463-58c1-45f5-8a07-3a2ca2f8a6db', '242f564a-a221-4ba2-97ee-f37122a3ca35', 4, '물속에 가라앉은 유리구슬', false),
  ('d392ca97-73c8-46fe-9339-b26752da73aa', '05988807-5115-402f-a310-bb224cd910c1', 1, '자', false),
  ('e3a907c9-5a4a-4cee-a637-9f0126862665', '05988807-5115-402f-a310-bb224cd910c1', 2, '우산', false),
  ('3532c566-67fc-464a-aec7-d047c22198cb', '05988807-5115-402f-a310-bb224cd910c1', 3, '비누', false),
  ('16f38fbb-01ab-4f73-9679-bacbce01ed1b', '05988807-5115-402f-a310-bb224cd910c1', 4, '바나나', true),
  ('5cc5ff4d-2a1e-421d-a859-bd95c23bf965', '7014c2c5-a80d-44d1-8bd4-c024c060ff76', 1, '학용품', true),
  ('125b0db1-291b-4cac-a6d4-d73bf2d2a77c', '7014c2c5-a80d-44d1-8bd4-c024c060ff76', 2, '과일', false),
  ('c7915170-c055-4897-8ce7-988d196f1bcf', '7014c2c5-a80d-44d1-8bd4-c024c060ff76', 3, '악기', false),
  ('db0b80ed-53b6-4100-9850-3f7de4f98ffc', '7014c2c5-a80d-44d1-8bd4-c024c060ff76', 4, '옷', false),
  ('20dd0681-ee1c-4baa-8ae3-f43d56b5edcc', '24160d5b-e41c-43a5-acd5-8d3d38be2e7d', 1, '7', false),
  ('5e405e70-ab5e-4df5-b8ea-a1039f304621', '24160d5b-e41c-43a5-acd5-8d3d38be2e7d', 2, '13', true),
  ('f5ff02ce-1280-4139-8c57-6004e6e6f004', '24160d5b-e41c-43a5-acd5-8d3d38be2e7d', 3, '10', false),
  ('767685fb-bbd4-4d84-b9d6-60da480fae3b', '24160d5b-e41c-43a5-acd5-8d3d38be2e7d', 4, '4', false),
  ('b146f7a8-7b4d-47b4-81c8-76f874206bd6', '90cc32ef-6232-4c84-b3de-298728557cfd', 1, '단추의 재료', false),
  ('98d2d804-3876-4fd4-bbe5-4bee07516dbd', '90cc32ef-6232-4c84-b3de-298728557cfd', 2, '단추의 구멍 수', false),
  ('7ea2f4b7-c57e-4ee7-93cb-848d5de6e8a9', '90cc32ef-6232-4c84-b3de-298728557cfd', 3, '단추의 색깔', true),
  ('a7d93d62-7c13-4c6d-80f5-1ee1b8524b47', '90cc32ef-6232-4c84-b3de-298728557cfd', 4, '단추의 크기', false),
  ('2df3cdb8-a9eb-4849-ad7a-37c500a9a987', '1bd7749c-cb04-43af-a24a-a6162b0f4a72', 1, '책의 두께', false),
  ('745bda1a-1ef4-42ec-be54-717a55d39be8', '1bd7749c-cb04-43af-a24a-a6162b0f4a72', 2, '책의 색깔', false),
  ('c38f0ed4-60f4-4f90-bed1-8192b79e10fb', '1bd7749c-cb04-43af-a24a-a6162b0f4a72', 3, '책의 크기', false),
  ('60c09039-37b2-41b8-8927-c1715dc3de86', '1bd7749c-cb04-43af-a24a-a6162b0f4a72', 4, '책의 내용', true),
  ('6044505f-6a68-4ee1-9e0f-e71062917c85', '0e972622-b82a-4af6-95a1-9a91fcf181b7', 1, '짝수와 홀수', true),
  ('597df483-6937-4195-bd6d-634255471329', '0e972622-b82a-4af6-95a1-9a91fcf181b7', 2, '큰 수와 작은 수', false),
  ('880c1794-9ea9-4134-98e9-d43f75be5cb9', '0e972622-b82a-4af6-95a1-9a91fcf181b7', 3, '한 자리 수와 두 자리 수', false),
  ('3d22f912-a41c-4a98-bc4d-7a3ce9f80439', '0e972622-b82a-4af6-95a1-9a91fcf181b7', 4, '5보다 큰 수와 작은 수', false),
  ('f717c7ed-b5a4-483c-bec8-df1759c95785', 'fded8424-b6f8-486a-baa3-aa1ff6c56132', 1, '1모둠은 바퀴가 없고 2모둠은 바퀴가 있습니다.', false),
  ('cb0cbb11-31c8-48d1-962b-134fbe5d1388', 'fded8424-b6f8-486a-baa3-aa1ff6c56132', 2, '1모둠은 많은 사람이 함께 타고 2모둠은 주로 한 사람이 탑니다.', true),
  ('dace2bb0-9403-4619-8d68-9de25beebd11', 'fded8424-b6f8-486a-baa3-aa1ff6c56132', 3, '1모둠은 물에서 다니고 2모둠은 하늘에서 다닙니다.', false),
  ('532e0635-2910-4285-a3a1-2ca9f004f9f3', 'fded8424-b6f8-486a-baa3-aa1ff6c56132', 4, '1모둠은 동물이고 2모둠은 식물입니다.', false),
  ('0d0727af-5175-438c-9430-9402b636a4b7', 'ad08071c-4a9e-4bbc-a961-3124f7c2613b', 1, '블록의 무게', false),
  ('2f5e67e9-aac2-403e-b3b5-a5f0ab045745', 'ad08071c-4a9e-4bbc-a961-3124f7c2613b', 2, '블록의 재료', false),
  ('7bb67582-3f79-48d4-a9f7-5d299f25e1ad', 'ad08071c-4a9e-4bbc-a961-3124f7c2613b', 3, '빨간 블록이 파란 블록보다 2개 많습니다.', true),
  ('830c3641-6f54-4360-b2f3-a3f1cc8910fd', 'ad08071c-4a9e-4bbc-a961-3124f7c2613b', 4, '블록을 만든 사람', false),
  ('9a7b9ad2-e3a6-4a89-83dd-e550c4452cd9', '4fe929fc-0832-4f74-88c2-81a8f155562f', 1, '사는 곳', false),
  ('79419442-5916-467f-9456-3ec3133892d8', '4fe929fc-0832-4f74-88c2-81a8f155562f', 2, '먹이', false),
  ('f297406b-ce05-424d-ac61-083f9a7de5fa', '4fe929fc-0832-4f74-88c2-81a8f155562f', 3, '몸의 색깔', false),
  ('9bee59d7-24b8-4124-8bb5-b3eab59d52a0', '4fe929fc-0832-4f74-88c2-81a8f155562f', 4, '다리 수', true),
  ('02b06781-cc70-4aa1-b3b2-970469854ce3', '718cf3dc-ca79-46b8-9591-0eb135412805', 1, '꽃이 피는 식물과 솔방울이 열리는 나무', true),
  ('948638eb-ed91-4806-a521-0996f6902953', '718cf3dc-ca79-46b8-9591-0eb135412805', 2, '키가 1m보다 큰 것과 작은 것', false),
  ('15634ead-af7a-481d-a99a-4d4e53849e84', '718cf3dc-ca79-46b8-9591-0eb135412805', 3, '잎이 정확히 10장인 것과 아닌 것', false),
  ('9446b806-0a7f-43d9-b95f-e10149c4d861', '718cf3dc-ca79-46b8-9591-0eb135412805', 4, '실내에만 사는 것과 실외에만 사는 것', false),
  ('d3c75fc3-d7e9-43ab-a383-626fbf26171b', '5638de18-500f-4742-a1e5-6e5c68d62125', 1, '7, 9', false),
  ('31e48c5f-bf7c-416f-86f9-7f9d70848dfd', '5638de18-500f-4742-a1e5-6e5c68d62125', 2, '12, 20', true),
  ('a4ffc02c-e207-43fc-8c64-2289c3460b1d', '5638de18-500f-4742-a1e5-6e5c68d62125', 3, '12, 9', false),
  ('b963fca5-b0f2-4dea-a314-0c05f95d8a1a', '5638de18-500f-4742-a1e5-6e5c68d62125', 4, '7, 20', false),
  ('549eb6e9-8381-4f20-8c46-a573ee0f35a0', 'a771d0b4-0cc6-44a9-88aa-9d2b5798afee', 1, '물건의 이름', false),
  ('75b1efdc-1929-40db-9c55-677fd52b5ea2', 'a771d0b4-0cc6-44a9-88aa-9d2b5798afee', 2, '색깔', false),
  ('062fc554-ae22-4bb1-9f7a-f8e5f5c83158', 'a771d0b4-0cc6-44a9-88aa-9d2b5798afee', 3, '모양', true),
  ('148df56d-bd12-4bbf-9067-22b27c7d3a45', 'a771d0b4-0cc6-44a9-88aa-9d2b5798afee', 4, '크기', false),
  ('dc446c6b-85c2-4e27-8140-26f6b4a75d45', '4a7ae45c-7152-4672-b5c5-a37cb2cedf76', 1, '색깔별 수 알아보기', false),
  ('b3d2491d-1cb8-4b8a-b411-ebe86cd21cbd', '4a7ae45c-7152-4672-b5c5-a37cb2cedf76', 2, '가격 비교하기', false),
  ('14615013-bade-44ea-a0e7-12bf7bc286d7', '4a7ae45c-7152-4672-b5c5-a37cb2cedf76', 3, '크기 재기', false),
  ('0d749311-5f4b-4d05-a2b0-c228b2b82f2b', '4a7ae45c-7152-4672-b5c5-a37cb2cedf76', 4, '입는 위치에 따라 찾기 쉽게 하기', true),
  ('4bd1233a-f136-42fe-970c-a595ea625154', 'd71db0b0-f672-4d83-965d-a503146b9217', 1, '짝수와 홀수', true),
  ('79f9b59a-5a10-4365-b345-9046f7772ce2', 'd71db0b0-f672-4d83-965d-a503146b9217', 2, '20보다 큰 수와 작은 수', false),
  ('b0c2d109-c8a5-4edf-91da-3eeb0b004cd8', 'd71db0b0-f672-4d83-965d-a503146b9217', 3, '십의 자리 숫자', false),
  ('430b517e-4c2c-4bcd-b424-cf8fdb43e5cb', 'd71db0b0-f672-4d83-965d-a503146b9217', 4, '3의 배수와 아닌 수', false),
  ('5552db00-04b1-4b0f-b830-7226909ec63f', 'd65135d7-3489-492d-88ae-8d9fd52e4d86', 1, '자전거', false),
  ('d97b3c68-46fb-4eeb-bfe1-19e126911cda', 'd65135d7-3489-492d-88ae-8d9fd52e4d86', 2, '버스', true),
  ('dba69dbb-f214-437c-ba21-d949edd1ba43', 'd65135d7-3489-492d-88ae-8d9fd52e4d86', 3, '오토바이', false),
  ('fd7b4b0b-31a8-4aa4-80ce-4b9fb0e6d5a2', 'd65135d7-3489-492d-88ae-8d9fd52e4d86', 4, '잘못된 것이 없습니다.', false),
  ('ef2aad6a-c45c-4585-a6c3-f7537f50af02', 'c8b47fdb-2a56-41ac-8da6-ddab8c0a36b9', 1, '당근', false),
  ('1805975f-da92-470d-a111-b2dbeb095a14', 'c8b47fdb-2a56-41ac-8da6-ddab8c0a36b9', 2, '오이', false),
  ('79376789-df28-4ddc-88de-4cb7e6197076', 'c8b47fdb-2a56-41ac-8da6-ddab8c0a36b9', 3, '배', true),
  ('8075cbbd-5dac-4e90-8406-28a0a21dd1fd', 'c8b47fdb-2a56-41ac-8da6-ddab8c0a36b9', 4, '빠진 것이 없습니다.', false),
  ('2e97b46f-c3a6-4b14-85be-a50af48513f2', '8f89136e-8cb9-4525-b809-b6292aca67cf', 1, '빨간 네모', false),
  ('e30adfc8-bb47-4d6b-bcc8-56ac50e29848', '8f89136e-8cb9-4525-b809-b6292aca67cf', 2, '파란 세모', false),
  ('b5c1fe0a-4569-4b34-bcda-f743d4d070b8', '8f89136e-8cb9-4525-b809-b6292aca67cf', 3, '파란 네모', false),
  ('203a79e7-67e9-453c-88b0-0a34d217f191', '8f89136e-8cb9-4525-b809-b6292aca67cf', 4, '빨간 세모', true),
  ('288fa349-f5aa-4869-a28b-11f93d575137', '13b51c55-6aea-4848-bf78-5df48f927f8e', 1, '14', true),
  ('9c478dd1-d648-4c42-9363-216528faec51', '13b51c55-6aea-4848-bf78-5df48f927f8e', 2, '9', false),
  ('a62d452b-bdce-46a2-a01c-2f65ba47b199', '13b51c55-6aea-4848-bf78-5df48f927f8e', 3, '11', false),
  ('9d222a09-a672-4c37-a580-ba0398382608', '13b51c55-6aea-4848-bf78-5df48f927f8e', 4, '15', false),
  ('556c6149-cbbf-4092-8929-9c7155b36666', 'ffed7c7c-0bab-4f37-9a62-5b2f62e1329e', 1, '책', false),
  ('ed599f22-3e7d-40b9-b87a-95e1b19372ff', 'ffed7c7c-0bab-4f37-9a62-5b2f62e1329e', 2, '축구공', true),
  ('47ec71e5-68df-4dc4-80ac-46bd0eb6171c', 'ffed7c7c-0bab-4f37-9a62-5b2f62e1329e', 3, '공책', false),
  ('3093320c-92b0-4d2f-b7e6-dd21cab55d02', 'ffed7c7c-0bab-4f37-9a62-5b2f62e1329e', 4, '잘못된 것이 없습니다.', false),
  ('5ccf0fc5-f17b-4ba2-adb9-259efbd55f9a', '7d1a86e8-0c01-45f6-b903-4b0f64ea0e14', 1, '토끼', false),
  ('2b90b6c7-28c2-4857-b254-33bc7fca6939', '7d1a86e8-0c01-45f6-b903-4b0f64ea0e14', 2, '거북', false),
  ('1fd194e3-64c1-4b91-852d-29f531de5a10', '7d1a86e8-0c01-45f6-b903-4b0f64ea0e14', 3, '독수리', true),
  ('46304484-9de4-411a-bd66-b8dba7f29370', '7d1a86e8-0c01-45f6-b903-4b0f64ea0e14', 4, '빠진 동물이 없습니다.', false),
  ('69f6556a-8a97-499c-bbb8-33b72b598e0e', '37ca26ac-35f9-43ed-8ef4-6db548cb1d1d', 1, '노란 큰 공', false),
  ('92ac7578-e203-4dc9-b645-c7a4400b7e8c', '37ca26ac-35f9-43ed-8ef4-6db548cb1d1d', 2, '노란 작은 공', false),
  ('fba44793-b793-44a7-9fff-56cba55576e4', '37ca26ac-35f9-43ed-8ef4-6db548cb1d1d', 3, '파란 작은 공', false),
  ('077c9427-f3b6-4120-9ae0-e9067d7135dc', '37ca26ac-35f9-43ed-8ef4-6db548cb1d1d', 4, '파란 큰 공', true),
  ('3128ed59-0638-4134-a22b-a094ca5a6806', '2b412b75-12f3-4216-9fc7-51885d8acec2', 1, '식사 도구와 학용품', true),
  ('a0f4fca9-51ea-4fd9-89bc-07f1fd7efce9', '2b412b75-12f3-4216-9fc7-51885d8acec2', 2, '금속과 나무', false),
  ('e1782207-63d1-41bf-b250-d72c068e49d1', '2b412b75-12f3-4216-9fc7-51885d8acec2', 3, '긴 것과 짧은 것', false),
  ('a698b6da-c041-403f-a710-a8c3f8061ea7', '2b412b75-12f3-4216-9fc7-51885d8acec2', 4, '빨간 것과 파란 것', false),
  ('45f5ceca-de95-40ac-94f9-f74b8567c6d2', '9a1f7d65-07f8-4439-9aa8-68ad6a33eb47', 1, '7', false),
  ('d719cd8e-b4c4-491a-b7a9-c686af0d70e5', '9a1f7d65-07f8-4439-9aa8-68ad6a33eb47', 2, '18', true),
  ('a2af4115-1eb9-49fa-b7f0-0ec738898477', '9a1f7d65-07f8-4439-9aa8-68ad6a33eb47', 3, '13', false),
  ('fd107d8d-5e91-48fa-823f-1541bd7d52bc', '9a1f7d65-07f8-4439-9aa8-68ad6a33eb47', 4, '잘못된 수가 없습니다.', false),
  ('b2daa3af-1d54-4011-b146-427d756cc79d', '9e5663ef-86e5-454a-94c7-aa3d0adcb554', 1, '빨간 세모와 파란 세모', true),
  ('c113b111-0bef-47b3-82e0-cd144235b64e', '9e5663ef-86e5-454a-94c7-aa3d0adcb554', 2, '빨간 세모와 빨간 네모', false),
  ('761f3ebe-ebb3-45a8-8c18-09f37eb8f932', '9e5663ef-86e5-454a-94c7-aa3d0adcb554', 3, '빨간 네모와 파란 세모', false),
  ('a940ebd7-d4a1-4ebb-8b1f-818b01425f17', '9e5663ef-86e5-454a-94c7-aa3d0adcb554', 4, '빨간 세모만', false),
  ('d0673441-fb43-41b2-a1b5-e3d290d17c3b', '1630075d-6852-4645-9141-104ba79af24e', 1, '연필', false),
  ('eefca122-e722-4772-a27b-2871ee5fca86', '1630075d-6852-4645-9141-104ba79af24e', 2, '색연필', false),
  ('d8e20ce7-5627-4e62-bd7d-e6af857d4c91', '1630075d-6852-4645-9141-104ba79af24e', 3, '책상', false),
  ('c129cfc2-6a3c-4c04-b2a7-bbe251ef8983', '1630075d-6852-4645-9141-104ba79af24e', 4, '지우개', true),
  ('501bd87b-1cb6-4444-ae6a-caa87772a6a7', '95658c4b-c31b-4e3b-aa88-50f87198b062', 1, '15보다 작은 수와 15 이상인 수', false),
  ('e980eb7e-4b32-4919-aa52-b0c8b3bbb43c', '95658c4b-c31b-4e3b-aa88-50f87198b062', 2, '짝수와 홀수', true),
  ('82b2fc46-0c47-4cf9-be24-21fa06119e8d', '95658c4b-c31b-4e3b-aa88-50f87198b062', 3, '한 자리 수와 두 자리 수', false),
  ('752eac4e-fed5-47c9-a1d2-d39eaada9200', '95658c4b-c31b-4e3b-aa88-50f87198b062', 4, '10보다 큰 수와 작은 수', false),
  ('cd72f643-b3a8-4dbc-b4b7-796ff08b4003', 'cd3a0422-f38e-4968-9a61-15e0fadba95a', 1, '색깔', false),
  ('d3e40d1a-3c26-4fb7-8e15-943106a13036', 'cd3a0422-f38e-4968-9a61-15e0fadba95a', 2, '구멍 수', false),
  ('60a305fc-8e52-40b5-a4f7-33316613710d', 'cd3a0422-f38e-4968-9a61-15e0fadba95a', 3, '크기', true),
  ('3f7a97f7-b4d9-4845-90cb-837b1e8ef508', 'cd3a0422-f38e-4968-9a61-15e0fadba95a', 4, '재료', false),
  ('f95b950e-29fd-4ce0-97d4-ddb4ea0b5418', 'ce19dbfb-683c-48f7-9026-5d0b5035c8ea', 1, '파란 네모를 더 넣습니다.', false),
  ('71837364-5cf6-45cc-8e2e-572bf13ad5e5', 'ce19dbfb-683c-48f7-9026-5d0b5035c8ea', 2, '파란 세모를 더 넣습니다.', false),
  ('3f4f5830-c183-4e52-a579-3081334e7913', 'ce19dbfb-683c-48f7-9026-5d0b5035c8ea', 3, '빨간 네모를 더 넣습니다.', true),
  ('ea383ea3-2f7f-46be-8235-373d95a372c6', 'ce19dbfb-683c-48f7-9026-5d0b5035c8ea', 4, '아무것도 더 넣지 않습니다.', false),
  ('411f6b56-da1c-4e07-af3e-d4bdb8ab0cfc', '06516ce7-7865-4105-9777-c6f2fe054ce5', 1, '18, 짝수이기 때문입니다.', false),
  ('88a4127f-b00a-4ddb-a87f-1df901bc0285', '06516ce7-7865-4105-9777-c6f2fe054ce5', 2, '21, 20보다 크기 때문입니다.', false),
  ('a8789164-b9f9-4410-b658-1b03ea620b3c', '06516ce7-7865-4105-9777-c6f2fe054ce5', 3, '25, 홀수이기 때문입니다.', false),
  ('da06aa21-e01d-4b73-a450-e57493189251', '06516ce7-7865-4105-9777-c6f2fe054ce5', 4, '24, 짝수이고 20보다 크기 때문입니다.', true),
  ('b8883ecf-82b4-4ccf-8704-8b66ba54ed64', 'a993ac7d-ae20-45c2-bd5b-c1007650b521', 1, '먹을 수 있는지', true),
  ('fbc802d1-5737-4c8f-8691-ad5a43a477cb', 'a993ac7d-ae20-45c2-bd5b-c1007650b521', 2, '물건의 색깔', false),
  ('16e8a201-1ba5-46ed-a015-637623675f30', 'a993ac7d-ae20-45c2-bd5b-c1007650b521', 3, '빨간색과 파란색', false),
  ('40dd8a82-8c46-438b-a977-7f55fc87b17d', 'a993ac7d-ae20-45c2-bd5b-c1007650b521', 4, '같은 색끼리 묶기', false),
  ('e807ebb6-2b6e-470b-b04b-229c6288d072', '06427732-d3b5-4474-8488-604fc93a28f1', 1, '날개 있음: 오리, 고양이 / 날개 없음: 참새, 토끼', false),
  ('0f0108df-bba5-41a3-a909-fb11f51d448e', '06427732-d3b5-4474-8488-604fc93a28f1', 2, '날개 있음: 오리, 참새 / 날개 없음: 고양이, 토끼', true),
  ('74d1b05e-f85a-42e8-ab03-4ae46c358cd5', '06427732-d3b5-4474-8488-604fc93a28f1', 3, '날개 있음: 고양이, 토끼 / 날개 없음: 오리, 참새', false),
  ('e5435d71-9e1b-492f-b245-92b665acc60b', '06427732-d3b5-4474-8488-604fc93a28f1', 4, '날개 있음: 참새, 토끼 / 날개 없음: 오리, 고양이', false),
  ('9cddaff6-b0dd-49c8-b005-158dc3e0b8f7', '10656aa7-f917-48d5-8148-6967121755c3', 1, '빨간 큰 상자', false),
  ('e906c480-a5b6-414c-9473-85575c4245a3', '10656aa7-f917-48d5-8148-6967121755c3', 2, '빨간 작은 상자', false),
  ('42e46a6f-b4d1-4b14-b6d7-248e938584e2', '10656aa7-f917-48d5-8148-6967121755c3', 3, '파란 작은 상자', true),
  ('f54d3a34-097d-4d83-8b8c-eb680ef1a4d5', '10656aa7-f917-48d5-8148-6967121755c3', 4, '파란 큰 상자', false),
  ('c1f7cd49-a1cd-41c4-a7ad-5ed7299e22ed', 'c970faec-edd8-4fe7-b451-65398b5321ba', 1, '모든 물건을 한 상자에 넣으면 가장 빨리 찾습니다.', false),
  ('284c90fd-a9c9-47cd-ba4d-c0f8f909afa8', 'c970faec-edd8-4fe7-b451-65398b5321ba', 2, '색깔만 보고 연필과 공책을 섞으면 쓰임을 알기 쉽습니다.', false),
  ('d68862f4-eb25-402b-b883-c2ccd1068101', 'c970faec-edd8-4fe7-b451-65398b5321ba', 3, '크기가 비슷하면 쓰임과 관계없이 함께 둡니다.', false),
  ('028abab6-1a78-4887-8e37-0df9cd53b83d', 'c970faec-edd8-4fe7-b451-65398b5321ba', 4, '연필류, 공책류처럼 쓰임이 같은 것끼리 두면 필요한 물건을 찾기 쉽습니다.', true);

insert into public.learning_question_skills (
  question_id, skill_code, is_primary
)
values
  ('c3dadff8-a851-4b99-874b-43b527ae2ac4', 'identify-classification-rule', true),
  ('d2671053-580c-496a-9aae-75e8490e9227', 'identify-classification-rule', true),
  ('d383eaf6-61f2-4109-8b22-7dae50225ae8', 'classify-by-given-rule', true),
  ('3f3ea6a6-b981-4f26-a8b3-4893e1028653', 'classify-by-given-rule', true),
  ('7fb21abf-8b0c-4f82-adb2-b854990d121d', 'identify-classification-rule', true),
  ('0c2c9cd1-f350-4d9d-89e1-9589fe4f8953', 'classify-by-given-rule', true),
  ('242f564a-a221-4ba2-97ee-f37122a3ca35', 'classify-by-given-rule', true),
  ('05988807-5115-402f-a310-bb224cd910c1', 'classify-by-given-rule', true),
  ('7014c2c5-a80d-44d1-8bd4-c024c060ff76', 'identify-classification-rule', true),
  ('24160d5b-e41c-43a5-acd5-8d3d38be2e7d', 'classify-by-given-rule', true),
  ('90cc32ef-6232-4c84-b3de-298728557cfd', 'compare-classification-rules', true),
  ('1bd7749c-cb04-43af-a24a-a6162b0f4a72', 'compare-classification-rules', true),
  ('0e972622-b82a-4af6-95a1-9a91fcf181b7', 'infer-rule-from-groups', true),
  ('fded8424-b6f8-486a-baa3-aa1ff6c56132', 'infer-rule-from-groups', true),
  ('ad08071c-4a9e-4bbc-a961-3124f7c2613b', 'explain-classification-reasoning', true),
  ('4fe929fc-0832-4f74-88c2-81a8f155562f', 'explain-classification-reasoning', true),
  ('718cf3dc-ca79-46b8-9591-0eb135412805', 'infer-rule-from-groups', true),
  ('5638de18-500f-4742-a1e5-6e5c68d62125', 'classify-by-given-rule', true),
  ('a771d0b4-0cc6-44a9-88aa-9d2b5798afee', 'compare-classification-rules', true),
  ('4a7ae45c-7152-4672-b5c5-a37cb2cedf76', 'explain-classification-reasoning', true),
  ('d71db0b0-f672-4d83-965d-a503146b9217', 'infer-rule-from-groups', true),
  ('d65135d7-3489-492d-88ae-8d9fd52e4d86', 'find-misclassified-item', true),
  ('c8b47fdb-2a56-41ac-8da6-ddab8c0a36b9', 'find-missing-classified-item', true),
  ('8f89136e-8cb9-4525-b809-b6292aca67cf', 'classify-by-two-properties', true),
  ('13b51c55-6aea-4848-bf78-5df48f927f8e', 'classify-by-two-properties', true),
  ('ffed7c7c-0bab-4f37-9a62-5b2f62e1329e', 'find-misclassified-item', true),
  ('7d1a86e8-0c01-45f6-b903-4b0f64ea0e14', 'find-missing-classified-item', true),
  ('37ca26ac-35f9-43ed-8ef4-6db548cb1d1d', 'classify-by-two-properties', true),
  ('2b412b75-12f3-4216-9fc7-51885d8acec2', 'infer-rule-from-groups', true),
  ('9a1f7d65-07f8-4439-9aa8-68ad6a33eb47', 'find-misclassified-item', true),
  ('9e5663ef-86e5-454a-94c7-aa3d0adcb554', 'explain-classification-reasoning', true),
  ('1630075d-6852-4645-9141-104ba79af24e', 'find-misclassified-item', true),
  ('95658c4b-c31b-4e3b-aa88-50f87198b062', 'infer-rule-from-groups', true),
  ('cd3a0422-f38e-4968-9a61-15e0fadba95a', 'compare-classification-rules', true),
  ('ce19dbfb-683c-48f7-9026-5d0b5035c8ea', 'find-missing-classified-item', true),
  ('06516ce7-7865-4105-9777-c6f2fe054ce5', 'explain-classification-reasoning', true),
  ('a993ac7d-ae20-45c2-bd5b-c1007650b521', 'explain-classification-reasoning', true),
  ('06427732-d3b5-4474-8488-604fc93a28f1', 'classify-by-given-rule', true),
  ('10656aa7-f917-48d5-8148-6967121755c3', 'classify-by-two-properties', true),
  ('c970faec-edd8-4fe7-b451-65398b5321ba', 'explain-classification-reasoning', true);

select (public.publish_learning_content_version('bf3dd0af-3cff-4d29-bdd3-f12e2ef08d9d'::uuid)).id;

commit;
